/* eslint-disable @typescript-eslint/no-unused-vars */

// Traditional planetary aspect interpretations (Sun through Pluto)
// These are the classical astrological combinations between the main planets

export const planetaryAspectCombinations: Record<
  string,
  Record<string, Record<string, string>>
> = {
  sun: {
    moon: {
      conjunction: "The conscious will and unconscious instincts merge, creating a focused but potentially one-sided personality. ✅ Gift: Internal unity, strong sense of purpose, emotional authenticity, wholeness of being. ⚠️ Challenge: Lack of objectivity about oneself, difficulty seeing other perspectives, potential rigidity, reduced creative tension for growth.",
      sextile: "The conscious and unconscious minds work together harmoniously when effort is applied. ✅ Gift: Emotional intelligence when cultivated, natural integration of thinking and feeling, practical self-awareness. ⚠️ Challenge: Requires conscious effort to activate, potential remains undeveloped without active work.",
      square: "Internal conflict between conscious will and emotional needs creates dynamic tension. ✅ Gift: Powerful self-awareness through inner work, emotional depth, motivation for personal growth, psychological resilience. ⚠️ Challenge: Internal contradictions create stress, difficulty making decisions, potential for self-sabotage, emotional turmoil.",
      trine: "Conscious will and unconscious instincts flow together effortlessly. ✅ Gift: Natural self-confidence, emotional stability, inner peace, effortless self-expression. ⚠️ Challenge: May lack motivation for deep growth, potential complacency, taking gifts for granted.",
      opposition: "Conscious will and unconscious needs pull in opposite directions. ✅ Gift: Objectivity about oneself, ability to balance opposites, awareness of internal contradictions, relationship wisdom. ⚠️ Challenge: Internal division, feeling pulled in two directions, difficulty integrating conscious and unconscious needs.",
      quincunx: "Conscious will and emotional needs operate at awkward angles requiring constant adjustment. ✅ Gift: Flexibility, adaptability, creative problem-solving through integration of mismatched energies. ⚠️ Challenge: Constant need for adjustment, never feeling quite aligned, exhausting fine-tuning of self-expression."
    },
    mercury: {
      conjunction: "The mind and identity fuse, creating strong intellectual confidence and clear self-expression. ✅ Gift: Natural ability to articulate personal vision, mental confidence, authentic communication, integrated thinking and being. ⚠️ Challenge: Mental subjectivity, difficulty seeing beyond one's own perspective, talking more than listening, intellectual ego.",
      sextile: "Mental abilities and self-expression support each other through active engagement. ✅ Gift: Clear communication skills when cultivated, ability to articulate ideas effectively, learning agility, intellectual versatility. ⚠️ Challenge: Requires conscious effort to develop, potential remains dormant without active practice, needs stimulation to activate.",
      square: "Mental expression and personal identity clash, creating communication challenges. ✅ Gift: Strong analytical abilities through inner work, unique perspectives, mental problem-solving, intellectual independence, original thinking. ⚠️ Challenge: Communication difficulties, misunderstood by others, inner mental tension, conflict between thinking and being.",
      trine: "Mind and identity work in perfect harmony, creating natural communication abilities. ✅ Gift: Intellectual confidence, clear self-expression, natural writing or speaking abilities, effortless articulation, mental ease. ⚠️ Challenge: May not develop full intellectual potential, taking communication gifts for granted, avoiding mental challenges.",
      opposition: "Identity and mental expression operate at cross-purposes. ✅ Gift: Objectivity about oneself through reflection, ability to see multiple perspectives, mental balance, intellectual fairness, diplomatic communication. ⚠️ Challenge: Internal division between thoughts and identity, difficulty integrating self-concept with mental expression, polarized thinking.",
      quincunx: "Identity and thinking patterns require ongoing adjustment and adaptation. ✅ Gift: Mental flexibility, adaptive communication style, ability to adjust thinking to different contexts, intellectual versatility. ⚠️ Challenge: Constant need to recalibrate expression, mental restlessness, never quite feeling thoughts match identity, exhausting adjustments."
    },
    venus: {
      conjunction: "Personal magnetism and creative self-expression flow naturally, bringing charm and artistic abilities. ✅ Gift: Natural charisma, artistic talents, social ease, aesthetic sense, attractiveness, creative confidence. ⚠️ Challenge: Vanity, over-identification with beauty, superficiality, excessive pleasure-seeking, relying on charm over substance.",
      sextile: "Personal charm and creative abilities can be developed through conscious effort. ✅ Gift: Social grace when cultivated, artistic talents through practice, diplomatic skills, relationship-building abilities, refined taste. ⚠️ Challenge: Requires active development, talents dormant without cultivation, needs effort to manifest charm.",
      square: "Personal values and self-expression conflict, creating relationship and creative tensions. ✅ Gift: Authentic self-worth through inner work, genuine artistic expression, depth in relationships, true beauty beyond appearances, evolved values. ⚠️ Challenge: Relationship tensions, creative blocks, self-worth struggles, conflicting values, superficial versus authentic dilemma.",
      trine: "Personal magnetism and creative expression flow together naturally. ✅ Gift: Natural charm, artistic ability, ease in relationships, aesthetic harmony, social popularity, effortless creativity. ⚠️ Challenge: Taking gifts for granted, underdeveloped artistic potential, reliance on charm, avoiding relationship depth, complacency.",
      opposition: "Personal values and self-expression exist in tension with others' expectations. ✅ Gift: Awareness of relationship dynamics, ability to balance self with others, diplomatic skills, partnership wisdom, social objectivity. ⚠️ Challenge: Internal tension between desires and harmony, people-pleasing, loss of authenticity, compromising values for acceptance.",
      quincunx: "Personal values and self-expression require constant adjustment to aesthetic values and relationship harmony. ✅ Gift: Flexibility in relationships, adaptive aesthetic sense, creative problem-solving in love, versatile charm. ⚠️ Challenge: Constant relationship adjustments, unstable values, never quite harmonious, exhausting social calibration."
    },
    mars: {
      conjunction: "Willpower and action unite to create dynamic leadership and strong initiative. ✅ Gift: Dynamic energy, strong initiative, leadership abilities, courage, assertiveness, competitive drive, physical vitality. ⚠️ Challenge: Aggression, impatience, conflicts, recklessness, burnout, difficulty with gentleness, anger management issues.",
      sextile: "Willpower and action support each other when properly directed. ✅ Gift: Leadership potential when developed, constructive assertiveness, focused energy through effort, physical confidence, strategic action. ⚠️ Challenge: Requires conscious direction, energy unfocused without effort, needs discipline to channel properly.",
      square: "Will and action create friction, leading to impatience and potential conflict. ✅ Gift: Extraordinary achievement through channeled tension, competitive excellence, leadership forged through challenges, warrior spirit, breakthrough energy. ⚠️ Challenge: Impatience, internal conflicts, aggressive tendencies, frustration, hasty decisions, accident-prone.",
      trine: "Will and action unite smoothly, creating natural leadership and initiative. ✅ Gift: Natural courage, effortless leadership, smooth assertion, physical grace, confidence without aggression, harmonious action. ⚠️ Challenge: May not develop full competitive edge, taking courage for granted, avoiding necessary conflict.",
      opposition: "Will and action exist in polarized tension, creating internal or external conflicts. ✅ Gift: Diplomatic skills through balance, ability to cooperate competitively, awareness of assertion dynamics, strategic partnerships, balanced aggression. ⚠️ Challenge: Internal conflict about action, polarized between assertion and passivity, relationship conflicts, competitive tensions.",
      quincunx: "Will and action require continuous recalibration and strategic adjustment. ✅ Gift: Tactical thinking, adaptive action strategies, ability to modify approach flexibly, strategic versatility, situational awareness. ⚠️ Challenge: Constantly adjusting tactics, unstable action patterns, never quite aligned energy, exhausting recalibration."
    },
    jupiter: {
      conjunction: "Confidence and expansion merge to create natural optimism and leadership abilities. ✅ Gift: Natural optimism, confidence, good fortune, generosity, philosophical wisdom, expansive vision, leadership charisma, beneficial opportunities. ⚠️ Challenge: Overconfidence, exaggeration, overextension, unrealistic expectations, arrogance, excess, taking on too much.",
      sextile: "Confidence and expansion work together when opportunities are actively pursued. ✅ Gift: Growth potential through risk-taking, optimism when cultivated, success through opportunity-seeking, beneficial networking, wisdom development. ⚠️ Challenge: Requires seizing opportunities, potential dormant without action, needs courage to manifest.",
      square: "Confidence and expansion create overextension and unrealistic expectations. ✅ Gift: Proper judgment through lessons, realistic goal-setting learned through experience, humility development, wisdom from failures, growth through corrections. ⚠️ Challenge: Overreach, unrealistic expectations, hubris, failed ventures, legal issues, moral conflicts.",
      trine: "Confidence and expansion flow together, creating natural optimism and good fortune. ✅ Gift: Natural success, good fortune, effortless growth, optimism, generosity, philosophical wisdom, beneficial opportunities without struggle. ⚠️ Challenge: Overconfidence from ease, taking blessings for granted, lack of gratitude, underestimating challenges.",
      opposition: "Personal confidence conflicts with excessive expansion or moral certainty. ✅ Gift: Balance between optimism and realism, awareness of belief systems, perspective-taking, philosophical objectivity, wisdom through contrast. ⚠️ Challenge: Conflicting beliefs, moral tensions, over-optimism versus pessimism, philosophical disagreements.",
      quincunx: "Personal confidence needs ongoing adjustment to avoid overextension or unrealistic expectations. ✅ Gift: Adaptive goal-setting, flexible beliefs, practical wisdom, ability to adjust expectations based on experience, philosophical flexibility. ⚠️ Challenge: Constantly recalibrating expectations, unstable beliefs, never quite confident or realistic enough."
    },
    saturn: {
      conjunction: "Identity formation occurs through discipline, responsibility, and facing limitations. ✅ Gift: Serious purpose, methodical approach, self-discipline, authentic authority, maturity, realistic self-view, lasting achievements, wisdom through experience. ⚠️ Challenge: Pessimism, fear of self-expression, heavy responsibilities early in life, self-doubt, depression, rigid identity.",
      sextile: "Personal discipline and structure support identity development through consistent effort. ✅ Gift: Building lasting achievements through work, authentic authority development, mature leadership, patient progress, earned respect. ⚠️ Challenge: Requires consistent effort over time, slow development, patience needed, delayed gratification.",
      square: "Self-expression meets restriction and limitation, creating internal authority conflicts. ✅ Gift: Character built through obstacles, strength through adversity, earned authority, balance of freedom and responsibility, resilience, maturity through challenges. ⚠️ Challenge: Internal authority conflicts, limitation frustrations, blocked expression, heavy burdens, self-restriction, depression.",
      trine: "Personal authority and discipline work together harmoniously. ✅ Gift: Natural leadership, sustained achievement capacity, methodical success, mature confidence, reliable authority, enduring accomplishments without struggle. ⚠️ Challenge: May not develop full resilience, taking discipline for granted, avoiding necessary challenges.",
      opposition: "Self-expression meets external limitations and authority conflicts. ✅ Gift: Maturity through balancing freedom and responsibility, awareness of authority dynamics, wisdom through restrictions, diplomatic maturity, partnership commitment. ⚠️ Challenge: External limitations on expression, authority conflicts, burden of responsibility, restriction by others.",
      quincunx: "Self-expression requires constant adjustment to limitations and responsibilities. ✅ Gift: Creative authenticity within constraints, flexible discipline, adaptive authority, ability to express despite restrictions, strategic patience. ⚠️ Challenge: Constant adjustment to limitations, never quite free or responsible enough, exhausting calibration."
    },
    uranus: {
      conjunction: "Individual expression seeks freedom and originality, creating innovative and rebellious personalities. ✅ Gift: Originality, innovation, authentic individuality, revolutionary spirit, breakthrough thinking, technological aptitude, electric charisma, progressive leadership. ⚠️ Challenge: Erratic behavior, inconsistent expression, rebelliousness for its own sake, instability, alienation, difficulty with commitment.",
      sextile: "Individual expression and innovation support each other through conscious experimentation. ✅ Gift: Originality when cultivated, progressive thinking developed through exploration, creative breakthroughs, innovative solutions, technological skills. ⚠️ Challenge: Requires experimental courage, innovation dormant without risk-taking, needs conscious uniqueness development.",
      square: "Individual expression conflicts with need for freedom and change. ✅ Gift: Authentic self-discovery through crises, innovation born from disruption, true individuality, revolutionary breakthroughs, liberation from false identity. ⚠️ Challenge: Unpredictable behavior, identity crises, rebellion versus stability, disruptive changes, alienation, instability.",
      trine: "Individual expression and innovation flow together naturally. ✅ Gift: Natural originality, effortless innovation, progressive without disruption, authentic uniqueness, technological ease, comfortable individuality. ⚠️ Challenge: May not develop full revolutionary potential, taking uniqueness for granted, avoiding necessary disruption.",
      opposition: "Individual expression conflicts with need for complete freedom or rebellion. ✅ Gift: Awareness of authenticity versus acceptance tension, balanced innovation, integration of uniqueness with relationships, diplomatic revolution. ⚠️ Challenge: Torn between authenticity and belonging, relationship instability, others disrupt identity, freedom versus connection.",
      quincunx: "Individual expression needs ongoing adaptation to changing need for freedom or innovation. ✅ Gift: Flexible self-expression, adaptive innovation, ability to reinvent as needed, versatile authenticity, strategic uniqueness. ⚠️ Challenge: Constant identity reinvention, unstable sense of self, never quite free or stable enough."
    },
    neptune: {
      conjunction: "The ego seeks transcendence through imagination, spirituality, or creative expression. ✅ Gift: Spiritual sensitivity, artistic inspiration, compassion, imagination, psychic abilities, transcendent experiences, mystical connection, creative genius. ⚠️ Challenge: Ego confusion, identity dissolution, escapism, unrealistic self-perception, victim mentality, boundary issues, addiction vulnerability.",
      sextile: "Ego and intuition work together when spiritual or creative practices are cultivated. ✅ Gift: Spiritual imagination development, artistic abilities through practice, compassion cultivation, psychic sensitivity when explored, inspired creativity. ⚠️ Challenge: Requires spiritual discipline, gifts dormant without practice, needs conscious development of sensitivity.",
      square: "Ego clarity conflicts with spiritual dissolution and confusion. ✅ Gift: Discernment between illusion and truth through challenges, spiritual discrimination, grounded mysticism, clarity through confusion, compassion with boundaries. ⚠️ Challenge: Identity confusion, escapist tendencies, illusions about self, victim patterns, boundary dissolution, deception.",
      trine: "Ego and intuition work in harmony, creating natural spiritual or artistic gifts. ✅ Gift: Natural spirituality, artistic inspiration, effortless imagination, comfortable compassion, psychic abilities, mystical ease without confusion. ⚠️ Challenge: May not develop spiritual discipline, taking gifts for granted, avoiding material reality.",
      opposition: "Clear ego identity conflicts with dissolution and spiritual surrender. ✅ Gift: Discernment between spirituality and escapism, integration of ego and transcendence, balanced mysticism, awareness of illusion, grounded compassion. ⚠️ Challenge: Ego versus spiritual dissolution, boundary confusion with others, sacrifice versus self, illusion in relationships.",
      quincunx: "Ego clarity requires constant adjustment to spiritual or imaginative influences. ✅ Gift: Adaptive spiritual identity, flexible mysticism, creative inspiration integration, ability to serve higher purposes while maintaining self. ⚠️ Challenge: Constant identity-spirituality recalibration, unclear boundaries, never quite grounded or transcendent enough."
    },
    pluto: {
      conjunction: "Personal will merges with transformative power, creating intense, magnetic personalities. ✅ Gift: Magnetic charisma, transformative power, psychological depth, regenerative ability, intense focus, profound impact, leadership through crisis, authentic power. ⚠️ Challenge: Controlling behavior, manipulation, compulsive transformation needs, power struggles, obsessive self-focus, destructive tendencies.",
      sextile: "Personal will and transformative power support each other through conscious inner work. ✅ Gift: Self-reinvention ability through effort, positive influence when developed, psychological insight cultivation, healing power, transformative leadership. ⚠️ Challenge: Requires deep inner work, power dormant without psychological exploration, needs shadow integration.",
      square: "Personal will clashes with transformative power, creating intense internal struggles. ✅ Gift: Tremendous personal power through transformation, depth through crisis, authentic power beyond control, psychological mastery, rebirth capacity. ⚠️ Challenge: Intense internal struggles, power struggles, compulsive patterns, crisis after crisis, control issues, destruction before rebirth.",
      trine: "Personal will and transformative power flow together smoothly. ✅ Gift: Natural magnetism, positive influence without manipulation, effortless psychological insight, smooth transformation, healing presence, authentic power. ⚠️ Challenge: May not develop full depth, taking power for granted, avoiding necessary crisis for growth.",
      opposition: "Personal will faces intense transformative pressure from others or circumstances. ✅ Gift: Awareness of power dynamics, balance between control and surrender, psychological objectivity, deep relationship transformation, empowerment through others. ⚠️ Challenge: Power struggles with others, external transformation pressure, control versus surrender, manipulation in relationships.",
      quincunx: "Personal will needs ongoing adjustment to transformative pressures and power dynamics. ✅ Gift: Adaptive personal power, flexible transformation approach, strategic evolution, ability to adjust power use, psychological versatility. ⚠️ Challenge: Constant power recalibration, unstable transformation process, never quite empowered or surrendered enough."
    }
  },
  moon: {
    mercury: {
      conjunction: "Emotions and thoughts merge, creating intuitive thinking and empathetic communication. ✅ Gift: Intuitive intelligence, empathetic communication, emotional articulation, quick emotional processing, unified feeling-thinking. ⚠️ Challenge: Emotional thinking clouds judgment, difficulty separating feelings from facts, reactive communication, overthinking emotions.",
      sextile: "Emotions and thoughts support each other when consciously developed. ✅ Gift: Emotional intelligence when cultivated, clear feeling communication, balanced thinking and feeling, practical empathy. ⚠️ Challenge: Requires conscious development, potential dormant without practice, needs effort to integrate.",
      square: "Emotions and rational thinking create internal conflict and communication challenges. ✅ Gift: Emotional intelligence through inner work, depth in communication, psychological insight, balanced analysis after struggle. ⚠️ Challenge: Internal emotional-mental conflict, communication difficulties, feelings versus logic battles, misunderstood emotions.",
      trine: "Emotions and thoughts flow together harmoniously, creating natural empathy and intuitive communication. ✅ Gift: Natural emotional intelligence, effortless feeling articulation, intuitive understanding, smooth emotional communication. ⚠️ Challenge: May not develop full analytical depth, taking emotional clarity for granted, avoiding difficult feelings.",
      opposition: "Emotions and rational thinking exist in polarized tension. ✅ Gift: Objectivity about feelings, balanced emotional-mental perspective, diplomatic communication, emotional fairness. ⚠️ Challenge: Polarized between feeling and thinking, internal emotional-mental division, difficulty integrating heart and mind.",
      quincunx: "Emotions and thinking require ongoing adjustment and adaptation. ✅ Gift: Flexible emotional communication, adaptive feeling-thinking, versatile emotional expression, situational empathy. ⚠️ Challenge: Constant emotional-mental recalibration, never quite feeling thoughts match emotions, exhausting integration."
    },
    venus: {
      conjunction: "Emotional needs and aesthetic values unite, creating natural charm and artistic sensitivity. ✅ Gift: Natural charm, artistic emotional expression, emotional beauty, nurturing love, comfortable affection, aesthetic sensitivity. ⚠️ Challenge: Emotional dependency on approval, comfort-seeking, difficulty with emotional discomfort, needing beauty to feel secure.",
      sextile: "Emotional needs and aesthetic appreciation work together harmoniously. ✅ Gift: Grace in relationships when developed, artistic emotional abilities, loving capacity through cultivation, emotional diplomacy. ⚠️ Challenge: Requires relationship effort, emotional grace dormant without practice, needs conscious love development.",
      square: "Emotional needs conflict with social values and relationship expectations. ✅ Gift: Authentic emotional expression through challenge, genuine self-worth, real emotional needs beyond pleasing, depth in love. ⚠️ Challenge: Emotional-relationship tensions, feelings versus harmony conflict, approval struggles, authentic versus pleasant.",
      trine: "Emotional needs and aesthetic values work in perfect harmony. ✅ Gift: Natural emotional charm, effortless artistic sensitivity, comfortable love, easy emotional beauty, harmonious relationships. ⚠️ Challenge: May avoid emotional depth, taking love for granted, comfort-seeking over growth, superficial emotional ease.",
      opposition: "Personal emotional needs conflict with social harmony and others' values. ✅ Gift: Awareness of relationship needs, balance between self and others emotionally, diplomatic feelings, partnership emotional wisdom. ⚠️ Challenge: Emotional needs versus others' expectations, people-pleasing feelings, loss of emotional authenticity for harmony.",
      quincunx: "Emotional needs require constant adjustment to aesthetic values and relationship harmony. ✅ Gift: Flexible emotional expression in love, adaptive relationship feelings, versatile affection, creative emotional harmony. ⚠️ Challenge: Constant emotional relationship adjustments, unstable emotional values, never quite feeling harmonious."
    },
    mars: {
      conjunction: "Instincts and action fuse, creating quick emotional responses and protective instincts. ✅ Gift: Emotional courage, protective instincts, quick emotional action, passionate feelings, defensive strength, emotional initiative. ⚠️ Challenge: Mood swings, emotional outbursts, impulsive reactions, anger issues, emotional volatility, reactive feelings.",
      sextile: "Instincts and action support each other through conscious effort. ✅ Gift: Protective emotional abilities when developed, emotional courage through practice, assertive feelings cultivation, healthy emotional defenses. ⚠️ Challenge: Requires conscious effort to channel, emotional courage dormant without practice, needs active development.",
      square: "Instincts and aggressive impulses create emotional volatility and reactive patterns. ✅ Gift: Emotional courage through challenge, channeled protective instincts, strength through emotional battles, passionate depth. ⚠️ Challenge: Emotional volatility, reactive anger, impulsive feelings, mood instability, defensive overreactions.",
      trine: "Instincts and action flow together smoothly, creating emotional courage and protective abilities. ✅ Gift: Natural emotional courage, effortless protective instincts, smooth emotional assertiveness, comfortable passion. ⚠️ Challenge: May not develop full emotional depth, taking courage for granted, avoiding emotional conflict.",
      opposition: "Emotional instincts oppose aggressive or assertive impulses. ✅ Gift: Emotional diplomatic skills, balance between feeling and action, awareness of emotional assertion dynamics, strategic emotions. ⚠️ Challenge: Emotional versus action polarization, passive-aggressive patterns, difficulty integrating feelings and assertion.",
      quincunx: "Emotional instincts need ongoing adjustment to action and assertiveness. ✅ Gift: Flexible emotional responses, adaptive emotional action, versatile protective instincts, situational emotional courage. ⚠️ Challenge: Constant emotional-action recalibration, unstable emotional responses, never quite feeling or acting right."
    },
    jupiter: {
      conjunction: "Emotional expression expands naturally, creating generous and optimistic feelings. ✅ Gift: Emotional generosity, optimistic feelings, faith in life, abundant emotions, expansive heart, philosophical feelings, emotional growth. ⚠️ Challenge: Emotional excess, overeating for comfort, unrealistic emotional expectations, exaggerated feelings, emotional overindulgence.",
      sextile: "Emotional expansion and optimism support each other when opportunities are embraced. ✅ Gift: Emotional generosity when cultivated, optimism through positive experiences, growth-oriented feelings, philosophical emotional development. ⚠️ Challenge: Requires embracing opportunities, emotional generosity dormant without engagement, needs active positivity.",
      square: "Emotional expression conflicts with excessive optimism or moral expectations. ✅ Gift: Emotional moderation through lessons, balanced feelings with perspective, realistic emotional expectations, humility in feelings. ⚠️ Challenge: Emotional excess, overoptimistic feelings, moral emotional judgments, unrealistic emotional hopes.",
      trine: "Emotional expression and expansion work together naturally. ✅ Gift: Natural emotional generosity, effortless optimism, comfortable faith, easy emotional growth, meaningful feelings. ⚠️ Challenge: May take emotional abundance for granted, avoiding emotional depth, overconfident in feelings.",
      opposition: "Emotional expression conflicts with excessive optimism or philosophical beliefs. ✅ Gift: Balance between feelings and philosophy, emotional perspective, realistic emotional optimism, wisdom about feelings. ⚠️ Challenge: Emotional versus philosophical conflicts, feelings versus beliefs tension, overoptimism versus emotional reality.",
      quincunx: "Emotional expression requires adjustment to expansion and optimistic expectations. ✅ Gift: Adaptive emotional optimism, flexible philosophical feelings, versatile emotional growth, situational emotional generosity. ⚠️ Challenge: Constant emotional-philosophical adjustments, unstable emotional expectations, never quite feeling optimistic or realistic enough."
    },
    saturn: {
      conjunction: "Emotional security seeks structure and control, creating serious and responsible feelings. ✅ Gift: Emotional maturity, responsible feelings, stable emotions through discipline, serious depth, lasting emotional foundations, emotional wisdom. ⚠️ Challenge: Emotional restriction, depression, fear of vulnerability, suppressed feelings, heavy emotional burden, difficulty expressing feelings.",
      sextile: "Emotional security and structure work together through disciplined effort. ✅ Gift: Emotional stability through work, lasting emotional foundations built over time, mature feelings development, patient emotional growth. ⚠️ Challenge: Requires disciplined emotional effort, stability slow to develop, patience needed, delayed emotional gratification.",
      square: "Emotional needs clash with restrictions and fears, creating depression or emotional blocks. ✅ Gift: Emotional resilience through struggle, strength through processing pain, maturity through emotional hardship, authentic feelings beyond fear. ⚠️ Challenge: Depression, emotional blocks, fear of feelings, suppressed emotions, heavy emotional burdens, restricted expression.",
      trine: "Emotional security and structure support each other effortlessly. ✅ Gift: Natural emotional stability, effortless emotional maturity, comfortable emotional responsibility, patient feelings, lasting emotional peace. ⚠️ Challenge: May avoid emotional risk, taking stability for granted, difficulty with emotional spontaneity.",
      opposition: "Emotional needs face restrictions, limitations, or authoritarian pressure. ✅ Gift: Awareness of emotional responsibility balance, maturity through emotional restrictions, wisdom about feelings limits, emotional-duty integration. ⚠️ Challenge: External emotional restrictions, others limit feelings, duty versus emotional needs, emotional responsibility burden.",
      quincunx: "Emotional needs require ongoing adaptation to limitations and responsibilities. ✅ Gift: Flexible emotional maturity, adaptive emotional responsibility, creative feelings within restrictions, strategic emotional expression. ⚠️ Challenge: Constant emotional-duty adjustments, unstable emotional security, never quite feeling free or responsible enough."
    },
    uranus: {
      conjunction: "Emotional needs seek freedom and excitement, creating unpredictable moods and innovative intuition. ✅ Gift: Emotional independence, innovative feelings, intuitive breakthroughs, unique emotional expression, excitement in feelings, original emotional responses. ⚠️ Challenge: Emotional instability, unpredictable moods, difficulty with emotional attachment, inconsistent feelings, emotional detachment.",
      sextile: "Emotional innovation and intuitive insights support each other when explored. ✅ Gift: Emotional originality when cultivated, psychic abilities through exploration, innovative feelings development, unique emotional insights. ⚠️ Challenge: Requires experimental courage, emotional originality dormant without exploration, needs conscious uniqueness.",
      square: "Emotional security conflicts with need for freedom and change. ✅ Gift: Emotional independence through disruption, innovative feelings born from instability, authentic emotional freedom, unique emotional breakthroughs. ⚠️ Challenge: Emotional instability, unpredictable feelings, security versus freedom battles, disrupted attachments, emotional alienation.",
      trine: "Emotional innovation and intuitive insights flow together naturally. ✅ Gift: Natural emotional originality, effortless intuitive abilities, comfortable emotional independence, unique feelings without instability. ⚠️ Challenge: May not develop full emotional depth, taking uniqueness for granted, avoiding emotional intimacy.",
      opposition: "Emotional security conflicts with need for freedom and revolutionary change. ✅ Gift: Awareness of security-freedom balance, integration of stability and independence, balanced emotional innovation, relationship electrical charge. ⚠️ Challenge: Emotional security versus freedom tension, relationships disrupt stability, others demand emotional independence, attachment versus liberation.",
      quincunx: "Emotional security needs constant adjustment to changing need for freedom. ✅ Gift: Flexible emotional attachments, adaptive emotional independence, versatile emotional patterns, situational emotional freedom. ⚠️ Challenge: Constant emotional security-freedom adjustments, unstable attachment patterns, never quite feeling secure or free enough."
    },
    neptune: {
      conjunction: "Emotions seek transcendence through imagination or spirituality, creating psychic sensitivity. ✅ Gift: Psychic emotional sensitivity, spiritual feelings, compassionate heart, imaginative emotions, transcendent emotional experiences, artistic sensitivity. ⚠️ Challenge: Emotional confusion, escapism through feelings, boundary dissolution, victim feelings, emotional illusions, addictive emotional patterns.",
      sextile: "Emotions and spiritual sensitivity enhance each other through conscious development. ✅ Gift: Compassion cultivation, imaginative feelings development, healing emotional abilities, artistic emotional expression when practiced. ⚠️ Challenge: Requires spiritual emotional work, sensitivity dormant without practice, needs conscious compassion development.",
      square: "Emotional clarity conflicts with confusion, illusion, or escapist tendencies. ✅ Gift: Emotional discernment through struggle, clarity through confusion, grounded compassion, intuition versus illusion discrimination, emotional boundaries. ⚠️ Challenge: Emotional confusion, escapist feelings, illusions about emotions, victim patterns, boundary dissolution, emotional deception.",
      trine: "Emotions and spiritual sensitivity enhance each other harmoniously. ✅ Gift: Natural compassion, effortless imagination, comfortable psychic feelings, easy spiritual emotions, accessible transcendent experiences. ⚠️ Challenge: May avoid emotional reality, taking sensitivity for granted, difficulty with emotional boundaries.",
      opposition: "Emotional clarity faces dissolution, confusion, or spiritual surrender. ✅ Gift: Awareness of emotional boundaries, balance between feeling and transcendence, grounded spirituality, emotional-spiritual integration. ⚠️ Challenge: Emotional clarity versus dissolution, boundary confusion with others, feelings versus spiritual surrender, emotional illusions in relationships.",
      quincunx: "Emotional clarity requires ongoing adjustment to spiritual or imaginative influences. ✅ Gift: Flexible emotional spirituality, adaptive compassion, versatile emotional boundaries, creative emotional transcendence. ⚠️ Challenge: Constant emotional-spiritual adjustments, unstable emotional boundaries, never quite feeling grounded or transcendent enough."
    },
    pluto: {
      conjunction: "Emotional depths merge with transformative power, creating intense and magnetic emotional expression. ✅ Gift: Emotional depth and power, magnetic feelings, transformative emotional capacity, psychological emotional insight, healing through emotions, profound feelings. ⚠️ Challenge: Emotional manipulation, obsessive feelings, compulsive emotional patterns, power struggles through emotions, controlling through feelings.",
      sextile: "Emotional depths and transformative power work together through inner exploration. ✅ Gift: Psychological emotional insight when developed, healing abilities through emotional work, transformative feelings cultivation, depth capacity. ⚠️ Challenge: Requires deep emotional exploration, psychological gifts dormant without shadow work, needs conscious depth development.",
      square: "Emotional expression conflicts with deep psychological pressures and power struggles. ✅ Gift: Transformed emotional patterns through crisis, emotional authenticity beyond manipulation, psychological depth through struggle, powerful feelings. ⚠️ Challenge: Intense emotional struggles, power struggles through feelings, obsessive emotions, emotional crises, manipulative feelings.",
      trine: "Emotional depths and transformative power work together smoothly. ✅ Gift: Natural psychological insight, effortless deep emotional processing, comfortable emotional intensity, smooth emotional transformation. ⚠️ Challenge: May avoid emotional surface reality, taking depth for granted, difficulty with light emotions.",
      opposition: "Emotional expression faces intense transformative pressure and power dynamics. ✅ Gift: Awareness of emotional manipulation dynamics, balance between surface and depth feelings, emotional power objectivity, transformative emotional relationships. ⚠️ Challenge: Emotional power struggles with others, manipulation in relationships, feelings versus psychological depth, emotional control dynamics.",
      quincunx: "Emotional patterns need continuous adjustment to transformative pressures. ✅ Gift: Flexible emotional transformation, adaptive psychological processing, versatile emotional depth, strategic emotional power. ⚠️ Challenge: Constant emotional-psychological adjustments, unstable emotional patterns, never quite feeling shallow or deep enough."
    }
  },
  mercury: {
    venus: {
      conjunction: "Mind and aesthetic values merge, creating harmonious and attractive communication. ✅ Gift: Beautiful thinking, charming communication, diplomatic intellect, artistic mental expression, pleasant speech, aesthetic intelligence. ⚠️ Challenge: Intellectual vanity, thinking prioritizes beauty over truth, superficial mental analysis, avoidance of unpleasant facts.",
      sextile: "Mental abilities and aesthetic appreciation support each other through conscious effort. ✅ Gift: Developed beautiful thinking, charming communication when cultivated, diplomatic skills through practice, aesthetic mental appreciation. ⚠️ Challenge: Requires conscious effort, charm dormant without practice, needs active development of grace.",
      square: "Mental analysis conflicts with aesthetic values and social harmony. ✅ Gift: Critical thinking through challenge, intellectual honesty balanced with diplomacy, authentic mental expression, depth beyond charm. ⚠️ Challenge: Mental-aesthetic conflicts, harsh communication, truth versus tact battles, difficulty with diplomatic expression.",
      trine: "Thinking and aesthetic appreciation flow together harmoniously. ✅ Gift: Natural beautiful thinking, effortless charming communication, graceful intellect, aesthetic mental ease, pleasant expression. ⚠️ Challenge: May avoid intellectual depth, taking charm for granted, superficial analysis, avoiding unpleasant truths.",
      opposition: "Analytical thinking faces aesthetic values and social expectations. ✅ Gift: Objectivity about values, balance between honesty and diplomacy, intellectual fairness about beauty, mental-aesthetic integration. ⚠️ Challenge: Thinking versus aesthetics polarization, honesty versus charm conflict, mental versus social harmony.",
      quincunx: "Thinking patterns require ongoing adjustment to aesthetic values and social harmony. ✅ Gift: Flexible diplomatic communication, adaptive aesthetic thinking, versatile mental charm, situational grace. ⚠️ Challenge: Constant mental-aesthetic adjustments, unstable communication style, never quite analytical or charming enough."
    },
    mars: {
      conjunction: "Thinking and action unite, creating sharp, direct communication and quick mental responses. ✅ Gift: Sharp mental quickness, decisive thinking, direct communication, mental courage, quick wit, assertive intellect. ⚠️ Challenge: Argumentative thinking, mental aggression, harsh communication, impulsive thoughts, verbal conflicts.",
      sextile: "Thinking and decisive action work together when properly directed. ✅ Gift: Strategic thinking when developed, mental courage through practice, quick decisive analysis, assertive communication skills. ⚠️ Challenge: Requires conscious direction, mental courage dormant without practice, needs active strategic development.",
      square: "Thinking clashes with impulsive action, creating mental conflicts and argumentative tendencies. ✅ Gift: Strategic thinking through challenge, balanced analysis with action, mental strength, sharp intellect. ⚠️ Challenge: Mental conflicts, argumentative patterns, impulsive versus analytical battles, verbal aggression.",
      trine: "Mental processes and decisive action work together effortlessly. ✅ Gift: Natural quick thinking, effortless mental courage, smooth assertive communication, confident intellect. ⚠️ Challenge: May avoid mental depth, taking quickness for granted, superficial analysis, avoiding thoughtful consideration.",
      opposition: "Mental analysis conflicts with impulsive action and aggressive communication. ✅ Gift: Diplomatic strategic thinking, balance between analysis and action, mental-action integration, thoughtful assertiveness. ⚠️ Challenge: Mental versus action polarization, thinking versus doing conflict, analysis paralysis or impulsiveness.",
      quincunx: "Mental processes need constant adjustment to action-oriented demands. ✅ Gift: Tactical adaptive thinking, flexible mental strategies, versatile analysis-action balance, situational decisiveness. ⚠️ Challenge: Constant thinking-action adjustments, unstable mental approach, never quite analytical or decisive enough."
    },
    jupiter: {
      conjunction: "Mind and expansion fuse, creating broad thinking and philosophical communication. ✅ Gift: Broad philosophical thinking, optimistic intellect, big-picture understanding, expansive communication, wisdom-seeking mind. ⚠️ Challenge: Mental overconfidence, exaggeration in thinking, overlooking details, intellectual arrogance.",
      sextile: "Mental expansion and optimistic thinking support each other when opportunities are pursued. ✅ Gift: Philosophical thinking when cultivated, big-picture connections through learning, optimistic intellect development. ⚠️ Challenge: Requires pursuing opportunities, wisdom dormant without exploration, needs active learning.",
      square: "Detailed thinking conflicts with broad generalizations and optimistic assumptions. ✅ Gift: Intellectual humility through lessons, balanced detail-philosophy thinking, realistic mental expectations, grounded wisdom. ⚠️ Challenge: Mental overreach, overgeneralizations, detail versus big-picture conflicts, intellectual excess.",
      trine: "Detailed thinking and broad perspectives complement each other naturally. ✅ Gift: Natural philosophical intelligence, effortless big-picture understanding, balanced analysis, wisdom ease. ⚠️ Challenge: May avoid intellectual depth, taking wisdom for granted, superficial philosophy, mental complacency.",
      opposition: "Detailed thinking faces broad generalizations and philosophical beliefs. ✅ Gift: Intellectual objectivity, balance between detail and philosophy, mental perspective, analytical wisdom. ⚠️ Challenge: Detail versus philosophy polarization, facts versus beliefs conflicts, mental versus wisdom tension.",
      quincunx: "Detailed thinking requires ongoing adaptation to expansive or philosophical perspectives. ✅ Gift: Flexible intellectual focus, adaptive detail-philosophy balance, versatile mental scope, situational analysis depth. ⚠️ Challenge: Constant mental focus adjustments, unstable intellectual scope, never quite detailed or broad enough."
    },
    saturn: {
      conjunction: "Thinking becomes structured and disciplined, creating methodical mental processes. ✅ Gift: Disciplined methodical thinking, structured intellect, serious mental focus, practical intelligence, concentrated analysis. ⚠️ Challenge: Mental rigidity, pessimistic thinking, fear of mental mistakes, heavy analytical burden, blocked thoughts.",
      sextile: "Disciplined thinking and mental structure work together through consistent effort. ✅ Gift: Practical intelligence through work, methodical thinking development, disciplined analysis over time, earned mental mastery. ⚠️ Challenge: Requires consistent mental effort, slow intellectual development, patience needed, delayed understanding.",
      square: "Mental flexibility conflicts with rigid thinking and fear of mental mistakes. ✅ Gift: Intellectual discipline through overcoming blocks, mental strength through struggle, structured thinking beyond fear. ⚠️ Challenge: Mental blocks, rigid thinking, fear of errors, intellectual self-criticism, analytical paralysis.",
      trine: "Mental discipline and structured thinking support each other smoothly. ✅ Gift: Natural practical intelligence, effortless methodical thinking, comfortable mental concentration, structured ease. ⚠️ Challenge: May avoid mental creativity, taking discipline for granted, rigid analysis, avoiding intellectual risk.",
      opposition: "Mental flexibility faces rigid thinking and authoritarian mental structures. ✅ Gift: Intellectual independence, balance between flexibility and discipline, mental-structural integration, analytical freedom. ⚠️ Challenge: Flexible versus rigid thinking polarization, mental freedom versus structure conflict, analytical tension.",
      quincunx: "Mental flexibility needs continuous adjustment to structural limitations and responsibilities. ✅ Gift: Practical mental adaptability, creative thinking within constraints, versatile disciplined analysis, strategic intelligence. ⚠️ Challenge: Constant mental flexibility-structure adjustments, unstable intellectual approach, never quite free or disciplined enough."
    },
    uranus: {
      conjunction: "Mind and innovation merge, creating original thinking and breakthrough insights. ✅ Gift: Original innovative thinking, breakthrough mental insights, genius intellect, revolutionary ideas, inventive mind. ⚠️ Challenge: Scattered thinking, mental inconsistency, erratic analysis, difficulty with mental focus, intellectual instability.",
      sextile: "Original thinking and innovative insights support each other when actively explored. ✅ Gift: Breakthrough thinking when cultivated, creative problem-solving development, innovative intellect through exploration. ⚠️ Challenge: Requires experimental thinking, innovation dormant without exploration, needs conscious originality.",
      square: "Logical thinking conflicts with innovative insights and mental rebellion. ✅ Gift: Intellectual breakthroughs through challenge, integrated conventional-revolutionary thinking, authentic mental innovation. ⚠️ Challenge: Mental rebellion, scattered analysis, logic versus innovation conflicts, intellectual disruption.",
      trine: "Logical thinking and innovative insights enhance each other naturally. ✅ Gift: Natural original thinking, effortless breakthrough insights, comfortable mental innovation, stable genius. ⚠️ Challenge: May avoid mental convention, taking originality for granted, difficulty with practical thinking.",
      opposition: "Conventional thinking faces innovative insights and mental rebellion. ✅ Gift: Intellectual versatility, balance between traditional and revolutionary thinking, mental integration, analytical innovation. ⚠️ Challenge: Conventional versus innovative thinking polarization, mental tradition versus revolution conflict, intellectual tension.",
      quincunx: "Conventional thinking requires ongoing adjustment to innovative insights and changing perspectives. ✅ Gift: Mental agility, adaptive thinking patterns, versatile intellectual approach, flexible analytical innovation. ⚠️ Challenge: Constant thinking pattern adjustments, unstable mental approach, never quite conventional or innovative enough."
    },
    neptune: {
      conjunction: "Thinking blends with imagination, creating intuitive and inspired mental processes. ✅ Gift: Intuitive inspired thinking, imaginative intellect, psychic mental abilities, spiritual understanding, artistic ideas. ⚠️ Challenge: Confused thinking, difficulty distinguishing facts from fantasy, mental fog, deceptive thoughts, unclear analysis.",
      sextile: "Rational thinking and intuitive insights enhance each other through conscious development. ✅ Gift: Inspired thinking when cultivated, spiritual communication abilities, imaginative analysis development, intuitive intellect. ⚠️ Challenge: Requires conscious spiritual work, inspiration dormant without practice, needs active intuition development.",
      square: "Clear thinking conflicts with imagination, confusion, or deceptive information. ✅ Gift: Mental discernment through challenge, clarity through confusion, grounded imagination, fact-fantasy discrimination. ⚠️ Challenge: Mental confusion, deceptive thinking, illusions in analysis, unclear thoughts, difficulty with mental clarity.",
      trine: "Rational thinking and intuitive insights work together harmoniously. ✅ Gift: Natural inspired thinking, effortless psychic abilities, comfortable spiritual intellect, imaginative ease. ⚠️ Challenge: May avoid mental reality, taking inspiration for granted, difficulty with practical analysis, mental escapism.",
      opposition: "Clear analytical thinking faces confusion, imagination, or deceptive information. ✅ Gift: Mental discernment, balance between clarity and intuition, rational-spiritual integration, analytical imagination. ⚠️ Challenge: Clear versus confused thinking polarization, facts versus fantasy conflict, analytical versus intuitive tension.",
      quincunx: "Clear thinking needs constant adjustment to imaginative or spiritual influences. ✅ Gift: Adaptive rational-intuitive thinking, flexible mental-spiritual balance, versatile analytical imagination, situational clarity. ⚠️ Challenge: Constant mental-spiritual adjustments, unstable thinking clarity, never quite rational or intuitive enough."
    },
    pluto: {
      conjunction: "Mind merges with deep psychological insight, creating penetrating and transformative thinking. ✅ Gift: Penetrating psychological thinking, transformative intellect, investigative mind, profound insights, mental depth and power. ⚠️ Challenge: Obsessive thinking, mental manipulation, paranoid analysis, compulsive thoughts, intellectual control.",
      sextile: "Analytical thinking and psychological depth work together through conscious exploration. ✅ Gift: Investigative abilities when developed, transformative insights through exploration, psychological intellect cultivation. ⚠️ Challenge: Requires deep mental work, investigative gifts dormant without shadow exploration, needs conscious depth.",
      square: "Surface thinking conflicts with deep psychological insights and mental intensity. ✅ Gift: Transformed thinking through challenge, mental authenticity beyond manipulation, profound analysis, psychological strength. ⚠️ Challenge: Mental obsessions, uncomfortable truths create conflict, paranoid thinking, intellectual power struggles.",
      trine: "Analytical thinking and psychological depth complement each other effortlessly. ✅ Gift: Natural investigative abilities, effortless profound insights, comfortable mental depth, psychological ease. ⚠️ Challenge: May avoid mental lightness, taking depth for granted, difficulty with surface communication, intense analysis.",
      opposition: "Surface thinking faces deep psychological insights and mental transformation. ✅ Gift: Awareness of mental patterns, balance between light and deep communication, intellectual integration, analytical depth objectivity. ⚠️ Challenge: Surface versus deep thinking polarization, light versus profound communication conflict, mental versus psychological tension.",
      quincunx: "Surface thinking requires ongoing adjustment to deep psychological insights. ✅ Gift: Flexible communication depth, adaptive analytical intensity, versatile mental-psychological balance, strategic profound thinking. ⚠️ Challenge: Constant thinking depth adjustments, unstable communication intensity, never quite light or profound enough."
    }
  },
  venus: {
    mars: {
      conjunction: "Love and desire merge, creating passionate and attractive energy. ✅ Gift: Passionate romantic magnetism, integrated love and sexuality, attractive energy, sensual affection, exciting relationships, natural seduction. ⚠️ Challenge: Sexual compulsiveness, difficulty separating love from lust, relationship impulsiveness, passion over tenderness.",
      sextile: "Love and desire support each other when consciously balanced. ✅ Gift: Healthy integrated sexuality when cultivated, passionate romantic balance, sensual affection development, attractive confidence. ⚠️ Challenge: Requires conscious relationship work, integration dormant without effort, needs active balance development.",
      square: "Love and desire create tension between romantic ideals and sexual needs. ✅ Gift: Mature integrated love through challenge, balance of tenderness and passion, evolved relationship sexuality, authentic desire. ⚠️ Challenge: Romantic versus sexual conflicts, tender versus passionate battles, relationship physical tensions.",
      trine: "Love and desire flow together harmoniously, creating natural romantic and sexual magnetism. ✅ Gift: Natural passionate romance, effortless sexual-romantic balance, magnetic attractiveness, sensual ease, integrated affection. ⚠️ Challenge: May take relationship ease for granted, avoiding relationship depth, complacent in love.",
      opposition: "Romantic values face aggressive or sexual demands. ✅ Gift: Awareness of giving-receiving balance, integration of tender and passionate, relationship objectivity, sexual-romantic wisdom. ⚠️ Challenge: Romantic versus sexual polarization, tender versus aggressive conflict, relationship passion-affection tension.",
      quincunx: "Romantic expression requires ongoing adjustment to sexual or aggressive energies. ✅ Gift: Flexible romantic approaches, adaptive love expression, versatile affection-passion balance, situational intimacy. ⚠️ Challenge: Constant romantic-sexual adjustments, unstable intimacy patterns, never quite tender or passionate enough."
    },
    jupiter: {
      conjunction: "Love and expansion unite, creating generous and optimistic affection. ✅ Gift: Generous love, optimistic relationships, abundant affection, joyful romance, expansive heart, relationship faith. ⚠️ Challenge: Excessive romantic indulgence, unrealistic relationship expectations, over-idealized love, relationship excess.",
      sextile: "Affection and expansion work together when opportunities for love are pursued. ✅ Gift: Generous love when cultivated, joyful relationships through openness, optimistic romance development, abundant affection. ⚠️ Challenge: Requires pursuing love opportunities, generosity dormant without engagement, needs active romantic optimism.",
      square: "Romantic values conflict with excessive indulgence or unrealistic expectations. ✅ Gift: Relationship moderation through lessons, realistic love expectations, balanced affection, grounded romance. ⚠️ Challenge: Romantic excess, over-idealized partners, unrealistic love hopes, relationship extravagance.",
      trine: "Affection and expansion complement each other naturally. ✅ Gift: Natural generous love, effortless joyful relationships, optimistic romance, abundant affection ease, meaningful love. ⚠️ Challenge: May take love abundance for granted, avoiding relationship challenges, complacent in romance.",
      opposition: "Personal romantic values conflict with excessive expectations or moral judgments. ✅ Gift: Relationship wisdom, balance between desires and broader perspectives, love-philosophy integration, romantic perspective. ⚠️ Challenge: Personal versus philosophical love conflicts, romantic versus moral tension, affection versus beliefs.",
      quincunx: "Love values need constant adjustment to changing beliefs or excessive expectations. ✅ Gift: Adaptable romantic expression, flexible love based on growth, versatile affection, situational romance. ⚠️ Challenge: Constant love-belief adjustments, unstable romantic values, never quite indulgent or restrained enough."
    },
    saturn: {
      conjunction: "Love seeks security and commitment, creating serious and lasting affections. ✅ Gift: Committed lasting love, serious mature affection, loyal relationships, secure romance, reliable love, enduring bonds. ⚠️ Challenge: Fear of love, restricted affection, commitment anxiety, difficulty expressing tenderness, heavy relationship burdens.",
      sextile: "Love and commitment support each other through dedicated effort. ✅ Gift: Lasting relationships through work, mature love development, patient affection building, loyal romance over time. ⚠️ Challenge: Requires dedicated relationship effort, love maturity slow to develop, patience needed, delayed romantic gratification.",
      square: "Love needs conflict with fear, restriction, or commitment issues. ✅ Gift: Lasting love capacity through overcoming blocks, mature affection beyond fear, committed romance despite challenges. ⚠️ Challenge: Love fears, commitment struggles, restricted affection, relationship blocks, freedom versus dedication conflicts.",
      trine: "Love and commitment work together effortlessly. ✅ Gift: Natural lasting relationships, effortless mature affection, comfortable commitment, reliable romance without sacrifice. ⚠️ Challenge: May avoid romantic risk, taking commitment for granted, difficulty with romantic spontaneity.",
      opposition: "Love and affection face restrictions, fears, or commitment demands. ✅ Gift: Awareness of freedom-responsibility balance, mature relationship wisdom, committed love integration, romantic-duty awareness. ⚠️ Challenge: Love freedom versus commitment tension, romantic restriction by others, affection versus responsibility.",
      quincunx: "Affectionate expression requires ongoing adaptation to limitations and responsibilities. ✅ Gift: Creative love within constraints, flexible commitment, adaptive affection, strategic romantic expression. ⚠️ Challenge: Constant love-duty adjustments, unstable romantic security, never quite free or committed enough."
    },
    uranus: {
      conjunction: "Love and freedom merge, creating exciting but unpredictable romantic expression. ✅ Gift: Exciting unconventional love, independent relationships, innovative romance, electric attraction, freedom in love, unique affection. ⚠️ Challenge: Relationship instability, fear of commitment, unpredictable affection, inconsistent romance, emotional detachment.",
      sextile: "Romantic expression and freedom enhance each other when consciously balanced. ✅ Gift: Exciting relationships when cultivated, independent love balance, innovative romance development, respectful freedom. ⚠️ Challenge: Requires conscious independence balance, excitement dormant without effort, needs active freedom work.",
      square: "Romantic stability conflicts with need for excitement and independence. ✅ Gift: Authentic love through balancing security-freedom, evolved independent romance, genuine relationships beyond convention. ⚠️ Challenge: Romantic stability versus freedom battles, relationship disruption, commitment versus independence conflicts.",
      trine: "Romantic expression and freedom enhance each other naturally. ✅ Gift: Natural exciting relationships, effortless independent love, comfortable innovative romance, freedom without instability. ⚠️ Challenge: May avoid romantic intimacy, taking uniqueness for granted, difficulty with relationship depth.",
      opposition: "Romantic stability faces need for excitement and independence. ✅ Gift: Awareness of security-freedom tension, balanced innovative love, relationship independence integration, romantic evolution. ⚠️ Challenge: Romantic security versus freedom polarization, relationship stability versus excitement, commitment versus liberation.",
      quincunx: "Romantic stability needs continuous adjustment to changing need for freedom or excitement. ✅ Gift: Flexible relationship patterns, adaptive romantic independence, versatile love-freedom balance, evolving affection. ⚠️ Challenge: Constant romantic freedom adjustments, unstable relationship patterns, never quite secure or free enough."
    },
    neptune: {
      conjunction: "Love seeks transcendence and idealization, creating romantic and spiritual affection. ✅ Gift: Spiritual romantic love, transcendent affection, compassionate relationships, idealistic romance, divine love connection, artistic sensitivity. ⚠️ Challenge: Unrealistic romantic expectations, deceptive relationships, love illusions, victim in romance, boundary dissolution.",
      sextile: "Love and spiritual connection work together through conscious development. ✅ Gift: Compassionate love when cultivated, spiritual romance development, artistic love abilities, transcendent affection practice. ⚠️ Challenge: Requires spiritual relationship work, compassion dormant without practice, needs conscious idealism development.",
      square: "Clear romantic values conflict with illusion, idealization, or deception. ✅ Gift: Discriminating love through challenge, genuine affection beyond fantasy, grounded romance, reality-based relationships. ⚠️ Challenge: Romantic illusions, deceptive relationships, love fantasy versus reality, idealization disappointments.",
      trine: "Love and spiritual connection flow together smoothly. ✅ Gift: Natural compassionate love, effortless spiritual romance, grounded idealism, divine affection ease, artistic love expression. ⚠️ Challenge: May avoid romantic reality, taking spiritual love for granted, difficulty with practical relationships.",
      opposition: "Clear romantic values face idealization, confusion, or deceptive influences. ✅ Gift: Awareness of fantasy versus genuine love, spiritual relationship integration, romantic discernment, love-transcendence balance. ⚠️ Challenge: Romantic clarity versus illusion polarization, genuine versus fantasy love, affection versus escapism.",
      quincunx: "Clear romantic values require ongoing adjustment to spiritual or imaginative influences. ✅ Gift: Adaptive spiritual love, flexible romantic idealism, versatile compassionate affection, transcendent romance adaptation. ⚠️ Challenge: Constant love-spiritual adjustments, unstable romantic clarity, never quite realistic or transcendent enough."
    },
    pluto: {
      conjunction: "Love and transformation unite, creating intense and magnetic attraction. ✅ Gift: Intense magnetic love, transformative relationships, deep passionate affection, profound romantic connection, healing through love, powerful attraction. ⚠️ Challenge: Obsessive relationships, manipulative charm, possessive love, jealous affection, controlling through beauty.",
      sextile: "Affection and transformation support each other through conscious emotional work. ✅ Gift: Deep relationship abilities when developed, transformative love cultivation, psychological romance insights, healing affection. ⚠️ Challenge: Requires deep relationship work, transformation dormant without shadow work, needs conscious depth.",
      square: "Surface affection conflicts with deep emotional and sexual intensity. ✅ Gift: Transformed love through confronting shadow, authentic affection beyond manipulation, profound relationships, evolved romance. ⚠️ Challenge: Jealousy struggles, possessiveness battles, love power dynamics, romantic obsessions, relationship crises.",
      trine: "Affection and transformation work together harmoniously. ✅ Gift: Natural deep relationships, effortless transformative love, comfortable intensity, profound affection without manipulation. ⚠️ Challenge: May avoid light romance, taking depth for granted, difficulty with surface affection.",
      opposition: "Surface affection faces deep transformation and power dynamics. ✅ Gift: Awareness of hidden relationship patterns, balance between surface and depth, love power objectivity, transformative romance wisdom. ⚠️ Challenge: Surface versus deep love polarization, affection versus power conflicts, romantic manipulation dynamics.",
      quincunx: "Surface affection needs constant adjustment to deep transformation and power dynamics. ✅ Gift: Flexible romantic depth, adaptive love intensity, versatile affection-power balance, strategic intimacy. ⚠️ Challenge: Constant love depth adjustments, unstable romantic intensity, never quite light or profound enough."
    }
  },
  mars: {
    jupiter: {
      conjunction: "Action and expansion merge, creating enthusiastic and ambitious energy. ✅ Gift: Enthusiastic bold action, ambitious confident energy, adventurous spirit, generous assertion, successful endeavors, optimistic courage. ⚠️ Challenge: Overconfident action, taking on too much, overreach, poor timing, reckless ambition.",
      sextile: "Action and expansion support each other when opportunities are actively pursued. ✅ Gift: Confident action toward growth when developed, adventurous courage through practice, strategic boldness, successful risk-taking. ⚠️ Challenge: Requires seizing opportunities, boldness dormant without action, needs conscious courage application.",
      square: "Impulsive action conflicts with expansive judgment, creating overreach and poor timing. ✅ Gift: Strategic wisdom through lessons, balanced enthusiasm with realism, proper timing learned through experience, measured ambition. ⚠️ Challenge: Overreach, poor timing, excessive enthusiasm, unrealistic action plans, reckless ventures.",
      trine: "Action and expansion flow together naturally, creating confident and successful endeavors. ✅ Gift: Natural bold successful action, effortless ambitious achievement, good timing, confident courage, beneficial risk-taking. ⚠️ Challenge: May take success for granted, overconfidence from ease, avoiding necessary caution.",
      opposition: "Personal action faces excessive expansion or moral judgment. ✅ Gift: Awareness of assertion-philosophy balance, strategic action wisdom, integrated courage-beliefs, measured boldness. ⚠️ Challenge: Action versus philosophy conflicts, assertion versus moral judgment, courage versus restraint.",
      quincunx: "Action requires ongoing adjustment to expanding opportunities or changing beliefs. ✅ Gift: Tactical action flexibility, adaptive courage strategies, versatile assertiveness, evolving boldness. ⚠️ Challenge: Constant action-opportunity adjustments, unstable assertion patterns, never quite bold or cautious enough."
    },
    saturn: {
      conjunction: "Action meets restriction, creating disciplined but potentially frustrated energy. ✅ Gift: Disciplined controlled action, sustained methodical energy, long-term goal achievement, patient assertion, enduring efforts. ⚠️ Challenge: Frustrated action, anger about limitations, blocked energy, overly controlling behavior, restricted assertion.",
      sextile: "Disciplined action and structure work together through consistent effort. ✅ Gift: Long-term goal accomplishment through work, methodical sustained action, committed assertion, patient achievement. ⚠️ Challenge: Requires consistent disciplined effort, slow action results, patience needed, delayed action gratification.",
      square: "Dynamic action conflicts with limitations and fear, creating frustration and blocked energy. ✅ Gift: Authentic power through working within constraints, assertive energy despite restrictions, strength through frustration. ⚠️ Challenge: Blocked action, intense frustration, fear restricts assertion, anger at limitations, constrained energy.",
      trine: "Dynamic action and discipline complement each other effortlessly. ✅ Gift: Natural methodical long-term achievement, effortless disciplined action, comfortable sustained assertion, patient success. ⚠️ Challenge: May avoid action risks, taking discipline for granted, difficulty with spontaneous action.",
      opposition: "Dynamic energy faces restrictions, limitations, or authoritarian control. ✅ Gift: Awareness of assertion-structure balance, respectful assertiveness, strategic action within limits, measured energy. ⚠️ Challenge: Action versus structure conflicts, dynamic versus restricted energy, assertion versus authority.",
      quincunx: "Dynamic energy needs constant adjustment to limitations and responsibilities. ✅ Gift: Creative action within constraints, flexible disciplined energy, adaptive assertiveness, strategic patient action. ⚠️ Challenge: Constant action-limitation adjustments, unstable energy patterns, never quite free or disciplined enough."
    },
    uranus: {
      conjunction: "Action and innovation unite, creating explosive and unpredictable energy. ✅ Gift: Explosive breakthrough action, unpredictable innovative energy, revolutionary assertion, original bold moves, inventive courage. ⚠️ Challenge: Reckless behavior, inability to sustain action, erratic energy, inconsistent assertion, disruptive impulses.",
      sextile: "Dynamic action and innovation enhance each other when consciously directed. ✅ Gift: Breakthrough action abilities when developed, original assertiveness through exploration, innovative courage cultivation. ⚠️ Challenge: Requires conscious experimental direction, innovation dormant without risk, needs active originality.",
      square: "Consistent action conflicts with need for freedom and innovation. ✅ Gift: Authentic rebellion through balanced revolutionary-constructive action, evolved innovative assertion, genuine freedom energy. ⚠️ Challenge: Inconsistent action, freedom versus discipline battles, rebellious versus constructive conflict, disruptive energy.",
      trine: "Purposeful action and innovation work together harmoniously. ✅ Gift: Natural original action, effortless breakthrough implementation, comfortable innovative assertion, stable revolutionary energy. ⚠️ Challenge: May avoid sustained effort, taking originality for granted, difficulty with consistent action.",
      opposition: "Consistent action faces revolutionary change or need for complete freedom. ✅ Gift: Awareness of sustained-breakthrough tension, balanced innovative action, integrated consistency-freedom energy. ⚠️ Challenge: Sustained versus innovative action polarization, consistent versus freedom energy, discipline versus revolution.",
      quincunx: "Consistent action requires ongoing adaptation to changing need for freedom or innovation. ✅ Gift: Flexible action strategies, adaptive innovative energy, versatile assertion approaches, evolving courage. ⚠️ Challenge: Constant action-freedom adjustments, unstable energy patterns, never quite consistent or innovative enough."
    },
    neptune: {
      conjunction: "Action becomes inspired but potentially confused, creating spiritual warrior energy. ✅ Gift: Inspired spiritual action, compassionate warrior energy, idealistic courage, transcendent assertion, fighting for higher causes. ⚠️ Challenge: Misdirected action, confused energy, fighting for unclear causes, escapist assertion, victim warrior.",
      sextile: "Purposeful action and spiritual inspiration support each other through conscious alignment. ✅ Gift: Idealistic cause action when developed, inspired courage through spiritual practice, compassionate assertion cultivation. ⚠️ Challenge: Requires conscious spiritual alignment, inspiration dormant without practice, needs active higher guidance.",
      square: "Clear action conflicts with confusion, idealism, or deceptive influences. ✅ Gift: Discerning action through challenge, inspired versus escapist discrimination, grounded idealistic courage, clarity in assertion. ⚠️ Challenge: Confused action, deceptive energy directions, misdirected efforts, escapist versus inspired battles.",
      trine: "Clear action and spiritual inspiration enhance each other naturally. ✅ Gift: Natural inspired effective action, effortless idealistic practical courage, comfortable compassionate assertion, spiritual warrior ease. ⚠️ Challenge: May avoid material action, taking inspiration for granted, difficulty with practical assertion.",
      opposition: "Clear action faces confusion, idealism, or spiritual surrender. ✅ Gift: Awareness of assertion-compassion balance, integrated action-service, grounded spiritual courage, strategic selfless energy. ⚠️ Challenge: Action versus surrender polarization, assertion versus compassion, clear versus confused energy.",
      quincunx: "Clear action needs continuous adjustment to spiritual influences or imaginative inspiration. ✅ Gift: Adaptive inspired action, flexible spiritual energy, versatile compassionate assertion, evolving idealistic courage. ⚠️ Challenge: Constant action-spiritual adjustments, unstable inspired energy, never quite clear or transcendent enough."
    },
    pluto: {
      conjunction: "Action and transformation merge, creating intense and potentially destructive power. ✅ Gift: Intense powerful action, transformative assertion energy, profound courage, regenerative efforts, deep change capacity. ⚠️ Challenge: Compulsive aggression, obsessive goal pursuit, destructive power, manipulative action, controlling energy.",
      sextile: "Dynamic action and transformative power work together through conscious direction. ✅ Gift: Powerful change action when developed, transformative courage through psychological work, deep assertion cultivation. ⚠️ Challenge: Requires conscious psychological direction, power dormant without shadow work, needs active depth exploration.",
      square: "Personal action conflicts with deep transformative forces and power struggles. ✅ Gift: Authentic power through confronting manipulation, channeled intense energy constructively, evolved assertiveness beyond control. ⚠️ Challenge: Action power struggles, compulsive energy patterns, manipulative assertion, destructive versus constructive battles.",
      trine: "Dynamic action and transformative power complement each other smoothly. ✅ Gift: Natural powerful effective action, effortless deep change capacity, comfortable intense assertion, smooth transformative energy. ⚠️ Challenge: May avoid surface action, taking power for granted, difficulty with light assertion.",
      opposition: "Personal action faces intense transformative pressure and power dynamics. ✅ Gift: Awareness of manipulation dynamics, balance between assertion and surrender, integrated action-transformation, strategic power use. ⚠️ Challenge: Action versus transformation polarization, assertion versus surrender, personal versus deep forces.",
      quincunx: "Personal action requires ongoing adjustment to transformative pressures and power dynamics. ✅ Gift: Flexible transformative action, adaptive power use, versatile psychological assertion, strategic deep energy. ⚠️ Challenge: Constant action-power adjustments, unstable transformative energy, never quite assertive or surrendered enough."
    }
  },
  jupiter: {
    saturn: {
      conjunction: "Expansion and limitation merge, creating disciplined growth and structured optimism. ✅ Gift: Realistic successful growth, practical optimism, disciplined abundance, structured faith, enduring achievements, balanced ambition. ⚠️ Challenge: Conflicted beliefs about success, alternating excessive confidence and pessimism, restricted growth, limited faith.",
      sextile: "Optimistic expansion and practical structure support each other through conscious effort. ✅ Gift: Lasting success building when developed, realistic optimism through work, disciplined growth cultivation, patient achievement. ⚠️ Challenge: Requires consistent structural effort, slow growth manifestation, patience needed, delayed optimism rewards.",
      square: "Optimistic expansion conflicts with practical limitations and conservative restraint. ✅ Gift: Realistic optimism through lessons, balanced faith with practicality, wisdom from failures, growth within constraints. ⚠️ Challenge: Faith versus practical reality conflicts, optimism restricted by circumstances, growth blocked by limitations.",
      trine: "Expansion and structure work together harmoniously, creating successful and enduring growth. ✅ Gift: Natural lasting success, effortless realistic optimism, comfortable disciplined growth, balanced faith-realism, sustainable achievements. ⚠️ Challenge: May take success for granted, avoiding bold risks, complacent growth, underestimating challenges.",
      opposition: "Optimistic expansion faces practical limitations and conservative restraint. ✅ Gift: Awareness of faith-realism balance, integration of growth and responsibility, optimism-structure wisdom, strategic expansion. ⚠️ Challenge: Faith versus realism polarization, growth versus responsibility conflicts, optimism versus limitation tension.",
      quincunx: "Optimistic expansion requires ongoing adjustment to practical limitations and responsibilities. ✅ Gift: Realistic adaptive goal-setting, flexible growth plans, versatile optimism-structure balance, practical faith evolution. ⚠️ Challenge: Constant growth-limitation adjustments, unstable expansion patterns, never quite optimistic or realistic enough."
    },
    uranus: {
      conjunction: "Expansion and innovation unite, creating revolutionary beliefs and sudden opportunities. ✅ Gift: Revolutionary progressive beliefs, sudden breakthrough opportunities, innovative philosophical expansion, freedom-seeking wisdom, experimental growth. ⚠️ Challenge: Unrealistic expectations about change, extremist philosophical positions, unstable beliefs, chaotic growth.",
      sextile: "Philosophical growth and innovative insights work together when actively explored. ✅ Gift: Progressive beliefs when cultivated, consciousness expansion through experimentation, innovative wisdom development, breakthrough philosophy. ⚠️ Challenge: Requires experimental exploration, progressive beliefs dormant without risk, needs conscious innovation pursuit.",
      square: "Philosophical beliefs conflict with need for revolutionary change or complete freedom. ✅ Gift: Authentic beliefs through questioning tradition, integrated conventional-revolutionary philosophy, evolved progressive wisdom, genuine freedom understanding. ⚠️ Challenge: Belief system disruptions, philosophical rebellion, tradition versus innovation conflicts, unstable faith.",
      trine: "Philosophical expansion and innovation complement each other naturally. ✅ Gift: Natural progressive beliefs, effortless experimental growth, comfortable innovative wisdom, freedom philosophy without disruption. ⚠️ Challenge: May avoid traditional wisdom, taking progressive beliefs for granted, difficulty with conventional philosophy.",
      opposition: "Established beliefs face revolutionary insights and need for complete philosophical freedom. ✅ Gift: Awareness of tradition-innovation tension, balanced progressive beliefs, integrated conventional-revolutionary wisdom, philosophical versatility. ⚠️ Challenge: Established versus revolutionary beliefs polarization, tradition versus innovation philosophy, faith versus freedom.",
      quincunx: "Established beliefs need constant adjustment to innovative insights and changing freedom needs. ✅ Gift: Philosophical flexibility, adaptive belief systems, versatile wisdom approach, evolving progressive faith. ⚠️ Challenge: Constant belief-innovation adjustments, unstable philosophical foundation, never quite traditional or revolutionary enough."
    },
    neptune: {
      conjunction: "Expansion and transcendence merge, creating spiritual idealism and inspirational beliefs. ✅ Gift: Spiritual idealistic faith, inspirational philosophical beliefs, compassionate wisdom, transcendent optimism, service-oriented growth, divine connection. ⚠️ Challenge: Impractical spirituality, faith versus wishful thinking confusion, escapist beliefs, unrealistic spiritual expectations.",
      sextile: "Optimistic expansion and spiritual inspiration enhance each other through conscious development. ✅ Gift: Philosophical compassion when cultivated, spiritual growth through service, inspired optimism development, transcendent wisdom practice. ⚠️ Challenge: Requires conscious spiritual development, compassion dormant without practice, needs active faith cultivation.",
      square: "Realistic optimism conflicts with idealistic confusion or escapist spirituality. ✅ Gift: Discriminating faith through lessons, genuine inspiration versus wishful thinking discernment, grounded spiritual beliefs, practical idealism. ⚠️ Challenge: Faith confusion, spiritual versus practical conflicts, idealistic disappointments, escapist versus realistic beliefs.",
      trine: "Optimistic growth and spiritual inspiration flow together smoothly. ✅ Gift: Natural faith and compassion, effortless spiritual wisdom, comfortable transcendent beliefs, meaningful service, inspired optimism ease. ⚠️ Challenge: May avoid practical reality, taking spiritual gifts for granted, difficulty with material concerns.",
      opposition: "Realistic optimism faces idealistic confusion or escapist spirituality. ✅ Gift: Awareness of genuine faith versus illusion, balance between practical and transcendent beliefs, grounded spiritual wisdom, integrated optimism-compassion. ⚠️ Challenge: Realistic versus idealistic polarization, practical versus spiritual beliefs, optimism versus escapism tension.",
      quincunx: "Realistic optimism requires ongoing adaptation to spiritual influences and imaginative inspiration. ✅ Gift: Adaptive spiritual beliefs, flexible faith systems, versatile optimism-compassion balance, evolving transcendent wisdom. ⚠️ Challenge: Constant belief-spiritual adjustments, unstable faith foundation, never quite practical or transcendent enough."
    },
    pluto: {
      conjunction: "Expansion and transformation unite, creating powerful beliefs and intense convictions. ✅ Gift: Powerful transformative beliefs, intense philosophical convictions, profound wisdom, regenerative faith, deep psychological expansion, empowered growth. ⚠️ Challenge: Fanatical beliefs, compulsive conversion needs, dogmatic philosophy, manipulative faith, power-hungry expansion.",
      sextile: "Growth-oriented beliefs and transformative insights support each other through conscious exploration. ✅ Gift: Deep psychological growth when developed, transformative wisdom through exploration, profound philosophical insights, regenerative expansion. ⚠️ Challenge: Requires deep psychological work, transformation dormant without shadow exploration, needs conscious depth pursuit.",
      square: "Optimistic beliefs conflict with deep psychological truths and power dynamics. ✅ Gift: Transformed philosophical understanding through crisis, authentic beliefs beyond dogma, wisdom confronting shadow, evolved faith through struggle. ⚠️ Challenge: Belief power struggles, philosophical crises, dogmatic thinking battles, optimism versus dark truths conflicts.",
      trine: "Expansive beliefs and transformative power work together effortlessly. ✅ Gift: Natural deep wisdom, effortless psychological growth, comfortable profound beliefs, regenerative philosophy without manipulation. ⚠️ Challenge: May avoid surface philosophy, taking depth for granted, difficulty with light beliefs.",
      opposition: "Optimistic beliefs face intense transformation and psychological depth. ✅ Gift: Awareness of shadow in philosophy, balance between surface optimism and deep truth, integrated light-dark beliefs, transformative wisdom objectivity. ⚠️ Challenge: Surface versus deep philosophy polarization, optimism versus psychological truth, faith versus transformation.",
      quincunx: "Expansive beliefs need continuous adjustment to transformative pressures and psychological insights. ✅ Gift: Flexible transformative philosophy, adaptive profound wisdom, versatile optimism-depth balance, evolving psychological faith. ⚠️ Challenge: Constant belief-transformation adjustments, unstable philosophical depth, never quite optimistic or profound enough."
    }
  },
  saturn: {
    uranus: {
      conjunction: "Structure and innovation merge, creating revolutionary discipline or restricted freedom. ✅ Gift: Revolutionary disciplined systems, innovative tradition-building, structured freedom, progressive authority, methodical innovation, evolved discipline. ⚠️ Challenge: Authoritarian rebellion, structure versus freedom conflicts, restricted innovation, rigid revolution, conflicted discipline.",
      sextile: "Disciplined structure and innovation support each other through conscious effort. ✅ Gift: Innovative system building when developed, progressive change through method, disciplined freedom cultivation, structured breakthrough implementation. ⚠️ Challenge: Requires consistent innovative effort, slow progressive change, patience with revolution needed, delayed freedom rewards.",
      square: "Structural limitation conflicts with need for innovation and freedom. ✅ Gift: Authentic authority balancing tradition-progress, evolved discipline through innovation challenges, integrated stability-revolution, flexible structure through struggle. ⚠️ Challenge: Structure versus freedom battles, tradition versus innovation conflicts, authority versus liberation, rigid versus revolutionary.",
      trine: "Structure and innovation work together harmoniously. ✅ Gift: Natural progressive methodical systems, effortless innovative tradition, comfortable structured freedom, enduring breakthrough implementations. ⚠️ Challenge: May avoid radical change, taking progressive stability for granted, difficulty with complete revolution.",
      opposition: "Established structure faces revolutionary change and need for complete freedom. ✅ Gift: Awareness of stability-innovation balance, integration of tradition and progress, strategic revolutionary discipline, evolved authority-freedom. ⚠️ Challenge: Structure versus revolution polarization, tradition versus innovation, authority versus liberation tension.",
      quincunx: "Structured approach requires ongoing adjustment to innovative insights and changing freedom needs. ✅ Gift: Flexible disciplined innovation, adaptive systematic freedom, versatile authority-revolution balance, evolving structured progress. ⚠️ Challenge: Constant structure-innovation adjustments, unstable disciplined freedom, never quite stable or revolutionary enough."
    },
    neptune: {
      conjunction: "Structure and transcendence unite, creating spiritual discipline or crystallized illusions. ✅ Gift: Spiritual disciplined practice, practical mysticism, grounded transcendence, organized service, structured compassion, manifested ideals. ⚠️ Challenge: Rigid spirituality, crystallized illusions, structure versus transcendence conflicts, materialized escapism.",
      sextile: "Practical structure and spiritual inspiration work together when consciously developed. ✅ Gift: Manifested spiritual ideals through work, disciplined service practice, organized compassion cultivation, structured transcendence development. ⚠️ Challenge: Requires consistent spiritual effort, slow ideal manifestation, patience with service needed, delayed transcendence rewards.",
      square: "Practical structure conflicts with spiritual idealism and imaginative confusion. ✅ Gift: Discriminating spiritual discipline through lessons, practical versus escapist discernment, grounded mysticism, authentic structured service. ⚠️ Challenge: Structure versus spiritual conflicts, practical versus idealistic battles, discipline restricts transcendence, rigid versus dissolving.",
      trine: "Practical discipline and spiritual inspiration complement each other naturally. ✅ Gift: Natural manifested spirituality, effortless organized service, comfortable grounded transcendence, sustained spiritual practice ease. ⚠️ Challenge: May avoid material reality, taking spiritual discipline for granted, difficulty with practical concerns.",
      opposition: "Practical discipline faces spiritual idealism and imaginative dissolution. ✅ Gift: Awareness of earthly-transcendent balance, integration of responsibility and service, strategic structured compassion, material-spiritual wisdom. ⚠️ Challenge: Practical versus spiritual polarization, responsibility versus transcendence, structure versus dissolution tension.",
      quincunx: "Practical structure needs constant adjustment to spiritual influences and imaginative inspiration. ✅ Gift: Adaptive disciplined spirituality, flexible structured service, versatile practical-transcendent balance, evolving organized compassion. ⚠️ Challenge: Constant structure-spiritual adjustments, unstable disciplined transcendence, never quite practical or spiritual enough."
    },
    pluto: {
      conjunction: "Limitation and transformation merge, creating intense pressure for structured change. ✅ Gift: Transformative disciplined power, structured regeneration, profound methodical change, empowered authority, deep systematic transformation. ⚠️ Challenge: Oppressive control, authoritarian manipulation, rigid transformation demands, power-hungry discipline, destructive structure.",
      sextile: "Structured discipline and transformative power support each other through conscious application. ✅ Gift: Deep transformation through sustained work, systematic psychological change when developed, methodical regeneration cultivation, disciplined empowerment. ⚠️ Challenge: Requires consistent deep work, slow transformation progress, patience with regeneration needed, delayed power rewards.",
      square: "Established structure conflicts with deep transformative forces and power dynamics. ✅ Gift: Authentic power beyond control through struggle, transformed authority confronting shadow, evolved discipline through psychological crisis, genuine structured empowerment. ⚠️ Challenge: Authority power struggles, control versus transformation battles, structural crises, rigid versus regenerative conflicts.",
      trine: "Structured approach and transformative power flow together smoothly. ✅ Gift: Natural deep methodical transformation, effortless systematic regeneration, comfortable disciplined empowerment, sustained psychological change ease. ⚠️ Challenge: May avoid surface structure, taking transformative discipline for granted, difficulty with light authority.",
      opposition: "Structural authority faces intense transformation and power dynamics. ✅ Gift: Awareness of authentic versus controlling authority, balance between structure and transformation, strategic disciplined empowerment, evolved power-discipline integration. ⚠️ Challenge: Authority versus transformation polarization, control versus regeneration, structure versus deep change tension.",
      quincunx: "Established structure requires ongoing adjustment to transformative pressures and power dynamics. ✅ Gift: Flexible disciplined transformation, adaptive systematic empowerment, versatile authority-power balance, evolving structured regeneration. ⚠️ Challenge: Constant structure-transformation adjustments, unstable disciplined empowerment, never quite stable or transformed enough."
    }
  },
  uranus: {
    neptune: {
      conjunction: "Innovation and transcendence merge, creating spiritual revolution or confused idealism. ✅ Gift: Spiritual revolutionary breakthrough, mystical innovation, progressive transcendence, inspired freedom, visionary idealism, breakthrough spiritual insights (generational). ⚠️ Challenge: Impractical confused spirituality, escapist revolution, unrealistic mystical expectations, chaotic transcendence, idealistic instability.",
      sextile: "Innovation and spiritual inspiration support each other through conscious exploration. ✅ Gift: Revolutionized spiritual understanding when cultivated, progressive transcendence development, innovative mysticism practice, breakthrough compassion (generational opportunity). ⚠️ Challenge: Requires conscious spiritual experimentation, mystical innovation dormant without exploration, needs active progressive spirituality.",
      square: "Revolutionary change conflicts with spiritual idealism and imaginative confusion. ✅ Gift: Authentic innovation distinguishing breakthrough from fantasy, evolved progressive spirituality, genuine revolutionary compassion, grounded visionary mysticism (generational tension). ⚠️ Challenge: Revolutionary versus escapist conflicts, innovation versus illusion battles, freedom versus spiritual confusion, breakthrough versus fantasy.",
      trine: "Innovation and spiritual inspiration flow together harmoniously. ✅ Gift: Natural revolutionary spiritual understanding, effortless progressive transcendence, comfortable breakthrough mysticism, innovative compassion without disruption (generational harmony). ⚠️ Challenge: May avoid material innovation, taking spiritual progressiveness for granted, difficulty with practical revolution.",
      opposition: "Revolutionary change faces spiritual idealism and imaginative dissolution. ✅ Gift: Awareness of innovation-transcendence balance, integration of progressive and spiritual service, strategic revolutionary compassion (generational awareness). ⚠️ Challenge: Revolutionary versus spiritual polarization, innovation versus transcendence, freedom versus surrender tension.",
      quincunx: "Innovative insights require ongoing adjustment to spiritual influences and imaginative inspiration. ✅ Gift: Adaptive revolutionary spirituality, flexible innovative transcendence, versatile freedom-compassion balance, evolving progressive mysticism. ⚠️ Challenge: Constant innovation-spiritual adjustments, unstable revolutionary transcendence, never quite breakthrough or transcendent enough."
    },
    pluto: {
      conjunction: "Innovation and transformation unite, creating revolutionary change or destructive rebellion. ✅ Gift: Revolutionary transformative breakthrough, powerful innovative regeneration, profound freedom change, explosive empowerment, radical rebirth (generational power). ⚠️ Challenge: Extreme destructive upheaval, rebellious power struggles, chaotic transformation, disruptive regeneration, revolutionary violence.",
      sextile: "Revolutionary change and transformative power work together when consciously directed. ✅ Gift: Breakthrough systematic transformation when developed, innovative psychological regeneration, revolutionary empowerment cultivation, progressive deep change (generational potential). ⚠️ Challenge: Requires conscious revolutionary direction, transformation dormant without radical work, needs active breakthrough empowerment.",
      square: "Need for freedom conflicts with deep transformative pressures and power dynamics. ✅ Gift: Revolutionary transformation beyond control through struggle, authentic liberation confronting shadow, evolved freedom through psychological crisis (generational upheaval). ⚠️ Challenge: Freedom versus power battles, liberation versus control conflicts, revolutionary crises, radical versus regenerative tensions.",
      trine: "Revolutionary energy and transformative power complement each other naturally. ✅ Gift: Natural breakthrough regenerative transformation, effortless revolutionary empowerment, comfortable radical rebirth without destruction (generational ease). ⚠️ Challenge: May avoid gradual change, taking revolutionary power for granted, difficulty with incremental transformation.",
      opposition: "Need for complete freedom faces intense transformation and power dynamics. ✅ Gift: Awareness of liberation versus empowerment distinction, balance between freedom and transformation, strategic revolutionary regeneration (generational tension awareness). ⚠️ Challenge: Freedom versus transformation polarization, liberation versus power, radical change versus deep regeneration.",
      quincunx: "Revolutionary energy needs constant adjustment to transformative pressures and power dynamics. ✅ Gift: Flexible innovative transformation, adaptive revolutionary empowerment, versatile freedom-power balance, evolving radical regeneration. ⚠️ Challenge: Constant revolution-transformation adjustments, unstable breakthrough empowerment, never quite free or transformed enough."
    }
  },
  neptune: {
    pluto: {
      conjunction: "Transcendence and transformation merge, creating spiritual regeneration or confused power dynamics. ✅ Gift: Spiritual transformative regeneration, transcendent psychological empowerment, profound compassionate rebirth, mystical deep change, divine power (rare generational). ⚠️ Challenge: Confused idealistic manipulation, spiritual power abuse, escapist transformation, mystical control, illusion versus empowerment.",
      sextile: "Spiritual inspiration and transformative power support each other through conscious development. ✅ Gift: Transformation through spiritual practice when developed, regenerative compassion cultivation, psychological transcendence service, profound mystical empowerment (generational opportunity). ⚠️ Challenge: Requires conscious spiritual-psychological work, transcendent transformation dormant without practice, needs active mystical depth.",
      square: "Spiritual idealism conflicts with deep transformative forces and power dynamics. ✅ Gift: Authentic spirituality beyond materialism through confrontation, evolved transcendence versus escapism discernment, genuine mystical empowerment (generational tension). ⚠️ Challenge: Spiritual versus psychological battles, transcendence versus power conflicts, idealistic manipulation, escapist versus transformative.",
      trine: "Spiritual inspiration and transformative power flow together harmoniously. ✅ Gift: Natural spiritual psychological transformation, effortless regenerative transcendence, comfortable mystical empowerment without manipulation (generational harmony). ⚠️ Challenge: May avoid material power, taking spiritual transformation for granted, difficulty with earthly empowerment.",
      opposition: "Spiritual transcendence faces intense transformation and power dynamics. ✅ Gift: Awareness of surrender-empowerment balance, integration of spiritual and psychological transformation, strategic mystical regeneration (rare generational awareness). ⚠️ Challenge: Spiritual versus psychological polarization, transcendence versus transformation, surrender versus empowerment tension.",
      quincunx: "Spiritual influences require ongoing adjustment to transformative pressures and power dynamics. ✅ Gift: Adaptive transcendent transformation, flexible mystical empowerment, versatile spiritual-psychological balance, evolving compassionate regeneration. ⚠️ Challenge: Constant spiritual-transformation adjustments, unstable transcendent empowerment, never quite surrendered or empowered enough."
    }
  }
};