/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Comfort Zone Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * comfort zones, safety needs, security patterns, and the environments
 * where you feel most at ease and naturally yourself.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Comfort Zone - Where you feel most safe, secure, and naturally yourself
 */
export const comfortZoneInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your comfort zone is found in environments where you can take leadership, express your creative vision, and maintain a sense of personal power and autonomy. You feel most secure when you're in control of your circumstances and have the freedom to initiate new projects and ideas. Your safety comes from being able to express your authentic self without constraint and having the authority to make decisions that affect your life and direction.",
    positive: "Natural confidence and self-assurance that allows you to feel comfortable in leadership roles and new situations where others might feel uncertain. Your comfort with taking charge and expressing your vision creates opportunities for growth and achievement that others might miss due to fear or hesitation. You inspire confidence in others through your own sense of security and certainty about your capabilities and direction.",
    challenge: "May feel uncomfortable or insecure in situations where you can't take the lead or must follow others' directions for extended periods of time. Tendency to avoid environments that require patience, collaboration, or deference to others' authority, potentially limiting your growth and learning opportunities. Can become anxious or stressed when forced to remain passive or wait for others to make decisions that affect your life.",
    advice: "Expand your comfort zone by learning to find security in collaborative environments and situations where you can contribute your strengths without needing to control every aspect of the process. Practice finding your authentic voice and power even in situations where you're not officially in charge. Build confidence in your ability to influence and contribute positively regardless of your formal role or position."
  },
  2: {
    general: "Your comfort zone is characterized by quiet, reflective environments where you can access your intuition and inner wisdom without external pressure or overwhelming stimulation. You feel most secure in spaces that honor mystery, subtlety, and emotional depth, preferring intimate settings over large groups or public attention. Your safety comes from having time for inner reflection and the ability to process experiences privately before sharing them with others.",
    positive: "Deep inner wisdom and intuitive understanding that provides security and guidance even in uncertain situations. Your comfort with mystery and the unknown allows you to navigate ambiguous circumstances with grace and trust in your inner knowing. You create sacred spaces and peaceful environments that feel healing and restorative for yourself and others who appreciate depth and contemplation.",
    challenge: "May feel overwhelmed or anxious in loud, chaotic, or highly stimulating environments that don't allow for quiet reflection and inner processing. Tendency to avoid situations that require quick decisions, public speaking, or assertive action before you've had adequate time for inner consultation. Can become stressed when forced to share your thoughts or feelings before you feel ready or when others pressure you for immediate responses.",
    advice: "Gradually expand your comfort zone by finding ways to access your inner wisdom and sense of safety even in more active or stimulating environments. Practice trusting your intuition to guide you in real-time rather than always needing extensive quiet time before acting. Develop strategies for maintaining your inner peace and connection to wisdom while still engaging actively with the world around you."
  },
  3: {
    general: "Your comfort zone is found in beautiful, nurturing environments where you can express creativity, share abundance, and enjoy sensual pleasures in the company of people who appreciate beauty and harmony. You feel most secure when surrounded by aesthetic beauty, natural abundance, and opportunities for creative expression and artistic appreciation. Your safety comes from environments that feel fertile, generous, and supportive of growth and creative manifestation.",
    positive: "Natural ability to create comfortable, beautiful spaces that feel welcoming and nourishing for yourself and others. Your appreciation for beauty and comfort helps you recognize and seek out environments that truly support your well-being and creative expression. You excel at making any space feel more beautiful and comfortable through your attention to aesthetic details and sensual pleasure.",
    challenge: "May feel uncomfortable or depleted in harsh, sterile, or aesthetically unappealing environments that don't provide sensual satisfaction or creative inspiration. Tendency to avoid situations that feel scarce, competitive, or lacking in beauty and abundance, potentially limiting your resilience and adaptability. Can become anxious or depressed when forced to spend time in environments that feel spiritually or aesthetically impoverished.",
    advice: "Learn to find or create beauty and comfort even in challenging environments, recognizing that your ability to appreciate and manifest beauty is portable and not dependent on external circumstances. Practice finding security in your own creative abilities rather than requiring perfect external conditions for comfort. Develop resilience by gradually exposing yourself to less ideal environments while maintaining your connection to inner beauty and abundance."
  },
  4: {
    general: "Your comfort zone is built on structure, routine, and predictable environments where you can rely on established systems and consistent patterns. You feel most secure when you have clear rules, defined responsibilities, and stable foundations that you can count on over time. Your safety comes from having organized systems, reliable routines, and the assurance that your basic needs will be met through consistent effort and planning.",
    positive: "Natural ability to create stable, secure environments and systems that provide lasting comfort and security for yourself and others. Your commitment to building solid foundations creates resilience and the ability to weather challenges through preparation and consistent effort. You excel at creating order and structure that allows others to feel safe and supported in achieving their goals.",
    challenge: "May feel anxious or uncomfortable in unpredictable situations that require flexibility, spontaneity, or adaptation to rapidly changing circumstances. Tendency to avoid new experiences or opportunities that don't fit within your established routines and comfort patterns, potentially limiting growth and discovery. Can become stressed when your structures and systems are disrupted even temporarily or when others challenge your preferred ways of organizing life.",
    advice: "Gradually expand your comfort zone by introducing small changes and variations into your routines while maintaining the core structure that provides your security. Practice finding stability within yourself rather than depending entirely on external structures and systems for comfort. Build confidence in your ability to adapt and create new structures when necessary while honoring your genuine need for consistency and order."
  },
  5: {
    general: "Your comfort zone is found within traditional structures, established institutions, and environments that honor conventional wisdom and moral principles. You feel most secure when you can operate within accepted guidelines and belief systems that provide clear moral and ethical direction. Your safety comes from being part of communities and traditions that share your values and provide structured guidance for living according to time-tested principles.",
    positive: "Deep sense of security that comes from connection to traditional wisdom and established moral frameworks that have provided guidance for many people over time. Your respect for conventional approaches and proven systems helps you avoid common pitfalls and benefit from accumulated human wisdom. You provide stability and moral grounding that helps others feel secure and guided in their own development.",
    challenge: "May feel uncomfortable or lost in situations that require questioning traditional approaches or operating outside established moral and social frameworks. Tendency to avoid environments or relationships that challenge your belief systems or require you to think independently outside conventional wisdom. Can become anxious when faced with moral ambiguity or situations where traditional guidelines don't provide clear direction.",
    advice: "Expand your comfort zone by learning to find security in your own moral compass and inner wisdom while still honoring valuable traditional guidance and community support. Practice thinking independently about ethical issues while maintaining connection to the wisdom traditions that provide your foundation. Develop confidence in your ability to navigate new situations using both traditional wisdom and personal discernment."
  },
  6: {
    general: "Your comfort zone is characterized by harmonious, beautiful environments where relationships are balanced, conflicts are minimal, and aesthetic pleasure is prioritized. You feel most secure in partnerships and social situations where everyone feels appreciated and valued. Your safety comes from mutual respect, shared aesthetic values, and environments where beauty and harmony take precedence over conflict or competition.",
    positive: "Natural ability to create harmonious, aesthetically pleasing environments that feel comfortable and welcoming for everyone involved. Your diplomatic skills and appreciation for balance help you navigate social situations gracefully and find compromise solutions that satisfy multiple parties. You excel at making others feel valued and appreciated, creating lasting comfort through relationship harmony.",
    challenge: "May feel extremely uncomfortable in conflictual environments or situations that require taking sides, making difficult decisions, or dealing with interpersonal tension. Tendency to avoid necessary confrontations or difficult conversations, potentially allowing problems to persist rather than addressing them directly. Can become stressed when forced to make decisions that might disappoint others or disrupt existing harmony.",
    advice: "Learn to find security in your ability to navigate conflict constructively rather than avoiding all tension and disagreement. Practice making difficult decisions based on your authentic values even when they temporarily disrupt harmony or disappoint others. Develop comfort with the natural fluctuations in relationships while maintaining your gift for creating beauty and balance."
  },
  7: {
    general: "Your comfort zone is found in dynamic, goal-oriented environments where you can pursue objectives actively and see concrete progress toward your aims. You feel most secure when you have clear targets to work toward and can maintain forward momentum in your endeavors. Your safety comes from staying busy with meaningful challenges and having the freedom to compete, achieve, and overcome obstacles through your own effort and determination.",
    positive: "Natural energy and drive that allows you to feel comfortable with challenge and competition where others might feel overwhelmed or discouraged. Your confidence in your ability to overcome obstacles creates security even in difficult situations because you trust your capacity to work through problems. You inspire others through your example of persistence and determination in pursuing worthwhile goals.",
    challenge: "May feel restless or anxious in peaceful, static situations that don't provide adequate challenge or opportunity for achievement and forward progress. Tendency to create unnecessary goals or conflicts when life becomes too comfortable or routine, potentially disrupting stability when rest might be more beneficial. Can become frustrated or depressed when unable to pursue your objectives due to external constraints or circumstances beyond your control.",
    advice: "Learn to find security in moments of rest and stillness rather than constantly needing activity and achievement to feel safe and worthwhile. Practice enjoying the process of working toward goals rather than only feeling comfortable when you're making visible progress. Develop appreciation for the value of different life rhythms, including periods of rest that support long-term achievement."
  },
  8: {
    general: "Your comfort zone is characterized by gentle environments where you can exercise patience, compassion, and inner strength without external pressure or harsh demands. You feel most secure in situations that allow for gradual development and healing rather than forced or rapid change. Your safety comes from having time to process experiences deeply and the freedom to approach challenges with loving persistence rather than aggressive action.",
    positive: "Deep inner strength and resilience that provides security even in difficult circumstances because you trust your ability to endure and transform challenges through patient, compassionate response. Your gentle approach to problems often yields better long-term results than more aggressive strategies. You create healing environments that feel safe and supportive for vulnerable people and difficult situations.",
    challenge: "May feel uncomfortable or overwhelmed in high-pressure situations that demand quick, decisive action or aggressive pursuit of goals without time for gentle consideration. Tendency to avoid competitive or confrontational environments even when your participation might be beneficial, potentially limiting opportunities for growth and achievement. Can become stressed when others pressure you to act more quickly or forcefully than feels natural and sustainable.",
    advice: "Recognize that your gentle strength is valuable in many situations while also developing confidence in your ability to act decisively when necessary. Practice finding your inner security and power even in more demanding or competitive environments. Learn to distinguish between appropriate patience and excessive avoidance of necessary action or healthy challenge."
  },
  9: {
    general: "Your comfort zone is found in quiet, contemplative environments where you can pursue wisdom, learning, and spiritual understanding without external demands for social interaction or practical achievement. You feel most secure when you have solitude for reflection and study, and access to knowledge and wisdom that helps you understand life's deeper meanings. Your safety comes from inner understanding and the confidence that comes from accumulated wisdom and experience.",
    positive: "Deep well of inner wisdom and understanding that provides security and guidance regardless of external circumstances. Your comfort with solitude and reflection allows you to find answers and peace within yourself rather than depending entirely on others for security and direction. You offer profound insights and guidance that help others find their own inner wisdom and spiritual understanding.",
    challenge: "May feel uncomfortable or drained in highly social environments that don't allow for adequate solitude and reflection, potentially avoiding beneficial relationships and opportunities. Tendency to withdraw from practical engagement with the world when overwhelmed, sometimes missing opportunities to share your wisdom in ways that could benefit others. Can become isolated or disconnected from everyday life when spending too much time in contemplation without practical application.",
    advice: "Balance your need for solitude and contemplation with regular engagement in the practical world where your wisdom can be shared and applied beneficially. Practice finding inner peace and security even in social situations by staying connected to your inner wisdom while engaging with others. Recognize that sharing your insights and understanding can enhance rather than diminish your spiritual security and growth."
  },
  10: {
    general: "Your comfort zone is characterized by environments that honor natural cycles and allow for periodic change rather than forcing constant stability or continuous intensity. You feel most secure when you can flow with natural rhythms and timing rather than being pressured to maintain consistent energy or availability. Your safety comes from trusting in the natural cycles of expansion and contraction, activity and rest, engagement and withdrawal.",
    positive: "Natural understanding of life's rhythms and cycles that allows you to feel comfortable with change and transition rather than needing constant stability or control. Your ability to flow with circumstances and timing often leads to better outcomes than forcing situations or fighting natural patterns. You help others recognize and work with natural cycles rather than exhausting themselves through constant resistance to change.",
    challenge: "May become passive or fatalistic about circumstances that actually require active intervention or personal responsibility, using belief in natural cycles to avoid necessary action. Tendency to feel uncomfortable with sustained effort or consistency when natural rhythms might actually support more focused engagement. Can become confused about when to flow with circumstances and when to actively work toward change and improvement.",
    advice: "Learn to distinguish between healthy acceptance of natural cycles and passive avoidance of necessary action and responsibility for your life circumstances. Practice maintaining your connection to natural rhythms while also engaging actively when situations call for consistent effort and focused attention. Develop wisdom about when to flow and when to act decisively within the framework of natural timing."
  },
  11: {
    general: "Your comfort zone is built on clear principles, fair treatment, and environments where justice and ethical behavior are valued and practiced consistently. You feel most secure when you can operate according to clear moral guidelines and when you see evidence that actions have appropriate consequences. Your safety comes from knowing that you're living according to your values and that you can expect reasonable fairness in your dealings with others.",
    positive: "Strong moral compass and sense of justice that provides internal security and guidance for making decisions and navigating complex situations. Your commitment to fairness and ethical behavior creates trust and respect in your relationships and communities. You help others clarify their own values and make decisions that align with their authentic moral principles rather than just convenience or immediate desire.",
    challenge: "May feel extremely uncomfortable or stressed in environments where ethical standards are unclear, inconsistent, or openly violated, potentially limiting your ability to function in imperfect situations. Tendency to become paralyzed by moral complexity or situations where all available choices seem to have negative ethical implications. Can become judgmental or rigid when others don't share your moral standards or when situations require ethical flexibility.",
    advice: "Learn to find security in your own moral compass while accepting that others may have different ethical frameworks and that complex situations sometimes require nuanced rather than absolute responses. Practice making ethical decisions efficiently rather than becoming paralyzed by analysis of every moral implication. Develop tolerance for moral ambiguity while maintaining your core commitment to fairness and justice."
  },
  12: {
    general: "Your comfort zone is found in unique, unconventional environments where different perspectives are valued and where you don't have to conform to standard expectations or approaches. You feel most secure when you can see situations from multiple angles and when your alternative viewpoints are appreciated rather than criticized. Your safety comes from having the freedom to explore unusual approaches and from being around people who value innovation and different ways of thinking.",
    positive: "Natural ability to find comfort in situations that others might find confusing or challenging because you can see multiple perspectives and creative solutions. Your willingness to approach problems differently often leads to breakthrough insights and innovative solutions that conventional thinking might miss. You help others expand their comfort zones by modeling acceptance of uncertainty and alternative approaches.",
    challenge: "May feel uncomfortable in conventional environments that require standard approaches and don't appreciate alternative perspectives or unconventional solutions. Tendency to make situations more complex than necessary when simpler, more direct approaches might be more effective and practical. Can become isolated or misunderstood when your alternative perspectives aren't appreciated or when others expect more conventional behavior.",
    advice: "Learn to find security in your unique perspective while also developing the ability to communicate and work within conventional frameworks when necessary. Practice identifying when alternative approaches genuinely serve the situation and when conventional methods might be more effective. Build bridges between your innovative thinking and practical application that others can understand and appreciate."
  },
  13: {
    general: "Your comfort zone is paradoxically found in environments of change and transformation where endings and new beginnings are accepted as natural parts of life. You feel most secure when you don't have to maintain artificial stability or pretend that situations are permanent when they're actually in transition. Your safety comes from your ability to let go of what no longer serves and trust in the process of renewal and rebirth.",
    positive: "Natural comfort with change and transformation that allows you to navigate life transitions with greater ease than those who resist change. Your understanding that endings are necessary for new beginnings helps you release situations and relationships that no longer serve your growth. You help others find courage to make necessary changes and transform their lives when they've outgrown their current circumstances.",
    challenge: "May feel uncomfortable or restless in stable situations that don't provide adequate opportunity for growth and change, potentially creating unnecessary transitions or crises. Tendency to focus so much on transformation that you don't appreciate or build upon positive stable situations that could support your development. Can become addicted to change itself rather than using transformation to create genuinely better circumstances.",
    advice: "Learn to find security in stability and consistency when these serve your authentic development rather than constantly seeking change for its own sake. Practice appreciating and building upon positive circumstances while remaining open to transformation when it's genuinely needed. Develop discernment about when change serves growth and when stability supports your goals and well-being."
  },
  14: {
    general: "Your comfort zone is characterized by balanced, moderate environments where extremes are avoided and where healing and integration are prioritized over intense experience or dramatic change. You feel most secure in situations that support gradual progress and sustainable development rather than rapid or extreme shifts. Your safety comes from maintaining equilibrium and from environments that support your physical, emotional, and spiritual health in integrated ways.",
    positive: "Natural ability to create and maintain balanced environments that support long-term health and sustainable development for yourself and others. Your moderate approach often prevents problems and creates steady progress toward goals without the exhaustion that comes from extreme effort. You help others find balance and moderation when they've been caught in unhealthy extremes or unsustainable patterns.",
    challenge: "May feel uncomfortable with necessary intensity or passionate engagement, seeking balance even when situations require more focused energy or emotional depth. Tendency to avoid experiences that might temporarily disrupt your equilibrium even when they could lead to important growth or positive change. Can become stuck in comfortable moderation when breakthrough experiences or more dramatic action might be beneficial.",
    advice: "Maintain your valuable ability to create balance and sustainability while also remaining open to appropriate intensity and passionate engagement when they serve your growth. Practice distinguishing between healthy moderation and excessive avoidance of necessary challenge or emotional depth. Recognize that sometimes achieving greater balance requires temporarily embracing intensity or change."
  },
  15: {
    general: "Your comfort zone paradoxically involves intensity, passion, and environments where power dynamics and strong desires are acknowledged rather than hidden or suppressed. You feel most secure when you can be honest about your authentic desires and when others are equally direct about their wants and motivations. Your safety comes from accepting and working with the shadow aspects of human nature rather than pretending they don't exist.",
    positive: "Comfort with intensity and honest acknowledgment of desires and power dynamics that allows you to navigate complex situations that others might find overwhelming or confusing. Your willingness to face difficult truths about human nature often leads to more authentic relationships and realistic solutions to problems. You help others accept their own desires and power rather than being controlled by unconscious drives and motivations.",
    challenge: "May feel uncomfortable in environments that require subtlety, restraint, or the suppression of intense desires and emotions for the sake of social harmony or long-term goals. Tendency to create unnecessary intensity or drama when situations might benefit from gentler approaches or patient development. Can become obsessed with power or control when these drives aren't acknowledged and channeled constructively.",
    advice: "Learn to channel your comfort with intensity toward building authentic relationships and achieving meaningful goals rather than creating drama or pursuing power for its own sake. Practice recognizing when situations benefit from your direct approach and when more subtle or restrained responses might be more effective. Use your understanding of power and desire to create conscious, consensual experiences rather than unconscious manipulation."
  },
  16: {
    general: "Your comfort zone is found in environments of revelation, breakthrough, and sudden insight where truth is valued over comfort and where dramatic insights lead to liberation from limiting patterns. You feel most secure when you can be completely authentic rather than maintaining facades or illusions, even when truth is initially disruptive. Your safety comes from living according to revealed truth rather than comfortable lies or social conditioning.",
    positive: "Natural ability to handle sudden changes and revelations that might shock or destabilize others, often finding liberation and relief in breakthrough moments that expose truth. Your comfort with disruption of illusions helps you and others break free from limiting patterns and relationships that no longer serve authentic development. You help others find courage to face necessary truths and make liberating changes in their lives.",
    challenge: "May feel uncomfortable with gradual development or situations that require patience and gentle approach rather than dramatic breakthrough or sudden revelation. Tendency to create unnecessary crisis or dramatic change when more gradual approaches might be more effective and less disruptive to yourself and others. Can become addicted to intensity and revelation rather than building stable foundations after breakthrough insights.",
    advice: "Balance your gift for breakthrough and revelation with ability to build stable foundations that support the insights and changes you experience. Practice communicating your realizations in ways that others can receive and integrate rather than shocking or overwhelming them. Learn to appreciate gradual development and patient building processes that support lasting transformation rather than just dramatic change."
  },
  17: {
    general: "Your comfort zone is characterized by environments of hope, inspiration, and connection to higher purpose where your ideals and vision for the future can flourish. You feel most secure when you can maintain faith in positive possibilities and when you're working toward goals that serve something greater than personal benefit. Your safety comes from your connection to spiritual guidance and your trust in the ultimate goodness of life and human potential.",
    positive: "Natural optimism and faith that provides security even in difficult circumstances because you maintain connection to hope and higher purpose. Your inspirational vision helps others maintain courage and direction when they might otherwise despair or lose motivation. You excel at finding meaning and purpose in challenges and helping others see the positive potential in their circumstances.",
    challenge: "May feel uncomfortable or depressed in cynical environments or situations that focus on problems without maintaining connection to solutions and positive possibilities. Tendency to avoid difficult realities or practical limitations when they conflict with your vision of what should be possible. Can become discouraged when your ideals aren't immediately realized or when others don't share your optimistic perspective.",
    advice: "Maintain your valuable connection to hope and higher purpose while also developing practical skills for working with current realities and limitations. Practice grounding your inspiration in concrete actions that move toward your ideals rather than just maintaining vision without practical application. Learn to find hope and meaning even in imperfect circumstances while working toward positive change."
  },
  18: {
    general: "Your comfort zone is found in mysterious, intuitive environments where logic isn't required to explain everything and where psychic, emotional, and spiritual dimensions are honored as valid sources of information. You feel most secure when you can trust your intuition and when others accept that not everything needs to be rationally understood. Your safety comes from your connection to inner guidance and your ability to navigate by feeling rather than only through logical analysis.",
    positive: "Deep intuitive abilities and comfort with mystery that allows you to find guidance and security in situations where others might feel lost or confused. Your sensitivity to subtle energies and emotional undercurrents often provides valuable information that logical analysis might miss. You help others trust their own intuition and access inner wisdom when external guidance isn't clear or available.",
    challenge: "May feel uncomfortable or overwhelmed in highly rational, logical environments that don't honor intuitive ways of knowing or that require extensive analytical justification for decisions. Tendency to become confused or lose your center when others pressure you to explain or defend your intuitive insights logically. Can become lost in illusion or fantasy when your psychic sensitivity isn't balanced with practical discernment and grounding.",
    advice: "Trust your intuitive abilities while also developing practical discernment that helps you distinguish between genuine inner guidance and emotional projection or wishful thinking. Practice communicating your insights in ways that others can understand without compromising your connection to non-rational sources of wisdom. Learn to stay grounded while accessing psychic and intuitive information."
  },
  19: {
    general: "Your comfort zone is characterized by positive, optimistic environments where success and happiness are celebrated and where you can express authentic joy and enthusiasm without constraint. You feel most secure when you can maintain a positive outlook and when you're surrounded by others who appreciate success and good fortune. Your safety comes from your natural magnetism and ability to attract positive experiences and supportive relationships.",
    positive: "Natural charisma and positive energy that creates comfortable, uplifting environments for yourself and others. Your authentic enthusiasm and joy in life attracts opportunities and relationships that support your continued success and happiness. You help others maintain hope and positive perspective when they might otherwise become discouraged or cynical about their possibilities.",
    challenge: "May feel uncomfortable in negative environments or situations that require dealing with serious problems, criticism, or extended challenges without relief. Tendency to avoid or minimize difficulties rather than addressing them directly when they require sustained attention and problem-solving effort. Can become superficial or lose depth when constantly avoiding anything that might diminish your positive energy or optimistic perspective.",
    advice: "Maintain your valuable positive energy while also developing resilience and skills for dealing constructively with challenges and difficulties when they arise. Practice using your natural optimism to find solutions and maintain hope during difficult periods rather than avoiding problems entirely. Learn to appreciate the full spectrum of human experience while maintaining your gift for creating joy and positive outcomes."
  },
  20: {
    general: "Your comfort zone involves environments that honor spiritual purpose and calling where you can serve something greater than personal comfort or convenience. You feel most secure when your daily life aligns with your spiritual understanding and when you can contribute to collective awakening and positive transformation. Your safety comes from your connection to divine guidance and your trust that serving higher purpose will provide for your authentic needs.",
    positive: "Deep sense of purpose and meaning that provides security even when external circumstances are challenging because you trust in divine guidance and spiritual protection. Your commitment to serving higher purpose often attracts support and resources that wouldn't be available if you were focused only on personal benefit. You inspire others to recognize and follow their own spiritual calling and purpose.",
    challenge: "May feel uncomfortable or lost when spiritual guidance isn't clear or when you're required to focus on practical matters without obvious spiritual significance. Tendency to neglect practical needs and responsibilities when focused on spiritual service, potentially creating unnecessary hardship for yourself and others. Can become overwhelmed by the responsibility of spiritual calling or confused about how to serve higher purpose in practical ways.",
    advice: "Balance your spiritual calling with attention to practical needs and responsibilities, recognizing that caring for yourself and your everyday obligations can be part of your spiritual service. Practice discerning between authentic spiritual guidance and personal desires or fears disguised as spiritual direction. Find ways to integrate your spiritual purpose with practical daily life rather than separating them into conflicting demands."
  },
  21: {
    general: "Your comfort zone is characterized by environments where you can experience and express complete fulfillment and integration of all aspects of yourself. You feel most secure when you can operate from wholeness rather than feeling fragmented or incomplete. Your safety comes from your achievement of inner integration and your ability to create success and satisfaction that honors all dimensions of your being.",
    positive: "Natural sense of completion and fulfillment that provides deep security and allows you to help others achieve their own integration and success. Your wholeness and achievement inspire others and provide a model of what's possible when all aspects of personality and potential are honored and expressed. You excel at creating lasting satisfaction and meaningful accomplishment that serves both personal fulfillment and collective benefit.",
    challenge: "May feel uncomfortable with incomplete or developing situations that require patience and gradual building rather than immediate access to fulfillment and success. Tendency to take your achievements and integration for granted rather than continuing to grow and evolve as circumstances and opportunities change. Can become restless or dissatisfied when life lacks adequate challenge or opportunity for new accomplishment and mastery.",
    advice: "Appreciate your achievements and integration while remaining open to continued growth and evolution as your circumstances and understanding deepen. Use your success and fulfillment to support others in achieving their own integration rather than becoming complacent about your accomplishments. Maintain curiosity about new possibilities for growth and service even when your current level of achievement feels complete and satisfying."
  },
  22: {
    general: "Your comfort zone is characterized by unlimited potential and freedom to explore new possibilities without being constrained by past experience or conventional expectations. You feel most secure when you have complete freedom to experiment and discover rather than being limited by predetermined roles or expectations. Your safety comes from your trust in your own innocence and ability to learn and adapt to whatever situations you encounter.",
    positive: "Natural openness and adaptability that allows you to feel comfortable in new situations where others might feel anxious or out of place. Your freedom from limiting assumptions often leads to breakthrough discoveries and innovative solutions that more experienced people might miss. You help others maintain beginner's mind and openness to new possibilities rather than being limited by past experience or conventional thinking.",
    challenge: "May feel uncomfortable with structure, long-term commitments, or situations that require sustained focus and development rather than constant novelty and exploration. Tendency to avoid developing expertise or taking on responsibilities that might limit your freedom to experiment and change direction whenever you choose. Can become restless or irresponsible when situations require consistency and follow-through over time.",
    advice: "Balance your valuable openness and freedom with willingness to develop some areas of expertise and commitment that can ground your explorations in practical skill and knowledge. Practice finding security in your own learning ability rather than requiring complete external freedom to feel safe and comfortable. Learn to appreciate both exploration and development, recognizing that some depth and commitment can enhance rather than limit your potential for discovery."
  }
};