/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Dad's Talents Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) represents
 * the paternal lineage gifts, talents, and masculine energy passed down
 * through the father's line that can be activated and utilized.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Dad's Talents - Paternal lineage gifts and masculine energy inheritance
 */
export const dadsTalentsInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your father's lineage carries the gift of pioneering leadership and the ability to initiate new ventures with confidence and determination. This inherited talent manifests as natural entrepreneurial instincts, the courage to take risks, and the ability to lead others through your clear vision and decisive action. You have access to a powerful masculine energy that can break through obstacles and create something from nothing.",
    positive: "Strong inherited capacity for leadership and innovation that allows you to pioneer new paths in any field you choose. Natural confidence and determination that inspires others to follow your vision and support your initiatives. Access to powerful creative force that can manifest ideas into reality through focused will and action.",
    challenge: "May inherit tendency toward impatience or aggressive approaches that can alienate others or create unnecessary conflict. Risk of becoming overly independent and refusing help, even when collaboration would be beneficial. Potential for burnout from pushing too hard without adequate rest or consideration for others' pace.",
    advice: "Channel your inherited leadership gifts constructively by learning to balance independence with collaboration and patience. Honor your father's pioneering spirit while developing emotional intelligence and consideration for others. Use your natural authority to uplift and empower others rather than dominating or controlling situations."
  },
  2: {
    general: "Your paternal lineage provides gifts of intuition, emotional intelligence, and the ability to create through receptive, nurturing masculine energy. This represents a gentle but powerful form of masculine strength that works through cooperation, patience, and deep understanding of others' needs. You inherit the talent for healing, mediation, and creating harmony in challenging situations.",
    positive: "Inherited emotional wisdom and intuitive understanding that allows you to connect deeply with others and provide valuable guidance. Natural healing abilities and the gift of creating peace and cooperation in conflict situations. Access to patient, nurturing masculine energy that can support and empower others to reach their potential.",
    challenge: "May struggle with traditional masculine expectations, feeling that your gentle approach isn't strong enough or valued by others. Risk of being taken advantage of due to your cooperative nature and tendency to put others' needs before your own. Potential difficulty with boundaries and asserting yourself when necessary.",
    advice: "Recognize that your gentle, intuitive approach represents a powerful form of masculine strength that the world desperately needs. Learn to value your emotional intelligence and healing gifts as real talents worth developing and sharing. Practice setting healthy boundaries while maintaining your natural compassion and cooperation."
  },
  3: {
    general: "Your father's lineage bestows abundant creative talents and the ability to nurture and bring forth new life, ideas, and opportunities. This inheritance includes artistic gifts, natural magnetism, and the talent for creating abundance and beauty in the world. You have access to generative masculine energy that can birth new projects, relationships, and creative expressions with ease.",
    positive: "Rich creative inheritance with multiple artistic talents and the natural ability to generate abundance and beauty in various forms. Inherited magnetism and charm that attracts resources, opportunities, and supportive relationships. Strong nurturing instincts that can help others grow and flourish under your guidance and care.",
    challenge: "May scatter creative energy across too many projects without bringing them to completion, inheriting a tendency toward creative restlessness. Risk of being overly generous or giving away too much of your creative gifts without proper compensation or recognition. Potential difficulty with focus and practical implementation of creative visions.",
    advice: "Focus your abundant creative inheritance by choosing specific projects to develop fully rather than starting many things without finishing them. Learn to value your creative gifts appropriately and set boundaries around your generosity. Develop practical skills to complement your creative talents and bring your visions into reality."
  },
  4: {
    general: "Your paternal lineage provides the gifts of structure, discipline, and the ability to build solid foundations that last for generations. This inheritance includes practical wisdom, methodical thinking, and the talent for creating systems and processes that provide security and stability. You have access to steady, reliable masculine energy that can weather any storm through patience and perseverance.",
    positive: "Inherited practical wisdom and the natural ability to create lasting structures, whether in business, family, or community. Strong work ethic and discipline that allows you to build wealth and security through consistent, methodical effort. Natural talent for organization and systems thinking that can benefit many people over time.",
    challenge: "May inherit tendency toward rigidity or excessive conservatism that prevents adaptation to changing circumstances. Risk of becoming too focused on security and control, missing opportunities for growth and expansion. Potential difficulty with flexibility and embracing new methods or technologies.",
    advice: "Honor your inherited gifts for structure and stability while remaining open to necessary changes and innovations. Use your natural discipline and methodical approach as a foundation for gradual growth and adaptation. Balance your need for security with calculated risks that can expand your impact and opportunities."
  },
  5: {
    general: "Your father's lineage carries the gifts of wisdom, teaching, and the ability to preserve and transmit important knowledge and traditions. This inheritance includes respect for established systems, natural teaching abilities, and the talent for guiding others through proper methods and time-tested wisdom. You have access to authoritative masculine energy that can lead through knowledge and moral guidance.",
    positive: "Inherited wisdom and natural teaching abilities that allow you to guide others effectively through established principles and proven methods. Strong moral compass and respect for tradition that provides stability and guidance in uncertain times. Natural authority and credibility that others respect and trust for important decisions.",
    challenge: "May inherit tendency toward rigid adherence to tradition even when change is necessary for growth. Risk of becoming overly dogmatic or judgmental about others who don't follow conventional paths. Potential difficulty with innovation and adapting to rapidly changing circumstances.",
    advice: "Honor traditional wisdom while remaining open to new insights and methods that serve the greater good. Use your inherited teaching gifts to help others understand both timeless principles and necessary adaptations. Balance respect for tradition with flexibility and openness to innovation when it serves a higher purpose."
  },
  6: {
    general: "Your paternal lineage provides gifts of harmony, diplomacy, and the ability to create beautiful, balanced relationships and environments. This inheritance includes aesthetic sense, natural charm, and the talent for bringing people together in cooperation and love. You have access to graceful masculine energy that can heal divisions and create win-win solutions for everyone involved.",
    positive: "Inherited diplomatic skills and natural ability to create harmony and cooperation between different people and groups. Strong aesthetic sense and appreciation for beauty that can enhance any environment or relationship. Natural charm and social skills that help you build valuable networks and partnerships throughout life.",
    challenge: "May inherit tendency toward people-pleasing or avoiding necessary conflicts that need to be addressed for genuine resolution. Risk of being overly influenced by others' opinions or losing your own center in the desire to maintain harmony. Potential difficulty with making difficult decisions that might upset others.",
    advice: "Use your inherited gifts for harmony and diplomacy while maintaining your own authentic center and values. Learn that sometimes conflict is necessary for creating genuine peace and understanding. Balance your natural desire to please others with honest communication and healthy boundaries."
  },
  7: {
    general: "Your father's lineage bestows the gifts of courage, determination, and the ability to overcome any obstacle through focused willpower and strategic action. This inheritance includes competitive spirit, natural resilience, and the talent for victory in challenging situations. You have access to warrior masculine energy that can push through barriers and achieve seemingly impossible goals.",
    positive: "Inherited courage and determination that allows you to face any challenge with confidence and persistence. Natural competitive abilities and strategic thinking that help you succeed in difficult situations where others might give up. Strong resilience and ability to bounce back quickly from setbacks or failures.",
    challenge: "May inherit tendency toward aggression or impatience that can create unnecessary conflicts or rush important decisions. Risk of becoming overly competitive or viewing life as constant battle rather than seeking cooperation. Potential burnout from pushing too hard without adequate rest or consideration for sustainability.",
    advice: "Channel your inherited warrior energy constructively by choosing worthy challenges that serve the greater good. Learn to balance competition with cooperation and strategic thinking with patience. Use your natural courage and determination to protect and empower others rather than simply pursuing personal victory."
  },
  8: {
    general: "Your paternal lineage provides the gifts of inner strength, patience, and the ability to transform difficult situations through gentle but persistent effort. This inheritance includes emotional resilience, natural healing abilities, and the talent for taming and transforming wild or chaotic energies. You have access to calm, steady masculine power that can handle any crisis with grace.",
    positive: "Inherited emotional strength and natural ability to remain calm and centered during crises or challenging situations. Deep reservoir of patience and persistence that allows you to work steadily toward long-term goals without being discouraged by temporary setbacks. Natural healing presence that can help others find their own inner strength and resilience.",
    challenge: "May inherit tendency toward over-accommodation or taking too long to act when decisive action is needed. Risk of underestimating your own power and abilities, accepting less than you deserve in various life situations. Potential difficulty with asserting yourself appropriately when patience is being taken advantage of.",
    advice: "Trust in your inherited inner strength and use it to set appropriate boundaries while maintaining your naturally patient and healing presence. Learn to recognize when patience is appropriate and when assertive action is needed. Value your unique gifts and charge appropriately for the healing and stability you provide to others."
  },
  9: {
    general: "Your father's lineage carries the gifts of wisdom, insight, and the ability to guide others through your deep understanding of life's patterns and meanings. This inheritance includes natural teaching abilities, philosophical thinking, and the talent for seeing the bigger picture in complex situations. You have access to sage-like masculine energy that can illuminate truth and provide valuable guidance.",
    positive: "Inherited wisdom and natural ability to understand complex situations and provide valuable guidance to others seeking direction. Deep philosophical understanding and intuitive insights that help you see patterns and meanings that others miss. Natural teaching abilities and the gift of explaining complex concepts in ways others can understand and apply.",
    challenge: "May inherit tendency toward isolation or withdrawal from worldly affairs, preferring contemplation over active engagement. Risk of becoming overly detached or judgmental about others who don't share your level of insight or understanding. Potential difficulty with practical application of your wisdom in everyday situations.",
    advice: "Share your inherited wisdom generously while remaining grounded in practical reality and everyday human needs. Use your natural insight and understanding to help others while avoiding the trap of spiritual superiority or detachment. Balance contemplation with active engagement in the world where your guidance is needed."
  },
  10: {
    general: "Your paternal lineage bestows the gifts of timing, adaptability, and the ability to recognize and work with life's natural cycles and changes. This inheritance includes intuitive understanding of when to act and when to wait, natural luck with opportunities, and the talent for turning challenges into advantages. You have access to cyclical masculine energy that flows with rather than against life's rhythms.",
    positive: "Inherited intuitive timing and natural ability to recognize opportunities and favorable cycles for action and decision-making. Adaptability and resilience that helps you thrive during changing circumstances when others struggle with uncertainty. Natural luck and ability to turn apparent setbacks into unexpected advantages through patience and perspective.",
    challenge: "May inherit tendency toward fatalism or over-dependence on external circumstances rather than taking personal responsibility for outcomes. Risk of becoming too passive or waiting too long for perfect conditions rather than creating opportunities through action. Potential difficulty with consistent effort during less favorable cycles.",
    advice: "Use your inherited understanding of timing and cycles while taking personal responsibility for creating positive outcomes through consistent action. Learn to recognize when external conditions are favorable and when you need to create your own opportunities. Balance patience with appropriate action and trust with personal effort."
  },
  11: {
    general: "Your father's lineage provides the gifts of justice, fairness, and the ability to make balanced decisions that serve the highest good for all involved. This inheritance includes strong moral compass, natural mediation abilities, and the talent for seeing all sides of complex situations. You have access to balanced masculine energy that can bring justice and harmony to difficult circumstances.",
    positive: "Inherited sense of justice and natural ability to make fair decisions that consider all parties and serve the greater good. Strong ethical foundation and moral clarity that others trust and respect for important decisions. Natural mediation skills and the gift of finding balanced solutions to complex problems and conflicts.",
    challenge: "May inherit tendency toward perfectionism or over-analysis that delays important decisions until opportunities are missed. Risk of being overly rigid about fairness or becoming paralyzed by trying to consider every possible perspective. Potential difficulty with quick decision-making when immediate action is required.",
    advice: "Trust your inherited sense of justice while learning to make timely decisions within ethical frameworks you establish in advance. Use your natural fairness and balance to serve others while avoiding paralysis from over-analysis. Balance idealism with practical needs and timing when making important decisions."
  },
  12: {
    general: "Your paternal lineage carries the gifts of sacrifice, surrender, and the ability to see situations from completely different perspectives that reveal hidden opportunities. This inheritance includes wisdom gained through letting go, natural spiritual insight, and the talent for finding value in apparent loss or limitation. You have access to transcendent masculine energy that can transform sacrifice into wisdom.",
    positive: "Inherited spiritual wisdom and natural ability to find meaning and opportunity in challenging or limiting circumstances. Deep understanding of when to let go and when to persist, gained through family experiences of sacrifice and surrender. Natural ability to see situations from unique perspectives that reveal solutions others miss completely.",
    challenge: "May inherit tendency toward martyrdom or excessive self-sacrifice that doesn't serve the greater good or your own well-being. Risk of becoming too passive or accepting of difficult circumstances that could be changed through appropriate action. Potential difficulty with practical assertiveness and worldly success.",
    advice: "Honor your inherited wisdom about sacrifice and surrender while ensuring that your giving serves a higher purpose rather than enabling others' irresponsibility. Use your unique perspective to find opportunities others miss while maintaining appropriate boundaries and self-care. Balance spiritual wisdom with practical action and worldly effectiveness."
  },
  13: {
    general: "Your father's lineage bestows the gifts of transformation, renewal, and the ability to help others navigate major life transitions and changes. This inheritance includes comfort with endings and beginnings, natural crisis management abilities, and the talent for facilitating necessary transformations. You have access to transformative masculine energy that can help others release what no longer serves them.",
    positive: "Inherited wisdom about transformation and natural ability to help others navigate major life changes and transitions with grace. Comfort with endings and beginnings that allows you to facilitate necessary changes in organizations, relationships, and communities. Strong crisis management skills and the gift of remaining calm during turbulent periods.",
    challenge: "May inherit tendency toward dramatic change or destruction when gradual evolution would be more effective and less traumatic. Risk of being too comfortable with endings and not appreciating the value of stability and continuity. Potential difficulty with building lasting structures that can evolve rather than requiring complete transformation.",
    advice: "Use your inherited gifts for transformation wisely by helping others navigate necessary changes while preserving what is valuable and functional. Learn to balance your comfort with endings with appreciation for stability and gradual evolution. Channel your transformative energy constructively rather than creating unnecessary drama or upheaval."
  },
  14: {
    general: "Your paternal lineage provides the gifts of temperance, moderation, and the ability to find the middle way that harmonizes opposing forces and creates sustainable solutions. This inheritance includes natural healing abilities, diplomatic skills, and the talent for bringing balance to chaotic or extreme situations. You have access to harmonizing masculine energy that can heal and integrate.",
    positive: "Inherited wisdom about balance and moderation that allows you to find sustainable solutions to complex problems and conflicts. Natural healing abilities and the gift of helping others find their center and regain emotional or physical equilibrium. Diplomatic skills and patience that help you mediate successfully between opposing parties or viewpoints.",
    challenge: "May inherit tendency toward over-compromise or avoiding necessary extremes when bold action or clear positioning is required. Risk of being too cautious or conservative, missing opportunities that require taking stronger positions or calculated risks. Potential difficulty with decisive action when moderation isn't the appropriate response.",
    advice: "Use your inherited gifts for balance and moderation while recognizing when situations call for decisive action or strong positioning. Trust your natural healing abilities and share them generously with others who need support finding their equilibrium. Balance your desire for harmony with the willingness to take appropriate risks when necessary."
  },
  15: {
    general: "Your father's lineage carries the gifts of material mastery, magnetism, and the ability to understand and work effectively with power, influence, and worldly success. This inheritance includes strong manifestation abilities, natural business acumen, and the talent for creating significant material prosperity. You have access to powerful masculine energy that can achieve substantial worldly success when used consciously.",
    positive: "Inherited understanding of material world dynamics and natural ability to create significant wealth and influence through focused effort. Strong manifestation abilities and magnetic personality that attracts resources, opportunities, and people who can support your goals. Natural business instincts and the gift of recognizing profitable opportunities others might miss.",
    challenge: "May inherit tendency toward material obsession or using power and influence in ways that serve ego rather than higher purpose. Risk of becoming trapped by success or making ethical compromises for material gain that ultimately damage your reputation and relationships. Potential difficulty with spiritual values and non-material priorities.",
    advice: "Use your inherited gifts for material mastery consciously and ethically, ensuring that your success serves not just yourself but others as well. Maintain clear values and boundaries that you won't cross regardless of material temptation or opportunity. Balance your natural magnetism and power with humility and service to higher purposes."
  },
  16: {
    general: "Your paternal lineage bestows the gifts of innovation, breakthrough thinking, and the ability to shatter outdated structures that limit growth and evolution. This inheritance includes revolutionary spirit, technological aptitude, and the talent for seeing through illusions to underlying truth. You have access to lightning-like masculine energy that can create sudden positive changes and awakening.",
    positive: "Inherited innovative thinking and natural ability to break through limitations and create breakthrough solutions to stubborn problems. Revolutionary spirit and courage to challenge outdated systems or methods that no longer serve the greater good. Quick thinking and adaptability that helps you thrive during periods of rapid change and uncertainty.",
    challenge: "May inherit tendency toward destructive rebellion or impatience with gradual change that leads to unnecessary disruption. Risk of being too quick to tear down existing structures without having better alternatives ready to replace them. Potential difficulty with authority and established systems, even when they serve valuable purposes.",
    advice: "Channel your inherited revolutionary energy constructively by working to improve rather than simply destroy existing systems and structures. Use your natural innovation and breakthrough thinking to create positive changes that serve the greater good. Balance your impatience with gradual evolution with respect for valuable traditions and existing relationships."
  },
  17: {
    general: "Your father's lineage provides the gifts of hope, optimism, and the ability to inspire others with your vision of positive possibilities and better futures. This inheritance includes natural faith in abundance, inspirational abilities, and the talent for helping others see their highest potential. You have access to starlike masculine energy that can guide others toward their dreams and aspirations.",
    positive: "Inherited optimism and natural ability to inspire others with hope and positive vision for the future. Strong faith in abundance and positive outcomes that tends to manifest favorable circumstances and opportunities. Natural teaching and motivational abilities that help others believe in themselves and pursue their dreams with confidence.",
    challenge: "May inherit tendency toward unrealistic optimism or naivety about practical challenges that require careful planning and preparation. Risk of making promises or commitments based on idealistic expectations rather than realistic assessment of what's possible. Potential difficulty with facing necessary challenges or shadow aspects that need attention.",
    advice: "Ground your inherited optimism and inspirational gifts in practical planning and realistic assessment of challenges and opportunities. Use your natural hope and positive vision to motivate both yourself and others while also developing practical skills and strategies. Balance faith in positive outcomes with responsible preparation and action."
  },
  18: {
    general: "Your paternal lineage carries the gifts of intuition, mystery, and the ability to navigate hidden or unconscious realms that influence life in powerful but subtle ways. This inheritance includes psychic abilities, emotional depth, and the talent for understanding what lies beneath surface appearances. You have access to lunar masculine energy that works through dreams, intuition, and emotional intelligence.",
    positive: "Inherited psychic sensitivity and natural ability to understand hidden motivations, unconscious patterns, and emotional undercurrents that others miss. Deep emotional intelligence and empathy that allows you to connect with others on profound levels and provide healing through understanding. Natural ability to work with dreams, symbols, and intuitive guidance.",
    challenge: "May inherit tendency toward confusion between intuition and emotional reactivity, making it difficult to distinguish genuine insight from personal projection. Risk of being overwhelmed by psychic sensitivity or taking on others' emotional problems without appropriate boundaries. Potential difficulty with practical application of intuitive insights in everyday situations.",
    advice: "Develop your inherited psychic and emotional gifts through proper training and practice while maintaining healthy boundaries and practical grounding. Learn to distinguish between genuine intuitive insight and emotional reactivity or wishful thinking. Use your natural empathy and understanding to help others while protecting your own emotional and psychic well-being."
  },
  19: {
    general: "Your father's lineage bestows the gifts of joy, success, and the ability to create happiness and celebration in life through natural magnetism and positive energy. This inheritance includes optimistic outlook, leadership abilities, and the talent for bringing out the best in others and situations. You have access to solar masculine energy that radiates warmth, confidence, and life-affirming power.",
    positive: "Inherited joy and natural ability to create success and happiness wherever you go through positive energy and magnetic personality. Strong leadership qualities and the gift of inspiring others to achieve their best and celebrate their accomplishments. Natural confidence and optimism that attracts favorable opportunities and supportive relationships throughout life.",
    challenge: "May inherit tendency toward ego inflation or taking success and good fortune for granted without proper appreciation or responsibility. Risk of avoiding necessary challenges or shadow work in favor of maintaining positive image and comfortable circumstances. Potential difficulty with humility and learning from failure or difficult experiences.",
    advice: "Use your inherited gifts for success and joy responsibly by sharing your positive energy generously while remaining humble and grateful for your good fortune. Address necessary challenges and personal growth work rather than avoiding them in favor of staying comfortable. Balance confidence with humility and success with service to others."
  },
  20: {
    general: "Your father's lineage provides the gifts of awakening, calling, and the ability to align your life with higher purpose and spiritual mission. This inheritance includes visionary abilities, transformational leadership, and the talent for helping others recognize and fulfill their deepest calling. You have access to transcendent masculine energy that can serve spiritual evolution and awakening.",
    positive: "Inherited connection to higher purpose and natural ability to recognize and fulfill your spiritual mission and calling in life. Visionary leadership and the gift of helping others awaken to their own potential and higher purpose. Natural ability to serve as a bridge between spiritual and material worlds through aligned action and authentic example.",
    challenge: "May inherit tendency toward spiritual idealism that disconnects from practical responsibilities and earthly needs. Risk of becoming overly focused on personal awakening or spiritual development without consideration for family and community obligations. Potential difficulty with balancing spiritual calling with material world success and relationships.",
    advice: "Honor your inherited spiritual gifts and calling while remaining grounded in practical responsibilities and human relationships. Use your natural vision and transformational abilities to serve others' awakening and evolution through example and guidance. Balance spiritual idealism with practical wisdom and earthly effectiveness in your chosen field of service."
  },
  21: {
    general: "Your father's lineage carries the gifts of mastery, completion, and the ability to achieve lasting success and fulfillment through integration of all your talents and abilities. This inheritance includes natural leadership, achievement orientation, and the talent for creating lasting legacies that benefit many people. You have access to accomplished masculine energy that can achieve worldly success while serving higher purposes.",
    positive: "Inherited potential for mastery and natural ability to achieve significant success and recognition through dedicated effort and integration of your various talents. Strong achievement orientation and the gift of inspiring others through your example of excellence and completion. Natural leadership abilities and the capacity to create lasting positive impact through your work and relationships.",
    challenge: "May inherit tendency toward perfectionism or setting impossibly high standards that create stress and prevent enjoyment of current achievements. Risk of becoming overly focused on external success and recognition without attention to inner fulfillment and spiritual development. Potential difficulty with delegation and allowing others to contribute their gifts.",
    advice: "Use your inherited drive for mastery and achievement while maintaining balance between external success and inner fulfillment. Celebrate your accomplishments and allow others to learn from your example while remaining humble and open to continued growth. Share your gifts generously and create opportunities for others to develop their own mastery and success."
  },
  22: {
    general: "Your paternal lineage bestows the gifts of unlimited potential, fresh perspective, and the ability to approach life with wonder, spontaneity, and openness to infinite possibilities. This inheritance includes natural creativity, adventurous spirit, and the talent for beginning new journeys with faith and enthusiasm. You have access to free-spirited masculine energy that can pioneer entirely new approaches to life and work.",
    positive: "Inherited sense of unlimited potential and natural ability to approach challenges and opportunities with fresh perspective and creative solutions. Adventurous spirit and willingness to take calculated risks that can lead to breakthrough discoveries and innovations. Natural optimism and faith that attracts serendipitous opportunities and fortunate coincidences.",
    challenge: "May inherit tendency toward impracticality or lack of follow-through that prevents you from developing your natural talents into sustainable success. Risk of being too trusting or naive about others' motives and the practical challenges involved in manifesting your visions. Potential difficulty with discipline and structure that could support your creative gifts.",
    advice: "Ground your inherited gifts of potential and fresh perspective with practical skills and disciplined effort to bring your visions into reality. Maintain your natural optimism and openness while developing discernment and practical wisdom about people and opportunities. Balance your adventurous spirit with appropriate preparation and follow-through to achieve lasting success."
  }
};