/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Dad's Karma Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * paternal karma, father relationships, masculine lineage patterns, and
 * karmic lessons inherited from or related to your father's energy.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Dad's Karma - Paternal karmic patterns and father relationship dynamics
 */
export const dadsKarmaInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your father's karma involves themes of leadership, independence, and the pioneering spirit, creating both opportunities and challenges around authority and self-expression in your life. His karmic pattern may involve learning to balance strong will with consideration for others, and this energy influences your relationship with power and initiative. You may carry forward his lessons about courage and innovation while also needing to heal patterns of dominance or impatience. The karmic gift involves natural leadership abilities and the challenge involves learning collaborative authority.",
    positive: "Inherited strong sense of personal power and confidence that helps you take initiative and lead others effectively. Your father's pioneering energy provides you with courage to break new ground and create original solutions. You have natural authority and the ability to inspire others to believe in themselves and pursue their own creative visions.",
    challenge: "May carry patterns of impatience, dominance, or difficulty with collaboration that stem from your father's unresolved authority issues. Tendency to repeat patterns of putting achievement before relationship or struggling with anger when others don't follow your lead. Can inherit challenges with vulnerability or asking for help when you need support.",
    advice: "Honor the leadership gifts from your father's lineage while consciously developing collaborative skills and emotional intelligence. Practice using your natural authority to serve others rather than just expressing personal will. Transform inherited patterns of dominance into empowering leadership that helps others find their own strength and voice."
  },
  2: {
    general: "Your father's karma involves themes of receptivity, intuition, and the balance between action and reflection, creating patterns around emotional expression and inner wisdom in your family line. His karmic lessons may involve learning to trust intuitive guidance and honor the feminine aspects of consciousness. You may carry forward his sensitivity and wisdom while needing to heal patterns of withdrawal or difficulty with direct communication. The karmic gift involves deep intuitive understanding and the challenge involves learning confident expression.",
    positive: "Inherited wisdom and intuitive understanding that provides reliable guidance for navigating life's complexities and helping others find their inner truth. Your father's reflective nature gives you the ability to see beneath surface appearances and understand deeper motivations. You have natural counseling abilities and the gift of patient listening that helps others feel heard and understood.",
    challenge: "May carry patterns of emotional withdrawal, passive-aggressive communication, or difficulty taking decisive action that stem from your father's unresolved relationship with power. Tendency to avoid conflict or suppress your own needs in order to maintain peace and harmony. Can struggle with self-doubt or difficulty trusting your own perceptions and insights.",
    advice: "Honor the intuitive gifts from your father's lineage while developing confidence to express your insights and needs clearly. Practice balancing receptivity with appropriate action and direct communication when situations require it. Transform inherited patterns of withdrawal into conscious choice about when to engage and when to step back for reflection."
  },
  3: {
    general: "Your father's karma involves themes of creativity, abundance, and nurturing expression, creating patterns around self-worth and material security in your family line. His karmic lessons may involve learning to receive love and appreciation while also giving generously from authentic abundance. You may carry forward his creative gifts and generous nature while needing to heal patterns of giving to get or measuring worth through external validation. The karmic gift involves natural creativity and abundance and the challenge involves learning authentic self-worth.",
    positive: "Inherited creative abilities and generous spirit that helps you create beauty and abundance while supporting others' growth and creative expression. Your father's nurturing energy provides you with the ability to make others feel valued and appreciated. You have natural artistic or creative talents and the gift of seeing potential in people and situations.",
    challenge: "May carry patterns of seeking validation through giving, difficulty receiving support, or measuring self-worth through achievements and others' approval that stem from your father's unresolved relationship with his own value. Tendency to overextend yourself or sacrifice your own needs to please others. Can struggle with boundaries or feeling worthy of love and support.",
    advice: "Honor the creative and nurturing gifts from your father's lineage while developing healthy boundaries and authentic self-worth that doesn't depend on others' approval. Practice receiving love and support as freely as you give it. Transform inherited patterns of conditional self-worth into recognition of your inherent value and lovability."
  },
  4: {
    general: "Your father's karma involves themes of structure, responsibility, and building lasting foundations, creating patterns around duty and achievement in your family line. His karmic lessons may involve learning to balance work with relationship and finding meaning beyond just accomplishment. You may carry forward his work ethic and organizational abilities while needing to heal patterns of rigidity or difficulty with emotional expression. The karmic gift involves natural discipline and building abilities and the challenge involves learning emotional flexibility.",
    positive: "Inherited strong work ethic and ability to create stable foundations that provide security and structure for yourself and others. Your father's disciplined approach gives you the persistence to achieve long-term goals and build lasting value. You have natural organizational abilities and the gift of creating systems that support growth and success over time.",
    challenge: "May carry patterns of workaholism, emotional rigidity, or difficulty with spontaneity that stem from your father's unresolved relationship with responsibility and duty. Tendency to suppress emotions or sacrifice relationships for achievement and security. Can struggle with perfectionism or difficulty adapting when circumstances require flexibility.",
    advice: "Honor the discipline and building abilities from your father's lineage while developing emotional intelligence and flexibility that enhances rather than threatens your achievements. Practice balancing work with relationship and play. Transform inherited patterns of rigidity into conscious structure that serves love and growth rather than just security and control."
  },
  5: {
    general: "Your father's karma involves themes of wisdom, tradition, and spiritual guidance, creating patterns around authority and belief systems in your family line. His karmic lessons may involve learning to balance respect for tradition with individual spiritual growth and authentic expression. You may carry forward his wisdom and moral foundation while needing to heal patterns of dogmatism or difficulty with questioning established beliefs. The karmic gift involves natural teaching abilities and the challenge involves learning spiritual flexibility.",
    positive: "Inherited wisdom and strong moral foundation that provides reliable guidance for making ethical decisions and helping others understand universal principles. Your father's spiritual understanding gives you the ability to teach and guide others with authority and compassion. You have natural respect for wisdom traditions and the gift of connecting others with meaningful spiritual principles.",
    challenge: "May carry patterns of spiritual rigidity, judgmental thinking, or difficulty with individual expression that stem from your father's unresolved relationship with authority and tradition. Tendency to suppress personal insights or conform to external expectations rather than developing authentic spiritual understanding. Can struggle with spiritual superiority or difficulty accepting different approaches to truth.",
    advice: "Honor the wisdom and moral foundation from your father's lineage while developing personal spiritual discernment and respect for others' individual paths. Practice balancing tradition with personal revelation and growth. Transform inherited patterns of spiritual rigidity into flexible wisdom that serves love and individual spiritual development."
  },
  6: {
    general: "Your father's karma involves themes of relationship, balance, and aesthetic appreciation, creating patterns around love and partnership in your family line. His karmic lessons may involve learning to balance individual needs with partnership and developing authentic appreciation for beauty and harmony. You may carry forward his diplomatic abilities and aesthetic sense while needing to heal patterns of people-pleasing or difficulty with conflict. The karmic gift involves natural harmony-creating abilities and the challenge involves learning authentic relationship.",
    positive: "Inherited diplomatic skills and aesthetic appreciation that helps you create harmonious relationships and beautiful environments that support everyone's wellbeing. Your father's partnership-oriented nature gives you the ability to see multiple perspectives and find fair solutions. You have natural peacemaking abilities and the gift of helping others appreciate beauty and balance.",
    challenge: "May carry patterns of conflict avoidance, people-pleasing, or difficulty with individual assertion that stem from your father's unresolved relationship with harmony and approval. Tendency to sacrifice authentic expression to maintain peace or seek validation through being agreeable. Can struggle with decision-making or standing up for your needs when they might disappoint others.",
    advice: "Honor the diplomatic and aesthetic gifts from your father's lineage while developing authentic self-expression and healthy conflict resolution skills. Practice maintaining harmony through truth rather than avoidance. Transform inherited patterns of people-pleasing into genuine consideration that includes honoring your own needs and boundaries."
  },
  7: {
    general: "Your father's karma involves themes of determination, competition, and focused achievement, creating patterns around goal pursuit and victory in your family line. His karmic lessons may involve learning to balance drive with compassion and finding meaning beyond just winning. You may carry forward his determination and goal-oriented nature while needing to heal patterns of aggression or difficulty with cooperation. The karmic gift involves natural drive and achievement abilities and the challenge involves learning collaborative success.",
    positive: "Inherited strong drive and determination that helps you overcome obstacles and achieve meaningful goals while inspiring others to pursue their own excellence. Your father's competitive spirit gives you the courage to face challenges and the skill to succeed through focused effort. You have natural leadership in pursuit of objectives and the gift of motivating others to reach their potential.",
    challenge: "May carry patterns of excessive competitiveness, impatience with others' pace, or difficulty with collaboration that stem from your father's unresolved relationship with achievement and recognition. Tendency to become aggressive or pushy when frustrated with obstacles or others' different approaches. Can struggle with burnout or difficulty finding satisfaction in achievements once they're accomplished.",
    advice: "Honor the drive and determination from your father's lineage while developing patience and collaborative skills that enhance rather than hinder your achievements. Practice using competition to inspire mutual excellence rather than creating separation. Transform inherited patterns of aggressive pursuit into focused effort that serves collective as well as individual success."
  },
  8: {
    general: "Your father's karma involves themes of inner strength, patience, and transformation through perseverance, creating patterns around resilience and emotional healing in your family line. His karmic lessons may involve learning to express strength through compassion and finding power in vulnerability. You may carry forward his resilience and healing abilities while needing to heal patterns of emotional suppression or difficulty asking for help. The karmic gift involves natural healing presence and the challenge involves learning emotional expression.",
    positive: "Inherited deep inner strength and healing presence that helps you endure challenges with grace while supporting others through their difficult times. Your father's patient nature gives you the ability to transform pain into wisdom and help others find their own resilience. You have natural counseling abilities and the gift of seeing strength in vulnerability and growth through challenge.",
    challenge: "May carry patterns of emotional suppression, difficulty expressing needs, or tendency to endure unnecessarily difficult situations that stem from your father's unresolved relationship with strength and vulnerability. Tendency to take on others' problems while neglecting your own emotional needs. Can struggle with asking for help or expressing anger and frustration in healthy ways.",
    advice: "Honor the strength and healing abilities from your father's lineage while developing healthy emotional expression and the ability to receive support when you need it. Practice using your strength to create positive change rather than just enduring difficulties. Transform inherited patterns of emotional suppression into conscious choice about when to be strong and when to be vulnerable."
  },
  9: {
    general: "Your father's karma involves themes of wisdom, solitude, and spiritual seeking, creating patterns around knowledge and inner guidance in your family line. His karmic lessons may involve learning to balance contemplation with engagement and sharing wisdom in accessible ways. You may carry forward his spiritual insights and love of learning while needing to heal patterns of isolation or intellectual superiority. The karmic gift involves natural wisdom and teaching abilities and the challenge involves learning practical application.",
    positive: "Inherited deep wisdom and spiritual understanding that provides profound insights for your own growth and guidance for others seeking truth and meaning. Your father's contemplative nature gives you the ability to see patterns and understand life's deeper significance. You have natural teaching abilities and the gift of helping others find their own inner wisdom and spiritual direction.",
    challenge: "May carry patterns of intellectual isolation, spiritual superiority, or difficulty with practical application that stem from your father's unresolved relationship with knowledge and social connection. Tendency to withdraw from relationships when others don't share your depth or spiritual interests. Can struggle with translating insights into practical action or accessible communication.",
    advice: "Honor the wisdom and spiritual understanding from your father's lineage while developing skills for sharing insights in ways others can understand and apply. Practice balancing contemplation with engaged participation in life and relationships. Transform inherited patterns of isolation into conscious choice about when to retreat for reflection and when to engage in service."
  },
  10: {
    general: "Your father's karma involves themes of fate, cycles, and understanding divine timing, creating patterns around acceptance and flow in your family line. His karmic lessons may involve learning to balance acceptance with appropriate action and understanding how personal choices interact with larger forces. You may carry forward his wisdom about timing and cycles while needing to heal patterns of passivity or difficulty taking responsibility. The karmic gift involves natural understanding of timing and the challenge involves learning active participation.",
    positive: "Inherited understanding of life's cycles and timing that helps you navigate challenges with faith and wisdom about when to act and when to wait. Your father's philosophical nature gives you the ability to see patterns and find meaning in experiences that might confuse others. You have natural wisdom about cause and effect and the gift of helping others understand their life's larger patterns.",
    challenge: "May carry patterns of fatalism, passive waiting, or difficulty taking initiative that stem from your father's unresolved relationship with personal power and cosmic forces. Tendency to avoid responsibility by attributing everything to fate or timing rather than recognizing your own agency. Can struggle with decision-making or taking action when opportunities require initiative.",
    advice: "Honor the wisdom about timing and cycles from your father's lineage while developing appropriate initiative and responsibility for your choices and actions. Practice working with divine timing while also taking inspired action when opportunities arise. Transform inherited patterns of passivity into conscious participation in creating your life within larger cosmic patterns."
  },
  11: {
    general: "Your father's karma involves themes of justice, balance, and ethical decision-making, creating patterns around fairness and moral responsibility in your family line. His karmic lessons may involve learning to balance justice with compassion and making ethical decisions under complex circumstances. You may carry forward his strong moral sense and fairness while needing to heal patterns of rigidity or difficulty with moral ambiguity. The karmic gift involves natural ethical understanding and the challenge involves learning compassionate justice.",
    positive: "Inherited strong sense of justice and ethical understanding that helps you make fair decisions and create equitable solutions in challenging situations. Your father's principled nature gives you the ability to see truth clearly and stand up for what's right. You have natural mediation abilities and the gift of helping others understand consequences and make ethical choices.",
    challenge: "May carry patterns of moral rigidity, judgmental thinking, or difficulty with complex ethical situations that stem from your father's unresolved relationship with justice and human imperfection. Tendency to become paralyzed by analysis of right and wrong rather than taking compassionate action. Can struggle with accepting others' different moral perspectives or your own human mistakes.",
    advice: "Honor the ethical understanding and sense of justice from your father's lineage while developing compassion and flexibility for human complexity and imperfection. Practice applying principles with wisdom about circumstances and individual situations. Transform inherited patterns of moral rigidity into ethical wisdom that serves love and healing rather than judgment and punishment."
  },
  12: {
    general: "Your father's karma involves themes of sacrifice, surrender, and seeing from different perspectives, creating patterns around service and letting go in your family line. His karmic lessons may involve learning to distinguish between healthy sacrifice and martyrdom and finding wisdom through unconventional approaches. You may carry forward his wisdom and willingness to serve while needing to heal patterns of self-denial or difficulty with direct action. The karmic gift involves natural wisdom and service and the challenge involves learning healthy boundaries.",
    positive: "Inherited wisdom and spiritual understanding that comes from seeing life from different perspectives and willingness to sacrifice for meaningful purposes. Your father's service-oriented nature gives you the ability to help others and find meaning through contribution. You have natural counseling abilities and the gift of seeing solutions that others might miss through conventional thinking.",
    challenge: "May carry patterns of martyrdom, excessive self-sacrifice, or difficulty taking direct action that stem from your father's unresolved relationship with service and personal needs. Tendency to give too much of yourself or endure unnecessary hardship in the name of helping others. Can struggle with asserting your needs or taking action when situations require decisive intervention.",
    advice: "Honor the wisdom and service orientation from your father's lineage while developing healthy boundaries and the ability to take direct action when necessary. Practice distinguishing between meaningful sacrifice and unnecessary self-denial. Transform inherited patterns of martyrdom into conscious service that honors both your gifts and your authentic needs."
  },
  13: {
    general: "Your father's karma involves themes of transformation, endings, and rebirth, creating patterns around change and letting go in your family line. His karmic lessons may involve learning to navigate transitions with grace and finding meaning in life's cycles of death and renewal. You may carry forward his understanding of transformation while needing to heal patterns of crisis creation or difficulty with stability. The karmic gift involves natural transformation abilities and the challenge involves learning sustainable change.",
    positive: "Inherited ability to navigate major life transitions and help others transform through challenging circumstances with courage and wisdom. Your father's transformative nature gives you the strength to let go of what no longer serves and embrace new phases of growth. You have natural healing abilities and the gift of helping others find meaning and opportunity in difficult endings.",
    challenge: "May carry patterns of creating unnecessary drama, difficulty with stability, or fear of stagnation that stem from your father's unresolved relationship with change and security. Tendency to abandon situations too quickly or create crises when life becomes peaceful and predictable. Can struggle with building lasting foundations or appreciating gradual development and consistent growth.",
    advice: "Honor the transformation abilities from your father's lineage while developing appreciation for stability and gradual growth that supports rather than threatens authentic development. Practice creating conscious change rather than crisis-driven transformation. Transform inherited patterns of crisis creation into wisdom about when change serves growth and when consistency supports your goals."
  },
  14: {
    general: "Your father's karma involves themes of balance, healing, and integration, creating patterns around moderation and wholeness in your family line. His karmic lessons may involve learning to blend different aspects of life harmoniously and finding healing through patient integration. You may carry forward his healing abilities and balanced perspective while needing to heal patterns of suppressing intensity or difficulty with passion. The karmic gift involves natural healing presence and the challenge involves learning healthy intensity.",
    positive: "Inherited ability to create balance and healing in challenging situations and help others integrate different aspects of themselves into harmonious wholes. Your father's temperate nature gives you the wisdom to find middle ground and sustainable solutions. You have natural counseling abilities and the gift of helping others find moderation and healing in their lives.",
    challenge: "May carry patterns of avoiding intensity, suppressing passion, or difficulty with necessary conflict that stem from your father's unresolved relationship with strong emotions and direct confrontation. Tendency to maintain surface peace rather than working through important issues that need attention. Can struggle with expressing strong feelings or taking sides when situations require clear positions.",
    advice: "Honor the healing and balancing abilities from your father's lineage while developing comfort with appropriate intensity and passion when they serve authentic expression and growth. Practice maintaining your center while also engaging fully with life's emotional spectrum. Transform inherited patterns of emotional suppression into conscious moderation that includes rather than excludes strong feelings."
  },
  15: {
    general: "Your father's karma involves themes of power, material mastery, and working with shadow aspects, creating patterns around desire and control in your family line. His karmic lessons may involve learning to use power responsibly and transform material attachments into spiritual understanding. You may carry forward his understanding of power dynamics while needing to heal patterns of manipulation or difficulty with healthy boundaries. The karmic gift involves natural power awareness and the challenge involves learning conscious power use.",
    positive: "Inherited understanding of power dynamics and material reality that helps you navigate complex situations and achieve practical goals while maintaining spiritual perspective. Your father's worldly nature gives you the ability to work with challenging energies and people effectively. You have natural business or practical abilities and the gift of transforming difficult situations into opportunities for growth.",
    challenge: "May carry patterns of manipulation, power struggles, or difficulty with healthy relationships that stem from your father's unresolved relationship with control and material security. Tendency to use others for personal gain or struggle with addictive behaviors and attachments. Can struggle with trusting others or finding satisfaction in achievements once they're accomplished.",
    advice: "Honor the power awareness and practical abilities from your father's lineage while developing ethical use of influence and healthy relationship patterns. Practice using power to serve others' growth rather than just personal gain. Transform inherited patterns of manipulation into conscious influence that serves love and mutual benefit."
  },
  16: {
    general: "Your father's karma involves themes of sudden change, revelation, and breaking free from limiting structures, creating patterns around crisis and liberation in your family line. His karmic lessons may involve learning to create positive change without unnecessary destruction and finding stability after breakthrough experiences. You may carry forward his revolutionary spirit while needing to heal patterns of chaos creation or difficulty with gradual development. The karmic gift involves natural breakthrough abilities and the challenge involves learning constructive change.",
    positive: "Inherited ability to break through limiting patterns and help others liberate themselves from situations that no longer serve their growth and authentic expression. Your father's revolutionary nature gives you the courage to speak truth and create necessary changes. You have natural ability to see through illusions and the gift of helping others face reality and make liberating choices.",
    challenge: "May carry patterns of creating unnecessary drama, difficulty with authority, or tendency to destroy rather than transform that stem from your father's unresolved relationship with structure and gradual change. Tendency to rebel against all rules or create crisis when life becomes too predictable. Can struggle with building on insights rather than just breaking down old patterns.",
    advice: "Honor the breakthrough abilities from your father's lineage while developing skills for creating constructive change that builds better structures rather than just destroying old ones. Practice using revolutionary energy to serve positive transformation. Transform inherited patterns of destructive rebellion into conscious liberation that creates lasting positive change."
  },
  17: {
    general: "Your father's karma involves themes of hope, vision, and spiritual guidance, creating patterns around faith and inspiration in your family line. His karmic lessons may involve learning to ground spiritual vision in practical action and maintain hope through challenging circumstances. You may carry forward his inspirational abilities and optimistic perspective while needing to heal patterns of unrealistic expectations or difficulty with practical implementation. The karmic gift involves natural inspirational presence and the challenge involves learning practical idealism.",
    positive: "Inherited ability to maintain hope and inspire others with vision of positive possibilities even during difficult circumstances. Your father's idealistic nature gives you the faith to pursue meaningful goals and help others believe in their potential. You have natural teaching or inspirational abilities and the gift of connecting others with their spiritual guidance and higher purpose.",
    challenge: "May carry patterns of unrealistic expectations, spiritual bypassing, or difficulty with practical details that stem from your father's unresolved relationship with earthly reality and limitation. Tendency to focus on future possibilities while neglecting present responsibilities and relationships. Can struggle with disappointment when reality doesn't match idealistic visions.",
    advice: "Honor the inspirational and visionary abilities from your father's lineage while developing practical skills for manifesting ideals in concrete reality. Practice grounding spiritual vision in achievable steps and present-moment action. Transform inherited patterns of impractical idealism into inspired realism that creates positive change in the world."
  },
  18: {
    general: "Your father's karma involves themes of intuition, mystery, and navigating the unconscious realm, creating patterns around emotional depth and psychic sensitivity in your family line. His karmic lessons may involve learning to trust intuitive guidance while maintaining practical discernment and clear communication. You may carry forward his psychic abilities and emotional depth while needing to heal patterns of confusion or difficulty with boundaries. The karmic gift involves natural intuitive understanding and the challenge involves learning clear discernment.",
    positive: "Inherited psychic sensitivity and intuitive understanding that helps you navigate complex emotional territory and provide guidance for others seeking deeper understanding. Your father's mystical nature gives you access to wisdom and insights that come from beyond rational thinking. You have natural counseling abilities and the gift of helping others understand their unconscious patterns and spiritual journey.",
    challenge: "May carry patterns of emotional confusion, poor boundaries, or difficulty distinguishing between intuition and projection that stem from your father's unresolved relationship with psychic sensitivity and practical reality. Tendency to become overwhelmed by others' emotions or lost in fantasy rather than engaging with concrete circumstances. Can struggle with clear communication or taking practical action based on intuitive insights.",
    advice: "Honor the intuitive and mystical abilities from your father's lineage while developing clear boundaries and practical discernment that helps you use psychic gifts effectively. Practice grounding intuitive insights in concrete action and clear communication. Transform inherited patterns of confusion into conscious psychic ability that serves clarity and healing."
  },
  19: {
    general: "Your father's karma involves themes of joy, success, and radiant self-expression, creating patterns around achievement and recognition in your family line. His karmic lessons may involve learning to share success generously and find satisfaction in inner rather than just external validation. You may carry forward his confidence and positive energy while needing to heal patterns of narcissism or difficulty with failure. The karmic gift involves natural charisma and success abilities and the challenge involves learning humble achievement.",
    positive: "Inherited confidence and positive energy that helps you achieve success and inspire others to believe in their own potential for happiness and accomplishment. Your father's radiant nature gives you natural charisma and the ability to attract opportunities and supportive relationships. You have natural leadership abilities and the gift of helping others celebrate their achievements and find joy in life.",
    challenge: "May carry patterns of narcissism, need for constant admiration, or difficulty handling failure that stem from your father's unresolved relationship with ego and authentic self-worth. Tendency to measure worth through external success or become depressed when not receiving adequate recognition. Can struggle with sharing spotlight or supporting others' success when it might overshadow your own.",
    advice: "Honor the confidence and success abilities from your father's lineage while developing genuine humility and inner sources of satisfaction that don't depend entirely on external recognition. Practice using success to serve others rather than just personal ego gratification. Transform inherited patterns of narcissistic achievement into authentic success that includes and celebrates others' accomplishments."
  },
  20: {
    general: "Your father's karma involves themes of spiritual calling, awakening, and service to collective evolution, creating patterns around purpose and spiritual responsibility in your family line. His karmic lessons may involve learning to balance individual needs with collective service and finding practical ways to serve spiritual evolution. You may carry forward his spiritual awareness and sense of purpose while needing to heal patterns of spiritual superiority or difficulty with personal boundaries. The karmic gift involves natural spiritual authority and the challenge involves learning balanced service.",
    positive: "Inherited spiritual awareness and sense of higher purpose that helps you recognize your calling and inspire others to pursue their own spiritual development and service. Your father's awakened nature gives you natural spiritual authority and the ability to guide others through important transitions. You have natural teaching abilities and the gift of helping others understand their spiritual purpose and contribution.",
    challenge: "May carry patterns of spiritual grandiosity, neglect of personal needs, or difficulty with ordinary human concerns that stem from your father's unresolved relationship with spiritual identity and earthly responsibility. Tendency to sacrifice personal relationships and self-care for spiritual service. Can struggle with spiritual superiority or difficulty relating to people who don't share your spiritual interests.",
    advice: "Honor the spiritual awareness and sense of purpose from your father's lineage while maintaining healthy boundaries and attention to personal needs and relationships. Practice serving spiritual evolution while remaining grounded in human compassion and practical responsibility. Transform inherited patterns of spiritual superiority into humble service that includes rather than transcends ordinary human experience."
  },
  21: {
    general: "Your father's karma involves themes of completion, mastery, and integrated achievement, creating patterns around success and fulfillment in your family line. His karmic lessons may involve learning to appreciate achievements while remaining open to continued growth and sharing success with others. You may carry forward his mastery and accomplishment abilities while needing to heal patterns of complacency or difficulty with new challenges. The karmic gift involves natural mastery abilities and the challenge involves learning continued growth.",
    positive: "Inherited ability to achieve mastery and create lasting accomplishments that serve as examples for others seeking their own fulfillment and success. Your father's accomplished nature gives you the persistence and skill to complete important projects and goals. You have natural teaching abilities and the gift of helping others understand what authentic achievement and satisfaction look like in practice.",
    challenge: "May carry patterns of complacency, resting on past achievements, or difficulty with new learning that stem from your father's unresolved relationship with continued growth and beginner's mind. Tendency to judge others' efforts or become disconnected from the learning process. Can struggle with maintaining motivation when you've already achieved significant success in particular areas.",
    advice: "Honor the mastery and achievement abilities from your father's lineage while remaining open to continued learning and growth in new areas of life and service. Practice using your accomplishments to support others' development rather than setting yourself apart. Transform inherited patterns of complacency into wise mastery that continues to evolve and serve others' growth and learning."
  },
  22: {
    general: "Your father's karma involves themes of innocence, unlimited potential, and fresh perspective, creating patterns around openness and new beginnings in your family line. His karmic lessons may involve learning to balance openness with practical wisdom and maintaining wonder while developing experience. You may carry forward his spontaneity and unlimited potential while needing to heal patterns of naivety or difficulty with sustained effort. The karmic gift involves natural openness and potential and the challenge involves learning practical wisdom.",
    positive: "Inherited openness and fresh perspective that helps you approach life with wonder and discover new possibilities that others might miss through preconceptions. Your father's spontaneous nature gives you the freedom to explore and experiment without being limited by past experience. You have natural creativity and the gift of helping others maintain beginner's mind and openness to growth.",
    challenge: "May carry patterns of naivety, difficulty with commitment, or tendency to abandon projects when they become challenging that stem from your father's unresolved relationship with responsibility and sustained effort. Tendency to avoid developing depth or expertise in favor of constant exploration. Can struggle with practical follow-through or learning from others' experience and wisdom.",
    advice: "Honor the openness and fresh perspective from your father's lineage while developing practical wisdom and the ability to commit to sustained development in areas that truly matter to you. Practice maintaining wonder while also learning from experience and guidance. Transform inherited patterns of spiritual or practical immaturity into conscious choice about when to explore and when to deepen your commitment and expertise."
  }
};