/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Heart's Wishes Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * deep heart desires, soul longings, emotional fulfillment needs, and
 * what your heart truly wishes for in life and relationships.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Heart's Wishes - Your deepest desires and emotional fulfillment needs
 */
export const heartsWishesInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your heart wishes for the freedom to express your authentic self boldly and to create something entirely new and meaningful in the world. You long to be recognized as a unique individual with valuable contributions to make, and your heart desires the courage to lead and pioneer new possibilities. Deep down, you wish for the confidence to take risks and the support to pursue your most innovative ideas without fear of judgment. Your heart seeks the thrill of creation and the satisfaction of being first.",
    positive: "Natural confidence in expressing your heart's desires and the courage to pursue what truly excites and inspires you. Your authentic enthusiasm for new experiences and creative expression attracts others who support your dreams. You excel at recognizing and honoring your heart's true wishes without being swayed by others' expectations or conventional limitations.",
    challenge: "May wish for constant excitement and new beginnings without appreciating the value of developing and nurturing existing relationships and projects. Tendency to become restless when heart's desires aren't immediately fulfilled or when life requires patience rather than action. Can struggle with selfish desires that don't consider others' needs or the impact of your wishes on relationships.",
    advice: "Balance your heart's desire for new experiences with appreciation for the depth that comes from sustained commitment and development. Practice expressing your authentic wishes while also considering how they affect others and your relationships. Channel your pioneering heart energy toward creating lasting value rather than just seeking constant stimulation."
  },
  2: {
    general: "Your heart wishes for deep emotional connection, spiritual understanding, and the safety to explore your inner world without judgment or pressure. You long for relationships where you can share your intuitive insights and be truly understood on a soul level. Deep down, you wish for quiet spaces where you can reflect and process your emotions, and for others who appreciate the subtle, mysterious aspects of life. Your heart seeks sacred connection and the peace that comes from being accepted as you are.",
    positive: "Natural ability to recognize and honor your need for emotional depth and spiritual connection in relationships and life experiences. Your intuitive understanding of your own heart helps you create relationships that truly nourish your soul. You excel at expressing your deepest wishes through gentle, authentic sharing that invites others into genuine intimacy.",
    challenge: "May wish for perfect understanding without taking the risk of clearly communicating your needs and desires to others. Tendency to expect others to intuitively know what your heart wants without direct expression. Can become withdrawn when others don't naturally provide the emotional depth and spiritual connection you crave.",
    advice: "Practice expressing your heart's wishes clearly and directly rather than hoping others will guess what you need. Create opportunities for the deep connection you crave while also appreciating different forms of caring that others offer. Balance your desire for spiritual understanding with engagement in practical expressions of love and support."
  },
  3: {
    general: "Your heart wishes for abundant love, creative fulfillment, and the opportunity to nurture and be nurtured in relationships that feel rich and satisfying. You long to create beauty and share your creative gifts generously while also receiving appreciation and support for your contributions. Deep down, you wish for relationships and experiences that feel luxurious, beautiful, and deeply nourishing to your senses and emotions. Your heart seeks the joy of creation and the pleasure of being cherished.",
    positive: "Natural ability to recognize and create the abundant, beautiful experiences your heart craves while also sharing that abundance generously with others. Your appreciation for life's pleasures helps you attract relationships and opportunities that truly satisfy your heart's desires. You excel at expressing your wishes through creative action and generous love that creates more abundance for everyone.",
    challenge: "May wish for constant pleasure and comfort without appreciating the growth that comes from occasional challenge or scarcity. Tendency to become dependent on external abundance and others' appreciation for your sense of worth and satisfaction. Can struggle with giving too much in hopes of receiving the love and appreciation your heart craves.",
    advice: "Balance your heart's desire for abundance with appreciation for simple pleasures and the security that comes from inner satisfaction. Practice receiving love and appreciation as freely as you give it, recognizing your inherent worth. Create sustainable patterns of giving and receiving that honor both your generous heart and your need for nourishment."
  },
  4: {
    general: "Your heart wishes for security, stability, and the deep satisfaction that comes from building something lasting and meaningful through dedicated effort. You long for relationships and achievements that you can count on over time, and for the peace that comes from having solid foundations beneath your dreams. Deep down, you wish for the respect that comes from consistent reliability and the comfort of knowing your efforts create lasting value. Your heart seeks the pride of achievement and the security of stable foundations.",
    positive: "Strong ability to recognize what your heart truly needs for long-term satisfaction and the patience to build it gradually through consistent effort. Your realistic approach to heart's desires helps you create lasting fulfillment rather than temporary satisfaction. You excel at translating your deepest wishes into practical plans and sustained action that creates real results.",
    challenge: "May wish for guaranteed security and predictable outcomes without accepting the uncertainty that's natural in life and relationships. Tendency to suppress heart's desires that seem impractical or risky, limiting your emotional and creative expression. Can become rigid about how your wishes should be fulfilled, missing alternative paths to satisfaction.",
    advice: "Balance your need for security with openness to growth and change that can enhance rather than threaten your foundations. Practice expressing heart's desires that feel risky while building on the stable base you've created. Remember that true security includes flexibility and the ability to adapt while maintaining your core values and commitments."
  },
  5: {
    general: "Your heart wishes for meaning, spiritual connection, and the guidance that comes from being part of something larger than yourself. You long for relationships and experiences that connect you with traditional wisdom and established values that provide direction and purpose. Deep down, you wish for the respect and understanding that comes from living according to higher principles and for the community that shares your deepest beliefs. Your heart seeks the peace of spiritual belonging and moral clarity.",
    positive: "Natural connection to your deepest values and spiritual longings that provides clear direction for your heart's true desires. Your ability to find meaning in traditional wisdom helps you make choices that satisfy your soul as well as your emotions. You excel at expressing wishes that align with your highest values and spiritual understanding.",
    challenge: "May wish for perfect spiritual guidance and moral clarity without accepting the complexity and ambiguity that's natural in human experience. Tendency to suppress heart's desires that don't fit traditional expectations or established spiritual frameworks. Can become judgmental about your own or others' wishes that seem inconsistent with spiritual ideals.",
    advice: "Balance your connection to spiritual values with acceptance of your human emotions and desires as equally valid parts of your spiritual journey. Practice expressing heart's wishes while seeking guidance rather than suppressing them as unspiritual. Remember that authentic spiritual connection includes honoring your whole self, including your emotional and creative desires."
  },
  6: {
    general: "Your heart wishes for harmonious love, beautiful relationships, and the deep satisfaction that comes from mutual appreciation and aesthetic pleasure. You long for partnerships where beauty, balance, and mutual respect create an environment of lasting happiness and creative collaboration. Deep down, you wish for the kind of love that feels like art and for relationships that enhance rather than diminish your appreciation for life's beauty. Your heart seeks the joy of shared aesthetic experience and balanced partnership.",
    positive: "Natural ability to recognize and create the harmonious relationships and beautiful experiences your heart craves while also contributing to others' happiness and aesthetic satisfaction. Your appreciation for balance helps you express wishes in ways that consider others' needs and desires. You excel at creating win-win situations where everyone's heart wishes can be honored and fulfilled.",
    challenge: "May wish for perfect harmony without accepting the occasional conflict and tension that's natural in authentic relationships. Tendency to suppress difficult emotions or challenging desires in order to maintain surface peace and aesthetic pleasure. Can become dependent on others' approval and external beauty for your sense of emotional satisfaction.",
    advice: "Balance your desire for harmony with willingness to express authentic emotions and work through conflicts that can deepen rather than threaten your relationships. Practice voicing difficult heart's wishes while maintaining your commitment to mutual respect and consideration. Remember that true beauty and harmony can include working through challenges together."
  },
  7: {
    general: "Your heart wishes for the thrill of achievement, the satisfaction of overcoming challenges, and the recognition that comes from demonstrating your capabilities and determination. You long for goals that stretch your abilities and for the rush of energy that comes from pursuing something meaningful with focused intensity. Deep down, you wish for the confidence that comes from knowing you can handle whatever challenges arise and for others who appreciate your strength and drive. Your heart seeks the victory of achieved goals and respected capability.",
    positive: "Natural drive and enthusiasm that helps you pursue your heart's desires with courage and determination. Your ability to find excitement in challenges attracts opportunities to grow and achieve meaningful goals. You excel at translating heart's wishes into concrete objectives and taking consistent action to make them reality.",
    challenge: "May wish for constant challenge and achievement without appreciating the value of rest, reflection, and gentle enjoyment of what you've already accomplished. Tendency to become impatient when heart's desires require patience or collaboration rather than individual effort and determination. Can struggle with competitive desires that interfere with loving relationships and mutual support.",
    advice: "Balance your heart's desire for achievement with appreciation for peaceful moments and the satisfaction of supporting others' success as well as your own. Practice expressing wishes for growth and challenge while maintaining loving connections with others. Channel your competitive energy toward inspiring mutual excellence rather than creating separation or conflict."
  },
  8: {
    general: "Your heart wishes for deep healing, transformative love, and the strength to work through emotional challenges with grace and wisdom. You long for relationships where patience and compassion create the safety needed for authentic vulnerability and emotional growth. Deep down, you wish for the inner strength to handle whatever life brings and for others who understand that true love includes supporting each other through difficulties. Your heart seeks the peace of emotional healing and the strength of tested love.",
    positive: "Natural wisdom about your emotional needs and the patience to work toward healing and authentic satisfaction rather than seeking quick fixes. Your compassionate understanding of human struggle helps you express heart's wishes with consideration for timing and others' capacity. You excel at creating relationships where deep emotional work can happen safely and lovingly.",
    challenge: "May wish for emotional healing and support without taking the risks necessary to ask for help or express vulnerability. Tendency to focus so much on others' emotional needs that you neglect to express and pursue your own heart's desires. Can become resigned to emotional difficulties rather than actively working toward the healing and happiness your heart truly wants.",
    advice: "Practice expressing your heart's deepest wishes for healing and happiness while also taking concrete steps toward creating these experiences. Balance your care for others with equal attention to your own emotional needs and desires. Remember that seeking and accepting support for your heart's wishes is a strength, not a weakness."
  },
  9: {
    general: "Your heart wishes for wisdom, spiritual understanding, and the deep satisfaction that comes from contemplating life's mysteries and sharing insights with others. You long for solitude that nourishes your soul and for relationships that honor your need for depth and meaningful conversation. Deep down, you wish for the peace that comes from understanding your life's experiences and for the respect that comes from genuine wisdom and spiritual insight. Your heart seeks the fulfillment of inner knowing and meaningful spiritual connection.",
    positive: "Deep understanding of your need for contemplation and meaningful connection that helps you create a life aligned with your soul's deepest longings. Your wisdom about human nature helps you express heart's wishes in ways that others can understand and respect. You excel at finding satisfaction in inner experiences and sharing insights that truly serve others' growth.",
    challenge: "May wish for perfect understanding and wisdom without engaging in the relationships and experiences that provide opportunities for learning and growth. Tendency to withdraw from emotional connection when others don't share your depth or spiritual interests. Can become isolated in pursuit of wisdom, missing the heart connection that gives knowledge its real meaning.",
    advice: "Balance your need for solitary contemplation with regular engagement in relationships that allow you to share your wisdom and receive different perspectives. Practice expressing your heart's wishes for depth and meaning while also appreciating others' different approaches to life and learning. Remember that wisdom serves love and connection, not separation or superiority."
  },
  10: {
    general: "Your heart wishes for the understanding of life's patterns and cycles, the wisdom to accept divine timing, and the faith that everything happens for meaningful reasons. You long for the peace that comes from trusting life's natural flow and for the excitement of recognizing synchronicities and meaningful coincidences. Deep down, you wish for the security of knowing that you're part of a larger cosmic order and for the adventure of discovering how events connect in meaningful ways. Your heart seeks the wonder of divine timing and cosmic connection.",
    positive: "Natural understanding of timing and patterns that helps you align your heart's desires with natural rhythms and opportunities. Your faith in life's deeper meaning helps you maintain hope and patience when wishes take time to manifest. You excel at recognizing when the timing is right to pursue heart's desires and when to wait for better opportunities.",
    challenge: "May wish for perfect timing and clear signs without taking the initiative needed to create opportunities and manifest desires. Tendency to become passive about pursuing heart's wishes, waiting for fate to provide rather than actively participating in creating outcomes. Can use belief in cosmic timing to avoid taking responsibility for expressing and pursuing authentic desires.",
    advice: "Balance your understanding of divine timing with proactive steps toward creating the experiences your heart desires. Practice working with natural rhythms while also taking inspired action when opportunities arise. Remember that cosmic timing often includes your conscious participation rather than just passive waiting."
  },
  11: {
    general: "Your heart wishes for fairness, justice, and the deep satisfaction that comes from living according to your highest principles and values. You long for relationships where honesty and integrity create trust and mutual respect, and for the peace that comes from making decisions that feel morally right. Deep down, you wish for the clarity to know what's right and the courage to act accordingly, even when it's difficult. Your heart seeks the contentment of ethical living and just relationships.",
    positive: "Strong moral compass that helps you recognize heart's desires that align with your deepest values and create lasting satisfaction. Your commitment to fairness helps you express wishes in ways that consider others' needs and rights. You excel at making decisions about heart's desires based on both emotional truth and ethical considerations.",
    challenge: "May wish for perfect justice and moral clarity without accepting the complexity and ambiguity that's natural in human relationships and decisions. Tendency to suppress heart's desires that seem morally complicated or potentially unfair to others. Can become paralyzed by analysis of ethical implications rather than trusting your heart's wisdom and good intentions.",
    advice: "Balance your commitment to ethics with acceptance of human complexity and the understanding that perfect fairness isn't always possible. Practice expressing heart's desires while seeking solutions that honor both your needs and ethical considerations. Remember that authentic morality includes being honest about your heart's wishes rather than pretending they don't exist."
  },
  12: {
    general: "Your heart wishes for the wisdom that comes from seeing life from different perspectives, the freedom to release attachments that no longer serve, and the peace that comes from accepting what cannot be changed. You long for the understanding that emerges from sacrifice and the liberation that comes from letting go of old patterns and expectations. Deep down, you wish for the courage to surrender control and trust in outcomes beyond your planning. Your heart seeks the wisdom of acceptance and the freedom of release.",
    positive: "Natural wisdom about when to hold on and when to let go that helps you navigate heart's desires with grace and acceptance. Your ability to see situations from multiple perspectives helps you find creative solutions when direct approaches don't work. You excel at finding meaning and satisfaction even when your wishes don't manifest as expected.",
    challenge: "May wish for others to understand your sacrifices and alternative perspectives without clearly communicating your needs and desires. Tendency to give up on heart's wishes too easily rather than finding creative ways to honor them while serving larger purposes. Can become martyrlike about your desires, sacrificing them unnecessarily rather than seeking win-win solutions.",
    advice: "Balance your wisdom about acceptance with appropriate advocacy for your heart's authentic desires and needs. Practice finding creative ways to honor your wishes while also serving larger purposes rather than assuming they're incompatible. Remember that healthy sacrifice serves love and growth, not self-denial or martyrdom."
  },
  13: {
    general: "Your heart wishes for profound transformation, the courage to release what no longer serves your growth, and the faith to embrace new phases of life and relationship. You long for experiences that transform you at the deepest levels and for the freedom to evolve and change as your understanding deepens. Deep down, you wish for the strength to let go of familiar patterns that limit your growth and for others who understand that change serves love. Your heart seeks the rebirth that comes from authentic transformation.",
    positive: "Natural comfort with change and transformation that helps you recognize when heart's desires need to evolve and shift to serve your continued growth. Your courage in facing endings helps you make space for new wishes and dreams to emerge. You excel at helping others understand how releasing old desires can make room for wishes that better serve their authentic development.",
    challenge: "May wish for constant transformation and intensity without appreciating the value of stability and gentle development in relationships and personal growth. Tendency to abandon heart's desires when they become familiar rather than deepening your appreciation and commitment. Can create unnecessary endings when working through challenges might lead to greater satisfaction.",
    advice: "Balance your comfort with transformation with appreciation for the deepening that comes from sustained commitment and gradual development. Practice distinguishing between desires that truly need to be released and those that deserve continued investment and growth. Remember that authentic transformation often includes deepening existing connections rather than just creating new ones."
  },
  14: {
    general: "Your heart wishes for balance, healing, and the gentle integration of different aspects of your emotional and spiritual nature. You long for experiences that bring harmony to your inner conflicts and for relationships that support your gradual growth and healing. Deep down, you wish for the patience to allow emotional wounds to heal naturally and for the wisdom to blend different desires into satisfying wholes. Your heart seeks the peace of integration and the satisfaction of balanced fulfillment.",
    positive: "Natural ability to create balance between different heart's desires and to find satisfaction through moderation and patience rather than extremes. Your healing presence helps others find their own emotional balance and integration. You excel at expressing wishes in ways that consider multiple needs and create sustainable patterns of fulfillment.",
    challenge: "May wish for perfect emotional balance without accepting the natural fluctuations and intensity that're part of authentic emotional life. Tendency to suppress strong desires or passionate wishes in favor of maintaining comfortable equilibrium. Can become too focused on healing past wounds while neglecting to pursue new dreams and desires.",
    advice: "Balance your wisdom about moderation with openness to appropriate intensity and passionate pursuit of heart's desires when they serve your growth. Practice working with emotional fluctuations as natural rather than always seeking to maintain steady equilibrium. Remember that true healing includes embracing your full emotional range rather than just avoiding difficulties."
  },
  15: {
    general: "Your heart wishes for intense experiences, passionate connection, and the freedom to explore the full spectrum of human desire without judgment or shame. You long for relationships where power and vulnerability can be explored safely and for the excitement that comes from embracing your shadow aspects with consciousness. Deep down, you wish for the courage to want what you truly want and for others who can meet your intensity with understanding rather than fear. Your heart seeks the liberation of authentic desire and conscious power.",
    positive: "Natural honesty about your desires and the courage to pursue intense experiences that serve your growth and authentic expression. Your comfort with complex emotions and power dynamics helps you create relationships where deep exploration is possible. You excel at helping others accept their own shadow desires and find healthy ways to express them.",
    challenge: "May wish for intensity and drama without considering the impact on others or the sustainability of extreme patterns. Tendency to become obsessed with particular desires or people rather than maintaining balance and perspective. Can use the language of authenticity to justify selfish or harmful wishes that don't consider others' wellbeing.",
    advice: "Channel your comfort with intensity toward creating conscious, consensual experiences that serve mutual growth rather than just personal gratification. Practice expressing your authentic desires while also considering their impact on others and your long-term wellbeing. Remember that true freedom includes responsibility for the effects of your choices and desires."
  },
  16: {
    general: "Your heart wishes for breakthrough moments, sudden liberation from limiting patterns, and the exhilaration that comes from shattering false structures to reach authentic truth. You long for experiences that fundamentally change your understanding and for the freedom that comes from releasing illusions about yourself and your relationships. Deep down, you wish for the courage to face difficult truths and for the clarity that emerges from crisis and revelation. Your heart seeks the liberation of authentic awakening and the excitement of breakthrough insights.",
    positive: "Natural ability to recognize when heart's desires are based on illusions rather than authentic needs, and the courage to release false wishes for truer ones. Your comfort with sudden change helps you navigate breakthrough moments with grace and wisdom. You excel at helping others break free from limiting patterns and discover their authentic heart's desires.",
    challenge: "May wish for constant drama and breakthrough without appreciating the value of gradual development and stable satisfaction. Tendency to create crisis in order to experience the intensity and revelation you crave. Can abandon relationships and projects too quickly when they become familiar rather than allowing them to deepen and mature.",
    advice: "Balance your gift for breakthrough insights with patience for gradual development and sustained commitment to authentic desires. Practice building on revelations and insights rather than constantly seeking new dramatic experiences. Channel your revolutionary energy toward creating lasting positive change rather than just disrupting comfortable patterns."
  },
  17: {
    general: "Your heart wishes for hope, inspiration, and the deep faith that your dreams and highest aspirations can manifest in reality. You long for experiences that connect you with your spiritual purpose and for the guidance that helps you navigate toward your most beautiful possibilities. Deep down, you wish for the optimism to maintain vision even during difficult times and for others who share your faith in positive potential. Your heart seeks the fulfillment of inspired dreams and the joy of aligned purpose.",
    positive: "Natural connection to hope and positive vision that helps you maintain faith in your heart's deepest wishes even when circumstances seem challenging. Your optimistic outlook attracts opportunities and relationships that support your dreams and aspirations. You excel at inspiring others to believe in their own heart's wishes and to take steps toward manifesting their dreams.",
    challenge: "May wish for perfect outcomes and ideal fulfillment without engaging with the practical steps and potential challenges involved in manifesting dreams. Tendency to focus on future possibilities while neglecting present opportunities and relationships. Can become disappointed when reality doesn't match your ideal visions rather than appreciating partial fulfillment and gradual progress.",
    advice: "Ground your beautiful visions in practical steps and present-moment appreciation while maintaining your connection to inspired possibilities. Practice finding satisfaction in gradual progress toward your dreams rather than only in perfect fulfillment. Balance your faith in positive potential with realistic engagement with current circumstances and relationships."
  },
  18: {
    general: "Your heart wishes for mystery, depth, and the profound connection that comes from exploring the hidden realms of emotion and psychic experience. You long for relationships where soul recognition and intuitive understanding create bonds that transcend ordinary communication. Deep down, you wish for the safety to explore your deepest emotional waters and for others who can navigate mystery and uncertainty with you. Your heart seeks the magic of soul connection and the wonder of exploring the unknown together.",
    positive: "Natural attunement to your deepest emotional needs and intuitive wisdom about what your heart truly desires beyond surface attractions. Your comfort with mystery helps you navigate complex emotional territory and find satisfaction in subtle forms of connection. You excel at recognizing soul connections and creating relationships that honor both visible and invisible aspects of love.",
    challenge: "May wish for perfect psychic understanding without taking the practical steps needed to communicate and create real intimacy with others. Tendency to become lost in emotional projections or fantasies rather than working with actual relationship dynamics. Can expect others to intuitively understand your unspoken wishes without clear communication.",
    advice: "Balance your intuitive understanding of heart's desires with practical communication and action that creates real connection and intimacy. Practice distinguishing between genuine soul connection and emotional projection or wishful thinking. Ground your psychic insights in concrete expressions of love and care that others can receive and understand."
  },
  19: {
    general: "Your heart wishes for joy, celebration, and the radiant happiness that comes from authentic success and loving recognition. You long for experiences that fill you with genuine delight and for relationships where mutual appreciation creates an atmosphere of celebration and abundance. Deep down, you wish for the confidence to shine your light fully and for others who celebrate your success and happiness rather than diminishing it. Your heart seeks the fulfillment of joyful achievement and radiant self-expression.",
    positive: "Natural ability to recognize and pursue experiences that bring genuine joy and satisfaction to your heart. Your positive energy and enthusiasm attract relationships and opportunities that support your happiness and success. You excel at creating celebratory experiences and helping others recognize and appreciate their own reasons for joy and celebration.",
    challenge: "May wish for constant happiness and celebration without accepting the natural rhythms that include challenge and difficult growth experiences. Tendency to suppress or deny darker emotions and difficult desires in order to maintain positive energy. Can become dependent on external recognition and success for your sense of worth and emotional satisfaction.",
    advice: "Balance your natural joy and positive energy with acceptance of life's full emotional spectrum as equally valid parts of your human experience. Practice finding inner sources of happiness that don't depend entirely on external circumstances and others' approval. Remember that authentic joy can coexist with challenge and that working through difficulties often leads to deeper satisfaction."
  },
  20: {
    general: "Your heart wishes for spiritual awakening, the fulfillment of your soul's calling, and the deep satisfaction that comes from aligning your life with divine purpose. You long for experiences that serve not just personal happiness but collective good, and for the clarity to understand how your individual desires serve larger spiritual purposes. Deep down, you wish for the courage to answer your spiritual calling and for the support to serve in ways that feel meaningful and aligned. Your heart seeks the fulfillment of spiritual service and divine alignment.",
    positive: "Natural connection to your soul's deeper purpose that helps you recognize heart's desires that serve both personal fulfillment and spiritual growth. Your understanding of collective needs helps you express wishes in ways that consider larger purposes and impacts. You excel at finding satisfaction in service and inspiring others to align their desires with spiritual purpose.",
    challenge: "May wish for perfect spiritual clarity and calling without engaging with the uncertainty and gradual development that's part of authentic spiritual growth. Tendency to suppress personal desires in favor of what seems spiritually correct rather than finding ways to honor both. Can become overwhelmed by spiritual responsibility while neglecting personal emotional needs and heart's desires.",
    advice: "Balance your spiritual calling with attention to your personal emotional needs and individual heart's desires as equally important parts of your spiritual journey. Practice integrating personal fulfillment with service rather than seeing them as conflicting. Remember that answering spiritual calling includes honoring your whole self, not just transcending personal desires."
  },
  21: {
    general: "Your heart wishes for completion, fulfillment, and the deep satisfaction that comes from achieving wholeness in your emotional and spiritual development. You long for the integration of all aspects of yourself and for relationships that honor your full complexity and achievement. Deep down, you wish for the respect and recognition that comes from genuine accomplishment and for the peace of knowing you've fulfilled your potential. Your heart seeks the contentment of achieved goals and integrated wholeness.",
    positive: "Natural understanding of what creates lasting satisfaction and the patience to work toward genuine fulfillment rather than settling for temporary pleasures. Your integrated approach to heart's desires helps you create satisfaction that honors multiple aspects of your nature. You excel at helping others recognize their own path to wholeness and authentic fulfillment.",
    challenge: "May wish for perfect completion and achievement without remaining open to continued growth and evolution in your desires and understanding. Tendency to rest on past accomplishments rather than exploring new dimensions of heart's fulfillment. Can become disconnected from simple pleasures and spontaneous desires while focused on achieved goals and recognized success.",
    advice: "Honor your achievements and integrated understanding while remaining open to new forms of fulfillment and continued emotional growth. Practice appreciating both your accomplishments and your ongoing capacity for new desires and dreams. Balance your wisdom about lasting satisfaction with openness to surprise and discovery in your emotional life."
  },
  22: {
    general: "Your heart wishes for freedom, adventure, and the unlimited possibility of discovering new forms of joy and connection throughout your life. You long for experiences that feel fresh and spontaneous and for relationships that maintain wonder and curiosity rather than becoming routine or predictable. Deep down, you wish for the courage to remain open to surprise and for others who share your enthusiasm for life's endless possibilities. Your heart seeks the excitement of perpetual discovery and the joy of innocent wonder.",
    positive: "Natural openness to new experiences and forms of love that keeps your heart fresh and available for continued growth and surprise. Your enthusiasm and curiosity about life attract diverse opportunities for emotional fulfillment and connection. You excel at helping others maintain beginner's mind about their heart's desires and remain open to unexpected forms of satisfaction.",
    challenge: "May wish for constant novelty and excitement without appreciating the depth that comes from sustained commitment and developed relationships. Tendency to abandon heart's desires when they become familiar rather than discovering new dimensions within established connections. Can lack the patience and wisdom needed to navigate complex emotional situations that require maturity and experience.",
    advice: "Balance your love of freedom and novelty with willingness to explore the depths available within sustained commitments and developed relationships. Practice finding continued wonder and discovery within familiar connections rather than always seeking new experiences. Combine your natural openness with wisdom gained through experience and guidance from others who have traveled similar paths."
  }
};