/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Higher Self Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * connection to higher self, spiritual guidance, soul purpose, and the
 * highest expression of your authentic essence and divine nature.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Higher Self - Your connection to divine essence and soul purpose
 */
export const higherSelfInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your higher self embodies the pure creative force of the universe, representing divine will in action and the sacred power of bringing new realities into existence. Your soul purpose involves pioneering new possibilities and demonstrating what's possible when divine creativity flows through individual expression. You are here to show others how to connect with their own creative power and courage to manifest their unique vision. Your highest expression involves fearless leadership that serves not ego but divine purpose.",
    positive: "Natural connection to divine creative force that allows you to channel pure inspiration into manifested reality. Your higher self radiates confidence and courage that comes from knowing you are expressing divine will through your actions. You excel at inspiring others to connect with their own divine nature and creative power, leading by example rather than force.",
    challenge: "May confuse ego desires with divine will, using spiritual concepts to justify selfish actions or dominating behavior. Tendency to believe that your perspective is always divinely guided without adequate discernment or humility. Can become spiritually arrogant, assuming your impulses are always from higher self rather than lower ego patterns.",
    advice: "Cultivate genuine humility and discernment to distinguish between ego desires and authentic divine guidance. Practice serving the greater good through your leadership rather than just expressing personal will. Develop regular spiritual practices that help you align with divine will rather than assuming you're always connected."
  },
  2: {
    general: "Your higher self embodies divine feminine wisdom, intuitive knowing, and the sacred receptivity that allows spiritual truth to flow through you. Your soul purpose involves serving as a conduit for higher wisdom and helping others access their own inner knowing and spiritual guidance. You are here to demonstrate the power of quiet receptivity and the profound insights that come from deep listening to divine voice. Your highest expression involves sharing spiritual wisdom with gentle authority.",
    positive: "Natural connection to divine wisdom and intuitive guidance that provides reliable access to higher truth and spiritual insight. Your higher self operates through trust in the unseen and faith in divine timing and guidance. You excel at helping others quiet their minds and access their own inner wisdom and spiritual connection.",
    challenge: "May become passive about expressing divine guidance, waiting for others to ask rather than sharing wisdom when it would serve. Tendency to doubt your spiritual insights or defer to others' more assertive spiritual expressions. Can become lost in mystical experiences without grounding wisdom in practical service.",
    advice: "Trust your connection to divine wisdom while developing confidence to share insights when they would serve others' growth. Practice expressing spiritual guidance clearly and directly rather than only through subtle suggestion. Balance mystical receptivity with practical application of divine wisdom in daily life."
  },
  3: {
    general: "Your higher self embodies divine creativity, abundance, and the sacred feminine power of bringing beauty and life into manifestation. Your soul purpose involves creating heaven on earth through beauty, nurturing, and the generous sharing of divine love and creative expression. You are here to demonstrate how spiritual connection manifests as earthly abundance and how divine love expresses itself through creativity and care. Your highest expression involves being a living channel for divine creative love.",
    positive: "Natural ability to channel divine love and creativity into beautiful manifestations that nourish and inspire others. Your higher self expresses through generous sharing of gifts and the creation of abundant, beautiful experiences that reflect divine nature. You excel at showing others how spiritual connection enhances rather than diminishes earthly pleasure and creativity.",
    challenge: "May become too focused on earthly manifestations of spirituality, losing connection to the transcendent source. Tendency to use spiritual concepts to justify material desires or to measure spiritual growth by external abundance. Can become possessive about spiritual gifts or use them for personal gain rather than service.",
    advice: "Balance appreciation for earthly beauty and abundance with recognition of their spiritual source and purpose. Practice sharing your creative gifts freely while maintaining connection to the divine love that inspires them. Remember that true spiritual abundance includes generosity and service to others' spiritual growth."
  },
  4: {
    general: "Your higher self embodies divine order, sacred structure, and the cosmic laws that govern spiritual development and manifestation. Your soul purpose involves creating stable foundations for spiritual growth and demonstrating how discipline and dedication serve divine purpose. You are here to show others how to build lasting spiritual practices and create structures that support higher consciousness. Your highest expression involves being a reliable anchor for divine order in chaotic times.",
    positive: "Strong connection to divine order and cosmic law that provides stable foundation for spiritual development and service. Your higher self expresses through consistent spiritual practice and the ability to create lasting structures that support others' growth. You excel at demonstrating how discipline and dedication actually increase spiritual freedom rather than limiting it.",
    challenge: "May become rigid about spiritual practices or beliefs, confusing personal preferences with divine law. Tendency to judge others' spiritual paths that don't match your systematic approach. Can become too focused on form and structure while losing connection to the spirit they're meant to serve.",
    advice: "Honor your connection to divine order while remaining flexible about how spiritual truth can be expressed and practiced. Use your organizational gifts to support others' spiritual growth rather than imposing your preferred structures. Remember that divine law serves love and freedom, not control or limitation."
  },
  5: {
    general: "Your higher self embodies the wisdom of spiritual tradition, sacred teaching, and the accumulated divine knowledge that guides humanity's spiritual evolution. Your soul purpose involves bridging ancient wisdom with contemporary understanding and serving as a spiritual teacher or guide. You are here to help others connect with established spiritual paths while honoring their individual journey. Your highest expression involves transmitting divine wisdom through traditional yet personally meaningful forms.",
    positive: "Deep connection to spiritual tradition and divine wisdom that provides reliable guidance for your own and others' spiritual development. Your higher self operates through reverence for sacred teaching and the humility to learn from those who have walked the path before. You excel at helping others find their place within larger spiritual traditions while honoring their unique calling.",
    challenge: "May become overly attached to traditional forms without recognizing how divine truth can evolve and express itself in new ways. Tendency to judge non-traditional spiritual paths or to resist personal revelation that doesn't fit established frameworks. Can become spiritually conservative, limiting divine expression to familiar forms.",
    advice: "Honor spiritual tradition while remaining open to how divine truth continues to evolve and reveal itself. Practice distinguishing between eternal principles and temporary forms of expression. Use your knowledge of tradition to support others' spiritual growth rather than limiting their authentic expression."
  },
  6: {
    general: "Your higher self embodies divine love, sacred relationship, and the higher octave of beauty that reflects heavenly harmony. Your soul purpose involves demonstrating how love and beauty serve spiritual evolution and creating relationships that support mutual spiritual growth. You are here to show others how authentic partnership and aesthetic appreciation can be spiritual practices. Your highest expression involves being a living example of divine love in human relationship.",
    positive: "Natural connection to divine love that expresses itself through harmonious relationships and the creation of beauty that uplifts consciousness. Your higher self operates through the understanding that all beings are connected in divine love. You excel at helping others experience spiritual growth through loving relationship and appreciation of divine beauty.",
    challenge: "May avoid spiritual challenges or difficult growth experiences in favor of maintaining harmony and comfort. Tendency to focus on superficial beauty or pleasant relationships rather than the deeper spiritual work they can facilitate. Can become dependent on others' approval or external beauty for spiritual validation.",
    advice: "Embrace the full spectrum of spiritual experience, including challenges that deepen love and understanding. Practice finding divine beauty and love even in difficult circumstances and relationships. Use your gift for harmony to facilitate authentic spiritual growth rather than just maintaining surface peace."
  },
  7: {
    general: "Your higher self embodies divine will, spiritual warrior energy, and the sacred courage needed to overcome obstacles on the spiritual path. Your soul purpose involves demonstrating spiritual mastery through disciplined effort and inspiring others to persist in their own spiritual development. You are here to show how determination and focused intention can transform challenges into spiritual victories. Your highest expression involves using your spiritual strength to serve and protect others' growth.",
    positive: "Strong connection to divine will that provides courage and determination for your spiritual journey and service to others. Your higher self expresses through the spiritual warrior archetype, using strength and skill to advance consciousness. You excel at inspiring others to develop their own spiritual courage and persist through difficulties.",
    challenge: "May become spiritually competitive or aggressive, using spiritual concepts to justify dominating behavior. Tendency to focus on spiritual achievement and advancement rather than service and love. Can become impatient with others' slower spiritual development or dismiss gentler spiritual approaches.",
    advice: "Channel your spiritual warrior energy toward serving love and protecting others rather than just achieving personal spiritual victories. Practice patience and compassion for others' spiritual timing and different approaches to growth. Remember that true spiritual strength includes gentleness and humility."
  },
  8: {
    general: "Your higher self embodies divine compassion, spiritual strength through surrender, and the sacred power of transformation through love. Your soul purpose involves demonstrating how gentleness and patience can accomplish what force cannot, and how love transforms even the most difficult circumstances. You are here to show others the spiritual strength that comes from compassion and the power of healing through divine love. Your highest expression involves being a channel for divine healing and transformation.",
    positive: "Deep connection to divine compassion that provides strength to endure and transform challenging circumstances with grace. Your higher self operates through understanding that love is the most powerful force for spiritual transformation. You excel at helping others find spiritual strength through acceptance and compassion rather than resistance.",
    challenge: "May become spiritually passive, confusing surrender with avoidance of necessary spiritual action. Tendency to endure unnecessary suffering rather than using spiritual power to create positive change. Can become too focused on others' spiritual healing while neglecting your own spiritual needs and growth.",
    advice: "Balance spiritual surrender with appropriate action when divine guidance calls for it. Practice self-compassion and attention to your own spiritual needs while serving others. Remember that true spiritual strength sometimes requires saying no or setting boundaries with love."
  },
  9: {
    general: "Your higher self embodies divine wisdom, spiritual illumination, and the sacred knowledge that comes from deep communion with higher consciousness. Your soul purpose involves serving as a spiritual teacher, guide, or hermit who shares profound insights gained through contemplation and inner work. You are here to demonstrate the value of solitude for spiritual development and to share wisdom that helps others understand life's deeper spiritual meanings. Your highest expression involves transmitting divine wisdom through your presence and teaching.",
    positive: "Natural connection to divine wisdom and higher consciousness that provides profound insights for spiritual understanding and guidance. Your higher self operates through the understanding that comes from direct spiritual experience and contemplation. You excel at helping others access their own inner wisdom and understand their spiritual journey more deeply.",
    challenge: "May become spiritually isolated, preferring solitary contemplation to engaged service and relationship. Tendency to intellectualize spiritual experience rather than living it fully in relationship with others. Can become spiritually superior, judging others' less contemplative approaches to spiritual growth.",
    advice: "Balance your contemplative spiritual gifts with regular engagement in service and relationship that allows wisdom to be shared and applied. Practice expressing spiritual insights in ways that others can understand and use practically. Remember that wisdom serves love and should be shared with compassion rather than superiority."
  },
  10: {
    general: "Your higher self embodies divine timing, karmic understanding, and the sacred awareness of how spiritual law governs the cycles of growth and experience. Your soul purpose involves demonstrating how to work with divine timing and natural spiritual rhythms rather than forcing outcomes. You are here to help others understand the larger patterns of their spiritual journey and trust in divine providence. Your highest expression involves being a living example of faith in divine order and timing.",
    positive: "Deep connection to divine timing and karmic patterns that provides understanding of spiritual cause and effect and trust in divine providence. Your higher self operates through recognition that everything happens for spiritual reasons and according to divine timing. You excel at helping others understand their experiences within the larger context of spiritual growth and evolution.",
    challenge: "May become spiritually fatalistic, using belief in karma or divine timing to avoid taking necessary spiritual action. Tendency to become passive about spiritual growth, waiting for divine intervention rather than participating actively. Can use spiritual concepts about timing to justify procrastination or avoidance of responsibility.",
    advice: "Balance understanding of divine timing with appropriate action when spiritual guidance calls for it. Practice working with spiritual law while also taking responsibility for your choices and growth. Remember that divine timing often includes inspired action rather than just passive waiting."
  },
  11: {
    general: "Your higher self embodies divine justice, spiritual discernment, and the sacred ability to perceive truth and maintain cosmic balance. Your soul purpose involves serving as a channel for divine justice and helping others understand spiritual cause and effect. You are here to demonstrate how spiritual law operates and help others align their choices with higher spiritual principles. Your highest expression involves being an instrument of divine justice and spiritual clarity.",
    positive: "Strong connection to divine justice and spiritual law that provides clear discernment between truth and illusion, right and wrong. Your higher self operates through understanding of cosmic balance and the spiritual principles that govern evolution. You excel at helping others make spiritually aligned choices and understand the consequences of their actions.",
    challenge: "May become spiritually judgmental, confusing personal moral preferences with divine law. Tendency to focus on spiritual correctness rather than love and compassion in dealing with others' mistakes. Can become rigid about spiritual rules while losing sight of their purpose in serving love and growth.",
    advice: "Balance spiritual discernment with compassion and understanding for human imperfection and the learning process. Practice expressing divine justice through love rather than judgment or punishment. Remember that spiritual law serves evolution and love, not rigid control or superiority."
  },
  12: {
    general: "Your higher self embodies divine sacrifice, spiritual surrender, and the sacred wisdom that comes from releasing personal will to serve higher purpose. Your soul purpose involves demonstrating how spiritual growth often requires releasing old patterns and perspectives to receive new understanding. You are here to show others how sacrifice and surrender can be gifts rather than losses. Your highest expression involves being a willing vessel for divine transformation and unconventional spiritual wisdom.",
    positive: "Natural connection to divine wisdom that comes through surrender and the willingness to release personal attachments for spiritual truth. Your higher self operates through trust in divine guidance even when it requires sacrifice or unconventional approaches. You excel at helping others find spiritual meaning in difficult experiences and discover wisdom through surrender.",
    challenge: "May become spiritually self-destructive, confusing unnecessary suffering with spiritual sacrifice. Tendency to sacrifice appropriate self-care and boundaries in the name of spiritual service. Can become attached to being a spiritual martyr rather than serving genuine divine purpose.",
    advice: "Distinguish between authentic spiritual sacrifice that serves divine purpose and unnecessary suffering that doesn't. Practice healthy spiritual surrender that includes appropriate self-care and boundaries. Remember that divine sacrifice serves love and growth, not self-destruction or ego gratification."
  },
  13: {
    general: "Your higher self embodies divine transformation, spiritual death and rebirth, and the sacred power of profound change that serves soul evolution. Your soul purpose involves facilitating deep spiritual transformation and helping others navigate the death of old spiritual identities to birth new consciousness. You are here to demonstrate how spiritual death leads to resurrection and how endings serve divine purpose. Your highest expression involves being a catalyst for authentic spiritual transformation.",
    positive: "Deep connection to the transformative power of divine love that allows you to navigate spiritual death and rebirth with trust and grace. Your higher self operates through understanding that spiritual evolution requires the release of outdated forms and identities. You excel at helping others find courage for necessary spiritual transformation and meaning in times of spiritual crisis.",
    challenge: "May become addicted to spiritual drama or transformation, creating unnecessary crisis instead of allowing natural spiritual evolution. Tendency to focus on destruction rather than the new life that spiritual death serves. Can become identified with being an agent of spiritual change rather than serving authentic divine purpose.",
    advice: "Balance your gift for facilitating spiritual transformation with wisdom about when change serves authentic growth versus ego drama. Practice being present with others in transformation without trying to force or control the process. Remember that spiritual death serves rebirth and new life, not destruction for its own sake."
  },
  14: {
    general: "Your higher self embodies divine healing, spiritual integration, and the sacred ability to blend different spiritual energies into harmonious wholeness. Your soul purpose involves serving as a channel for divine healing and helping others find balance and integration in their spiritual development. You are here to demonstrate how moderation and patience create sustainable spiritual growth. Your highest expression involves being a source of spiritual healing and balanced wisdom.",
    positive: "Natural connection to divine healing energy that allows you to facilitate spiritual integration and balanced growth for yourself and others. Your higher self operates through understanding of spiritual alchemy and the art of blending opposing forces into harmony. You excel at helping others find sustainable approaches to spiritual development and healing from spiritual wounds.",
    challenge: "May avoid necessary spiritual intensity or depth in favor of maintaining comfortable spiritual balance. Tendency to suppress difficult spiritual emotions or experiences rather than working through them for integration. Can become spiritually neutral, avoiding the passion and commitment that deeper spiritual growth requires.",
    advice: "Balance your gift for spiritual healing with willingness to experience and work with the full spectrum of spiritual experience. Practice maintaining your center while also embracing appropriate spiritual intensity when it serves growth. Remember that true spiritual integration includes working with difficult experiences, not just avoiding them."
  },
  15: {
    general: "Your higher self embodies divine power, spiritual mastery over material illusion, and the sacred ability to work with shadow energies for transformation. Your soul purpose involves demonstrating how to use spiritual power responsibly and helping others understand the spiritual lessons within material attachments and desires. You are here to show how shadow work and power integration serve spiritual evolution. Your highest expression involves conscious use of spiritual power for healing and liberation.",
    positive: "Strong connection to divine power that allows you to work consciously with intense energies and help others understand their shadow aspects. Your higher self operates through understanding that spiritual mastery includes working with rather than denying difficult energies. You excel at helping others find spiritual freedom through conscious relationship with power and desire.",
    challenge: "May misuse spiritual power for personal gain or control over others rather than service to divine love. Tendency to become fascinated with spiritual power itself rather than its purpose in serving transformation. Can become spiritually manipulative, using spiritual concepts to justify controlling behavior.",
    advice: "Use your spiritual power always in service of love and others' authentic spiritual growth rather than personal gain or control. Practice humility and accountability in how you work with spiritual energy and influence. Remember that true spiritual power serves liberation and love, not domination or ego gratification."
  },
  16: {
    general: "Your higher self embodies divine revelation, spiritual awakening, and the sacred lightning of truth that shatters illusions and false spiritual structures. Your soul purpose involves serving as a catalyst for spiritual awakening and helping others break free from limiting spiritual beliefs and practices. You are here to demonstrate how spiritual crisis can lead to liberation and authentic connection with divine truth. Your highest expression involves being a clear channel for divine revelation and spiritual breakthrough.",
    positive: "Natural connection to divine revelation that provides sudden insights and spiritual breakthroughs that liberate you and others from limiting patterns. Your higher self operates through direct spiritual knowing that bypasses mental concepts and false spiritual structures. You excel at helping others experience authentic spiritual awakening and freedom from spiritual conditioning.",
    challenge: "May become addicted to spiritual drama or crisis, creating unnecessary disruption rather than allowing natural spiritual evolution. Tendency to destroy spiritual structures without helping build healthy replacements. Can become spiritually destructive, using revelation to hurt rather than heal others' spiritual journey.",
    advice: "Channel your gift for spiritual revelation toward genuine liberation and healing rather than destruction for its own sake. Practice communicating spiritual insights in ways that help others grow rather than shocking or overwhelming them. Remember that divine revelation serves love and spiritual freedom, not ego satisfaction or dramatic effect."
  },
  17: {
    general: "Your higher self embodies divine hope, spiritual vision, and the sacred connection to cosmic consciousness that provides guidance and inspiration. Your soul purpose involves serving as a beacon of spiritual hope and helping others maintain faith in divine love and spiritual evolution. You are here to demonstrate how spiritual vision can guide practical action and how divine guidance is always available. Your highest expression involves being a living star that guides others toward their spiritual destiny.",
    positive: "Deep connection to divine guidance and cosmic consciousness that provides unwavering spiritual hope and vision for positive possibilities. Your higher self operates through trust in divine love and the ultimate goodness of spiritual evolution. You excel at helping others maintain faith during difficult times and connect with their own spiritual guidance and purpose.",
    challenge: "May become spiritually idealistic, focusing on perfect spiritual visions rather than working with current spiritual realities. Tendency to avoid difficult spiritual work in favor of maintaining positive spiritual feelings. Can become disconnected from practical spiritual application while focused on cosmic consciousness.",
    advice: "Ground your spiritual vision in practical service and concrete actions that bring divine love into manifest reality. Practice maintaining hope while also engaging with current spiritual challenges and difficulties. Remember that divine guidance serves love in action, not just beautiful spiritual experiences."
  },
  18: {
    general: "Your higher self embodies divine mystery, spiritual intuition, and the sacred connection to the collective unconscious and spiritual realms beyond ordinary consciousness. Your soul purpose involves serving as a bridge between conscious and unconscious spiritual realities and helping others navigate the mysteries of spiritual development. You are here to demonstrate how intuition and spiritual sensitivity serve divine purpose. Your highest expression involves being a clear channel for divine mystery and unconscious wisdom.",
    positive: "Natural connection to divine mystery and spiritual realms that provides access to profound spiritual insights and healing energies. Your higher self operates through trust in intuitive guidance and sensitivity to subtle spiritual energies. You excel at helping others access their own spiritual intuition and understand the mysterious aspects of their spiritual journey.",
    challenge: "May become lost in spiritual fantasy or confusion, losing discernment between genuine spiritual guidance and psychological projection. Tendency to avoid clear spiritual thinking and practical application in favor of mystical experience. Can become spiritually confused, unable to distinguish between divine guidance and personal emotional needs.",
    advice: "Balance your spiritual sensitivity with practical discernment and clear thinking about spiritual experience. Practice grounding mystical insights in practical service and concrete spiritual application. Remember that divine mystery serves clarity and love, not confusion or avoidance of spiritual responsibility."
  },
  19: {
    general: "Your higher self embodies divine joy, spiritual radiance, and the sacred celebration of life that comes from authentic connection with divine love. Your soul purpose involves demonstrating how spiritual connection enhances rather than diminishes life's pleasures and how joy serves spiritual evolution. You are here to show others that spirituality includes celebration and that divine love expresses itself through happiness. Your highest expression involves being a radiant example of spiritual joy and divine celebration.",
    positive: "Natural connection to divine joy that creates authentic spiritual radiance and helps others experience the celebratory aspect of spiritual connection. Your higher self operates through understanding that divine love includes pleasure, success, and happiness. You excel at helping others integrate spiritual development with joy and life celebration.",
    challenge: "May avoid necessary spiritual challenges or difficult growth experiences in favor of maintaining positive spiritual feelings. Tendency to suppress or deny shadow aspects of spiritual development while focusing only on light and joy. Can become spiritually superficial, avoiding depth in favor of pleasant spiritual experiences.",
    advice: "Balance your spiritual joy with willingness to engage with the full spectrum of spiritual experience including challenges and difficulties. Practice finding divine love and celebration even within difficult spiritual work and growth. Remember that authentic spiritual joy comes from wholeness, not from avoiding difficulties."
  },
  20: {
    general: "Your higher self embodies divine awakening, spiritual resurrection, and the sacred calling to serve the collective spiritual evolution of humanity. Your soul purpose involves answering the divine call to spiritual service and helping others recognize their own spiritual calling and purpose. You are here to demonstrate how individual spiritual awakening serves collective transformation. Your highest expression involves being a clear instrument of divine will for humanity's spiritual evolution.",
    positive: "Profound connection to divine calling and collective spiritual purpose that provides clear direction for your spiritual service and evolution. Your higher self operates through understanding that individual awakening serves universal love and consciousness. You excel at helping others recognize and answer their own divine calling and spiritual purpose.",
    challenge: "May become overwhelmed by the magnitude of collective spiritual need, losing balance between service and personal spiritual care. Tendency to sacrifice individual spiritual needs entirely for collective service. Can become spiritually grandiose, confusing personal ego with divine calling or universal consciousness.",
    advice: "Balance your spiritual service to humanity with appropriate attention to your own spiritual needs and development. Practice discerning between authentic divine calling and ego desires for spiritual importance or recognition. Remember that serving collective spiritual evolution includes modeling healthy spiritual self-care and boundaries."
  },
  21: {
    general: "Your higher self embodies divine completion, spiritual mastery, and the sacred achievement of wholeness that serves as an example for others' spiritual development. Your soul purpose involves demonstrating what's possible through dedicated spiritual practice and serving as a model of integrated spiritual living. You are here to show how spiritual development leads to practical wisdom and authentic spiritual authority. Your highest expression involves being a living example of spiritual completion in service to others' growth.",
    positive: "Natural spiritual wholeness and integration that provides stable foundation for serving others' spiritual development and demonstrating authentic spiritual mastery. Your higher self operates through practical wisdom and the authority that comes from genuine spiritual achievement. You excel at helping others understand what authentic spiritual development looks like in practice.",
    challenge: "May become spiritually complacent, believing you have achieved all necessary spiritual growth rather than continuing to evolve. Tendency to judge others' spiritual development from a position of assumed superiority. Can become spiritually stagnant, resting on past spiritual achievements rather than continuing to serve and grow.",
    advice: "Honor your spiritual achievements while remaining open to continued growth and evolution in your spiritual understanding and service. Use your spiritual wholeness to support others' development rather than setting yourself apart. Remember that true spiritual mastery includes humility and continued dedication to learning and service."
  },
  22: {
    general: "Your higher self embodies divine innocence, unlimited spiritual potential, and the sacred beginner's mind that remains open to continuous spiritual discovery and evolution. Your soul purpose involves demonstrating how spiritual freshness and openness serve divine purpose and helping others maintain wonder and curiosity in their spiritual journey. You are here to show that spiritual development is an endless adventure of discovery. Your highest expression involves being a pure channel for divine spontaneity and unlimited spiritual possibility.",
    positive: "Natural spiritual openness and unlimited potential that allows you to approach spiritual development with fresh perspective and innocent wonder. Your higher self operates through trust in divine guidance and willingness to discover new aspects of spiritual truth. You excel at helping others maintain beginner's mind and openness to spiritual surprise and discovery.",
    challenge: "May lack spiritual discernment or experience needed to navigate complex spiritual situations effectively. Tendency toward spiritual naivety that trusts without appropriate wisdom or boundaries. Can become spiritually scattered, exploring many paths without developing depth or practical wisdom.",
    advice: "Balance your spiritual openness with practical wisdom gained through experience and guidance from mature spiritual teachers. Practice maintaining innocent wonder while also developing discernment and depth in your spiritual understanding. Remember that divine innocence serves wisdom and love, not carelessness or avoidance of spiritual responsibility."
  }
};