/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Ingredients for Love Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * what you need to give and receive in romantic relationships and partnerships.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Ingredients for Love - What you need to give and receive in relationships
 */
export const ingredientsForLoveInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Love requires independence, passion, and the ability to create and manifest dreams together with your partner while maintaining your individual identity. You need relationships that allow for leadership, initiative, and the freedom to pursue your personal goals and ambitions. Your love thrives when there's mutual respect for each other's autonomy and a shared commitment to building something meaningful together through combined willpower and determination.",
    positive: "You bring strong manifestation power, creative energy, and natural leadership abilities to relationships, inspiring your partner to pursue their own goals and dreams. Your passionate nature and ability to take initiative creates excitement and forward momentum in love, keeping relationships dynamic and growth-oriented. You have the gift of helping your partner believe in themselves and their potential while maintaining your own strong sense of self and purpose.",
    challenge: "May struggle with dominating relationships or having difficulty accepting influence from your partner, preferring to lead rather than collaborate as equals. Tendency toward impatience with your partner's different pace or methods, potentially creating pressure or conflict when they need more time to process or decide. Can struggle with vulnerability and emotional interdependence, finding it easier to give advice or solutions than to share your own fears and insecurities.",
    advice: "Balance your natural leadership qualities with genuine receptivity to your partner's ideas, needs, and leadership in areas where they excel. Practice vulnerability by sharing your uncertainties and fears, allowing your partner to support and guide you sometimes rather than always being the strong one. Create space in your relationship for both individual pursuits and collaborative projects, honoring both independence and togetherness as essential ingredients for lasting love."
  },
  2: {
    general: "Love needs intuition, mystery, emotional depth, and the ability to connect on psychic and spiritual levels that go beyond surface conversation or physical attraction. You require relationships that honor the mysterious, unspoken aspects of connection and allow for quiet, reflective intimacy alongside more active expressions of love. Your partnerships thrive when there's mutual respect for inner wisdom, emotional sensitivity, and the need for periodic withdrawal and reflection.",
    positive: "You bring profound psychic understanding, emotional attunement, and intuitive wisdom to relationships, often sensing your partner's needs before they're expressed. Your ability to create sacred, mysterious space in love allows for deep spiritual and emotional bonding that transcends ordinary relationship dynamics. You offer your partner the gift of being truly seen and understood on levels that most people never experience in their relationships.",
    challenge: "May be too passive in expressing your own needs and desires, expecting your partner to intuitively understand what you want without direct communication. Difficulty with confrontation or direct discussion of relationship problems, preferring to withdraw or hope issues resolve themselves naturally. Can become overly sensitive to your partner's moods and energy, losing your own emotional center and taking on their emotional states as your own.",
    advice: "Trust your intuitive understanding of your partner while also developing skills for clear, direct communication about your own needs and feelings. Practice expressing your desires and concerns openly rather than expecting your partner to guess or intuit what you need. Create healthy boundaries that allow you to be emotionally supportive without losing yourself in your partner's emotional world, maintaining your own inner sanctuary while sharing deep intimacy."
  },
  3: {
    general: "Love thrives on creativity, abundance, nurturing expression, and the ability to grow and create beauty together in both tangible and intangible ways. You need relationships that feel fertile and generative, where both partners can express their creative nature and nurture each other's growth and development. Your partnerships flourish when there's an abundance of affection, sensual pleasure, and mutual support for each other's creative expression and personal expansion.",
    positive: "You bring natural fertility, creativity, and generous love to relationships, creating an atmosphere of abundance and growth where your partner feels nurtured and supported. Your ability to see and cultivate your partner's potential helps them blossom into their fullest expression while you also pursue your own creative and personal development. You excel at creating beautiful, sensual experiences that deepen intimacy and bring joy and pleasure to your shared life together.",
    challenge: "May tend to mother or smother your partner, giving so much care and attention that they feel overwhelmed or unable to reciprocate in their own way. Difficulty receiving care and nurturing from your partner, feeling more comfortable in the giving role even when you need support and comfort. Can struggle with jealousy or possessiveness when your generous love isn't fully appreciated or when your partner seeks independence or outside friendships.",
    advice: "Balance your natural giving with gracious receiving, allowing your partner to nurture and care for you in their own unique way rather than only feeling valuable when you're providing. Create space for your partner's independence and growth while offering your support, trusting that healthy relationships involve both togetherness and individual development. Practice expressing your own needs for nurturing and support rather than always being the one who provides care for others."
  },
  4: {
    general: "Love requires structure, commitment, reliability, and the security of knowing that your partnership provides a stable foundation for building a life together. You need relationships that feel solid and dependable, where both partners can count on each other through life's challenges and changes. Your love thrives when there are clear agreements, shared values about commitment, and mutual dedication to creating lasting security and stability together.",
    positive: "You bring stability, protection, and dependable love to relationships, creating a secure foundation where your partner feels safe to be vulnerable and take risks in other areas of life. Your commitment to building lasting partnerships helps create the kind of deep security that allows both people to grow and evolve within the relationship. You excel at creating practical systems and structures that support your shared life and help manifest your mutual goals and dreams.",
    challenge: "May be too controlling or rigid in your approach to love, wanting to direct how the relationship develops rather than allowing for organic growth and change. Difficulty with spontaneity or adapting when your partner's needs or circumstances change, preferring predictable patterns even when flexibility would benefit the relationship. Can become overly focused on external security and structure while neglecting the emotional and spiritual aspects of love that also need attention.",
    advice: "Provide security and stability while allowing space for growth, change, and spontaneous expressions of love that keep your relationship dynamic and alive. Build strong foundations through clear communication and agreements while remaining flexible enough to adapt as both you and your partner evolve. Balance your focus on practical matters with attention to emotional intimacy and spiritual connection, recognizing that true security includes feeling emotionally safe and spiritually connected."
  },
  5: {
    general: "Love needs traditional values, spiritual connection, and guidance from higher wisdom that helps both partners grow in character and moral development. You require relationships that honor established principles of commitment, respect, and ethical behavior while supporting each other's spiritual and personal growth. Your partnerships thrive when there's shared commitment to learning, growth, and living according to meaningful values and principles that guide your decisions and behavior together.",
    positive: "You bring wisdom, moral foundation, and spiritual depth to relationships, helping create partnerships that are grounded in meaningful values and principles. Your respect for tradition and commitment provides stability while your dedication to growth and learning keeps the relationship evolving in positive directions. You offer your partner guidance and support for their spiritual and character development while also being open to learning and growing yourself.",
    challenge: "May be too conventional or judgmental about how love should be expressed, limiting your ability to appreciate your partner's unique way of showing love. Tendency to lecture or try to teach your partner rather than accepting them as they are and allowing them to find their own path of growth. Can become rigid about relationship rules and expectations, missing opportunities for deeper connection that might require flexibility or unconventional approaches.",
    advice: "Honor your values and spiritual beliefs while respecting your partner's individual journey and unique way of expressing love and commitment. Share your wisdom and guidance when invited while also remaining open to learning from your partner's different perspectives and experiences. Balance your commitment to traditional relationship values with flexibility and acceptance of your partner's individual needs and expression."
  },
  6: {
    general: "Love is fundamentally about harmony, choice, and creating a perfect partnership where both people feel valued, beautiful, and mutually supportive in all aspects of life. You need relationships that feel balanced and aesthetically pleasing, where conflicts are resolved through discussion and compromise rather than power struggles. Your love thrives when there's mutual appreciation for beauty, shared decision-making, and a sense that you're creating something beautiful and harmonious together.",
    positive: "You have a natural ability to create beautiful, balanced relationships where both partners feel valued and appreciated for their unique contributions. Your diplomatic skills and desire for harmony help resolve conflicts peacefully and create an atmosphere of mutual respect and cooperation. You bring an aesthetic sense and appreciation for beauty that enhances the quality of your shared life and creates memorable, meaningful experiences together.",
    challenge: "May struggle with conflict or difficult conversations, preferring to maintain surface harmony rather than addressing underlying issues that need attention. Tendency toward people-pleasing that prevents you from expressing your authentic needs and feelings when they might create temporary discord. Can become overly focused on how the relationship appears to others rather than how it actually feels to both partners in private moments.",
    advice: "Embrace necessary conflicts as opportunities for deeper connection and understanding rather than threats to your relationship's harmony. Practice expressing your authentic needs and feelings even when they might create temporary tension, trusting that real harmony comes from honest communication. Focus on creating genuine intimacy and connection rather than just maintaining appearances or avoiding all disagreements and challenges."
  },
  7: {
    general: "Love requires determination, movement, and the ability to overcome obstacles together while maintaining forward momentum toward shared goals and dreams. You need relationships that feel dynamic and purposeful, where both partners support each other's ambitions and work together to navigate life's challenges. Your love thrives when there's a sense of shared mission, mutual support for individual goals, and the excitement of building something meaningful together through combined effort.",
    positive: "You bring drive, determination, and unwavering support to relationships, helping your partner overcome obstacles and achieve their goals while pursuing your own ambitions. Your dynamic energy keeps relationships moving forward and prevents stagnation, ensuring that both partners continue growing and evolving together. You excel at being a champion for your partner's dreams and providing the motivation and encouragement they need to persist through challenges.",
    challenge: "May be impatient with your partner's different pace or methods, wanting to push forward when they need more time to process or feel ready. Difficulty with emotional subtlety and slower relationship processes like building trust, processing feelings, or developing deep intimacy over time. Can become focused on achieving relationship goals or milestones rather than appreciating the journey and present moments of connection and intimacy.",
    advice: "Slow down and appreciate the journey of building love rather than just focusing on achieving relationship milestones or overcoming the next challenge. Balance your drive for progress with patience for your partner's different pace and processing style, recognizing that sustainable love develops over time. Practice being present for quiet, intimate moments that don't involve action or achievement but are essential for deep emotional connection."
  },
  8: {
    general: "Love needs patience, inner strength, and the gentle power that comes from emotional resilience and the ability to transform challenges into opportunities for deeper connection. You require relationships that honor both strength and vulnerability, where partners can be authentic about their struggles while supporting each other with compassion. Your love thrives when there's mutual respect for the healing journey and space for both partners to grow through difficulties with grace and patience.",
    positive: "You bring a healing presence, emotional resilience, and quiet strength to relationships that helps your partner feel safe and supported during difficult times. Your ability to remain centered during relationship challenges provides stability and helps transform conflicts into opportunities for greater understanding and intimacy. You offer unconditional love and patient support that allows your partner to heal past wounds and develop greater self-acceptance and confidence.",
    challenge: "May endure relationship problems too long without addressing them directly, hoping that patience and love alone will resolve issues that need active communication. Tendency to suppress your own needs or anger to maintain peace, potentially building resentment or losing touch with your authentic feelings. Can become overly focused on healing or fixing your partner rather than maintaining appropriate boundaries and caring for your own emotional well-being.",
    advice: "Use your natural strength and patience to address relationship issues lovingly but directly rather than avoiding difficult conversations or enabling unhealthy patterns. Express your own needs and feelings clearly while maintaining your supportive nature, recognizing that authentic love includes honest communication about problems. Balance your desire to help and heal your partner with respect for their autonomy and responsibility for their own growth and healing process."
  },
  9: {
    general: "Love requires wisdom, solitude, and deep spiritual connection that honors both partners' need for individual reflection and shared meaning-making about life's deeper questions. You need relationships that provide space for contemplation, philosophical discussion, and mutual support for each other's spiritual journey and personal growth. Your love thrives when there's intellectual compatibility, shared appreciation for wisdom traditions, and respect for each other's need for periodic solitude and inner work.",
    positive: "You bring profound wisdom, spiritual depth, and thoughtful guidance to relationships, helping your partner develop greater self-understanding and life perspective. Your ability to see beyond surface issues to deeper patterns and meanings helps resolve conflicts and creates lasting solutions to relationship challenges. You offer the gift of deep listening, meaningful conversation, and patient support for your partner's personal growth and spiritual development.",
    challenge: "May isolate or become too introspective during relationship difficulties, withdrawing from your partner when they need connection and communication to resolve issues. Difficulty with emotional intimacy and vulnerability, preferring to discuss ideas and concepts rather than sharing feelings and personal struggles. Can become judgmental or superior about your insights and wisdom, lecturing your partner rather than creating space for mutual learning and growth.",
    advice: "Share your inner world and wisdom while staying emotionally connected and available to your partner, balancing solitude with intimate communication. Practice vulnerability by expressing your feelings and uncertainties rather than only offering guidance and insights to your partner. Create space for mutual learning and discovery in your relationship, recognizing that your partner may have different but equally valuable perspectives and wisdom to offer."
  },
  10: {
    general: "Love involves understanding cycles, destiny, and the recognition that relationships have natural rhythms of closeness and distance, challenge and ease, growth and stability. You need partnerships that can weather changes and transitions while maintaining connection to the larger purpose and meaning of your relationship. Your love thrives when both partners understand that relationships evolve through different phases and that timing plays an important role in when certain developments or decisions occur.",
    positive: "You bring understanding of relationship cycles and natural timing, helping both partners navigate transitions and changes with patience and perspective. Your recognition of karmic connections and destiny helps create a sense of meaning and purpose that sustains the relationship through difficult periods. You excel at recognizing when to take action and when to wait, helping your partnership evolve according to its natural rhythm and timing.",
    challenge: "May become too passive about relationship problems, believing everything is fated rather than taking responsibility for creating positive change through conscious effort. Tendency to rely too much on destiny or external circumstances rather than actively working to improve communication, intimacy, or resolve conflicts. Can use belief in cycles or fate to avoid making difficult decisions or commitments that require courage and conscious choice.",
    advice: "Work with destiny and natural timing while also taking active responsibility for creating the love you want through conscious communication and effort. Recognize that while relationships have natural cycles, you also have the power to influence the direction and quality of your partnership through your choices. Balance acceptance of what you cannot control with proactive effort to improve what you can influence in your relationship."
  },
  11: {
    general: "Love needs fairness, balance, and ethical treatment where both partners feel respected, valued, and treated with justice and consideration in all aspects of the relationship. You require partnerships where decisions are made collaboratively, responsibilities are shared equitably, and both people's needs and perspectives are given equal weight. Your love thrives when there's mutual respect for each other's rights, clear agreements about expectations, and consistent follow-through on commitments and promises.",
    positive: "You bring a strong sense of justice, fairness, and ethical behavior to relationships, creating partnerships where both people feel respected and valued. Your ability to see multiple perspectives helps resolve conflicts fairly and create agreements that serve both partners' needs and interests. You excel at creating balanced relationships where power, responsibility, and decision-making are shared appropriately between equals.",
    challenge: "May be too judgmental or rigid about right and wrong in relationships, missing opportunities for compassion and forgiveness when your partner makes mistakes. Tendency to keep score or focus on fairness to the point where spontaneous generosity and grace become difficult. Can become paralyzed by over-analyzing relationship decisions, wanting to ensure perfect fairness rather than trusting your heart and intuition about what feels right.",
    advice: "Balance your sense of justice with compassion and forgiveness, recognizing that love sometimes requires grace rather than strict fairness or accountability. Make decisions about relationship issues more quickly by establishing clear values and principles that can guide you without endless analysis. Focus on creating overall balance and mutual respect rather than keeping track of every give-and-take in your partnership."
  },
  12: {
    general: "Love requires sacrifice, new perspectives, and the patience to see relationships from completely different angles that reveal hidden gifts and possibilities within challenges. You need partnerships that honor the transformative power of love and the willingness to let go of ego needs for the sake of deeper connection. Your love thrives when both partners are willing to sacrifice lesser desires for greater intimacy and are open to seeing each other and the relationship from fresh, unconventional perspectives.",
    positive: "You bring willingness to sacrifice for love, ability to see relationships from your partner's perspective, and patience for love's transformative process to unfold naturally. Your openness to unconventional approaches and different viewpoints helps resolve conflicts and creates innovative solutions to relationship challenges. You offer the gift of selfless love and the wisdom that comes from seeing beyond surface appearances to deeper truths about love and relationships.",
    challenge: "May sacrifice too much of your own identity, needs, or well-being for the relationship, losing yourself rather than creating healthy interdependence. Difficulty maintaining clear boundaries and self-care while being generous and selfless in love, potentially creating imbalance or resentment. Can become martyr-like in relationships, focusing on what you're giving up rather than what you're gaining through conscious choice and mutual growth.",
    advice: "Practice healthy sacrifice that enhances love rather than depletes your well-being, ensuring that your giving comes from abundance rather than self-neglect. Maintain your individual identity and self-care while being generous in love, recognizing that taking care of yourself allows you to love more fully. Share the responsibility for sacrifice and perspective-shifting with your partner rather than carrying the entire burden of flexibility and accommodation yourself."
  },
  13: {
    general: "Love involves transformation, letting go, and the rebirth that comes from allowing relationships to evolve and change rather than trying to keep them static or comfortable. You need partnerships that can handle deep changes, transitions, and the natural endings that make space for new beginnings and growth. Your love thrives when both partners understand that true intimacy requires the courage to let old patterns die and be reborn into deeper, more authentic connection.",
    positive: "You bring the ability to transform through love, comfort with relationship changes and transitions, and willingness to let go of what no longer serves the partnership. Your understanding of love's transformative power helps create relationships that continuously deepen and evolve rather than becoming stagnant or superficial. You offer your partner the gift of experiencing love as a catalyst for personal growth and spiritual development.",
    challenge: "May fear commitment or long-term stability due to your awareness that all relationships change and that nothing remains the same forever. Tendency to create unnecessary drama or crisis in relationships when things become too comfortable or predictable. Can become too focused on transformation and change, missing opportunities to enjoy stability and consistent connection when they're available and beneficial.",
    advice: "Embrace love's transformative power while also building stable foundations that can support you and your partner through periods of change and growth. Allow for natural evolution in your relationship without forcing change or creating crisis when things are going well. Balance your comfort with transformation with appreciation for the stability and consistency that also nourish lasting love."
  },
  14: {
    general: "Love needs moderation, healing, and the balanced give-and-take that comes from both partners contributing their unique gifts while receiving what they need for growth and well-being. You require relationships that feel sustainable and nourishing rather than intense or dramatic, where both people can maintain their individual balance while creating harmony together. Your love thrives when there's mutual support for health, healing, and the integration of different aspects of life into a coherent, meaningful whole.",
    positive: "You bring natural ability to heal and balance relationship energies, creating partnerships that feel sustainable and nourishing for both people involved. Your moderate approach helps avoid extremes and creates steady progress toward deeper intimacy and understanding over time. You excel at helping your partner integrate different aspects of their life and personality while maintaining your own sense of balance and well-being.",
    challenge: "May avoid necessary emotional intensity or passion, seeking balance even when the relationship needs more fire, excitement, or deep feeling to grow. Tendency toward emotional neutrality that can feel safe but may limit the depth of intimacy and connection possible in your partnership. Can become too focused on maintaining equilibrium rather than allowing for the natural ups and downs that create growth and deeper bonding.",
    advice: "Balance your natural moderation with openness to intense emotions and passionate experiences that deepen intimacy even if they temporarily disrupt your equilibrium. Allow for natural fluctuations in relationship energy and emotional intensity rather than always seeking to maintain steady, moderate feelings. Recognize that sometimes love requires passionate engagement and emotional risk-taking rather than just careful balance and measured responses."
  },
  15: {
    general: "Love may involve intense passion, material desires, and power dynamics that need to be navigated consciously to avoid becoming trapped in unhealthy patterns of obsession or control. You need relationships that acknowledge the shadow aspects of love including jealousy, possessiveness, and sexual intensity while working to transform these energies constructively. Your love thrives when both partners can embrace their full humanity including desires and darker impulses while choosing to express them in ways that enhance rather than diminish the relationship.",
    positive: "You bring intense passion, material abundance, and powerful sexual energy to relationships, creating experiences of deep physical and emotional satisfaction. Your understanding of love's shadow aspects helps you and your partner navigate difficult emotions and desires with honesty and consciousness. You offer the gift of full acceptance of human nature and the willingness to work with rather than deny the more challenging aspects of intimate relationship.",
    challenge: "May become possessive, manipulative, or obsessed with your partner, focusing on control rather than love and mutual growth. Tendency to use material gifts, sexual attraction, or emotional intensity to maintain connection rather than developing deeper spiritual and emotional intimacy. Can become trapped by your own desires or your partner's needs, losing freedom and authentic self-expression in the relationship.",
    advice: "Enjoy the passion and material pleasures of love without becoming enslaved by desires or losing your individual freedom and authentic self-expression. Use your understanding of power dynamics to create conscious, consensual exchanges rather than manipulation or control. Channel your intense sexual and emotional energy toward deeper intimacy and spiritual connection rather than just physical satisfaction or material accumulation."
  },
  16: {
    general: "Love brings sudden revelations, breaking of old patterns, and liberation from limiting beliefs or behaviors that have prevented authentic intimacy and connection. You need relationships that can handle dramatic insights, unexpected changes, and the dismantling of structures or expectations that no longer serve your growth. Your love thrives when both partners are willing to have their illusions shattered and their assumptions challenged in service of greater truth and authentic connection.",
    positive: "You bring the ability to break free from unhealthy relationship patterns, sudden insights that resolve long-standing issues, and liberation from limiting beliefs about love. Your willingness to face difficult truths helps create relationships based on authenticity rather than fantasy or illusion. You offer your partner the gift of breakthrough moments that free both of you from patterns that have been preventing deeper intimacy and genuine connection.",
    challenge: "Tendency toward dramatic breakups, sudden relationship changes, or shocking revelations that destabilize your partnership without adequate communication or preparation. May create unnecessary drama or crisis in relationships when gradual change or patient communication would be more effective. Can use revelations or insights as weapons to hurt your partner rather than tools for mutual growth and understanding.",
    advice: "Use relationship revelations and insights to build better intimacy and understanding rather than just to escape or create drama when things become challenging. Communicate your realizations and need for change clearly and compassionately rather than creating shock or crisis to force transformation. Build upon the insights and liberation you experience rather than just breaking free from old patterns without creating new, healthier ones."
  },
  17: {
    general: "Love is hopeful, inspiring, and connected to higher purpose and spiritual vision that elevates both partners and helps them become their best selves. You need relationships that feel meaningful and aligned with your spiritual values and life purpose, where love serves not just personal happiness but also contribution to something greater. Your love thrives when there's shared vision for how your partnership can serve healing, growth, and positive change in the world while also nurturing your individual and mutual development.",
    positive: "You bring hope, inspiration, and spiritual vision to relationships, helping your partner connect with their highest potential and life purpose. Your faith in love's healing and transformative power creates an atmosphere of possibility and positive expectation that supports growth and manifestation. You offer the gift of seeing your partner's divine nature and potential even when they struggle to see it themselves.",
    challenge: "May have unrealistic expectations about love or your partner, expecting spiritual perfection rather than accepting human limitations and the need for gradual growth. Tendency to focus on potential and future possibilities rather than appreciating your partner as they are in the present moment. Can become disappointed when everyday relationship challenges don't match your idealistic vision of what love should be like.",
    advice: "Keep your spiritual ideals and vision for love while also embracing the beautiful imperfection of human relationships and the gradual process of growth and development. Appreciate your partner as they are now rather than just focusing on who they might become or their spiritual potential. Ground your inspiration and hope in practical daily actions and communication that nurture your actual relationship rather than just your vision of ideal love."
  },
  18: {
    general: "Love involves mystery, intuition, and the navigation of hidden depths and unconscious patterns that influence how you connect with and relate to your partner. You need relationships that honor the mysterious aspects of attraction and connection while providing safety for exploring the deeper, less conscious aspects of intimacy. Your love thrives when both partners are willing to explore dreams, fantasies, and the psychic connection that exists beyond rational understanding while maintaining clear communication about practical matters.",
    positive: "You bring deep intuitive understanding of love's mysteries, psychic connection with your partner, and ability to navigate the unconscious and emotional depths of intimate relationship. Your sensitivity to subtle energies and hidden dynamics helps you understand what's really happening beneath surface interactions. You offer the gift of profound emotional and psychic intimacy that most people never experience in their relationships.",
    challenge: "May struggle with deception, unclear emotional boundaries, or confusion about what's real versus fantasy in your relationship dynamics. Tendency to get lost in emotions, projections, or unconscious patterns rather than maintaining clear communication about practical relationship needs. Can become overly dependent on psychic or emotional connection while neglecting the practical aspects of partnership that also need attention.",
    advice: "Trust your intuitive understanding of love's mysteries while also maintaining clear communication about practical needs, boundaries, and expectations in your relationship. Develop discernment between genuine psychic connection and projection, fantasy, or emotional confusion that can cloud your perception. Balance your appreciation for love's mysteries with attention to clear, honest communication about everyday relationship matters."
  },
  19: {
    general: "Love is joyful, radiant, and naturally successful when both partners can express their authentic enthusiasm and appreciation for life and each other. You need relationships that feel celebratory and positive, where both people support each other's happiness and success while sharing genuine enjoyment of life together. Your love thrives when there's mutual encouragement, shared laughter, and the ability to find joy and meaning in both ordinary moments and special celebrations.",
    positive: "You bring natural joy, warmth, and enthusiasm to relationships, creating an atmosphere of celebration and positive energy that makes your partner feel appreciated and happy. Your optimistic nature and ability to find the good in situations helps resolve conflicts and maintain connection during challenging periods. You offer the gift of genuine happiness and the ability to help your partner reconnect with their own joy and life satisfaction.",
    challenge: "May avoid dealing with relationship shadows, difficult emotions, or necessary growth work, preferring to stay positive rather than addressing underlying issues. Tendency to suppress or deny negative feelings in yourself or your partner, which can prevent authentic intimacy and resolution of important problems. Can become superficial in your approach to love, focusing on fun and happiness while avoiding the deeper work that creates lasting intimacy.",
    advice: "Maintain your joyful approach to love while also creating space for authentic expression of all emotions including sadness, anger, and fear that are part of complete intimacy. Address necessary relationship growth areas and challenges while maintaining your positive outlook and faith in your partnership's potential. Balance your focus on happiness and celebration with willingness to do the deeper emotional work that creates lasting joy and satisfaction."
  },
  20: {
    general: "Love is a spiritual calling involving rebirth, awakening, and the recognition that intimate partnership can serve as a catalyst for profound personal and spiritual transformation. You need relationships that feel destined and meaningful, where love serves not just personal happiness but also spiritual awakening and service to higher purpose. Your love thrives when both partners understand that their relationship has significance beyond personal satisfaction and can contribute to healing and awakening in themselves and the world.",
    positive: "You bring spiritual awakening, transformational purpose, and the ability to use love as a catalyst for profound personal and spiritual growth. Your understanding that love is a sacred calling helps create relationships that feel meaningful and aligned with higher purpose. You offer your partner the gift of seeing love as a spiritual path and opportunity for service rather than just personal satisfaction or security.",
    challenge: "May struggle with the practical aspects of love and daily relationship maintenance, focusing on spiritual significance while neglecting ordinary needs for communication and care. Tendency to expect your partner to share your spiritual understanding and calling rather than accepting their individual path and timing. Can become overwhelmed by the responsibility or significance you place on love, making it difficult to enjoy simple intimacy and companionship.",
    advice: "Answer love's spiritual calling while also attending to daily relationship needs for communication, practical care, and ordinary human connection and enjoyment. Honor your sense that love serves higher purpose while also accepting your partner's individual spiritual path and timing for awakening. Balance the significance you place on love with appreciation for simple moments of connection, laughter, and mutual care that also nourish lasting partnership."
  },
  21: {
    general: "Love represents completion, fulfillment, and the mastery of relationship skills that allows you to create deeply satisfying partnerships that integrate all aspects of human connection. You need relationships that feel whole and complete, where both partners have developed the emotional maturity and communication skills necessary for lasting intimacy. Your love thrives when there's mutual achievement of relationship goals, shared sense of accomplishment, and the satisfaction that comes from building something meaningful and enduring together.",
    positive: "You bring mastery of relationship skills, achievement of fulfilling partnerships, and the ability to create love that feels complete and deeply satisfying for both people involved. Your emotional maturity and communication abilities help create stable, lasting relationships that weather challenges and continue growing over time. You offer your partner the gift of experiencing love as a space of mutual accomplishment and shared success in creating meaningful life together.",
    challenge: "May become complacent about relationship growth or take your partnership for granted, assuming that achievement of stability means the work is complete. Need for new relationship challenges or goals to maintain engagement and continued development, which can create unnecessary restlessness in stable partnerships. Can become overly focused on maintaining achievement rather than continuing to explore new depths of intimacy and connection.",
    advice: "Celebrate your relationship success and mastery while continuing to set new meaningful goals and challenges that keep your partnership growing and evolving. Appreciate the stability and fulfillment you've achieved while also remaining curious about new possibilities for deeper connection and mutual growth. Use your relationship skills and experience to help other couples while also maintaining attention to your own partnership's continued development."
  },
  22: {
    general: "Love is an adventure with fresh starts, innocent approaches, and unlimited potential for creating completely new paradigms of partnership that aren't constrained by conventional expectations or limitations. You need relationships that feel open to possibility and allow for spontaneous exploration of what love can become when approached with beginner's mind. Your love thrives when both partners maintain curiosity, playfulness, and willingness to discover together what authentic partnership means for your unique combination of personalities and dreams.",
    positive: "You bring innocence, spontaneity, and unlimited possibility to relationships, creating partnerships that feel fresh and full of potential for discovery and growth. Your willingness to approach love without preconceptions allows for authentic connection that isn't limited by past experiences or social expectations. You offer your partner the gift of experiencing love as an adventure and opportunity for mutual exploration and discovery.",
    challenge: "May be naive about relationship realities, practical needs, or the sustained effort required to build lasting partnership beyond initial attraction and excitement. Tendency toward impulsiveness in love decisions without adequate consideration of long-term consequences or compatibility factors. Can lack the experience or skills needed to navigate relationship challenges effectively, potentially creating problems through inexperience rather than lack of care.",
    advice: "Embrace love as an adventure and opportunity for discovery while also learning practical relationship skills and seeking guidance from experienced mentors who can help you avoid common pitfalls. Maintain your fresh perspective and openness to possibility while also developing the patience and commitment needed for building lasting partnership. Balance your spontaneous approach with careful consideration of important relationship decisions that affect your long-term happiness and compatibility."
  }
};