/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Inspiration Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * sources of inspiration, what motivates and uplifts you, and how you
 * find meaning and creative energy in life.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Inspiration - What inspires you and how you inspire others
 */
export const inspirationInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "You find inspiration in new beginnings, pioneering ventures, and opportunities to lead and create something from nothing. Your inspiration comes from the possibility of being first, breaking new ground, and demonstrating what's possible through courage and initiative. You are most inspired when you can express your unique vision and see others embrace their own creative power. The act of creation itself, especially when it involves innovation and leadership, fills you with energy and purpose.",
    positive: "Natural ability to inspire others through your confidence and willingness to take the first step into unknown territory. Your enthusiasm for new projects and possibilities is contagious, motivating others to believe in their own creative potential. You excel at finding inspiration in challenges that others might find daunting, seeing them as opportunities to demonstrate leadership and create something meaningful.",
    challenge: "May lose inspiration quickly when projects move past the initial creative phase into maintenance or routine development. Tendency to seek constant new sources of inspiration rather than finding depth in ongoing projects or established situations. Can become discouraged when you're not in a leadership position or when others don't immediately embrace your vision.",
    advice: "Cultivate inspiration not just from new beginnings but also from the process of nurturing and developing your creations over time. Learn to find fresh inspiration within familiar situations by discovering new angles and possibilities for innovation. Share your natural inspirational energy while also drawing inspiration from others' contributions and perspectives."
  },
  2: {
    general: "You find inspiration in quiet moments of reflection, spiritual insights, and the mysteries of life that reveal themselves through patient observation and inner listening. Your inspiration comes from intuitive understanding, sacred spaces, and the subtle energies that connect all living things. You are most inspired when you can access your inner wisdom and help others discover their own spiritual depths. The unseen realms, symbolism, and mystical experiences provide endless sources of creative energy for you.",
    positive: "Deep well of inner inspiration that comes from your connection to intuitive wisdom and spiritual understanding. Your ability to find inspiration in silence and subtle experiences helps you access profound insights that others might miss. You inspire others through your gentle wisdom and ability to see the sacred in everyday moments.",
    challenge: "May struggle to find inspiration in busy, noisy environments or situations that require quick action without time for reflection. Tendency to wait passively for inspiration to arise rather than actively seeking it through engagement with the world. Can become disconnected from practical sources of inspiration, preferring mystical insights to tangible experiences.",
    advice: "Balance your natural connection to inner inspiration with active engagement in the external world that can spark new insights. Practice finding moments of sacred reflection even in busy environments. Share your intuitive inspirations in ways that others can understand and apply practically in their lives."
  },
  3: {
    general: "You find inspiration in beauty, abundance, creativity, and the fertile possibilities that life offers for growth and expression. Your inspiration comes from nature, artistic expression, sensual pleasures, and the joy of creating and nurturing life in all its forms. You are most inspired when surrounded by beauty and when you can contribute to making the world more beautiful and abundant. The creative process itself, especially when it involves nurturing others or bringing beauty into being, fills you with enthusiasm.",
    positive: "Natural ability to find inspiration in life's abundance and to inspire others through your creative generosity and appreciation for beauty. Your enthusiasm for creative expression and nurturing growth is infectious, encouraging others to embrace their own creative fertility. You excel at creating inspiring environments and experiences that uplift everyone around you.",
    challenge: "May struggle to find inspiration in austere or challenging environments that lack obvious beauty or abundance. Tendency to depend on external beauty and comfort for inspiration rather than finding it within yourself. Can become overwhelmed by too many creative possibilities, making it difficult to focus your inspirational energy effectively.",
    advice: "Learn to find seeds of beauty and inspiration even in challenging circumstances, recognizing your power to create abundance wherever you are. Practice drawing inspiration from your inner creative source rather than depending entirely on external conditions. Focus your abundant inspirational energy on projects that truly resonate with your deepest values."
  },
  4: {
    general: "You find inspiration in structure, order, and the process of building something lasting through patient effort and dedication. Your inspiration comes from seeing plans come to fruition, systems working efficiently, and the satisfaction of creating solid foundations for future growth. You are most inspired when you can work methodically toward meaningful goals and see tangible progress. The act of organizing, structuring, and building step by step provides deep satisfaction and creative energy.",
    positive: "Steady source of inspiration that comes from dedication to craft and the satisfaction of building something substantial over time. Your ability to find inspiration in systematic progress and achieved milestones helps you maintain motivation when others might give up. You inspire others through your example of patient persistence and the quality of what you create.",
    challenge: "May struggle to find inspiration in chaotic or rapidly changing situations that don't allow for systematic building. Tendency to dismiss spontaneous or intuitive sources of inspiration in favor of planned, structured approaches. Can become too rigid in your inspirational patterns, missing opportunities for creative breakthroughs.",
    advice: "Balance your appreciation for structured inspiration with openness to unexpected sources of creative energy and spontaneous insights. Learn to find inspiration in the process of adaptation and flexibility, not just in following established plans. Allow others' more spontaneous approaches to inspire new possibilities within your structured framework."
  },
  5: {
    general: "You find inspiration in wisdom traditions, spiritual teachings, and the accumulated knowledge that has guided humanity through the ages. Your inspiration comes from understanding universal principles, studying with masters, and connecting with established paths of wisdom. You are most inspired when you can learn from those who have gone before and share traditional wisdom in meaningful ways. Sacred texts, spiritual teachers, and time-tested principles provide endless sources of guidance and creative energy.",
    positive: "Deep connection to inspirational wisdom that has stood the test of time, providing stable foundation for your creative and spiritual development. Your ability to find inspiration in traditional sources helps you avoid common pitfalls and build on proven foundations. You inspire others by connecting them with timeless wisdom and helping them understand universal principles.",
    challenge: "May struggle to find inspiration in contemporary or unconventional sources that challenge traditional understanding. Tendency to rely too heavily on external authorities for inspiration rather than trusting your own insights and experiences. Can become limited by traditional frameworks, missing opportunities for fresh inspiration and innovation.",
    advice: "Honor traditional sources of inspiration while also remaining open to new revelations and contemporary insights that expand ancient wisdom. Practice finding personal inspiration within traditional frameworks rather than just accepting them passively. Bridge traditional wisdom with modern understanding to create fresh sources of inspiration."
  },
  6: {
    general: "You find inspiration in harmony, beauty, relationships, and the aesthetic perfection that emerges when elements come together in perfect balance. Your inspiration comes from art, beautiful environments, loving relationships, and moments of perfect harmony between people or ideas. You are most inspired when you can create or experience beauty and when you see others finding harmony in their lives. The interplay of relationships, aesthetic experiences, and balanced compositions provides endless creative stimulation.",
    positive: "Natural ability to find inspiration in beauty and harmony, and to create inspiring experiences for others through your aesthetic sense. Your appreciation for balance and beauty helps you recognize inspirational moments that others might overlook. You inspire others through your ability to create harmonious environments and relationships that nurture creativity.",
    challenge: "May struggle to find inspiration in conflict, discord, or situations that lack obvious beauty or harmony. Tendency to avoid sources of inspiration that might disturb your sense of balance or require dealing with difficult emotions. Can become too dependent on external beauty and harmony for inspiration, losing touch with deeper sources.",
    advice: "Learn to find inspiration even in challenging or discordant situations, recognizing how they can lead to greater harmony and understanding. Practice drawing inspiration from the process of creating balance rather than just experiencing it. Embrace the full spectrum of human experience as a source of inspiration for creating authentic beauty."
  },
  7: {
    general: "You find inspiration in challenges, competition, goals, and the opportunity to overcome obstacles through determination and skill. Your inspiration comes from the thrill of pursuit, the satisfaction of victory, and the growth that comes from pushing beyond your limits. You are most inspired when you have clear objectives to pursue and when you can see tangible progress toward meaningful achievements. The dynamic energy of striving, competing, and conquering provides constant motivation.",
    positive: "Powerful ability to find inspiration in challenges that others might find discouraging, seeing them as opportunities for growth and achievement. Your competitive spirit and goal-oriented nature create constant sources of motivation and energy. You inspire others through your determination and ability to transform obstacles into stepping stones.",
    challenge: "May struggle to find inspiration in peaceful, contemplative situations that don't offer clear challenges or goals to pursue. Tendency to create unnecessary conflict or competition to generate the inspirational energy you crave. Can become exhausted by constant striving, losing touch with quieter sources of inspiration.",
    advice: "Balance your natural inspiration from challenges with appreciation for peaceful moments and collaborative achievements. Learn to find inspiration in the journey itself, not just in reaching goals or overcoming obstacles. Channel your competitive energy toward inspiring others to achieve their best rather than just pursuing personal victories."
  },
  8: {
    general: "You find inspiration in stories of resilience, transformation through adversity, and the quiet strength that emerges from patient endurance. Your inspiration comes from witnessing or experiencing how challenges can be transformed into wisdom and how gentle persistence can accomplish what force cannot. You are most inspired when you can help others find their inner strength or when you see love and compassion triumph over hardship. The process of healing and transformation provides deep meaning and creative energy.",
    positive: "Profound ability to find inspiration in difficult situations and to help others discover strength they didn't know they possessed. Your patient, compassionate approach to challenges creates inspiration from experiences that might discourage others. You inspire through your example of gentle strength and ability to transform pain into wisdom.",
    challenge: "May struggle to find inspiration in easy, joyful situations that don't require deep strength or transformation. Tendency to focus too much on struggles and challenges as sources of inspiration, potentially missing lighter forms of creative energy. Can become overly identified with the role of enduring hardship rather than preventing it.",
    advice: "Balance your ability to find inspiration in challenges with appreciation for joy, ease, and celebration as equally valid sources of creative energy. Practice finding inspiration in prevention and positive creation, not just in healing and transformation. Share your strength in ways that inspire others to avoid unnecessary hardship."
  },
  9: {
    general: "You find inspiration in solitude, wisdom, philosophical understanding, and the deep insights that come from contemplation and study. Your inspiration comes from understanding life's deeper meanings, exploring philosophical questions, and sharing wisdom gained through experience and reflection. You are most inspired when you can retreat into contemplation and when you discover profound truths that illuminate life's mysteries. Books, meditation, and philosophical dialogue provide endless sources of inspiration.",
    positive: "Rich inner world of inspiration that comes from deep contemplation and philosophical understanding. Your ability to find profound meaning in experiences and ideas creates a sustainable source of wisdom and creative insight. You inspire others through sharing insights that help them understand their own life experiences more deeply.",
    challenge: "May struggle to find inspiration in social situations or activities that don't allow for deep reflection and contemplation. Tendency to intellectualize inspiration rather than experiencing it directly through engagement with life. Can become isolated in your search for wisdom, missing inspiration that comes from connection and community.",
    advice: "Balance your contemplative sources of inspiration with active engagement in the world that provides new material for reflection. Practice finding inspiration in simple, everyday experiences as well as profound philosophical insights. Share your wisdom in ways that inspire practical action and positive change."
  },
  10: {
    general: "You find inspiration in natural cycles, synchronicities, and the recognition that life unfolds according to divine timing and natural rhythms. Your inspiration comes from observing patterns, understanding cycles of growth and rest, and recognizing when the time is right for action or patience. You are most inspired when you can flow with life's natural rhythms and when you see how everything connects in meaningful patterns. The dance of fortune, timing, and natural cycles provides constant fascination and creative energy.",
    positive: "Natural ability to find inspiration in life's cycles and patterns, recognizing opportunities and meanings that others might miss. Your understanding of timing helps you catch inspirational waves when they arise and rest when necessary. You inspire others by helping them understand and work with natural rhythms rather than against them.",
    challenge: "May become passive about seeking inspiration, waiting for the right timing rather than actively creating opportunities. Tendency to attribute too much to fate or cycles, potentially missing chances to create your own inspiration. Can struggle to find inspiration during natural low cycles, becoming discouraged rather than patient.",
    advice: "Balance your understanding of natural cycles with proactive creation of inspirational opportunities within those rhythms. Learn to find inspiration in all phases of cycles, not just the peaks or moments of obvious opportunity. Help others understand timing while also encouraging them to take inspired action when moved to do so."
  },
  11: {
    general: "You find inspiration in justice, fairness, ethical principles, and the vision of a world where everyone is treated with respect and dignity. Your inspiration comes from seeing wrongs made right, balance restored, and truth prevail over deception. You are most inspired when you can contribute to creating more justice and fairness in the world and when you see others standing up for what's right. The pursuit of justice and ethical clarity provides profound meaning and motivational energy.",
    positive: "Strong moral compass that provides clear inspiration for action and helps you maintain direction even in confusing situations. Your commitment to justice and fairness inspires others to examine their own ethics and take principled stands. You excel at finding inspiration in the vision of what's possible when people act with integrity.",
    challenge: "May struggle to find inspiration in morally ambiguous situations or when perfect justice seems impossible to achieve. Tendency to become discouraged when witnessing unfairness or injustice that you cannot immediately address. Can become rigid in your inspirational sources, missing opportunities that don't fit clear ethical categories.",
    advice: "Balance your inspiration from justice with acceptance of human imperfection and the gradual nature of positive change. Learn to find inspiration in small acts of fairness and incremental progress toward justice. Channel your ethical inspiration toward practical actions that create real improvement rather than just ideal visions."
  },
  12: {
    general: "You find inspiration in alternative perspectives, unconventional wisdom, and the insights that come from seeing things from completely different angles. Your inspiration comes from questioning assumptions, exploring paradoxes, and discovering how apparent limitations can become gateways to new understanding. You are most inspired when you can offer fresh perspectives that transform problems into opportunities. The process of reframing, reimagining, and seeing beyond conventional thinking provides endless creative stimulation.",
    positive: "Unique ability to find inspiration in situations that others find limiting or problematic, seeing hidden opportunities and alternative solutions. Your unconventional perspective helps others break free from limiting thought patterns and discover new possibilities. You inspire through your willingness to sacrifice conventional thinking for deeper truth.",
    challenge: "May struggle to find inspiration in straightforward situations that don't require alternative perspectives or complex reframing. Tendency to complicate things unnecessarily in search of unique angles rather than appreciating simple inspirations. Can become contrarian, rejecting conventional sources of inspiration even when they're valuable.",
    advice: "Balance your gift for alternative perspectives with appreciation for straightforward inspiration and conventional wisdom when they serve well. Practice finding the extraordinary within the ordinary rather than always seeking the unusual. Use your unique perspective to enhance rather than replace traditional sources of inspiration."
  },
  13: {
    general: "You find inspiration in transformation, rebirth, and the profound changes that occur when old forms give way to new possibilities. Your inspiration comes from witnessing or facilitating deep change, seeing how endings lead to beginnings, and understanding the cyclic nature of death and rebirth. You are most inspired when you can participate in or witness profound transformation and when you see others finding courage to let go and embrace change. The process of metamorphosis provides deep meaning and creative energy.",
    positive: "Profound ability to find inspiration in endings and transitions that others might fear, seeing them as gateways to new possibilities. Your comfort with transformation helps you maintain inspiration even during difficult changes. You inspire others by showing them how to find meaning and opportunity in life's inevitable transitions.",
    challenge: "May struggle to find inspiration in stable, peaceful situations that don't involve dramatic change or transformation. Tendency to create unnecessary endings or crises to generate the transformative energy you find inspiring. Can become addicted to intensity and change, missing the inspiration available in gentle growth.",
    advice: "Balance your inspiration from transformation with appreciation for stability and gradual evolution as equally valid forms of growth. Learn to find inspiration in subtle changes and gentle transitions, not just dramatic transformations. Help others navigate necessary changes while also honoring what deserves to be preserved and continued."
  },
  14: {
    general: "You find inspiration in balance, healing, integration, and the beautiful harmony that emerges when opposing forces find their perfect middle ground. Your inspiration comes from creating wholeness, facilitating healing, and discovering how different elements can work together in perfect proportion. You are most inspired when you can help create or experience perfect balance and when you see others finding their own center. The art of integration and healing provides constant creative stimulation.",
    positive: "Natural ability to find inspiration in the process of creating balance and integration, seeing beauty in the harmony of well-proportioned wholes. Your healing presence and balanced perspective inspire others to find their own center and integration. You excel at finding sustainable sources of inspiration that nurture long-term creativity.",
    challenge: "May struggle to find inspiration in intense, extreme experiences that temporarily disrupt balance and harmony. Tendency to avoid passionate sources of inspiration that might disturb your equilibrium. Can become too focused on maintaining balance, missing the creative energy that comes from temporary intensity.",
    advice: "Balance your natural inspiration from harmony with appreciation for the creative power of temporary intensity and passionate engagement. Learn to find inspiration in the dynamic process of seeking balance, not just in achieving it. Embrace the full spectrum of experience as necessary for true integration and wholeness."
  },
  15: {
    general: "You find inspiration in intensity, passion, the shadow realms of human experience, and the raw power that comes from embracing all aspects of life without judgment. Your inspiration comes from deep dives into complex emotions, explorations of power dynamics, and the transformation that occurs through accepting our whole selves. You are most inspired when you can work with powerful energies and when you see others embracing their authentic power. The exploration of depth and intensity provides profound creative fuel.",
    positive: "Powerful ability to find inspiration in aspects of life that others might fear or avoid, transforming shadow material into creative gold. Your willingness to embrace intensity creates profound and transformative inspirational experiences. You inspire others by showing them how to work with their own power and shadow aspects constructively.",
    challenge: "May struggle to find inspiration in light, simple, or gentle experiences that don't involve intensity or complex dynamics. Tendency to create unnecessary drama or intensity to access the deep inspiration you crave. Can become overwhelmed by or addicted to intense sources of inspiration.",
    advice: "Balance your natural attraction to intense inspiration with appreciation for gentler, lighter sources of creative energy. Learn to find depth and power in simplicity as well as complexity. Channel your intense inspirational energy toward healing and transformation rather than drama or manipulation."
  },
  16: {
    general: "You find inspiration in breakthrough moments, sudden revelations, and the lightning-strike insights that shatter old paradigms and create new possibilities. Your inspiration comes from moments of clarity, liberation from illusions, and the freedom that comes from seeing truth clearly. You are most inspired when old structures fall away to reveal new potential and when you can help others break free from limitations. The process of awakening and liberation provides explosive creative energy.",
    positive: "Natural ability to find inspiration in moments of disruption and revelation that create new possibilities for growth and understanding. Your openness to sudden change and breakthrough insights keeps you creatively alive and responsive. You inspire others through your willingness to embrace truth even when it shatters comfortable illusions.",
    challenge: "May struggle to find inspiration in gradual development or patient building that doesn't involve dramatic breakthroughs. Tendency to create unnecessary upheaval in search of the revelatory inspiration you crave. Can become addicted to breakthrough moments without building on the insights gained.",
    advice: "Balance your inspiration from breakthroughs with appreciation for gradual development and patient integration of insights. Learn to find inspiration in the process of building on revelations, not just experiencing them. Channel breakthrough energy toward constructive change rather than constant disruption."
  },
  17: {
    general: "You find inspiration in hope, faith, spiritual vision, and the guiding stars that show us the way toward our highest potential and most beautiful possibilities. Your inspiration comes from connecting with divine guidance, envisioning positive futures, and maintaining faith in humanity's potential for good. You are most inspired when you can see and share visions of what's possible and when you witness others finding their own guiding star. The connection to higher purpose provides infinite creative energy.",
    positive: "Boundless source of inspiration that comes from your connection to hope and higher vision, helping you maintain creativity even in difficult times. Your faith and optimism inspire others to reach for their own highest potential and maintain hope. You excel at finding and sharing inspiration that connects people with their spiritual purpose.",
    challenge: "May struggle to find inspiration in practical, mundane situations that don't obviously connect to higher purpose or spiritual vision. Tendency to overlook present opportunities while focused on future possibilities and distant stars. Can become disconnected from earthly sources of inspiration while reaching for the divine.",
    advice: "Balance your celestial sources of inspiration with grounded appreciation for earthly beauty and practical opportunities for good. Learn to find the sacred in the mundane and the spiritual in everyday acts of kindness. Connect your high visions with practical steps that make them accessible to others."
  },
  18: {
    general: "You find inspiration in dreams, mysteries, the unconscious realm, and the vast ocean of psychic and emotional experience that flows beneath surface reality. Your inspiration comes from intuitive insights, symbolic experiences, and the rich imagery of dreams and imagination. You are most inspired when you can dive deep into the mysterious waters of consciousness and when you help others understand their own depths. The exploration of mystery and psychic realms provides endless creative material.",
    positive: "Deep well of inspiration that comes from your connection to unconscious wisdom and the rich symbolic language of dreams and intuition. Your ability to find meaning in mysteries and unclear experiences creates unique creative insights. You inspire others by helping them access their own intuitive wisdom and hidden depths.",
    challenge: "May struggle to find inspiration in clear, logical, or well-defined situations that don't involve mystery or ambiguity. Tendency to become lost in confusion or fantasy while seeking the mystical inspiration you crave. Can have difficulty translating mystical inspiration into practical creative expression.",
    advice: "Balance your mystical sources of inspiration with practical skills for manifesting insights in tangible forms. Learn to find mystery and depth in everyday experiences as well as obviously mystical ones. Develop clear channels for expressing your intuitive inspirations in ways others can understand and use."
  },
  19: {
    general: "You find inspiration in joy, success, radiant self-expression, and the pure pleasure of being alive and sharing your light with the world. Your inspiration comes from celebration, achievement, positive connections with others, and the simple happiness of existence. You are most inspired when you can shine your light freely and when you see others discovering their own radiance. The experience of joy and authentic success provides natural creative energy.",
    positive: "Natural abundance of inspiration that comes from your positive outlook and ability to find joy in life's experiences. Your radiant energy and enthusiasm create inspirational atmospheres that uplift everyone around you. You excel at helping others connect with their own sources of joy and creative confidence.",
    challenge: "May struggle to find inspiration in difficult, dark, or challenging situations that don't offer obvious reasons for celebration. Tendency to avoid or deny negative experiences that could provide different forms of inspiration. Can become dependent on external success and recognition for maintaining inspirational energy.",
    advice: "Balance your natural joy-based inspiration with ability to find meaning and creative energy in life's full spectrum of experiences. Learn to maintain your inner light even when external circumstances aren't obviously positive. Share your gift for finding joy while also honoring others' need to process different experiences."
  },
  20: {
    general: "You find inspiration in spiritual awakening, collective transformation, and the call to serve something greater than personal desires or individual achievement. Your inspiration comes from recognizing divine purpose, answering spiritual callings, and participating in humanity's evolution. You are most inspired when you can contribute to collective awakening and when you see others answering their own spiritual call. The process of spiritual service provides profound meaning and creative purpose.",
    positive: "Profound source of inspiration that comes from your connection to collective consciousness and spiritual purpose beyond ego. Your ability to hear and answer spiritual callings inspires others to seek their own higher purpose. You excel at finding inspiration that serves not just personal creativity but collective evolution.",
    challenge: "May struggle to find inspiration in personal, individual experiences that don't obviously connect to collective or spiritual purposes. Tendency to dismiss personal desires or individual creative impulses as less important than spiritual service. Can become overwhelmed by the magnitude of collective needs and spiritual responsibilities.",
    advice: "Balance your inspiration from collective spiritual purpose with honoring your individual creative needs and personal journey. Learn that serving your authentic individual expression can be a form of spiritual service. Ground your spiritual inspiration in practical actions that create real positive change."
  },
  21: {
    general: "You find inspiration in completion, fulfillment, worldly success, and the satisfaction of seeing long-term visions manifest in reality. Your inspiration comes from achieving mastery, creating lasting impact, and experiencing the full circle of creative manifestation. You are most inspired when you can see the fruits of sustained effort and when you help others achieve their own worldly and spiritual fulfillment. The experience of completion and mastery provides deep satisfaction and continued creative motivation.",
    positive: "Sustainable source of inspiration that comes from your experience of achievement and your understanding of what creates lasting fulfillment. Your mastery and success inspire others to persist in their own creative journeys. You excel at finding continued inspiration even after achieving significant goals.",
    challenge: "May struggle to find inspiration in new beginnings or situations where you must start over without recognized mastery or achievement. Tendency to rest on past accomplishments rather than seeking fresh sources of inspiration. Can become disconnected from beginners' enthusiasm and the inspiration of discovery.",
    advice: "Balance your inspiration from mastery and completion with openness to new learning and fresh beginnings. Practice finding inspiration in sharing your knowledge while remaining open to others' innovations. Maintain connection to the original inspiration that started your journey while building on your achievements."
  },
  22: {
    general: "You find inspiration everywhere and in everything, approaching life with the unlimited curiosity and wonder of someone experiencing the world for the first time. Your inspiration comes from discovery, experimentation, and the freedom to explore without preconceptions or limitations. You are most inspired when you can approach situations with fresh eyes and when you help others rediscover their own capacity for wonder. The state of open possibility provides infinite creative potential.",
    positive: "Unlimited capacity for inspiration that comes from your fresh perspective and willingness to find wonder in any experience. Your childlike enthusiasm and openness to possibility inspire others to rediscover their own creative freedom. You excel at finding novel sources of inspiration that others might overlook due to familiarity.",
    challenge: "May struggle to find sustained inspiration in any one direction, constantly seeking new experiences rather than developing depth. Tendency to abandon sources of inspiration too quickly when they become familiar or require sustained effort. Can lack the experience to recognize valuable traditional sources of inspiration.",
    advice: "Balance your gift for finding fresh inspiration everywhere with willingness to explore some sources more deeply over time. Learn to rediscover wonder in familiar experiences through deeper exploration. Combine your natural openness with wisdom from others who have explored specific inspirational paths more fully."
  }
};