/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Mom's Karma Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * maternal karma, mother relationships, feminine lineage patterns, and
 * karmic lessons inherited from or related to your mother's energy.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Mom's Karma - Maternal karmic patterns and mother relationship dynamics
 */
export const momsKarmaInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your mother's karma involves themes of independence, pioneering spirit, and balancing individual expression with nurturing responsibilities, creating patterns around self-assertion and motherhood in your family line. Her karmic lessons may involve learning to maintain personal identity while caring for others and expressing leadership within family dynamics. You may carry forward her strength and independence while needing to heal patterns of emotional distance or difficulty with vulnerability. The karmic gift involves natural confidence and leadership and the challenge involves learning nurturing authority.",
    positive: "Inherited strong sense of personal power and independence that helps you maintain your identity while caring for others and pursuing your own goals. Your mother's pioneering energy provides you with courage to break traditional patterns and create new ways of being. You have natural leadership abilities in nurturing contexts and the gift of inspiring others to embrace their own strength and independence.",
    challenge: "May carry patterns of emotional distance, difficulty with dependency, or struggle between individual needs and caring responsibilities that stem from your mother's unresolved relationship with autonomy and connection. Tendency to suppress vulnerable emotions or avoid asking for help when you need support. Can inherit challenges with receiving care or allowing others to take care of you.",
    advice: "Honor the independence and strength from your mother's lineage while developing comfort with interdependence and emotional vulnerability that enhances rather than threatens your autonomy. Practice asking for and receiving support while maintaining your strong sense of self. Transform inherited patterns of emotional distance into conscious choice about when to be strong and when to be receptive."
  },
  2: {
    general: "Your mother's karma involves themes of intuition, emotional depth, and the balance between receptivity and self-protection, creating patterns around sensitivity and boundaries in your family line. Her karmic lessons may involve learning to trust intuitive wisdom while maintaining healthy emotional boundaries and expressing needs clearly. You may carry forward her psychic sensitivity and emotional wisdom while needing to heal patterns of emotional overwhelm or difficulty with direct communication. The karmic gift involves natural empathy and intuition and the challenge involves learning healthy emotional boundaries.",
    positive: "Inherited deep emotional intelligence and intuitive understanding that helps you navigate complex relationships and provide emotional support for others. Your mother's sensitive nature gives you the ability to understand unspoken needs and feelings. You have natural counseling abilities and the gift of creating emotional safety for others to express their authentic feelings and experiences.",
    challenge: "May carry patterns of emotional overwhelm, poor boundaries, or difficulty expressing needs directly that stem from your mother's unresolved relationship with sensitivity and self-protection. Tendency to absorb others' emotions or sacrifice your own needs to avoid conflict or emotional discomfort. Can struggle with passive-aggressive communication or emotional manipulation when direct expression feels unsafe.",
    advice: "Honor the emotional intelligence and intuitive gifts from your mother's lineage while developing clear communication skills and healthy boundaries that protect your sensitive nature. Practice expressing your needs and feelings directly rather than expecting others to intuitively understand. Transform inherited patterns of emotional overwhelm into conscious sensitivity that serves both your wellbeing and others' growth."
  },
  3: {
    general: "Your mother's karma involves themes of nurturing, creativity, and abundance, creating patterns around self-worth and giving in your family line. Her karmic lessons may involve learning to receive love and appreciation while giving generously and finding worth beyond just caring for others. You may carry forward her nurturing abilities and creative gifts while needing to heal patterns of codependency or difficulty receiving support. The karmic gift involves natural nurturing and creative abilities and the challenge involves learning self-worth and receiving.",
    positive: "Inherited generous nurturing spirit and creative abilities that help you care for others while creating beauty and abundance in your environment. Your mother's loving nature gives you the ability to make others feel valued and supported. You have natural artistic or creative talents and the gift of seeing and nurturing potential in people and situations.",
    challenge: "May carry patterns of codependency, difficulty receiving care, or measuring self-worth through giving and others' happiness that stem from your mother's unresolved relationship with her own value and needs. Tendency to overextend yourself or neglect your own needs while caring for others. Can struggle with guilt when focusing on your own goals or saying no to others' requests for help.",
    advice: "Honor the nurturing and creative gifts from your mother's lineage while developing healthy boundaries and authentic self-worth that doesn't depend on others' approval or your caregiving role. Practice receiving love and support as generously as you give it. Transform inherited patterns of codependency into conscious nurturing that honors both your needs and others' growth toward independence."
  },
  4: {
    general: "Your mother's karma involves themes of structure, security, and creating stable foundations for family, creating patterns around responsibility and tradition in your family line. Her karmic lessons may involve learning to balance duty with personal fulfillment and creating security without rigidity. You may carry forward her reliability and organizational abilities while needing to heal patterns of over-responsibility or difficulty with change. The karmic gift involves natural organizing and security-creating abilities and the challenge involves learning flexible responsibility.",
    positive: "Inherited strong sense of responsibility and ability to create stable, secure environments that provide foundation for growth and development. Your mother's practical nature gives you the skills to organize and manage complex situations effectively. You have natural ability to create structure that supports rather than limits others and the gift of providing reliable security and consistency.",
    challenge: "May carry patterns of over-responsibility, rigidity, or difficulty with spontaneity that stem from your mother's unresolved relationship with duty and personal needs. Tendency to take on too much responsibility for others' wellbeing or become controlling when security feels threatened. Can struggle with allowing change or accepting that some things are beyond your control.",
    advice: "Honor the responsibility and security-creating abilities from your mother's lineage while developing flexibility and trust that allows others to take appropriate responsibility for their own lives. Practice creating structure that supports growth rather than controlling outcomes. Transform inherited patterns of over-responsibility into conscious caretaking that empowers rather than enables others."
  },
  5: {
    general: "Your mother's karma involves themes of wisdom, tradition, and spiritual guidance within family context, creating patterns around teaching and moral authority in your family line. Her karmic lessons may involve learning to balance respect for tradition with individual spiritual growth and sharing wisdom without imposing beliefs. You may carry forward her wisdom and moral foundation while needing to heal patterns of rigidity or difficulty with questioning authority. The karmic gift involves natural teaching and wisdom-sharing abilities and the challenge involves learning flexible guidance.",
    positive: "Inherited wisdom and strong moral foundation that helps you provide guidance and teaching for others while maintaining respect for traditional values and spiritual principles. Your mother's wise nature gives you the ability to see larger patterns and understand life's deeper meanings. You have natural counseling abilities and the gift of helping others connect with meaningful spiritual and ethical principles.",
    challenge: "May carry patterns of moral rigidity, difficulty with different perspectives, or tendency to impose beliefs that stem from your mother's unresolved relationship with authority and individual expression. Tendency to judge others who don't share your values or become dogmatic about spiritual or moral principles. Can struggle with allowing others to find their own spiritual path or make their own mistakes.",
    advice: "Honor the wisdom and moral foundation from your mother's lineage while developing respect for others' individual spiritual journeys and different approaches to truth and meaning. Practice sharing wisdom while allowing others to discover their own understanding. Transform inherited patterns of spiritual rigidity into flexible guidance that serves others' authentic growth and spiritual development."
  },
  6: {
    general: "Your mother's karma involves themes of love, beauty, and harmonious relationships, creating patterns around partnership and aesthetic appreciation in your family line. Her karmic lessons may involve learning to balance giving and receiving in relationships and maintaining individual identity within partnerships. You may carry forward her relationship skills and aesthetic sense while needing to heal patterns of people-pleasing or difficulty with conflict. The karmic gift involves natural harmony-creating abilities and the challenge involves learning authentic relationship.",
    positive: "Inherited ability to create beautiful, harmonious relationships and environments that support everyone's wellbeing and aesthetic appreciation. Your mother's loving nature gives you natural diplomatic skills and the ability to see multiple perspectives in conflicts. You have natural artistic sensibilities and the gift of helping others appreciate beauty and find balance in their relationships.",
    challenge: "May carry patterns of people-pleasing, conflict avoidance, or difficulty maintaining individual identity in relationships that stem from your mother's unresolved relationship with harmony and authenticity. Tendency to sacrifice your own needs to maintain peace or seek validation through being agreeable and attractive. Can struggle with expressing anger or disappointment when relationships become challenging.",
    advice: "Honor the relationship skills and aesthetic gifts from your mother's lineage while developing authentic self-expression and healthy conflict resolution that deepens rather than threatens intimacy. Practice maintaining your individual identity while creating harmonious connections. Transform inherited patterns of people-pleasing into genuine love that includes honest communication about difficult feelings and needs."
  },
  7: {
    general: "Your mother's karma involves themes of determination, achievement, and balancing drive with nurturing, creating patterns around success and competition in your family line. Her karmic lessons may involve learning to pursue goals while maintaining loving relationships and finding satisfaction in process rather than just outcomes. You may carry forward her drive and goal-oriented nature while needing to heal patterns of burnout or difficulty with receiving support. The karmic gift involves natural achievement abilities and determination and the challenge involves learning collaborative success.",
    positive: "Inherited strong drive and determination that helps you achieve meaningful goals while inspiring others to pursue their own excellence and potential. Your mother's ambitious nature gives you the courage to overcome obstacles and the persistence to succeed in challenging endeavors. You have natural leadership abilities in pursuing objectives and the gift of motivating others to reach their potential.",
    challenge: "May carry patterns of workaholism, difficulty delegating, or tendency to sacrifice relationships for achievement that stem from your mother's unresolved relationship with success and receiving support. Tendency to become impatient with others' different pace or feel guilty when not constantly productive. Can struggle with asking for help or accepting that others might have different definitions of success.",
    advice: "Honor the drive and achievement abilities from your mother's lineage while developing balance between goal pursuit and relationship nurturing that enhances rather than sacrifices connection. Practice accepting support and collaboration in achieving goals. Transform inherited patterns of isolated achievement into collaborative success that includes and celebrates others' contributions."
  },
  8: {
    general: "Your mother's karma involves themes of emotional strength, healing, and patient transformation through love, creating patterns around resilience and emotional processing in your family line. Her karmic lessons may involve learning to express feelings directly while maintaining compassionate strength and asking for help when needed. You may carry forward her emotional resilience and healing abilities while needing to heal patterns of emotional suppression or difficulty with anger. The karmic gift involves natural healing presence and emotional strength and the challenge involves learning emotional expression.",
    positive: "Inherited deep emotional strength and healing presence that helps you endure challenges with grace while supporting others through their emotional difficulties and transformation. Your mother's resilient nature gives you the ability to find meaning in suffering and help others develop their own inner strength. You have natural counseling abilities and the gift of creating emotional safety for healing work.",
    challenge: "May carry patterns of emotional suppression, difficulty expressing anger, or tendency to endure unnecessary suffering that stem from your mother's unresolved relationship with strength and vulnerability. Tendency to focus on others' emotional needs while neglecting your own or believing you should handle everything alone. Can struggle with asking for emotional support or expressing frustration in healthy ways.",
    advice: "Honor the emotional strength and healing abilities from your mother's lineage while developing healthy expression of all emotions including anger and the ability to receive emotional support when needed. Practice using strength to create positive change rather than just enduring difficulties. Transform inherited patterns of emotional suppression into conscious choice about when to be strong and when to be vulnerable."
  },
  9: {
    general: "Your mother's karma involves themes of wisdom, introspection, and the balance between solitude and family connection, creating patterns around inner knowledge and emotional depth in your family line. Her karmic lessons may involve learning to share wisdom accessibly while maintaining necessary solitude and connecting inner understanding with practical family life. You may carry forward her wisdom and depth while needing to heal patterns of emotional withdrawal or difficulty with practical engagement. The karmic gift involves natural wisdom and insight and the challenge involves learning engaged sharing.",
    positive: "Inherited deep wisdom and understanding that comes from introspection and emotional depth, providing profound insights for your own growth and guidance for others. Your mother's contemplative nature gives you the ability to see patterns and understand life's deeper emotional and spiritual significance. You have natural counseling abilities and the gift of helping others find meaning in their experiences.",
    challenge: "May carry patterns of emotional withdrawal, intellectual isolation, or difficulty with practical emotional expression that stem from your mother's unresolved relationship with wisdom and social connection. Tendency to retreat into your inner world when relationships become challenging or overwhelming. Can struggle with translating insights into practical action or accessible communication with family members.",
    advice: "Honor the wisdom and contemplative gifts from your mother's lineage while developing skills for sharing insights in ways that serve others' practical emotional needs and family harmony. Practice balancing solitude with engaged participation in relationships and family life. Transform inherited patterns of withdrawal into conscious choice about when to retreat for reflection and when to engage in practical emotional support."
  },
  10: {
    general: "Your mother's karma involves themes of accepting life's cycles, understanding divine timing in family life, and finding meaning in changing circumstances, creating patterns around flow and adaptation in your family line. Her karmic lessons may involve learning to balance acceptance with appropriate action and understanding how personal choices affect family destiny. You may carry forward her wisdom about timing and cycles while needing to heal patterns of passivity or difficulty taking responsibility. The karmic gift involves natural understanding of timing and cycles and the challenge involves learning active participation.",
    positive: "Inherited understanding of life's natural rhythms and timing that helps you navigate family challenges with faith and wisdom about when circumstances will naturally improve. Your mother's philosophical nature gives you the ability to find meaning in difficult experiences and help others understand their life's larger patterns. You have natural wisdom about emotional cycles and the gift of helping others flow with rather than fight against life's changes.",
    challenge: "May carry patterns of fatalism, passive waiting, or difficulty taking initiative in family matters that stem from your mother's unresolved relationship with personal power and divine will. Tendency to avoid responsibility by attributing everything to fate or timing rather than recognizing your own agency in family dynamics. Can struggle with taking action when family situations require intervention or leadership.",
    advice: "Honor the wisdom about timing and cycles from your mother's lineage while developing appropriate initiative and responsibility for your choices and actions within family systems. Practice working with natural timing while also taking inspired action when opportunities or crises require response. Transform inherited patterns of passivity into conscious participation in creating positive family dynamics within larger life patterns."
  },
  11: {
    general: "Your mother's karma involves themes of fairness, justice in family relationships, and ethical decision-making in nurturing contexts, creating patterns around moral responsibility and balanced caregiving in your family line. Her karmic lessons may involve learning to balance justice with compassion and making fair decisions in complex family situations. You may carry forward her strong moral sense and fairness while needing to heal patterns of rigidity or difficulty with emotional complexity. The karmic gift involves natural ethical understanding and fairness and the challenge involves learning compassionate justice.",
    positive: "Inherited strong sense of justice and ethical understanding that helps you create fair solutions in family conflicts and teach others about responsibility and consequences. Your mother's principled nature gives you the ability to see truth clearly and maintain ethical standards in caring relationships. You have natural mediation abilities and the gift of helping others understand how to balance individual needs with family responsibilities.",
    challenge: "May carry patterns of moral rigidity, judgmental thinking about family members, or difficulty with emotional complexity that stem from your mother's unresolved relationship with justice and human imperfection. Tendency to become paralyzed by analysis of right and wrong in family situations rather than responding with compassionate action. Can struggle with accepting family members' different choices or your own emotional reactions that don't seem rational.",
    advice: "Honor the ethical understanding and sense of justice from your mother's lineage while developing compassion and flexibility for human emotional complexity and family imperfection. Practice applying principles with wisdom about individual circumstances and family dynamics. Transform inherited patterns of moral rigidity into ethical wisdom that serves family healing and growth rather than judgment and punishment."
  },
  12: {
    general: "Your mother's karma involves themes of sacrifice, service to family, and finding wisdom through seeing family dynamics from different perspectives, creating patterns around martyrdom and unconditional love in your family line. Her karmic lessons may involve learning to distinguish between healthy sacrifice and self-denial and finding empowerment through service. You may carry forward her selfless love and wisdom while needing to heal patterns of martyrdom or difficulty with boundaries. The karmic gift involves natural service and wisdom and the challenge involves learning healthy sacrifice.",
    positive: "Inherited wisdom and deep love that comes from seeing family situations from multiple perspectives and willingness to sacrifice for meaningful family purposes. Your mother's service-oriented nature gives you the ability to help family members and find meaning through contribution to others' wellbeing. You have natural counseling abilities and the gift of seeing solutions to family problems that others might miss.",
    challenge: "May carry patterns of martyrdom, excessive self-sacrifice, or difficulty setting boundaries in family relationships that stem from your mother's unresolved relationship with service and personal needs. Tendency to give too much of yourself to family members or endure unnecessary hardship in the name of love and loyalty. Can struggle with asserting your needs or recognizing when family members need to take responsibility for their own problems.",
    advice: "Honor the wisdom and service orientation from your mother's lineage while developing healthy boundaries and the ability to distinguish between meaningful sacrifice and unnecessary self-denial. Practice loving family members while also maintaining your own wellbeing and growth. Transform inherited patterns of martyrdom into conscious service that empowers rather than enables family members' dependence."
  },
  13: {
    general: "Your mother's karma involves themes of transformation, letting go of family patterns, and facilitating emotional death and rebirth processes, creating patterns around change and renewal in your family line. Her karmic lessons may involve learning to navigate family transitions with grace and help others transform through letting go of outdated patterns. You may carry forward her understanding of transformation while needing to heal patterns of crisis creation or difficulty with stability. The karmic gift involves natural transformation abilities and the challenge involves learning sustainable change.",
    positive: "Inherited ability to navigate major family transitions and help others transform through challenging circumstances with courage and wisdom about renewal. Your mother's transformative nature gives you the strength to let go of family patterns that no longer serve and embrace new phases of family development. You have natural healing abilities and the gift of helping family members find meaning and opportunity in difficult endings.",
    challenge: "May carry patterns of creating family drama, difficulty with family stability, or tendency to abandon family relationships when they become challenging that stem from your mother's unresolved relationship with change and security. Tendency to create crises in family when life becomes peaceful or to leave family situations too quickly rather than working through difficulties. Can struggle with building lasting family foundations or appreciating gradual family development.",
    advice: "Honor the transformation abilities from your mother's lineage while developing appreciation for family stability and gradual growth that supports rather than threatens authentic family development. Practice creating conscious change in family patterns rather than crisis-driven transformation. Transform inherited patterns of family crisis creation into wisdom about when change serves family growth and when consistency supports family goals."
  },
  14: {
    general: "Your mother's karma involves themes of emotional balance, family healing, and integrating different family members' needs harmoniously, creating patterns around moderation and wholeness in your family line. Her karmic lessons may involve learning to blend different family personalities and needs while maintaining her own emotional equilibrium. You may carry forward her healing abilities and balanced perspective while needing to heal patterns of emotional suppression or difficulty with family intensity. The karmic gift involves natural family healing presence and the challenge involves learning healthy emotional intensity.",
    positive: "Inherited ability to create emotional balance and healing in challenging family situations and help family members integrate different aspects of themselves into harmonious relationships. Your mother's temperate nature gives you the wisdom to find middle ground in family conflicts and create sustainable family solutions. You have natural family counseling abilities and the gift of helping family members find moderation and emotional healing.",
    challenge: "May carry patterns of avoiding family intensity, suppressing strong emotions, or difficulty with necessary family confrontations that stem from your mother's unresolved relationship with strong feelings and direct family communication. Tendency to maintain family surface peace rather than working through important issues that need attention. Can struggle with expressing strong feelings in family or taking sides when family situations require clear positions.",
    advice: "Honor the healing and balancing abilities from your mother's lineage while developing comfort with appropriate family intensity and emotional expression when they serve authentic family communication and growth. Practice maintaining your emotional center while also engaging fully with family's emotional spectrum. Transform inherited patterns of family emotional suppression into conscious moderation that includes rather than excludes strong family feelings."
  },
  15: {
    general: "Your mother's karma involves themes of power dynamics in family, material security, and working with shadow aspects of motherhood, creating patterns around control and family desires in your family line. Her karmic lessons may involve learning to use family influence responsibly and transform material attachments into understanding of family abundance. You may carry forward her understanding of family power while needing to heal patterns of manipulation or unhealthy family boundaries. The karmic gift involves natural family power awareness and the challenge involves learning conscious family influence.",
    positive: "Inherited understanding of family power dynamics and practical family management that helps you navigate complex family situations and achieve family goals while maintaining family connection. Your mother's worldly nature gives you the ability to work with challenging family members and situations effectively. You have natural family management abilities and the gift of transforming difficult family situations into opportunities for family growth.",
    challenge: "May carry patterns of family manipulation, control issues, or difficulty with healthy family boundaries that stem from your mother's unresolved relationship with power and family security. Tendency to use emotional manipulation to maintain family control or struggle with addictive family patterns and unhealthy attachments. Can struggle with trusting family members or finding satisfaction in family achievements once they're accomplished.",
    advice: "Honor the family power awareness and practical abilities from your mother's lineage while developing ethical use of family influence and healthy family relationship patterns. Practice using family power to serve family members' growth rather than personal control. Transform inherited patterns of family manipulation into conscious family influence that serves family love and mutual benefit."
  },
  16: {
    general: "Your mother's karma involves themes of sudden family revelations, breaking free from limiting family patterns, and creating liberation through family crisis, creating patterns around family upheaval and awakening in your family line. Her karmic lessons may involve learning to create positive family change without unnecessary destruction and finding family stability after breakthrough experiences. You may carry forward her revolutionary family spirit while needing to heal patterns of family chaos or difficulty with gradual family development. The karmic gift involves natural family breakthrough abilities and the challenge involves learning constructive family change.",
    positive: "Inherited ability to break through limiting family patterns and help family members liberate themselves from family situations that no longer serve their growth and authentic expression. Your mother's revolutionary nature gives you the courage to speak family truths and create necessary family changes. You have natural ability to see through family illusions and the gift of helping family members face family reality and make liberating family choices.",
    challenge: "May carry patterns of creating unnecessary family drama, difficulty with family authority, or tendency to destroy rather than transform family relationships that stem from your mother's unresolved relationship with family structure and gradual family change. Tendency to rebel against all family rules or create family crisis when family life becomes too predictable. Can struggle with building on family insights rather than just breaking down old family patterns.",
    advice: "Honor the family breakthrough abilities from your mother's lineage while developing skills for creating constructive family change that builds better family structures rather than just destroying old family ones. Practice using revolutionary family energy to serve positive family transformation. Transform inherited patterns of destructive family rebellion into conscious family liberation that creates lasting positive family change."
  },
  17: {
    general: "Your mother's karma involves themes of hope, family vision, and maintaining faith in family potential, creating patterns around family inspiration and idealism in your family line. Her karmic lessons may involve learning to ground family vision in practical action and maintain family hope through challenging family circumstances. You may carry forward her inspirational family abilities and optimistic family perspective while needing to heal patterns of family unrealistic expectations or difficulty with family practical implementation. The karmic gift involves natural family inspirational presence and the challenge involves learning practical family idealism.",
    positive: "Inherited ability to maintain family hope and inspire family members with vision of positive family possibilities even during difficult family circumstances. Your mother's idealistic nature gives you the faith to pursue meaningful family goals and help family members believe in their family potential. You have natural family teaching abilities and the gift of connecting family members with their family guidance and higher family purpose.",
    challenge: "May carry patterns of family unrealistic expectations, family spiritual bypassing, or difficulty with family practical details that stem from your mother's unresolved relationship with family earthly reality and family limitation. Tendency to focus on future family possibilities while neglecting present family responsibilities and family relationships. Can struggle with family disappointment when family reality doesn't match idealistic family visions.",
    advice: "Honor the family inspirational and visionary abilities from your mother's lineage while developing practical skills for manifesting family ideals in concrete family reality. Practice grounding family spiritual vision in achievable family steps and present-moment family action. Transform inherited patterns of impractical family idealism into inspired family realism that creates positive family change in the family world."
  },
  18: {
    general: "Your mother's karma involves themes of family intuition, emotional mystery, and navigating the unconscious realm of family dynamics, creating patterns around family psychic sensitivity and emotional depth in your family line. Her karmic lessons may involve learning to trust family intuitive guidance while maintaining practical family discernment and clear family communication. You may carry forward her family psychic abilities and emotional family depth while needing to heal patterns of family confusion or difficulty with family boundaries. The karmic gift involves natural family intuitive understanding and the challenge involves learning clear family discernment.",
    positive: "Inherited family psychic sensitivity and intuitive understanding that helps you navigate complex family emotional territory and provide family guidance for others seeking deeper family understanding. Your mother's mystical nature gives you access to family wisdom and insights that come from beyond rational thinking about family. You have natural family counseling abilities and the gift of helping family members understand their unconscious family patterns and family spiritual journey.",
    challenge: "May carry patterns of family emotional confusion, poor family boundaries, or difficulty distinguishing between family intuition and family projection that stem from your mother's unresolved relationship with family psychic sensitivity and practical family reality. Tendency to become overwhelmed by family members' emotions or lost in family fantasy rather than engaging with concrete family circumstances. Can struggle with clear family communication or taking practical family action based on intuitive family insights.",
    advice: "Honor the family intuitive and mystical abilities from your mother's lineage while developing clear family boundaries and practical family discernment that helps you use family psychic gifts effectively. Practice grounding family intuitive insights in concrete family action and clear family communication. Transform inherited patterns of family confusion into conscious family psychic ability that serves family clarity and family healing."
  },
  19: {
    general: "Your mother's karma involves themes of family joy, maternal radiance, and celebrating family success and happiness, creating patterns around family achievement and family recognition in your family line. Her karmic lessons may involve learning to share family success generously and find family satisfaction in inner rather than just external family validation. You may carry forward her family confidence and positive family energy while needing to heal patterns of family narcissism or difficulty with family failure. The karmic gift involves natural family charisma and family success abilities and the challenge involves learning humble family achievement.",
    positive: "Inherited family confidence and positive family energy that helps you achieve family success and inspire family members to believe in their own potential for family happiness and family accomplishment. Your mother's radiant family nature gives you natural family charisma and the ability to attract family opportunities and supportive family relationships. You have natural family leadership abilities and the gift of helping family members celebrate their family achievements and find family joy in life.",
    challenge: "May carry patterns of family narcissism, need for constant family admiration, or difficulty handling family failure that stem from your mother's unresolved relationship with family ego and authentic family self-worth. Tendency to measure family worth through external family success or become depressed when not receiving adequate family recognition. Can struggle with sharing family spotlight or supporting family members' success when it might overshadow your own family achievements.",
    advice: "Honor the family confidence and family success abilities from your mother's lineage while developing genuine family humility and inner sources of family satisfaction that don't depend entirely on external family recognition. Practice using family success to serve family members rather than just personal family ego gratification. Transform inherited patterns of family narcissistic achievement into authentic family success that includes and celebrates family members' accomplishments."
  },
  20: {
    general: "Your mother's karma involves themes of family spiritual calling, maternal awakening, and service to family collective evolution, creating patterns around family purpose and family spiritual responsibility in your family line. Her karmic lessons may involve learning to balance individual family needs with family collective service and finding practical ways to serve family spiritual evolution. You may carry forward her family spiritual awareness and sense of family purpose while needing to heal patterns of family spiritual superiority or difficulty with family personal boundaries. The karmic gift involves natural family spiritual authority and the challenge involves learning balanced family service.",
    positive: "Inherited family spiritual awareness and sense of higher family purpose that helps you recognize your family calling and inspire family members to pursue their own family spiritual development and family service. Your mother's awakened family nature gives you natural family spiritual authority and the ability to guide family members through important family transitions. You have natural family teaching abilities and the gift of helping family members understand their family spiritual purpose and family contribution.",
    challenge: "May carry patterns of family spiritual grandiosity, neglect of family personal needs, or difficulty with ordinary family human concerns that stem from your mother's unresolved relationship with family spiritual identity and family earthly responsibility. Tendency to sacrifice family personal relationships and family self-care for family spiritual service. Can struggle with family spiritual superiority or difficulty relating to family people who don't share your family spiritual interests.",
    advice: "Honor the family spiritual awareness and sense of family purpose from your mother's lineage while maintaining healthy family boundaries and attention to family personal needs and family relationships. Practice serving family spiritual evolution while remaining grounded in family human compassion and practical family responsibility. Transform inherited patterns of family spiritual superiority into humble family service that includes rather than transcends ordinary family human experience."
  },
  21: {
    general: "Your mother's karma involves themes of family completion, maternal mastery, and integrated family achievement, creating patterns around family success and family fulfillment in your family line. Her karmic lessons may involve learning to appreciate family achievements while remaining open to continued family growth and sharing family success with family members. You may carry forward her family mastery and family accomplishment abilities while needing to heal patterns of family complacency or difficulty with new family challenges. The karmic gift involves natural family mastery abilities and the challenge involves learning continued family growth.",
    positive: "Inherited ability to achieve family mastery and create lasting family accomplishments that serve as family examples for others seeking their own family fulfillment and family success. Your mother's accomplished family nature gives you the family persistence and family skill to complete important family projects and family goals. You have natural family teaching abilities and the gift of helping family members understand what authentic family achievement and family satisfaction look like in family practice.",
    challenge: "May carry patterns of family complacency, resting on past family achievements, or difficulty with new family learning that stem from your mother's unresolved relationship with continued family growth and family beginner's mind. Tendency to judge family members' efforts or become disconnected from the family learning process. Can struggle with maintaining family motivation when you've already achieved significant family success in particular family areas.",
    advice: "Honor the family mastery and family achievement abilities from your mother's lineage while remaining open to continued family learning and family growth in new areas of family life and family service. Practice using your family accomplishments to support family members' development rather than setting yourself apart from family. Transform inherited patterns of family complacency into wise family mastery that continues to evolve and serve family members' growth and family learning."
  },
  22: {
    general: "Your mother's karma involves themes of family innocence, unlimited family potential, and fresh family perspective, creating patterns around family openness and family new beginnings in your family line. Her karmic lessons may involve learning to balance family openness with practical family wisdom and maintaining family wonder while developing family experience. You may carry forward her family spontaneity and unlimited family potential while needing to heal patterns of family naivety or difficulty with sustained family effort. The karmic gift involves natural family openness and family potential and the challenge involves learning practical family wisdom.",
    positive: "Inherited family openness and fresh family perspective that helps you approach family life with family wonder and discover new family possibilities that family members might miss through family preconceptions. Your mother's spontaneous family nature gives you the family freedom to explore and experiment without being limited by past family experience. You have natural family creativity and the gift of helping family members maintain family beginner's mind and family openness to family growth.",
    challenge: "May carry patterns of family naivety, difficulty with family commitment, or tendency to abandon family projects when they become challenging that stem from your mother's unresolved relationship with family responsibility and sustained family effort. Tendency to avoid developing family depth or family expertise in favor of constant family exploration. Can struggle with practical family follow-through or learning from family members' experience and family wisdom.",
    advice: "Honor the family openness and fresh family perspective from your mother's lineage while developing practical family wisdom and the ability to commit to sustained family development in family areas that truly matter to you. Practice maintaining family wonder while also learning from family experience and family guidance. Transform inherited patterns of family spiritual or family practical immaturity into conscious family choice about when to explore family and when to deepen your family commitment and family expertise."
  }
};