/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Mom's Talents Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * the talents, gifts, and wisdom inherited through the maternal lineage,
 * including intuitive abilities, nurturing skills, and feminine wisdom.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Mom's Talents - Gifts and wisdom inherited through the maternal lineage
 */
export const momsTalentsInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Through your maternal lineage, you inherit powerful leadership abilities, pioneering spirit, and the talent for initiating new projects and ventures with confidence and determination. Your mother's line carries the energy of women who were trailblazers, entrepreneurs, and strong independent figures who created their own paths in life. This maternal inheritance gives you natural authority, creative manifestation abilities, and the courage to start new endeavors even when others doubt your vision.",
    positive: "Strong maternal inheritance of leadership qualities, entrepreneurial spirit, and the ability to manifest your ideas into reality through sheer determination and creative will. Your mother's lineage provides you with natural confidence, pioneering abilities, and the talent for inspiring others to follow your vision. You have inherited the maternal gift of being able to create something from nothing and the courage to take risks that others might find too daunting.",
    challenge: "May inherit maternal patterns of being overly independent, difficulty asking for help, or tendency to take on too much responsibility without sharing the load with others. Your maternal line may carry patterns of women who had to be strong all the time, creating challenges around vulnerability or accepting support. There may be inherited pressure to always be the leader or initiator, even when collaboration or following others would be more beneficial.",
    advice: "Honor your inherited maternal leadership gifts while also learning to collaborate and share responsibilities with others rather than carrying everything alone as some maternal figures may have done. Use your natural pioneering abilities to create positive change while also developing the ability to be vulnerable and ask for support when needed. Balance your strong maternal inheritance of independence with healthy interdependence and partnership."
  },
  2: {
    general: "Your maternal lineage carries deep intuitive wisdom, psychic abilities, and the talent for understanding hidden emotions and unspoken needs in yourself and others. The women in your mother's line were often the emotional healers, intuitive counselors, and keepers of family secrets who could sense what others needed before they asked. This maternal inheritance provides you with natural empathy, psychic sensitivity, and the ability to create safe emotional spaces for others to heal and grow.",
    positive: "Profound maternal inheritance of intuitive gifts, emotional intelligence, and the ability to sense what others need for healing and emotional support. Your mother's lineage provides you with natural psychic abilities, deep empathy, and the talent for creating emotionally safe spaces where others feel understood and accepted. You have inherited the maternal gift of emotional healing and the ability to hold space for others' emotional processing and growth.",
    challenge: "May inherit maternal patterns of being overly sensitive to others' emotions, taking on family pain, or difficulty maintaining emotional boundaries between yourself and others. Your maternal line may carry patterns of women who absorbed everyone else's emotional burdens, creating challenges around emotional overwhelm or difficulty distinguishing your feelings from others'. There may be inherited tendencies to give away emotional energy without ensuring your own emotional needs are met.",
    advice: "Trust and develop your inherited maternal intuitive gifts while also learning to maintain healthy emotional boundaries that protect your own well-being and energy. Use your natural empathy and healing abilities to help others while also ensuring that you receive the emotional support and care you need. Balance your maternal inheritance of emotional sensitivity with practical skills for managing your own emotional health and energy."
  },
  3: {
    general: "Through your maternal lineage, you inherit abundant creative talents, nurturing abilities, and the gift for manifesting beauty, fertility, and prosperity in all areas of life. The women in your mother's line were often the creators, artists, gardeners, and abundance-makers who knew how to bring forth life and beauty wherever they went. This maternal inheritance provides you with natural creativity, generosity, and the ability to nurture growth and development in yourself and others.",
    positive: "Rich maternal inheritance of creative abilities, nurturing talents, and the gift for manifesting abundance and beauty in your environment and relationships. Your mother's lineage provides you with natural fertility (creative and literal), artistic abilities, and the talent for making others feel cared for and appreciated. You have inherited the maternal gift of abundance creation and the ability to help others recognize and develop their own potential.",
    challenge: "May inherit maternal patterns of over-giving, difficulty receiving care from others, or tendency to deplete yourself while caring for everyone else's needs and growth. Your maternal line may carry patterns of women who gave so much to others that they neglected their own needs, creating challenges around self-care or accepting help. There may be inherited patterns of feeling responsible for everyone's happiness and well-being at the expense of your own fulfillment.",
    advice: "Honor your inherited maternal nurturing and creative gifts while also learning to receive care and support from others rather than always being the one who gives and creates for everyone else. Use your natural abundance and manifestation abilities to create prosperity that includes your own needs and desires, not just others'. Balance your maternal inheritance of generosity with healthy boundaries and self-care that allows you to give sustainably over time."
  },
  4: {
    general: "Your maternal lineage carries the talents for organization, practical management, and the ability to create stable, secure foundations that support family and community growth over generations. The women in your mother's line were often the builders, organizers, and practical managers who created the systems and structures that kept families and communities functioning smoothly. This maternal inheritance provides you with natural organizational abilities, practical wisdom, and the talent for creating lasting security and stability.",
    positive: "Strong maternal inheritance of organizational talents, practical management skills, and the ability to create stable foundations that support long-term growth and security. Your mother's lineage provides you with natural abilities for planning, resource management, and creating systems that work efficiently and reliably. You have inherited the maternal gift of practical wisdom and the ability to build things that last and serve others' needs effectively.",
    challenge: "May inherit maternal patterns of being overly controlling, resistant to change, or tendency to prioritize security and stability over creativity and spontaneity. Your maternal line may carry patterns of women who became rigid in their structures or fearful of change, creating challenges around flexibility or adapting to new circumstances. There may be inherited pressure to maintain traditional roles or methods even when innovation would be beneficial.",
    advice: "Use your inherited maternal organizational and practical gifts while also remaining open to new approaches and changes that can improve existing systems and structures. Honor the stability and security your maternal lineage created while also allowing for growth, evolution, and adaptation to changing circumstances. Balance your maternal inheritance of practical wisdom with openness to innovation and creative solutions."
  },
  5: {
    general: "Through your maternal lineage, you inherit wisdom, teaching abilities, and the talent for guiding others through spiritual and moral development with patience and traditional knowledge. The women in your mother's line were often the teachers, wisdom keepers, and moral guides who passed down important values, traditions, and spiritual understanding to future generations. This maternal inheritance provides you with natural teaching abilities, moral clarity, and the gift for helping others find their path of growth and spiritual development.",
    positive: "Deep maternal inheritance of wisdom, teaching talents, and the ability to guide others through their spiritual and personal development with patience and understanding. Your mother's lineage provides you with natural knowledge of traditional wisdom, moral principles, and the talent for sharing knowledge in ways that others can understand and apply. You have inherited the maternal gift of spiritual guidance and the ability to help others connect with their higher purpose and values.",
    challenge: "May inherit maternal patterns of being judgmental, overly traditional, or tendency to impose values and beliefs on others rather than allowing them to find their own authentic path. Your maternal line may carry patterns of women who became rigid in their beliefs or dogmatic about spiritual practices, creating challenges around accepting different approaches. There may be inherited patterns of feeling responsible for others' spiritual development or moral choices.",
    advice: "Honor your inherited maternal wisdom and teaching gifts while also respecting others' individual spiritual journeys and allowing them to find their own authentic path of growth. Use your natural knowledge and guidance abilities to support others while also remaining open to learning from different perspectives and approaches. Balance your maternal inheritance of traditional wisdom with acceptance of diverse spiritual paths and modern understanding."
  },
  6: {
    general: "Your maternal lineage carries the talents for creating harmony, beauty, and loving relationships, with gifts for diplomacy, aesthetic creation, and bringing people together in peaceful, cooperative ways. The women in your mother's line were often the peacemakers, artists, and relationship builders who knew how to create beauty and resolve conflicts through love and understanding. This maternal inheritance provides you with natural diplomatic abilities, aesthetic sense, and the talent for creating harmonious environments and relationships.",
    positive: "Graceful maternal inheritance of diplomatic talents, aesthetic abilities, and the gift for creating beautiful, harmonious relationships and environments that bring out the best in everyone involved. Your mother's lineage provides you with natural abilities for conflict resolution, artistic expression, and creating partnerships that feel balanced and mutually supportive. You have inherited the maternal gift of love and beauty creation and the ability to help others find harmony in their relationships.",
    challenge: "May inherit maternal patterns of avoiding conflict, people-pleasing, or tendency to maintain peace at the expense of authentic expression or necessary confrontation. Your maternal line may carry patterns of women who suppressed their own needs to keep others happy, creating challenges around assertiveness or standing up for your own values. There may be inherited patterns of focusing so much on others' happiness that you lose touch with your own needs and desires.",
    advice: "Use your inherited maternal diplomatic and harmony-creating gifts while also learning to express your authentic needs and engage in necessary conflicts constructively when they serve growth and truth. Honor the beauty and peace-making talents from your maternal lineage while also developing the courage to be authentic and stand up for your values when needed. Balance your maternal inheritance of harmony creation with healthy assertiveness and self-advocacy."
  },
  7: {
    general: "Through your maternal lineage, you inherit determination, courage, and the talent for overcoming obstacles and achieving goals through persistent effort and unwavering focus. The women in your mother's line were often the fighters, achievers, and determined spirits who never gave up and found ways to succeed despite challenging circumstances. This maternal inheritance provides you with natural resilience, competitive spirit, and the ability to persist through difficulties that would discourage others.",
    positive: "Powerful maternal inheritance of determination, courage, and the ability to overcome obstacles and achieve ambitious goals through persistent effort and strategic action. Your mother's lineage provides you with natural resilience, competitive abilities, and the talent for maintaining focus and motivation even during challenging times. You have inherited the maternal gift of never giving up and the ability to inspire others to persist through their own challenges and setbacks.",
    challenge: "May inherit maternal patterns of being overly competitive, impatient with slower progress, or tendency to push too hard without allowing for rest and recovery. Your maternal line may carry patterns of women who had to fight constantly for survival or success, creating challenges around relaxation or trusting that things can be easy. There may be inherited patterns of viewing life as a constant battle or struggle rather than recognizing opportunities for ease and flow.",
    advice: "Channel your inherited maternal determination and courage into purposeful goals while also learning to balance effort with rest and allowing for natural timing and flow in your achievements. Use your natural resilience and persistence to overcome genuine obstacles while also developing the wisdom to know when to push forward and when to pause and restore your energy. Balance your maternal inheritance of fighting spirit with trust in easier paths and collaborative approaches."
  },
  8: {
    general: "Your maternal lineage carries the talents for gentle healing, emotional resilience, and the ability to transform pain into wisdom and strength through patient, compassionate presence. The women in your mother's line were often the quiet healers, emotional support providers, and wise counselors who helped others find their inner strength during difficult times. This maternal inheritance provides you with natural healing abilities, emotional intelligence, and the gift for helping others transform their challenges into growth and wisdom.",
    positive: "Deep maternal inheritance of healing talents, emotional strength, and the ability to transform suffering into wisdom and help others find their inner resilience and power. Your mother's lineage provides you with natural compassion, healing presence, and the talent for remaining centered and supportive during crisis situations. You have inherited the maternal gift of gentle strength and the ability to help others heal from emotional wounds and trauma through patient, loving support.",
    challenge: "May inherit maternal patterns of taking on others' pain, enduring difficult situations too long, or tendency to neglect your own healing needs while caring for others' emotional well-being. Your maternal line may carry patterns of women who absorbed family trauma or stayed in difficult situations longer than was healthy, creating challenges around boundaries or self-advocacy. There may be inherited patterns of believing that suffering is noble or necessary for spiritual growth.",
    advice: "Trust and develop your inherited maternal healing gifts while also maintaining healthy boundaries that protect your own emotional well-being and energy from being depleted by others' pain. Use your natural compassion and healing abilities to support others while also ensuring that you receive the healing and support you need for your own growth. Balance your maternal inheritance of emotional strength with practical skills for self-care and boundary setting."
  },
  9: {
    general: "Through your maternal lineage, you inherit deep wisdom, contemplative abilities, and the talent for understanding life's deeper meanings and helping others gain perspective on their experiences. The women in your mother's line were often the wise elders, contemplatives, and seekers who spent time in reflection and developed profound understanding of human nature and spiritual truths. This maternal inheritance provides you with natural wisdom, introspective abilities, and the gift for helping others understand the deeper patterns and meanings in their lives.",
    positive: "Profound maternal inheritance of wisdom, contemplative talents, and the ability to understand and share deep insights about life's meaning and spiritual development. Your mother's lineage provides you with natural philosophical abilities, spiritual understanding, and the talent for helping others gain perspective on their challenges and experiences. You have inherited the maternal gift of deep wisdom and the ability to guide others toward greater understanding of themselves and their life purpose.",
    challenge: "May inherit maternal patterns of over-thinking, isolation from practical concerns, or tendency to withdraw from social engagement in favor of solitary contemplation and study. Your maternal line may carry patterns of women who became too focused on spiritual or intellectual pursuits at the expense of practical life or relationships. There may be inherited patterns of feeling misunderstood or separate from others due to depth of insight or spiritual understanding.",
    advice: "Honor your inherited maternal wisdom and contemplative gifts while also maintaining engagement with practical life and relationships rather than withdrawing into isolation as some maternal figures may have done. Use your natural understanding and insight to help others while also staying connected to everyday concerns and social relationships. Balance your maternal inheritance of deep wisdom with practical application and meaningful connections with others."
  },
  10: {
    general: "Your maternal lineage carries the understanding of life's cycles, natural timing, and the talent for recognizing when to act and when to wait for better opportunities to manifest. The women in your mother's line were often attuned to natural rhythms, seasonal changes, and the larger patterns that govern life, helping family members navigate transitions and changes with wisdom and grace. This maternal inheritance provides you with natural timing abilities, cyclical awareness, and the gift for helping others understand the larger patterns influencing their lives.",
    positive: "Intuitive maternal inheritance of timing wisdom, cyclical understanding, and the ability to recognize and work with life's natural rhythms and patterns for optimal results. Your mother's lineage provides you with natural awareness of when to plant seeds, when to harvest, and when to rest, both literally and metaphorically. You have inherited the maternal gift of patience and the ability to help others understand that everything has its proper timing and season.",
    challenge: "May inherit maternal patterns of being too passive, waiting for perfect timing, or tendency to rely on fate rather than taking proactive action when circumstances require initiative. Your maternal line may carry patterns of women who became overly accepting of difficult circumstances or fatalistic about their ability to create change. There may be inherited patterns of believing that everything is predetermined rather than recognizing your power to influence outcomes.",
    advice: "Use your inherited maternal wisdom about timing and cycles while also taking proactive steps to create the changes and opportunities you desire rather than waiting passively for them to appear. Honor the natural rhythms and patience from your maternal lineage while also developing the confidence to act decisively when the time is right. Balance your maternal inheritance of cyclical wisdom with conscious choice and active participation in creating your desired outcomes."
  },
  11: {
    general: "Through your maternal lineage, you inherit strong moral principles, fairness, and the talent for making ethical decisions and helping others understand right from wrong with compassion and wisdom. The women in your mother's line were often the moral compass of the family, the fair mediators, and the ethical guides who helped resolve conflicts and ensure that justice was served. This maternal inheritance provides you with natural integrity, ethical clarity, and the gift for helping others make decisions that align with their highest values.",
    positive: "Strong maternal inheritance of ethical wisdom, fairness, and the ability to make moral decisions that serve the highest good of all involved while maintaining compassion and understanding. Your mother's lineage provides you with natural integrity, justice-seeking abilities, and the talent for helping others understand the consequences of their choices and actions. You have inherited the maternal gift of moral clarity and the ability to guide others toward ethical behavior without judgment or condemnation.",
    challenge: "May inherit maternal patterns of being overly judgmental, perfectionistic, or tendency to impose moral standards on others rather than allowing them to learn through their own experiences. Your maternal line may carry patterns of women who became rigid about right and wrong or critical of others' mistakes and imperfections. There may be inherited patterns of feeling responsible for others' moral development or becoming frustrated when others don't live up to ethical standards.",
    advice: "Honor your inherited maternal ethical wisdom and fairness while also developing compassion and forgiveness for human imperfection and the learning process that everyone must go through. Use your natural moral clarity to guide others while also allowing them the freedom to make their own choices and learn from their own experiences. Balance your maternal inheritance of justice-seeking with acceptance of human complexity and the gradual nature of moral and spiritual development."
  },
  12: {
    general: "Your maternal lineage carries the wisdom of sacrifice, surrender, and the talent for seeing situations from completely different perspectives that reveal hidden gifts and opportunities within challenges. The women in your mother's line were often the self-sacrificing figures, the mystics, and the wise ones who understood that sometimes letting go and changing perspective can transform difficult situations into blessings. This maternal inheritance provides you with natural acceptance, alternative viewpoints, and the gift for helping others find meaning and growth through difficult experiences.",
    positive: "Deep maternal inheritance of wisdom about sacrifice, surrender, and the ability to find hidden gifts and opportunities within challenging circumstances through patience and perspective shifts. Your mother's lineage provides you with natural acceptance of life's difficulties, ability to see from multiple viewpoints, and the talent for helping others find meaning and growth through their struggles. You have inherited the maternal gift of spiritual patience and the ability to transform suffering into wisdom and compassion.",
    challenge: "May inherit maternal patterns of unnecessary martyrdom, giving up too much, or tendency to accept difficult situations without exploring whether healthy changes might be possible and beneficial. Your maternal line may carry patterns of women who sacrificed their own needs and dreams excessively or became stuck in victim consciousness. There may be inherited patterns of believing that suffering is noble or that self-sacrifice automatically serves others.",
    advice: "Use your inherited maternal wisdom about patience and perspective while also ensuring that any sacrifices you make serve genuine growth and benefit rather than unconscious martyrdom that helps no one. Honor the spiritual insights from your maternal lineage while also developing practical skills for creating positive change when it's needed and possible. Balance your maternal inheritance of acceptance with healthy assertiveness and the wisdom to know when to surrender and when to take action."
  },
  13: {
    general: "Through your maternal lineage, you inherit the ability to navigate major life transitions, transformations, and rebirths with courage and wisdom gained through experiencing significant changes and losses. The women in your mother's line often faced dramatic life changes, endings, and new beginnings, developing resilience and the understanding that transformation is a natural part of life's cycle. This maternal inheritance provides you with natural adaptability, transformation skills, and the gift for helping others navigate their own periods of change and renewal.",
    positive: "Powerful maternal inheritance of transformation abilities, resilience through change, and the wisdom to help others navigate major life transitions with courage and understanding. Your mother's lineage provides you with natural comfort with endings and beginnings, ability to let go when necessary, and the talent for finding new life and opportunities through periods of loss or change. You have inherited the maternal gift of rebirth wisdom and the ability to help others see that endings often lead to better beginnings.",
    challenge: "May inherit maternal patterns of creating unnecessary drama or change, fearing stability, or tendency to end things prematurely when patience and gradual growth might be more beneficial. Your maternal line may carry patterns of women who experienced traumatic losses or changes, creating anxiety about stability or difficulty trusting that good things can last. There may be inherited patterns of expecting loss or unconsciously sabotaging stable situations.",
    advice: "Use your inherited maternal transformation wisdom to navigate necessary changes while also building stable foundations that can support you through periods of transition and growth. Honor the resilience and adaptability from your maternal lineage while also developing the ability to appreciate and maintain stability when it serves your highest good. Balance your maternal inheritance of change navigation with the capacity to create and enjoy lasting security and continuity."
  },
  14: {
    general: "Your maternal lineage carries the talents for healing, balance, and the ability to integrate different aspects of life into harmonious wholes that serve everyone's highest good. The women in your mother's line were often the healers, mediators, and wise counselors who knew how to bring opposing forces together and create solutions that honored all perspectives. This maternal inheritance provides you with natural healing abilities, integration skills, and the gift for helping others find balance and wholeness in their lives.",
    positive: "Graceful maternal inheritance of healing talents, integration abilities, and the gift for creating balance and harmony that honors all aspects of complex situations and relationships. Your mother's lineage provides you with natural moderation skills, healing presence, and the talent for helping others integrate their different needs and desires into coherent, satisfying wholes. You have inherited the maternal gift of healing wisdom and the ability to help others find sustainable solutions that serve multiple needs simultaneously.",
    challenge: "May inherit maternal patterns of avoiding necessary extremes, over-compromising, or tendency to seek balance even when passionate intensity or decisive action would be more appropriate and effective. Your maternal line may carry patterns of women who avoided conflict or strong positions, creating challenges around assertiveness or taking stands when they're needed. There may be inherited patterns of suppressing strong emotions or desires in favor of maintaining equilibrium.",
    advice: "Honor your inherited maternal healing and integration gifts while also developing the ability to embrace passionate intensity and take strong positions when they serve growth and positive change. Use your natural balance and moderation abilities to create sustainable solutions while also allowing for the full range of human emotion and experience. Balance your maternal inheritance of harmony-seeking with the courage to engage in necessary conflicts and the willingness to take decisive action when moderation isn't sufficient."
  },
  15: {
    general: "Through your maternal lineage, you inherit understanding of material power, human psychology, and the ability to work with the shadow aspects of human nature including desires, temptations, and the use of personal magnetism and influence. The women in your mother's line often understood the power of sexuality, material resources, and psychological influence, sometimes using these gifts wisely and sometimes struggling with their potential for both creation and destruction. This maternal inheritance provides you with natural magnetism, psychological insight, and the ability to understand and work with human desires and motivations.",
    positive: "Powerful maternal inheritance of magnetism, psychological understanding, and the ability to work with material and sexual energy consciously for positive purposes and beneficial influence. Your mother's lineage provides you with natural charisma, understanding of human motivation, and the talent for using your personal power and influence to create positive change and abundance. You have inherited the maternal gift of understanding human psychology and the ability to work with desires and material forces ethically and effectively.",
    challenge: "May inherit maternal patterns around manipulation, using sexuality or material resources inappropriately, or tendency to become obsessed with power, control, or material accumulation at the expense of spiritual development. Your maternal line may carry patterns of women who struggled with addiction, codependency, or unhealthy relationships with power and sexuality. There may be inherited trauma around abuse of power or being victimized by others' misuse of influence and control.",
    advice: "Use your inherited maternal understanding of psychology and material power ethically and consciously for positive purposes while healing any patterns of manipulation or abuse that may exist in your lineage. Honor the magnetism and influence abilities from your maternal lineage while also developing strong ethical principles about how to use these gifts responsibly. Balance your maternal inheritance of psychological insight with spiritual values and the commitment to use your power in service of others' highest good as well as your own."
  },
  16: {
    general: "Your maternal lineage carries the ability to navigate sudden changes, revelations, and breakthrough moments that shatter old patterns and create opportunities for dramatic positive transformation. The women in your mother's line often experienced sudden upheavals, insights, or revelations that completely changed their understanding and life direction, developing the resilience and wisdom to rebuild quickly from unexpected changes. This maternal inheritance provides you with adaptability, breakthrough insights, and the gift for helping others navigate sudden changes and revelations with courage and wisdom.",
    positive: "Dynamic maternal inheritance of adaptability, breakthrough wisdom, and the ability to quickly recover from unexpected changes while finding new opportunities and insights within disruptions. Your mother's lineage provides you with natural resilience during crisis, ability to see new possibilities when old structures collapse, and the talent for helping others find their footing during sudden changes. You have inherited the maternal gift of rapid adaptation and the ability to help others transform crisis into opportunity.",
    challenge: "May inherit maternal patterns of creating unnecessary drama or crisis, expecting sudden disruptions, or tendency to make dramatic changes when gradual adjustment would be more effective and less destabilizing. Your maternal line may carry patterns of women who experienced traumatic sudden changes, creating anxiety about stability or unconscious patterns of sabotaging security when life becomes too peaceful. There may be inherited patterns of crisis addiction or difficulty maintaining steady progress and growth.",
    advice: "Use your inherited maternal adaptability and crisis navigation skills to handle necessary changes while also building stable foundations that can weather unexpected storms without being completely destroyed. Honor the resilience and breakthrough abilities from your maternal lineage while also developing the capacity to create and maintain steady progress and security. Balance your maternal inheritance of change navigation with the ability to appreciate and protect stability when it serves your growth and well-being."
  },
  17: {
    general: "Through your maternal lineage, you inherit hope, inspiration, and the talent for maintaining faith and optimism even during difficult times while helping others connect with their highest potential and spiritual purpose. The women in your mother's line were often the visionaries, hope-bringers, and spiritual guides who maintained faith in better possibilities and inspired others to keep going when circumstances seemed impossible. This maternal inheritance provides you with natural optimism, inspirational abilities, and the gift for helping others connect with their dreams and spiritual guidance.",
    positive: "Radiant maternal inheritance of hope, inspiration, and the ability to maintain faith in positive possibilities while helping others connect with their highest potential and spiritual guidance. Your mother's lineage provides you with natural optimism, visionary abilities, and the talent for inspiring others to believe in themselves and their dreams even during challenging times. You have inherited the maternal gift of spiritual inspiration and the ability to help others access guidance and hope from higher sources.",
    challenge: "May inherit maternal patterns of unrealistic optimism, avoiding practical concerns, or tendency to focus on future possibilities without taking adequate action in the present moment to manifest dreams and visions. Your maternal line may carry patterns of women who became disconnected from practical reality or disappointed when their idealistic expectations weren't met. There may be inherited patterns of spiritual bypassing or avoiding material concerns in favor of focusing only on higher realms.",
    advice: "Honor your inherited maternal hope and inspirational gifts while also developing practical skills and realistic planning that can help manifest your visions and dreams in the material world. Use your natural optimism and spiritual connection to inspire others while also attending to practical details and taking concrete action toward your goals. Balance your maternal inheritance of spiritual inspiration with grounded action and realistic assessment of what's required to create positive change."
  },
  18: {
    general: "Your maternal lineage carries deep connection to dreams, intuition, and the ability to navigate the unconscious realms and hidden aspects of life with wisdom and psychic sensitivity. The women in your mother's line were often the dreamers, psychics, and intuitives who served as bridges between conscious and unconscious realities, helping family members understand hidden dynamics and navigate emotional or spiritual mysteries. This maternal inheritance provides you with natural psychic abilities, dream wisdom, and the gift for understanding hidden or unconscious patterns that influence behavior and circumstances.",
    positive: "Profound maternal inheritance of psychic abilities, dream wisdom, and the talent for understanding and navigating hidden or unconscious aspects of life that others may not perceive or understand. Your mother's lineage provides you with natural intuitive gifts, connection to dream guidance, and the ability to help others understand the hidden emotional or spiritual dynamics influencing their lives. You have inherited the maternal gift of psychic insight and the ability to bridge conscious and unconscious realms for healing and understanding.",
    challenge: "May inherit maternal patterns of confusion between intuition and fantasy, difficulty distinguishing between genuine psychic information and emotional projection, or tendency to become lost in unconscious realms without adequate grounding. Your maternal line may carry patterns of women who struggled with mental health issues, addiction, or difficulty maintaining boundaries between their inner world and external reality. There may be inherited patterns of avoiding practical responsibility in favor of focusing only on spiritual or psychic matters.",
    advice: "Trust and develop your inherited maternal psychic and intuitive gifts while also maintaining clear boundaries between genuine spiritual guidance and emotional confusion or wishful thinking. Use your natural connection to dreams and unconscious wisdom to help others while also staying grounded in practical reality and daily responsibilities. Balance your maternal inheritance of psychic sensitivity with practical discernment and the ability to translate spiritual insights into helpful action in the material world."
  },
  19: {
    general: "Through your maternal lineage, you inherit joy, natural magnetism, and the talent for creating celebration, success, and positive energy that attracts abundance and opportunities for yourself and others. The women in your mother's line were often the celebrators, successful achievers, and naturally charismatic figures who knew how to create joy and attract success through positive energy and genuine enthusiasm. This maternal inheritance provides you with natural magnetism, celebratory abilities, and the gift for helping others recognize and develop their own success potential and natural joy.",
    positive: "Radiant maternal inheritance of joy, magnetism, and the ability to create success and celebration that attracts abundance and positive opportunities for yourself and others around you. Your mother's lineage provides you with natural charisma, success-attracting abilities, and the talent for inspiring others to recognize their own potential and celebrate their achievements. You have inherited the maternal gift of joyful manifestation and the ability to help others connect with their natural enthusiasm and success potential.",
    challenge: "May inherit maternal patterns of needing to always be positive, avoiding shadow work or difficult emotions, or tendency to maintain success and joy at the expense of authentic emotional expression and growth. Your maternal line may carry patterns of women who felt pressure to be perfect or successful, creating challenges around showing vulnerability or dealing with failure. There may be inherited patterns of taking success for granted or becoming superficial in relationships and personal development.",
    advice: "Honor your inherited maternal joy and success-creating gifts while also allowing space for authentic emotional expression and the full range of human experience including challenges and growth opportunities. Use your natural magnetism and celebration abilities to create genuine success while also developing the depth and authenticity that come from embracing both light and shadow aspects of life. Balance your maternal inheritance of positive energy with real emotional intelligence and the ability to support others through both their successes and their struggles."
  },
  20: {
    general: "Your maternal lineage carries the calling to spiritual awakening, higher purpose, and the ability to answer deep soul missions that serve both personal growth and collective healing and transformation. The women in your mother's line often experienced profound spiritual awakenings, life-changing revelations, or callings to serve purposes larger than personal interest, developing wisdom about integrating spiritual purpose with practical life. This maternal inheritance provides you with spiritual sensitivity, mission awareness, and the gift for helping others discover and answer their own soul calling.",
    positive: "Profound maternal inheritance of spiritual awakening abilities, soul mission awareness, and the talent for helping others discover and answer their highest calling while integrating spiritual purpose with practical life. Your mother's lineage provides you with natural connection to higher guidance, understanding of life purpose, and the ability to inspire others to live according to their deepest values and spiritual mission. You have inherited the maternal gift of spiritual calling and the ability to help others transform their lives through connection to higher purpose.",
    challenge: "May inherit maternal patterns of feeling overwhelmed by spiritual responsibility, struggling to integrate spiritual mission with practical needs, or tendency to sacrifice personal happiness for spiritual service. Your maternal line may carry patterns of women who became disconnected from practical life or personal relationships in pursuit of spiritual goals. There may be inherited patterns of feeling burdened by spiritual gifts or responsible for others' spiritual development.",
    advice: "Honor your inherited maternal spiritual sensitivity and mission awareness while also maintaining balance with practical life, personal needs, and healthy relationships that support your overall well-being. Use your natural connection to higher purpose to serve others while also ensuring that your spiritual service enhances rather than detracts from your personal happiness and fulfillment. Balance your maternal inheritance of spiritual calling with practical wisdom about sustainable service and the importance of caring for yourself while caring for others."
  },
  21: {
    general: "Through your maternal lineage, you inherit mastery, completion abilities, and the talent for achieving fulfillment and success that serves not only personal goals but also benefits others and contributes to lasting positive change. The women in your mother's line were often the achievers, masters, and wise elders who understood how to bring projects and relationships to successful completion while creating something meaningful that would benefit future generations. This maternal inheritance provides you with natural mastery abilities, completion skills, and the gift for helping others achieve their own fulfillment and success.",
    positive: "Masterful maternal inheritance of achievement abilities, completion skills, and the talent for creating fulfillment and success that serves multiple purposes and benefits others as well as yourself. Your mother's lineage provides you with natural wisdom about how to achieve lasting success, complete important projects, and create contributions that will benefit future generations. You have inherited the maternal gift of mastery and the ability to help others achieve their own highest potential and most meaningful goals.",
    challenge: "May inherit maternal patterns of perfectionism, pressure to achieve, or tendency to rest on accomplishments without continuing to grow and evolve in new directions. Your maternal line may carry patterns of women who became defined by their achievements or felt pressure to maintain success and reputation at the expense of personal exploration and continued learning. There may be inherited patterns of fear of failure or difficulty with taking risks that might threaten established success.",
    advice: "Honor your inherited maternal mastery and achievement abilities while also maintaining openness to continued growth, learning, and new challenges that expand your capabilities and understanding. Use your natural completion skills and success potential to create meaningful contributions while also allowing yourself the freedom to explore new directions and take risks that serve your personal evolution. Balance your maternal inheritance of mastery with curiosity and willingness to be a beginner in new areas that interest and challenge you."
  },
  22: {
    general: "Your maternal lineage carries the energy of new beginnings, unlimited potential, and the talent for approaching life with fresh perspective and innocent wisdom that sees possibilities others might miss. The women in your mother's line were often the innovators, fresh-start creators, and optimistic spirits who believed in unlimited potential and weren't limited by conventional thinking about what was possible. This maternal inheritance provides you with natural openness, beginner's mind abilities, and the gift for helping others see new possibilities and start fresh when needed.",
    positive: "Fresh maternal inheritance of unlimited potential, innovative thinking, and the ability to approach situations with beginner's mind that reveals new possibilities and creative solutions. Your mother's lineage provides you with natural optimism about what's possible, willingness to try new approaches, and the talent for inspiring others to break free from limiting beliefs and explore new directions. You have inherited the maternal gift of fresh perspective and the ability to help others start over with hope and unlimited potential.",
    challenge: "May inherit maternal patterns of naivety about practical realities, tendency to start over repeatedly without building on previous experience, or difficulty with commitment and following through on long-term projects and relationships. Your maternal line may carry patterns of women who avoided responsibility or commitment in favor of maintaining freedom and options. There may be inherited patterns of impulsiveness or difficulty learning from past mistakes and experience.",
    advice: "Honor your inherited maternal openness and fresh perspective abilities while also developing practical wisdom and the ability to build on previous experience rather than starting over completely each time you face challenges. Use your natural optimism and innovative thinking to create positive change while also developing the patience and commitment needed to see projects and relationships through to meaningful completion. Balance your maternal inheritance of unlimited potential with practical skills and the wisdom to learn from both your own and others' experience."
  }
};