/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Past Life Income Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * your relationship with money through past life patterns, karmic influences,
 * and inherited beliefs about wealth and abundance.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Past Life Income - How past life patterns affect your money mindset
 */
export const pastLifeIncomeInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Past life experiences as a leader, innovator, or pioneer strongly influence your current confidence and approach to generating wealth through personal initiative and entrepreneurial ventures. You carry cellular memories of being responsible for others' survival and prosperity, which creates both natural authority around money matters and potential burden from feeling responsible for everyone's financial well-being. Your soul remembers times when your personal power and decision-making directly determined the material success or failure of entire communities or organizations.",
    positive: "Strong innate ability to manifest wealth through personal power, leadership, and innovative thinking that draws from lifetimes of successful entrepreneurial and leadership experience. You have natural confidence in your ability to create something from nothing and intuitively understand how to motivate others and organize resources for maximum impact. Your past life mastery of material manifestation gives you an edge in business ventures and the ability to inspire confidence in investors and partners.",
    challenge: "May carry past trauma around the heavy responsibility of leadership and the weight of others' financial dependence on your decisions and abilities. Tendency to take on too much responsibility for others' financial well-being or to isolate yourself from collaborative financial opportunities due to memories of being betrayed or let down by partners or followers. Can struggle with guilt around personal wealth accumulation, feeling that having more than others is somehow wrong or dangerous.",
    advice: "Trust your natural ability to create wealth through initiative and leadership while learning to share both responsibility and rewards with others rather than carrying everything alone. Heal past wounds around leadership betrayal by carefully choosing trustworthy partners and collaborators who share your values and vision. Use your natural leadership abilities to create wealth that benefits not just yourself but also provides opportunities and prosperity for others in ethical, sustainable ways."
  },
  2: {
    general: "Past life connections to mystical traditions, healing arts, and spiritual service create a complex relationship with money that often involves tension between material needs and spiritual values. You carry memories of lifetimes spent in religious or healing roles where material wealth was discouraged or where you were supported by others while focusing on spiritual or service work. Your soul remembers the power of intuitive guidance and energy exchange, but may struggle with practical monetization of these gifts in the modern world.",
    positive: "Intuitive understanding of energy exchange, spiritual abundance principles, and the ability to generate income through healing, counseling, or spiritual guidance work. You have natural psychic abilities that can guide financial decisions and investments, often sensing opportunities or dangers that others miss. Your past life experience with sacred economics gives you unique insights into how money can flow in alignment with spiritual principles and service to others.",
    challenge: "May undervalue spiritual gifts or struggle with practical aspects of monetizing intuitive abilities, carrying unconscious beliefs that spiritual work should be free or that charging money corrupts sacred gifts. Difficulty with aggressive marketing or business practices, preferring to trust that right people will find you rather than actively promoting your services. Can struggle with the material world's demands and practical money management, preferring to focus on spiritual rather than financial matters.",
    advice: "Honor both spiritual and material needs in your financial life, recognizing that being adequately compensated for spiritual services allows you to help more people and live in integrity. Develop practical business skills while maintaining your spiritual values, finding ways to market your gifts that feel authentic and aligned with your soul's purpose. Create sustainable income streams that support your spiritual work rather than competing with it, understanding that material security can enhance rather than diminish your spiritual service."
  },
  3: {
    general: "Past life abundance through creativity, fertility, and nurturing roles creates a natural expectation that resources should flow easily and generously, but also patterns of giving too much away or struggling with scarcity when generosity isn't reciprocated. You carry cellular memories of times when your creative gifts and nurturing abilities brought prosperity to entire communities, making you naturally generous but sometimes naive about others' motivations. Your soul remembers the satisfaction of creating abundance through love and creative expression, but may struggle with boundaries around your generosity.",
    positive: "Natural ability to attract resources through creative and caring work, with an innate understanding of how to manifest abundance through beauty, creativity, and service to others. You have the gift of seeing potential and helping others develop their talents and resources, often becoming a catalyst for others' prosperity and success. Your generous nature and creative abilities naturally attract people and opportunities that can lead to financial abundance when properly channeled.",
    challenge: "May give away too much of your time, money, or creative work for free, especially to family and friends who expect your continued generosity without reciprocation. Tendency to struggle with scarcity consciousness from past lives involving famines, wars, or periods when your generosity was taken advantage of by others. Can have difficulty charging appropriately for creative work or setting boundaries with people who want to benefit from your abundance without contributing their fair share.",
    advice: "Balance your natural generosity with healthy financial boundaries that protect your ability to continue creating and giving sustainably over the long term. Learn to distinguish between worthy recipients of your generosity and people who are taking advantage of your giving nature without appreciation or reciprocity. Create systems that allow you to give generously while also building your own financial security, understanding that taking care of yourself enables you to help others more effectively."
  },
  4: {
    general: "Past life experiences in positions of authority, management, or stewardship of resources create strong patterns around financial responsibility, conservative money management, and the need to build lasting security for future generations. You carry memories of being trusted with others' wealth and resources, which creates both natural ability to build and manage wealth and potential anxiety about financial responsibility and loss. Your soul remembers the satisfaction of creating structures and systems that provided long-term security, but may struggle with rigidity or over-caution in current financial decisions.",
    positive: "Strong foundation for building lasting wealth through disciplined saving, conservative investing, and systematic approaches to financial planning and wealth accumulation. You have natural talent for managing resources efficiently and creating structures that protect and grow wealth over time. Your past life experience with financial stewardship gives you wisdom about long-term thinking and the importance of building solid foundations before taking risks.",
    challenge: "May be overly cautious or rigid in financial decisions due to past life memories of being held responsible for others' financial losses or failures. Tendency to miss profitable opportunities because of excessive need for security and predictability, preferring familiar methods even when better options are available. Can struggle with guilt or anxiety around money decisions, feeling the weight of responsibility for financial outcomes even when others are involved in the decision-making process.",
    advice: "Build on your natural stability and conservative financial wisdom while gradually expanding your comfort zone to include calculated risks that could enhance your wealth-building efforts. Use your gift for systematic thinking to research new opportunities thoroughly before making changes, allowing you to adapt while maintaining your security-focused approach. Trust your natural ability to create lasting wealth while also remaining open to innovative strategies that align with your values and risk tolerance."
  },
  5: {
    general: "Past life experiences in religious, teaching, or traditional authority roles create complex beliefs about money, often involving tensions between spiritual service and material needs or between traditional values and modern financial opportunities. You carry memories of lifetimes where financial support came through institutional channels or community support rather than individual entrepreneurship. Your soul remembers the dignity and purpose of serving higher ideals, but may struggle with integrating spiritual values with practical financial success in the modern world.",
    positive: "Understanding that money can serve higher purposes and support spiritual growth, education, and service to others rather than just personal gratification or material accumulation. You have natural wisdom about ethical financial behavior and the importance of using wealth responsibly to benefit society and support meaningful causes. Your past life experience with institutional resources gives you insights into how money can flow in service of larger purposes and community benefit.",
    challenge: "May carry unconscious vows of poverty or beliefs that money is inherently unspiritual, creating internal conflict between material success and spiritual integrity. Tendency to be overly dependent on others or institutions for financial security rather than developing independent wealth-building skills and confidence. Can struggle with practical aspects of money management or business development, preferring to focus on service or teaching rather than financial planning and wealth creation.",
    advice: "Recognize that money is a tool that can be used to serve your highest purpose and support the causes and people you care about most deeply. Develop practical financial skills while maintaining your spiritual values, understanding that financial independence can actually enhance your ability to serve others without compromising your integrity. Create income streams that align with your values and allow you to contribute to causes you believe in while also building personal financial security."
  },
  6: {
    general: "Past life experiences in partnerships, beauty industries, or roles involving relationships and collaboration create patterns around generating wealth through partnerships, aesthetic work, and creating harmony and beauty for others. You carry memories of lifetimes where financial success came through relationships, artistic work, or creating beautiful environments and experiences. Your soul remembers the satisfaction of collaborative success and creating abundance through beauty and partnership, but may struggle with financial independence or have patterns of dependency in money matters.",
    positive: "Natural ability to create wealth through partnerships, collaborative ventures, and work that involves beauty, relationships, or creating harmony for others. You have an intuitive understanding of how to create win-win financial situations and attract partners who complement your skills and resources. Your past life experience with aesthetic and relationship-based abundance gives you unique insights into how money can flow through creating beauty and bringing people together.",
    challenge: "May be too dependent on others financially or struggle with codependent patterns in business partnerships where boundaries around money and responsibility are unclear. Tendency to make financial decisions based on emotions or desire to please others rather than practical considerations and your own financial well-being. Can struggle with self-worth issues around money, either undercharging for services or becoming overly dependent on partners' financial contributions.",
    advice: "Develop both partnership abilities and financial independence, creating collaborative opportunities while maintaining your own financial autonomy and decision-making power. Learn to value your own contributions appropriately and charge fair prices for your work, recognizing that undervaluing yourself serves no one in the long run. Choose business and financial partners carefully, ensuring that relationships are balanced and mutually beneficial rather than one-sided or codependent."
  },
  7: {
    general: "Past life experiences as a warrior, traveler, or someone who had to fight for survival and resources create a dynamic, sometimes aggressive approach to money combined with resilience and ability to overcome financial obstacles. You carry memories of lifetimes where wealth came through conquest, adventure, or overcoming significant challenges and opposition. Your soul remembers the thrill of victory and the satisfaction of earning wealth through courage and determination, but may also carry trauma around financial battles or losses that required starting over repeatedly.",
    positive: "Natural ability to overcome financial obstacles and recover from setbacks, with the courage and determination to pursue opportunities that others might find too risky or challenging. You have warrior-like persistence in building wealth and the ability to adapt quickly to changing financial circumstances or market conditions. Your past life experience with financial battles gives you resilience and strategic thinking that can be very valuable in competitive business environments.",
    challenge: "May have battle scars around money or tendency toward financial extremes, either accumulating wealth aggressively or engaging in financial risk-taking that threatens your security. Tendency to approach money matters as battles to be won rather than collaborative opportunities for mutual benefit, potentially creating unnecessary conflict or competition. Can struggle with financial partnerships or sharing resources, preferring to maintain complete control over your financial destiny.",
    advice: "Channel your warrior spirit and determination into consistent, strategic wealth-building approaches rather than relying solely on high-risk, high-reward financial ventures. Learn to collaborate and share financial opportunities with others while maintaining your independence and strategic thinking abilities. Use your natural resilience and courage to build sustainable wealth over time rather than just recovering from financial setbacks repeatedly."
  },
  8: {
    general: "Past life experiences involving inner strength, healing work, or persecution for your gifts create a gentle but powerful approach to money combined with potential issues around receiving abundance or feeling worthy of material success. You carry memories of lifetimes where your healing abilities or spiritual gifts were either honored and supported by the community or feared and persecuted. Your soul remembers the power of transformation and healing, but may struggle with practical monetization of these gifts or fear of being attacked for your success.",
    positive: "Natural ability to transform financial challenges through patience, inner strength, and the power of gentle persistence rather than aggressive action or manipulation. You have healing abilities that can be monetized in various ways, and your patient approach to wealth building often leads to sustainable, long-term success. Your past life experience with overcoming adversity gives you the inner strength to persist through financial difficulties while maintaining your integrity and values.",
    challenge: "May have been persecuted for your gifts in past lives, creating fear of being too visible or successful financially, or unconscious beliefs that having money makes you a target. Tendency to struggle with receiving abundance or charging appropriately for healing services, feeling that spiritual gifts should be given freely. Can be too patient with financial problems, enduring difficult situations longer than necessary rather than taking decisive action to improve your circumstances.",
    advice: "Trust in your quiet power to build wealth through service, healing, and patient persistence while also developing confidence in your right to receive abundance and material success. Heal past wounds around persecution by gradually increasing your visibility and success while building supportive communities that appreciate and protect your gifts. Learn to charge appropriately for your services, understanding that receiving fair compensation allows you to help more people and continue developing your abilities."
  },
  9: {
    general: "Past life experiences as a wise teacher, hermit, or keeper of ancient knowledge create a deep understanding of true value and the relationship between wisdom and wealth, but also potential patterns of isolation from material opportunities or giving away valuable knowledge freely. You carry memories of lifetimes spent in contemplation, study, or teaching, often supported by others while you focused on developing and sharing wisdom. Your soul remembers the satisfaction of helping others through knowledge and guidance, but may struggle with practical aspects of monetizing wisdom or building personal wealth.",
    positive: "Deep understanding of true value and the ability to guide others in making wise financial decisions based on long-term thinking and spiritual principles. You have accumulated wisdom over many lifetimes that can be valuable to others, and your patient, thoughtful approach to money often leads to sustainable abundance. Your past life experience as a teacher or guide gives you natural ability to help others achieve financial success and understanding.",
    challenge: "May have patterns of isolating from material opportunities or giving away valuable knowledge and guidance without appropriate compensation, believing that wisdom should be freely shared. Tendency to focus on spiritual or intellectual pursuits while neglecting practical wealth-building activities, potentially missing opportunities to monetize your accumulated wisdom. Can struggle with the practical aspects of business and marketing, preferring to focus on developing knowledge rather than sharing it profitably.",
    advice: "Share your financial wisdom and knowledge while building practical abundance that supports your continued learning and service to others. Learn to value your accumulated wisdom appropriately and create income streams through teaching, consulting, or writing that allow you to support yourself while helping others. Balance your love of learning and contemplation with practical engagement in wealth-building activities that align with your values and purpose."
  },
  10: {
    general: "Past life experiences involving fate, destiny, and major cycles of fortune create an understanding of financial timing and natural rhythms, but also potential patterns of extreme ups and downs or over-reliance on external circumstances for financial success. You carry memories of lifetimes where wealth came and went according to larger cycles beyond individual control, creating both wisdom about timing and potential passivity about personal financial responsibility. Your soul remembers the wheel of fortune and how financial circumstances can change dramatically based on timing and larger forces.",
    positive: "Natural understanding of financial cycles and ability to time investments, career changes, and major financial decisions according to larger economic and personal cycles. You have intuitive sense of when to take risks and when to be conservative, often benefiting from being in the right place at the right time. Your past life experience with major financial cycles gives you perspective and patience during both prosperous and challenging financial periods.",
    challenge: "May have experienced extreme financial ups and downs in past lives, creating either fear of loss during prosperous times or expectation that current difficulties are permanent. Tendency to rely too much on luck, timing, or external circumstances rather than taking consistent action to create and maintain financial stability. Can become too passive about financial planning, believing that everything is predetermined rather than recognizing your power to influence financial outcomes through conscious choices.",
    advice: "Use your understanding of cycles and timing to create stable financial foundations that can weather natural fluctuations while also taking advantage of opportune moments for growth. Combine your intuitive timing abilities with consistent practical action and planning to create more predictable financial outcomes. Learn to work with natural cycles while also taking personal responsibility for building and maintaining the wealth you desire."
  },
  11: {
    general: "Past life experiences in legal, judicial, or justice-related roles create a strong ethical foundation for financial decisions and natural ability to create wealth through fair means, but also potential rigidity around what constitutes ethical money-making or past karma around financial judgments. You carry memories of lifetimes where you were responsible for making fair decisions about resources, property, or financial disputes. Your soul remembers the importance of justice and fairness in financial matters, but may struggle with the gray areas and practical compromises required in modern business.",
    positive: "Strong moral foundation for creating wealth through ethical means, with natural ability to see all sides of financial situations and make fair decisions that benefit everyone involved. You have integrity in business dealings that creates trust and long-term success, and your ethical approach attracts partners and opportunities that align with your values. Your past life experience with justice gives you wisdom about creating sustainable wealth through fair practices.",
    challenge: "May carry past karma around judgment or experiences of being judged unfairly in financial matters, creating either perfectionism or paralysis around money decisions. Tendency to be overly rigid about what constitutes ethical business practices, potentially missing opportunities that require moral flexibility or practical compromise. Can become judgmental of others' financial choices or struggle with the imperfect realities of business and wealth creation in the modern world.",
    advice: "Build wealth through ethical means while accepting that perfect fairness isn't always possible and that some compromise and flexibility are necessary in practical business situations. Release past judgments and karma around money by focusing on creating positive financial outcomes in the present rather than trying to balance past accounts. Use your natural sense of justice to create business practices and financial systems that serve the greater good while also meeting your personal needs."
  },
  12: {
    general: "Past life experiences involving sacrifice, martyrdom, or mystical practices create complex patterns around financial sacrifice and the relationship between spiritual service and material needs. You carry memories of lifetimes where you gave up material wealth for spiritual purposes or where your service required personal financial sacrifice. Your soul remembers the wisdom that comes from letting go and the spiritual insights available through voluntary poverty or sacrifice, but may struggle with creating appropriate balance between service and personal financial needs.",
    positive: "Deep understanding that sometimes financial sacrifice leads to greater spiritual and material abundance in the long run, with wisdom about when to let go and when to hold on. You have natural ability to see financial situations from completely different perspectives, often finding creative solutions that others miss. Your past life experience with sacrifice gives you the ability to make conscious choices about what truly matters and how to align your financial life with your spiritual values.",
    challenge: "May have unconscious patterns of financial martyrdom or unnecessary suffering around money, believing that struggling financially somehow makes you more spiritual or worthy. Tendency to sacrifice your own financial well-being for others without ensuring that your service is actually helpful or appreciated. Can struggle with receiving abundance or building personal wealth, feeling guilty about having more than others or believing that spiritual people shouldn't focus on material success.",
    advice: "Learn to distinguish between wise sacrifice that serves a higher purpose and unconscious martyrdom that serves no one effectively. Create healthy balance between service to others and care for your own financial well-being, understanding that taking care of yourself allows you to serve more effectively. Use your wisdom about letting go to release limiting beliefs about money while building practical abundance that supports your service and spiritual growth."
  },
  13: {
    general: "Past life experiences involving major transformations, deaths, and rebirths create a powerful ability to completely transform financial circumstances, but also potential fear of financial stability due to memories of sudden loss or dramatic change. You carry cellular memories of lifetimes where everything changed suddenly, including financial situations, creating both resilience and potential anxiety about building lasting wealth. Your soul remembers the power of transformation and renewal, but may struggle with trusting that financial stability can be maintained over time.",
    positive: "Natural ability to completely transform financial circumstances through willingness to let go of what no longer serves and embrace new opportunities for wealth creation. You have the courage to make major financial changes when necessary and the resilience to rebuild after setbacks or losses. Your past life experience with transformation gives you unique insights into how to navigate financial transitions and help others through major money-related changes.",
    challenge: "May fear financial stability or unconsciously sabotage wealth-building efforts due to past life memories of sudden financial loss or having everything taken away. Tendency to create unnecessary drama or crisis around money, or to make dramatic financial changes when gradual adjustment would be more effective. Can struggle with building lasting financial foundations due to expectation that everything will eventually change or be lost.",
    advice: "Embrace transformation as your natural path to greater financial freedom while also building some stable foundations that can support you through periods of change. Use your understanding of cycles and renewal to create financial strategies that can weather dramatic changes while also taking advantage of transformation opportunities. Learn to distinguish between necessary financial transformation and unconscious patterns of self-sabotage or crisis creation."
  },
  14: {
    general: "Past life experiences in healing, mediation, or balance-focused roles create a moderate, sustainable approach to wealth building and natural ability to create financial harmony, but also potential for avoiding necessary financial risks or intensity. You carry memories of lifetimes where you helped others find balance and heal financial wounds or conflicts. Your soul remembers the satisfaction of creating harmony and healing, but may struggle with the bold action or calculated risks sometimes necessary for significant financial growth.",
    positive: "Natural ability to create balanced, sustainable financial flow that provides steady growth without excessive stress or risk, with talent for helping others heal their money wounds and find financial balance. You have wisdom about moderation and the importance of building wealth in ways that support overall well-being rather than just accumulation. Your past life experience with healing gives you insights into how money problems often reflect deeper emotional or spiritual issues that need attention.",
    challenge: "May avoid financial extremes even when bold action or significant risk would be appropriate for achieving important financial goals, preferring safety and balance over potentially profitable opportunities. Tendency to compromise too much in financial negotiations or business situations, seeking middle ground when taking a stronger position would be more beneficial. Can be slow to make necessary financial changes, preferring gradual adjustment even when dramatic action is needed.",
    advice: "Trust your natural ability to create balanced, sustainable financial growth while also remaining open to opportunities that require more intensity, risk, or focused action. Use your healing abilities to address any money wounds or limiting beliefs that might be preventing you from achieving your full financial potential. Balance your preference for moderation with willingness to take calculated risks when they align with your long-term financial goals and values."
  },
  15: {
    general: "Past life experiences involving material power, temptation, or bondage create complex patterns around wealth, success, and the potential shadow aspects of money and material accumulation. You carry memories of lifetimes where material power was either used wisely or became corrupting, creating both natural ability to work with material forces and potential karma around greed, corruption, or power abuse. Your soul remembers both the benefits and dangers of material success, creating internal tension between desire for wealth and fear of its potential negative effects.",
    positive: "Deep understanding of the material world's power and how to work with money and resources consciously and effectively, with natural ability to accumulate significant wealth when focused. You have insights into human psychology around money and power that can be valuable in business and investment decisions. Your past life experience with material forces gives you the ability to help others understand and heal their relationship with money and success.",
    challenge: "May carry karmic patterns around greed, addiction, corruption, or abuse of material power, creating internal conflict between desire for success and fear of becoming corrupted by wealth. Tendency to unconsciously recreate past patterns of excess, manipulation, or using money to control others, or conversely to reject material success entirely due to fear of these patterns. Can struggle with guilt or shame around financial success, believing that having money makes you somehow bad or unspiritual.",
    advice: "Transform past shadow patterns around money and power into conscious, ethical use of material resources that serves both your needs and the greater good. Use your understanding of money's power to create wealth that enhances rather than corrupts your spiritual development and relationships. Address any unconscious guilt or fear around financial success through healing work that allows you to embrace abundance without repeating past mistakes."
  },
  16: {
    general: "Past life experiences involving sudden upheavals, wars, disasters, or institutional collapse create resilience and ability to rebuild quickly from financial setbacks, but also potential trauma around financial security and sudden change. You carry memories of lifetimes where stable financial situations were suddenly destroyed by external forces beyond your control. Your soul remembers both the trauma of sudden loss and the strength that comes from rebuilding, creating complex patterns around financial security and change.",
    positive: "Strong resilience and ability to rebuild quickly from financial setbacks, with natural talent for adapting to changing economic conditions and finding opportunities in chaos or disruption. You have the courage to make dramatic financial changes when necessary and the ability to help others navigate financial crises or major transitions. Your past life experience with sudden change gives you perspective on what really matters and how to maintain inner stability during external financial upheaval.",
    challenge: "May carry deep trauma from sudden financial loss, wars, disasters, or economic collapse, creating anxiety about financial security or tendency to expect sudden loss even during prosperous times. Tendency to unconsciously create financial drama or crisis, or to make sudden, dramatic financial decisions that destabilize your security. Can struggle with trusting financial institutions or long-term planning due to memories of systems failing or being destroyed.",
    advice: "Use your natural resilience and adaptability to build financial security that can weather unexpected changes while also creating enough flexibility to take advantage of opportunities that arise during transitions. Heal past trauma around sudden financial loss through gradual building of diverse income sources and emergency funds that provide genuine security. Learn to distinguish between intuitive warnings about real financial risks and anxiety based on past trauma that may not apply to current circumstances."
  },
  17: {
    general: "Past life experiences as a visionary, hope-bringer, or spiritual guide create an optimistic approach to money and natural faith in abundance, but also potential for unrealistic expectations or avoiding practical financial planning. You carry memories of lifetimes where you inspired others and helped them see possibilities for a better future, often providing hope during difficult times. Your soul remembers the power of vision and faith, but may struggle with the practical steps and sustained effort required to manifest financial dreams in the material world.",
    positive: "Natural faith in abundance and ability to inspire others financially, with talent for seeing possibilities and opportunities that others miss due to pessimism or limited thinking. You have the gift of maintaining hope and positive vision during financial challenges, which often attracts support and opportunities from unexpected sources. Your past life experience with spiritual guidance gives you insights into how money can serve higher purposes and support positive change in the world.",
    challenge: "May be too idealistic about money, expecting abundance to flow easily without adequate practical planning or sustained effort to build wealth systematically. Tendency to avoid dealing with practical financial details or difficult money decisions, preferring to focus on vision and inspiration rather than implementation. Can become disappointed when financial reality doesn't match your optimistic expectations, or lose faith when progress is slower than anticipated.",
    advice: "Combine your natural optimism and vision about financial abundance with practical planning and consistent action that can manifest your dreams in the material world. Use your inspirational abilities to motivate yourself and others while also developing concrete skills and strategies for building wealth. Balance faith in abundance with realistic assessment of what's required to achieve your financial goals, understanding that vision needs to be supported by practical action."
  },
  18: {
    general: "Past life experiences involving mystery, hidden knowledge, or deception create an intuitive but sometimes confused approach to money and complex patterns around financial truth and illusion. You carry memories of lifetimes where financial information was hidden, where you had access to secret knowledge about wealth, or where you were deceived about financial matters. Your soul remembers both the power of hidden financial wisdom and the danger of financial deception, creating internal tension between trust and suspicion in money matters.",
    positive: "Strong intuition about hidden financial opportunities and ability to sense when something isn't right about financial situations or investments, even when everything appears normal on the surface. You have natural psychic abilities that can guide financial decisions and help you avoid scams or poor investments that others might fall for. Your past life experience with financial mysteries gives you insights into the hidden forces and psychological factors that influence money flow and economic patterns.",
    challenge: "May struggle with financial confusion or have been deceived about money in past lives, creating either excessive suspicion or naive trust in current financial situations. Tendency to make financial decisions based on fear, intuition, or emotional reactions rather than clear analysis of facts and practical considerations. Can be attracted to get-rich-quick schemes or mysterious investment opportunities that promise more than they can deliver.",
    advice: "Trust your financial intuition while also seeking clear, verifiable information about investment opportunities and financial decisions rather than relying solely on gut feelings or promises. Develop practical financial education and analytical skills that can support and verify your intuitive insights about money matters. Learn to distinguish between genuine psychic guidance about financial opportunities and emotional reactions or wishful thinking that might lead you astray."
  },
  19: {
    general: "Past life experiences involving success, celebration, and natural abundance create a positive relationship with money and expectation that wealth should flow easily, but also potential for taking abundance for granted or avoiding financial responsibility. You carry memories of lifetimes where you were naturally successful and prosperous, where money came easily and life was generally positive and fulfilling. Your soul remembers the joy of abundance and success, but may struggle with the effort and planning required to maintain prosperity or deal with financial challenges when they arise.",
    positive: "Natural magnetism for financial abundance and success, with positive energy and optimistic outlook that tends to attract opportunities and support from others. You have the gift of making money feel joyful and celebratory rather than stressful or burdensome, which often leads to sustainable abundance. Your past life experience with success gives you confidence and natural ability to manifest prosperity through positive thinking and enthusiastic action.",
    challenge: "May take financial abundance for granted or have unrealistic expectations about how easily money should come, potentially avoiding the practical work required to build and maintain wealth. Tendency to overspend on pleasure, generosity, or immediate gratification rather than planning for long-term financial security. Can struggle with financial challenges or setbacks, expecting everything to work out easily and becoming discouraged when sustained effort is required.",
    advice: "Maintain your natural gratitude for abundance and positive approach to money while also developing practical financial management skills and planning for long-term security. Use your natural magnetism for prosperity to create sustainable wealth-building habits rather than just enjoying financial success without protecting it. Balance your generous, celebratory approach to money with wise stewardship that ensures your abundance continues to grow and serve you over time."
  },
  20: {
    general: "Past life experiences involving spiritual awakening, calling, and service to higher purpose create a relationship with money that must align with spiritual values and life mission rather than just personal accumulation. You carry memories of lifetimes where you experienced profound spiritual awakening and dedicated your life to serving higher purposes, often requiring financial sacrifice or support from others. Your soul remembers the satisfaction of meaningful service, but may struggle with practical aspects of monetizing spiritual work or integrating material success with spiritual values.",
    positive: "Deep understanding that financial abundance can serve spiritual awakening and higher purpose rather than competing with spiritual development, with natural ability to create income streams that align with your soul's mission. You have the gift of inspiring others to see money as a tool for service and positive change rather than just personal accumulation. Your past life experience with spiritual calling gives you wisdom about how to balance material needs with spiritual values and purpose.",
    challenge: "May struggle with integrating spiritual purpose with practical financial needs, believing that spiritual work should not be monetized or that focusing on money contradicts spiritual values. Tendency to expect others to support your spiritual work financially rather than developing sustainable income streams that align with your mission. Can become overwhelmed by the perceived conflict between material success and spiritual integrity, potentially avoiding financial planning or wealth building entirely.",
    advice: "Answer your spiritual calling around money by creating income streams that serve both your material needs and your higher purpose, understanding that financial independence can enhance your spiritual service. Develop practical skills for monetizing spiritual work in ethical ways that honor both your gifts and your need for material security. Use your understanding of higher purpose to create financial abundance that serves not just yourself but also contributes to positive change and spiritual awakening in others."
  },
  21: {
    general: "Past life experiences involving mastery, completion, and achievement create natural wisdom about financial success and the ability to create lasting wealth that serves multiple purposes and benefits others. You carry memories of lifetimes where you achieved significant material success and used wealth wisely to benefit yourself and your community. Your soul remembers the satisfaction of financial mastery and the responsibility that comes with abundance, but may struggle with staying motivated once basic financial security is achieved.",
    positive: "Natural wisdom about achieving lasting financial success through patience, skill development, and long-term thinking, with ability to create wealth that serves multiple purposes and benefits others. You have mastery of financial principles and practical skills that allow you to build sustainable prosperity while maintaining integrity and values. Your past life experience with successful wealth creation gives you insights that can help others achieve financial independence and security.",
    challenge: "May rest on past achievements or current financial success rather than continuing to grow and evolve in your relationship with money and wealth creation. Need for new financial challenges or purposes to maintain motivation and continued development, which can create restlessness or dissatisfaction even when financially successful. Can become overly focused on maintaining current wealth rather than exploring new possibilities for growth, service, or creative expression through money.",
    advice: "Use your natural mastery of financial principles to help others achieve prosperity while also setting new meaningful goals that challenge you to continue growing in your relationship with money. Celebrate your financial achievements while remaining open to new ways of creating, using, and sharing wealth that align with your evolving values and purpose. Balance maintaining your financial success with continued learning and exploration of how money can serve your highest potential and contribute to positive change."
  },
  22: {
    general: "Past life experiences involving new beginnings, fresh starts, and unlimited potential create an approach to money that is open to possibility but may lack practical experience or wisdom from previous financial mistakes. You carry memories of lifetimes where you started over financially with optimism and enthusiasm, but may also remember making naive decisions or missing important practical considerations. Your soul remembers the excitement of unlimited potential, but may struggle with developing the practical skills and experience needed for sustained financial success.",
    positive: "Unlimited potential for creating new financial paradigms and income streams that aren't constrained by conventional thinking or past limitations, with natural optimism and willingness to try innovative approaches. You have fresh perspective on money and wealth creation that can lead to breakthrough opportunities and creative solutions to financial challenges. Your past life experience with new beginnings gives you resilience and ability to start over when necessary without being discouraged by setbacks.",
    challenge: "May repeat past financial mistakes or be naive about practical realities of money management and wealth building, making decisions based on enthusiasm rather than experience. Tendency toward impractical financial approaches that sound good in theory but don't account for real-world constraints and requirements. Can lack the patience or sustained effort needed to build lasting financial success, preferring exciting new opportunities over steady, consistent wealth-building strategies.",
    advice: "Embrace your fresh perspective and unlimited potential for financial success while also learning from others' experience and developing practical skills for managing money effectively. Balance your openness to new financial opportunities with careful evaluation of risks and requirements before making major financial commitments. Use your natural optimism and willingness to start over as strengths while also building the practical knowledge and experience needed for long-term financial security and success."
  }
};