/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Past Life Money Mindset Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * your core beliefs, attitudes, and unconscious programming around money
 * based on experiences and conditioning from past lifetimes.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Past Life Money Mindset - Core beliefs and attitudes about money from past lifetimes
 */
export const pastLifeMoneyMindsetInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your past life money mindset is deeply rooted in beliefs about personal power, self-reliance, and the conviction that you must create your own financial destiny through individual effort and determination. You carry cellular memories of lifetimes where financial success depended entirely on your personal initiative, leadership abilities, and willingness to take risks that others wouldn't dare attempt. This creates a core belief that money comes to those who are bold enough to go after it and that financial security depends on your ability to manifest resources through sheer willpower and creative action.",
    positive: "Strong inner conviction that you have the power to create wealth and financial success through your own efforts, with natural confidence in your ability to manifest money when you set your mind to it. Your past life experiences have instilled an entrepreneurial mindset that sees opportunities where others see obstacles and believes that there are always new ways to generate income. You possess an inherent understanding that money is energy that responds to focused intention, decisive action, and the courage to pioneer new approaches to wealth creation.",
    challenge: "May carry unconscious beliefs that you must do everything alone financially, that asking for help is weakness, or that relying on others for financial support somehow diminishes your power or independence. Your past life experiences might have created a mindset that views money as something you must fight for or earn through struggle, making it difficult to receive abundance that comes easily or through collaboration. There may be deep programming that equates financial worth with personal worth, creating pressure to constantly prove yourself through material achievement.",
    advice: "Honor your natural ability to create wealth through personal initiative while learning to accept support and collaboration as additional sources of strength rather than signs of weakness. Transform any beliefs about money requiring struggle into understanding that abundance can flow through many channels, including partnership, investment, and passive income streams. Use your powerful manifestation abilities to create not just personal wealth but also opportunities that benefit others, recognizing that true financial mastery includes both independence and interdependence."
  },
  2: {
    general: "Your past life money mindset is characterized by intuitive understanding of abundance as a spiritual principle, but also potential confusion about the relationship between material wealth and spiritual purity. You carry memories of lifetimes where money was viewed through the lens of service, energy exchange, and the understanding that true wealth includes emotional, spiritual, and energetic resources as well as material ones. This creates a complex relationship with money that honors both its practical necessity and its potential to either support or distract from spiritual development and service to others.",
    positive: "Deep intuitive understanding that money is energy and that abundance flows according to spiritual laws of giving and receiving, creating natural alignment between financial decisions and higher values. Your past life experiences have developed an appreciation for the non-material forms of wealth including wisdom, love, healing abilities, and spiritual insight that can also be exchanged for material resources. You possess natural psychic abilities around money, often sensing good and bad financial opportunities through intuitive guidance rather than logical analysis alone.",
    challenge: "May carry unconscious beliefs that money is unspiritual, that charging for spiritual services corrupts their purity, or that having too much material wealth interferes with spiritual development. Your past life experiences might have created guilt around enjoying material pleasures or fear that financial success will make you selfish or disconnected from spiritual truth. There may be programming that undervalues intuitive and healing services, making it difficult to charge appropriately for gifts that feel natural or divinely given.",
    advice: "Integrate your spiritual understanding of abundance with practical money management, recognizing that financial resources can support rather than compete with your spiritual development and service. Learn to value your intuitive and healing gifts appropriately, understanding that receiving fair compensation allows you to continue serving others while meeting your own material needs. Develop clear boundaries between money as a practical tool and money as a measure of spiritual worth, using your financial resources to support both material security and spiritual growth."
  },
  3: {
    general: "Your past life money mindset is rooted in beliefs about abundance as a natural birthright, creativity as a source of wealth, and the understanding that money should flow as generously as nature provides for all living beings. You carry memories of lifetimes where resources were shared freely, where creative expression was valued and supported by community, and where abundance was seen as something to be enjoyed and shared rather than hoarded or competed for. This creates a core belief that there is enough for everyone and that wealth increases when it is shared generously and used to nurture growth and beauty.",
    positive: "Natural expectation that abundance should flow easily and generously, with strong belief in your ability to manifest resources through creative expression and nurturing activities. Your past life experiences have instilled confidence in the generative power of creativity, love, and service to others as sustainable sources of income and wealth. You possess an inherent understanding that money, like love, grows when it is shared and that investing in others' growth and happiness creates returns in multiple forms including financial abundance.",
    challenge: "May carry unconscious beliefs that money should always be easy, that struggling financially means you're doing something wrong spiritually, or that wealthy people should support others without expecting anything in return. Your past life experiences might have created naivety about money management, budgeting, or the practical work required to sustain financial abundance over time. There may be programming that makes it difficult to say no to financial requests or to charge appropriately for your time, energy, and creative work.",
    advice: "Balance your natural generosity and abundance mindset with practical financial planning and boundary-setting that protects your ability to continue creating and giving sustainably. Learn to distinguish between wise sharing that empowers others and enabling behavior that depletes your resources without creating genuine benefit. Use your creative abilities and nurturing nature to build sustainable income streams that align with your values while also providing adequate financial security for your own needs and future goals."
  },
  4: {
    general: "Your past life money mindset is built on beliefs about financial security through systematic planning, hard work, and the creation of stable structures that can provide long-term wealth and protection for future generations. You carry memories of lifetimes where financial survival depended on discipline, careful resource management, and the ability to build lasting foundations that could weather economic storms and uncertainties. This creates a core belief that money should be earned through honest work, saved for the future, and used to create security rather than spent on immediate pleasures or risky ventures.",
    positive: "Strong foundation of practical financial wisdom including natural abilities for budgeting, saving, long-term planning, and building wealth through consistent effort and strategic thinking. Your past life experiences have developed patience and discipline around money, with understanding that real wealth is built slowly and systematically rather than through get-rich-quick schemes. You possess inherent knowledge about the importance of financial planning, emergency funds, and creating multiple streams of stable income that can support you and your family over time.",
    challenge: "May carry unconscious beliefs that money must be earned through struggle and sacrifice, that enjoying wealth is frivolous or irresponsible, or that taking financial risks is dangerous and should be avoided. Your past life experiences might have created excessive caution around money, making it difficult to invest in opportunities that could accelerate wealth building or to spend money on experiences and pleasures that enhance quality of life. There may be programming that equates financial worth with moral worth, creating guilt around enjoying abundance or shame around financial difficulties.",
    advice: "Use your natural financial discipline and planning abilities while also remaining open to calculated risks and investments that can accelerate your wealth-building goals. Learn to balance security-focused money management with strategic risk-taking that aligns with your long-term financial vision and risk tolerance. Allow yourself to enjoy the fruits of your financial discipline and hard work, recognizing that money is meant to enhance life quality as well as provide security."
  },
  5: {
    general: "Your past life money mindset is shaped by beliefs about money serving higher purposes, traditional values around financial responsibility, and the understanding that wealth should be used to support spiritual development, education, and moral causes. You carry memories of lifetimes where financial resources were viewed as tools for service, learning, and the advancement of knowledge and wisdom rather than primarily for personal gratification. This creates a core belief that money should be earned and used ethically, in alignment with moral principles and in service of causes greater than individual material accumulation.",
    positive: "Natural alignment between financial decisions and moral principles, with strong conviction that money should be earned through honest means and used to support education, spiritual growth, and beneficial causes. Your past life experiences have developed wisdom about the proper relationship between material wealth and spiritual values, understanding that money can support rather than corrupt spiritual development when used consciously. You possess inherent knowledge about traditional financial principles including the importance of tithing, charitable giving, and using wealth to support community development and social progress.",
    challenge: "May carry unconscious beliefs that enjoying material wealth is morally questionable, that simple living is more virtuous than abundance, or that focusing on money interferes with spiritual priorities. Your past life experiences might have created guilt around personal financial success or fear that having money will make you materialistic or corrupt your spiritual values. There may be programming that undervalues practical financial planning in favor of trusting divine providence or that judges others' financial choices based on rigid moral standards.",
    advice: "Integrate your strong moral foundation with practical financial planning, recognizing that ethical wealth-building serves both your personal needs and your ability to contribute to causes you value. Learn to appreciate material abundance as a tool for spiritual service rather than an obstacle to spiritual development. Use your natural wisdom about ethics and values to guide financial decisions while also accepting that different people may have different but equally valid approaches to money and wealth creation."
  },
  6: {
    general: "Your past life money mindset is centered on beliefs about financial harmony, partnership in wealth creation, and the understanding that money should enhance relationships and create beauty rather than cause conflict or competition. You carry memories of lifetimes where financial decisions were made collaboratively, where wealth was shared equitably among partners, and where money was used to create beautiful environments and experiences that brought people together. This creates a core belief that financial success should feel harmonious and balanced, serving the needs of relationships as well as individual security.",
    positive: "Natural ability to create financial harmony in relationships and partnerships, with strong instinct for fair and equitable financial arrangements that serve everyone's needs and interests. Your past life experiences have developed skills for collaborative financial planning, shared investment strategies, and using money to enhance relationship quality and create beautiful shared experiences. You possess inherent understanding that money can strengthen relationships when handled with fairness, transparency, and mutual consideration.",
    challenge: "May carry unconscious beliefs that financial conflicts indicate relationship failure, that discussing money is unromantic or materialistic, or that love should make financial concerns irrelevant. Your past life experiences might have created avoidance of financial planning or decision-making, preferring to hope that money issues will resolve themselves harmoniously without direct confrontation. There may be programming that makes financial independence feel selfish or that prioritizes relationship harmony over practical financial needs and boundaries.",
    advice: "Use your natural diplomatic skills to have honest, caring conversations about money and financial goals with partners and family members rather than avoiding these topics in hopes of maintaining harmony. Learn to balance relationship considerations with practical financial planning, recognizing that clear agreements and boundaries actually strengthen rather than threaten loving relationships. Create financial practices that honor both individual autonomy and collaborative decision-making, allowing for both shared and separate financial resources and goals."
  },
  7: {
    general: "Your past life money mindset is driven by beliefs about money as fuel for achievement, competition as a healthy part of wealth creation, and the conviction that financial success requires determination, strategy, and the willingness to overcome obstacles through persistent effort. You carry memories of lifetimes where wealth was earned through conquest, trading, travel, or other dynamic activities that required courage, quick thinking, and the ability to adapt rapidly to changing circumstances. This creates a core belief that money comes to those who are willing to take action, compete when necessary, and persist through challenges that would discourage others.",
    positive: "Strong drive and determination around financial goals, with natural ability to overcome obstacles, adapt to changing economic conditions, and compete successfully in challenging markets or industries. Your past life experiences have developed resilience around money, understanding that financial setbacks are temporary and that persistence and strategic action can overcome almost any monetary challenge. You possess inherent knowledge about the importance of taking calculated risks, moving quickly on opportunities, and maintaining momentum in pursuit of financial objectives.",
    challenge: "May carry unconscious beliefs that money must be fought for, that financial success requires defeating others, or that collaboration and sharing are signs of weakness in financial matters. Your past life experiences might have created a mindset that views money primarily through the lens of competition and scarcity rather than abundance and cooperation. There may be programming that equates rest or contentment with financial stagnation, making it difficult to enjoy current abundance or to appreciate gradual, steady progress toward financial goals.",
    advice: "Channel your natural drive and competitive spirit into collaborative financial ventures and win-win opportunities that create success for multiple parties rather than zero-sum games. Learn to balance aggressive pursuit of financial goals with strategic patience and the ability to enjoy current abundance while working toward future objectives. Use your natural resilience and adaptability to build sustainable wealth-creation systems rather than relying solely on individual effort and competition."
  },
  8: {
    general: "Your past life money mindset is characterized by beliefs about money requiring patience, inner strength, and the understanding that true wealth comes through gradual accumulation, wise management, and the ability to transform financial challenges into opportunities through gentle persistence. You carry memories of lifetimes where financial security was built through quiet determination, careful nurturing of resources, and the wisdom to wait for the right timing rather than forcing immediate results. This creates a core belief that sustainable wealth develops slowly and that financial strength comes from inner resources as much as external circumstances.",
    positive: "Natural patience and inner strength around financial matters, with deep understanding that real wealth is built through consistent effort over time rather than dramatic gestures or quick schemes. Your past life experiences have developed emotional resilience around money, allowing you to remain centered during financial difficulties and to see opportunities for growth within challenging circumstances. You possess inherent wisdom about the healing aspects of money, understanding how financial resources can be used to support recovery, transformation, and the development of inner strength.",
    challenge: "May carry unconscious beliefs that suffering is necessary for financial growth, that patience means accepting inadequate circumstances indefinitely, or that asserting financial needs is aggressive or unspiritual. Your past life experiences might have created a tendency to endure financial difficulties too long without taking appropriate action to improve circumstances. There may be programming that undervalues your financial contributions or that makes it difficult to ask for fair compensation for your patient, supportive work.",
    advice: "Use your natural patience and inner strength to build sustainable wealth while also learning to advocate clearly for your financial needs and to take decisive action when circumstances require change. Balance your gentle approach to money with appropriate assertiveness about compensation, boundaries, and financial goals that serve your long-term security and growth. Transform any patterns of financial martyrdom into conscious choices about when to be patient and when to take action to improve your financial circumstances."
  },
  9: {
    general: "Your past life money mindset is rooted in beliefs about money as a tool for wisdom acquisition, the value of knowledge over material accumulation, and the understanding that true wealth comes from spiritual and intellectual development rather than external possessions. You carry memories of lifetimes where financial resources were used primarily to support learning, teaching, contemplation, and the sharing of wisdom rather than for material comfort or social status. This creates a core belief that money should serve higher purposes and that the pursuit of wisdom and understanding is more valuable than the accumulation of material wealth.",
    positive: "Deep understanding of the relationship between knowledge and wealth, with natural ability to monetize wisdom, teaching, and guidance in ways that serve both your financial needs and others' growth and development. Your past life experiences have developed appreciation for the long-term value of education, skills development, and intellectual property as sources of sustainable income. You possess inherent wisdom about using money to support learning, research, and the acquisition of knowledge that can benefit both yourself and future generations.",
    challenge: "May carry unconscious beliefs that focusing on money interferes with spiritual or intellectual development, that charging for wisdom or guidance is inappropriate, or that material comfort corrupts the purity of knowledge and teaching. Your past life experiences might have created tendency to isolate from practical financial concerns in favor of purely intellectual or spiritual pursuits. There may be programming that undervalues practical skills and earthly knowledge in favor of abstract or esoteric wisdom, making it difficult to monetize your knowledge effectively.",
    advice: "Integrate your natural wisdom and teaching abilities with practical financial planning, recognizing that material security can support rather than interfere with your intellectual and spiritual development. Learn to value your knowledge and guidance appropriately, understanding that receiving fair compensation for your wisdom allows you to continue learning and teaching while meeting your practical needs. Use your deep understanding of value and worth to create income streams that align with your intellectual interests and spiritual values while also providing adequate financial support."
  },
  10: {
    general: "Your past life money mindset is shaped by beliefs about financial cycles, timing, and the understanding that wealth and poverty are both temporary conditions that change according to larger forces and natural rhythms beyond individual control. You carry memories of lifetimes where financial fortune fluctuated dramatically, where timing was crucial for financial success, and where understanding cosmic or economic cycles provided advantage in money matters. This creates a core belief that financial circumstances are influenced by fate, timing, and the ability to recognize and work with larger patterns rather than just individual effort.",
    positive: "Natural understanding of financial timing and cycles, with intuitive ability to recognize when to invest, when to save, when to take risks, and when to be conservative based on larger economic and personal patterns. Your past life experiences have developed philosophical perspective on money that prevents excessive attachment to either wealth or poverty, understanding that both are temporary conditions in the larger cycle of life. You possess inherent wisdom about working with rather than against natural financial rhythms and the importance of being prepared for both prosperous and challenging periods.",
    challenge: "May carry unconscious beliefs that financial outcomes are entirely determined by fate or external forces, leading to either fatalistic acceptance of difficult circumstances or irresponsible behavior based on belief in guaranteed good fortune. Your past life experiences might have created tendency to wait passively for financial opportunities rather than taking proactive steps to create wealth. There may be programming that views planning and goal-setting as pointless because everything is predetermined by larger forces beyond personal control.",
    advice: "Use your natural understanding of cycles and timing to make wise financial decisions while also taking personal responsibility for creating the wealth and security you desire within the context of larger circumstances. Learn to balance acceptance of factors beyond your control with proactive effort in areas where you can influence outcomes. Combine your philosophical perspective on money with practical planning and action, recognizing that wisdom includes both understanding larger patterns and working skillfully within them."
  },
  11: {
    general: "Your past life money mindset is built on beliefs about financial fairness, ethical decision-making, and the conviction that money should be earned and used in ways that serve justice and moral principles rather than pure self-interest. You carry memories of lifetimes where financial decisions were evaluated based on their ethical implications, where wealth was distributed according to principles of fairness and merit, and where money was viewed as a responsibility that should be handled with integrity and consideration for its impact on others. This creates a core belief that financial success should be achieved through honest means and that wealth carries moral obligations.",
    positive: "Strong ethical foundation for all financial decisions, with natural ability to create wealth through fair business practices, honest dealings, and long-term thinking that considers the impact of financial choices on all parties involved. Your past life experiences have developed wisdom about the relationship between ethics and sustainable prosperity, understanding that businesses and investments built on solid moral foundations tend to be more stable and profitable over time. You possess inherent sense of justice around money that helps you make decisions that serve both your financial goals and your moral principles.",
    challenge: "May carry unconscious beliefs that making money requires compromising your ethics, that wealthy people are necessarily greedy or exploitative, or that financial success somehow makes you morally suspect. Your past life experiences might have created excessive perfectionism around financial decisions, making it difficult to take action when circumstances are complex or when perfect solutions aren't available. There may be programming that creates guilt around personal financial success or that makes it difficult to enjoy wealth while others are struggling financially.",
    advice: "Use your strong ethical foundation to create financial success through honest, fair means while recognizing that perfection isn't required and that you can make positive financial choices even in imperfect circumstances. Learn to balance moral considerations with practical financial needs, understanding that your own financial security enables you to help others more effectively. Channel your sense of justice into creating financial systems and practices that serve both your personal goals and the broader good, recognizing that ethical wealth creation benefits everyone."
  },
  12: {
    general: "Your past life money mindset is characterized by beliefs about financial sacrifice, the spiritual lessons available through material challenges, and the understanding that sometimes letting go of money attachments leads to greater abundance and freedom. You carry memories of lifetimes where financial sacrifice was necessary for spiritual development, where material loss led to important insights and growth, and where conventional approaches to money were less effective than surrendering to higher guidance and trusting in divine provision. This creates a complex relationship with money that values both practical resources and the wisdom that comes from releasing attachment to material security.",
    positive: "Deep spiritual understanding of money's proper role in life, with natural ability to remain peaceful and centered during financial challenges and to find meaning and growth opportunities within material difficulties. Your past life experiences have developed faith in abundance that transcends material circumstances, allowing you to take financial risks or make sacrifices that serve higher purposes. You possess inherent wisdom about when holding onto money creates limitation and when releasing financial attachments opens space for greater abundance and freedom.",
    challenge: "May carry unconscious beliefs that financial struggle is spiritually beneficial, that enjoying material comfort interferes with spiritual development, or that sacrificing your financial needs somehow serves others better than meeting them appropriately. Your past life experiences might have created tendency toward financial martyrdom or passive acceptance of inadequate circumstances when action would be more appropriate. There may be programming that makes it difficult to ask for fair compensation or to pursue financial goals with appropriate determination and focus.",
    advice: "Use your spiritual wisdom about money while also taking practical responsibility for meeting your material needs and creating appropriate financial security for yourself and your family. Learn to distinguish between conscious sacrifice that serves a higher purpose and unconscious martyrdom that serves no one effectively. Balance your understanding of money's limitations with appreciation for its practical value as a tool for creating security, comfort, and opportunities to serve others more effectively."
  },
  13: {
    general: "Your past life money mindset is shaped by beliefs about financial transformation, the necessity of releasing old money patterns that no longer serve, and the understanding that true wealth often requires the death of limiting beliefs and the rebirth of new relationship with abundance. You carry memories of lifetimes where financial circumstances changed dramatically, where old sources of income or security were lost and new ones had to be discovered, and where economic transformation was both frightening and ultimately liberating. This creates a core belief that financial growth requires letting go of what is familiar and safe in order to embrace new possibilities.",
    positive: "Natural ability to transform financial circumstances completely when necessary, with courage to release old money patterns, jobs, or income sources that no longer serve your growth and evolution. Your past life experiences have developed resilience around financial transitions and the wisdom to see opportunities for renewal within apparent losses or endings. You possess inherent understanding that money, like all energy, must flow and change rather than remaining static, and that financial transformation often leads to greater abundance and freedom.",
    challenge: "May carry unconscious beliefs that financial change is always traumatic, that releasing old income sources is dangerous, or that transformation requires suffering and loss rather than conscious choice and planning. Your past life experiences might have created fear of financial stability or tendency to create unnecessary financial crisis when life becomes too comfortable or predictable. There may be programming that associates money with impermanence in ways that make it difficult to plan for the future or to enjoy current financial security.",
    advice: "Use your natural ability to transform financial circumstances while also building stable foundations that can support you through periods of change and transition. Learn to initiate conscious financial transformation before crisis forces change, recognizing that you have the power to guide your financial evolution rather than just reacting to external circumstances. Balance your comfort with financial change with appreciation for stability and security when they serve your highest good and long-term goals."
  },
  14: {
    general: "Your past life money mindset is built on beliefs about financial balance, moderation, and the understanding that sustainable wealth comes through harmonizing different approaches to money rather than pursuing extremes of either accumulation or spending. You carry memories of lifetimes where financial wisdom was demonstrated through patience, gradual progress, and the ability to find middle ground between competing financial priorities and pressures. This creates a core belief that the healthiest relationship with money involves neither obsession nor avoidance, but rather conscious integration of material needs with spiritual values.",
    positive: "Natural ability to create balanced, sustainable financial practices that avoid both excessive materialism and impractical idealism about money, with wisdom about integrating different approaches to wealth creation and management. Your past life experiences have developed patience for gradual financial progress and understanding that real wealth is built through consistent, moderate efforts rather than dramatic gestures or extreme measures. You possess inherent wisdom about healing financial wounds and helping others find balance in their own relationship with money and material resources.",
    challenge: "May carry unconscious beliefs that financial extremes are always dangerous, that passionate pursuit of wealth is inappropriate, or that moderate progress means accepting less than your full potential for abundance. Your past life experiences might have created tendency to compromise too much in financial negotiations or to avoid taking bold action when circumstances require decisive financial moves. There may be programming that makes it difficult to advocate strongly for your financial needs or to pursue ambitious goals with appropriate intensity and focus.",
    advice: "Use your natural gift for financial balance while also recognizing when circumstances call for more focused effort, passionate pursuit of goals, or decisive action that temporarily disrupts equilibrium. Learn to distinguish between healthy moderation and limiting compromise, understanding that sometimes balanced living requires periods of intense focus on particular financial objectives. Channel your wisdom about financial healing into both your own money relationship and service to others who need support in developing healthier financial practices."
  },
  15: {
    general: "Your past life money mindset is characterized by beliefs about money as power, the seductive nature of material wealth, and the understanding that financial success can be both liberating and enslaving depending on how it is pursued and used. You carry memories of lifetimes where money was associated with control, influence, and the ability to manipulate circumstances and people, but also where the pursuit of wealth became obsessive or corrupting. This creates a complex relationship with money that recognizes both its practical power and its potential to create psychological and spiritual bondage when pursued unconsciously.",
    positive: "Deep understanding of money as a form of power and energy that can be used consciously for positive purposes, with natural ability to create significant wealth through focused intention and strategic action. Your past life experiences have developed insight into human psychology around money, making you effective at understanding what motivates financial behavior and how to work with rather than against these psychological forces. You possess inherent knowledge about the material world's laws and how to work with them to create abundance and influence that serves beneficial purposes.",
    challenge: "May carry unconscious beliefs that money corrupts spiritual purity, that wealthy people are necessarily selfish or manipulative, or that pursuing financial success will compromise your ethical integrity and authentic self-expression. Your past life experiences might have created guilt around enjoying material pleasures or fear that financial success will make you a target for others' envy or resentment. There may be programming that associates money with addiction, obsession, or loss of control over your choices and values.",
    advice: "Use your understanding of money's power consciously and ethically while healing any past associations between wealth and corruption or manipulation. Learn to enjoy material abundance and influence without becoming attached to them as sources of identity or security, recognizing that money is a tool rather than a master. Channel your natural ability to work with material forces into creating wealth that serves both your personal needs and positive purposes that benefit others and contribute to collective well-being."
  },
  16: {
    general: "Your past life money mindset is shaped by beliefs about sudden financial changes, the impermanence of material security, and the understanding that money systems and structures can collapse unexpectedly, requiring adaptability and resilience to rebuild from financial destruction. You carry memories of lifetimes where stable financial circumstances were disrupted by wars, natural disasters, economic collapse, or other dramatic events that forced complete restructuring of relationship with money and wealth. This creates a core belief that financial planning must include preparation for unexpected changes and that true security comes from inner resources and adaptability rather than external accumulation.",
    positive: "Natural resilience and adaptability around financial challenges, with ability to rebuild quickly from setbacks and to find opportunities for innovation and improvement within financial disruption. Your past life experiences have developed independence from conventional financial systems and the creativity to generate income through unconventional means when traditional approaches are not available. You possess inherent understanding that financial freedom comes from flexibility and inner resources rather than just external accumulation and security.",
    challenge: "May carry unconscious beliefs that financial stability is illusory, that planning for the future is pointless because circumstances will change unpredictably, or that accumulating wealth makes you vulnerable to loss and disappointment. Your past life experiences might have created anxiety about financial security or tendency to sabotage stability when life becomes too comfortable or predictable. There may be programming that associates financial planning with false security or that makes it difficult to trust in long-term financial strategies and investments.",
    advice: "Use your natural adaptability and resilience to create flexible financial strategies that can weather unexpected changes while also building appropriate stability and security for current circumstances. Learn to balance preparation for change with appreciation for stability when it's available, recognizing that both flexibility and consistency have value in financial planning. Channel your understanding of impermanence into wise financial choices that serve both immediate needs and long-term goals while remaining adaptable to changing circumstances."
  },
  17: {
    general: "Your past life money mindset is rooted in beliefs about money serving spiritual purpose, abundance as divine gift, and the understanding that financial resources should be used to support hope, healing, and the manifestation of positive visions for the future. You carry memories of lifetimes where wealth was viewed as a blessing to be shared, where financial abundance flowed through alignment with higher purpose and spiritual principles, and where money was used to support dreams, inspiration, and the creation of better circumstances for many people. This creates a core belief that money should serve idealistic goals and that financial success should contribute to healing and positive transformation.",
    positive: "Natural faith in abundance and ability to attract financial resources through alignment with positive vision and service to others, with understanding that money flows more easily when it serves purposes larger than personal accumulation. Your past life experiences have developed optimism about financial possibilities and the ability to inspire others to support financially beneficial projects and dreams. You possess inherent wisdom about using money to create hope, beauty, and healing opportunities that benefit both yourself and others who are touched by your vision and generosity.",
    challenge: "May carry unconscious beliefs that focusing on practical financial matters interferes with spiritual idealism, that detailed money management shows lack of faith in divine provision, or that wealthy people lose touch with higher values and compassionate service. Your past life experiences might have created tendency to give money away impulsively or to support causes without adequate research or planning. There may be programming that makes it difficult to balance idealistic financial goals with practical planning and realistic assessment of resources and timelines.",
    advice: "Use your natural faith in abundance and service orientation while also developing practical financial skills and realistic planning that can support your idealistic goals more effectively. Learn to balance generous financial support for causes you believe in with wise stewardship that ensures your own security and ability to continue giving over time. Channel your inspirational energy into creating sustainable financial systems and practices that serve both spiritual values and practical needs for security and growth."
  },
  18: {
    general: "Your past life money mindset is characterized by beliefs about money involving hidden factors, intuitive guidance, and the understanding that financial reality often differs from surface appearances, requiring psychic sensitivity and careful discernment to navigate successfully. You carry memories of lifetimes where financial deception was common, where intuitive guidance was necessary to avoid monetary traps, and where the emotional and psychological aspects of money were as important as the practical considerations. This creates a complex relationship with money that values both practical information and intuitive insight in making financial decisions.",
    positive: "Natural psychic ability around money with capacity to sense hidden opportunities, avoid financial deception, and receive intuitive guidance about investments, career moves, and money decisions that logical analysis alone might miss. Your past life experiences have developed sensitivity to the emotional and energetic aspects of money that influence financial outcomes in ways that aren't immediately obvious. You possess inherent understanding of the psychological factors that drive financial behavior and the ability to work with rather than against these unconscious forces.",
    challenge: "May carry unconscious beliefs that money always involves deception, that trusting others financially is dangerous, or that clear information about money is rarely available or reliable. Your past life experiences might have created confusion between genuine intuitive guidance and emotional reactivity or wishful thinking about financial matters. There may be programming that makes it difficult to trust your own financial judgment or that creates paranoia about others' financial motives and honesty.",
    advice: "Use your natural intuitive abilities around money while also developing practical financial education and analytical skills that can verify and support your psychic insights about financial opportunities and risks. Learn to distinguish between genuine intuitive guidance and emotional confusion or projection, developing practices that help you access clear inner wisdom about money decisions. Balance your sensitivity to hidden factors with trust in your ability to make good financial choices when you combine intuition with practical information and wise counsel."
  },
  19: {
    general: "Your past life money mindset is built on beliefs about abundance as natural birthright, financial success as expression of personal radiance and positive energy, and the understanding that money flows easily to those who maintain optimistic outlook and generous spirit. You carry memories of lifetimes where wealth came through joy, celebration, and the ability to attract abundance through charisma, positive energy, and generous sharing of resources with others. This creates a core belief that money should be enjoyed, shared, and used to create happiness and celebration rather than hoarded out of fear or accumulated through struggle and sacrifice.",
    positive: "Natural magnetism for abundance and financial opportunities through positive energy, enthusiastic approach to money goals, and ability to inspire others to support your financial success and prosperity. Your past life experiences have developed understanding that gratitude, generosity, and celebration actually increase rather than decrease financial abundance. You possess inherent wisdom about money as energy that multiplies when shared joyfully and that flows toward people who radiate confidence, appreciation, and positive expectation about their financial future.",
    challenge: "May carry unconscious beliefs that money should always be easy and fun, that financial challenges indicate personal failure or negative thinking, or that planning and budgeting interfere with natural abundance flow. Your past life experiences might have created tendency to take financial abundance for granted or to spend impulsively without adequate consideration for future needs and goals. There may be programming that makes it difficult to deal with financial shadows, setbacks, or the practical work required to maintain and grow wealth over time.",
    advice: "Use your natural magnetism and positive energy around money while also developing practical financial skills and realistic planning that can support and sustain your abundant mindset over time. Learn to maintain optimism and generosity while also creating appropriate boundaries and systems that protect your financial security and enable continued prosperity. Balance your joyful approach to money with responsible stewardship and the wisdom to address financial challenges directly rather than avoiding them in favor of positive thinking alone."
  },
  20: {
    general: "Your past life money mindset is shaped by beliefs about financial awakening, money as spiritual calling, and the understanding that true wealth involves alignment between material resources and soul purpose rather than accumulation for its own sake. You carry memories of lifetimes where financial circumstances were transformed through spiritual awakening, where money decisions were guided by higher purpose and divine calling, and where wealth was viewed as a tool for serving collective evolution and healing. This creates a core belief that money should serve awakening and transformation both for yourself and others.",
    positive: "Natural ability to attract financial resources when aligned with soul purpose and spiritual calling, with understanding that money flows more powerfully when it serves purposes larger than personal comfort or security. Your past life experiences have developed faith in abundance that transcends material circumstances and the ability to make financial decisions based on inner guidance and spiritual principles. You possess inherent wisdom about using money to support awakening, healing, and positive transformation for both yourself and others who are touched by your work and service.",
    challenge: "May carry unconscious beliefs that spiritual calling and financial success are incompatible, that monetizing spiritual work corrupts its purity, or that focusing on money interferes with authentic spiritual development and service. Your past life experiences might have created tendency to sacrifice practical financial needs for spiritual ideals or to expect others to support your spiritual work without adequate exchange or reciprocity. There may be programming that associates money with ego and separation rather than recognizing its potential to support unity and collective healing.",
    advice: "Use your spiritual sensitivity and purpose-driven approach to money while also recognizing that financial abundance can support rather than interfere with your spiritual calling and service to others. Learn to value your spiritual gifts and services appropriately, understanding that receiving fair compensation enables you to continue serving while meeting your own material needs for security and growth. Integrate your understanding of money as spiritual tool with practical skills for creating sustainable abundance that serves both your personal evolution and your contribution to collective awakening."
  },
  21: {
    general: "Your past life money mindset is characterized by beliefs about financial mastery, wealth as achievement, and the understanding that true abundance involves integration of material success with spiritual fulfillment and service to others. You carry memories of lifetimes where financial goals were successfully completed, where wealth was created through skillful effort and wise planning, and where money was used to create lasting benefits for both personal fulfillment and community development. This creates a core belief that financial success should feel complete and satisfying, serving multiple purposes and contributing to overall life fulfillment.",
    positive: "Natural wisdom about creating complete financial success through integration of practical skills, spiritual principles, and service to others, with ability to achieve financial goals that feel satisfying and meaningful rather than empty or purely materialistic. Your past life experiences have developed understanding of wealth as stewardship and the importance of creating financial success that benefits not only yourself but also future generations and communities. You possess inherent knowledge about balancing different aspects of financial life including earning, saving, investing, spending, and giving in ways that create overall harmony and satisfaction.",
    challenge: "May carry unconscious beliefs that financial achievement is an end in itself, that reaching financial goals means the work is complete, or that successful people should rest on their accomplishments rather than continuing to grow and evolve. Your past life experiences might have created tendency to become complacent about money once basic security is achieved or to lose motivation when financial challenges are resolved. There may be programming that makes it difficult to set new financial goals or to continue learning and growing in relationship with money once initial success is achieved.",
    advice: "Use your natural financial wisdom and achievement abilities while remaining open to continued growth, learning, and evolution in your relationship with money and wealth creation. Celebrate your financial accomplishments while also setting new goals that challenge you to expand your understanding and skills around money and service. Channel your mastery into helping others achieve their own financial success and fulfillment, recognizing that true wealth includes both personal achievement and contribution to others' prosperity and well-being."
  },
  22: {
    general: "Your past life money mindset is rooted in beliefs about unlimited financial potential, beginner's mind around money, and the understanding that conventional approaches to wealth may not apply to your unique path and circumstances. You carry memories of lifetimes where financial success came through innovative approaches, where traditional money rules were less relevant than creative thinking and willingness to try new methods, and where abundance flowed through maintaining openness to possibilities rather than limiting beliefs about how money should or shouldn't work. This creates a core belief that financial limitations are largely self-imposed and that there are always new ways to create wealth and abundance.",
    positive: "Natural openness to innovative financial opportunities and unconventional approaches to wealth creation, with willingness to try new methods and explore possibilities that others might dismiss as impractical or unrealistic. Your past life experiences have developed faith in unlimited potential and the understanding that money, like all energy, responds to consciousness and intention in ways that transcend traditional rules and limitations. You possess inherent wisdom about approaching money with fresh perspective and the courage to pioneer new financial territories that others haven't yet explored.",
    challenge: "May carry unconscious beliefs that practical financial planning is unnecessary, that conventional money wisdom doesn't apply to your situation, or that optimism and positive thinking alone are sufficient for creating financial success. Your past life experiences might have created tendency toward financial naivety or impulsiveness without adequate consideration of practical consequences and realistic planning. There may be programming that makes it difficult to learn from others' financial experience or to develop the practical skills and discipline needed for sustained financial success.",
    advice: "Use your natural openness and innovative thinking around money while also developing practical financial skills and learning from others' experience in areas where conventional wisdom can accelerate your success. Balance your faith in unlimited potential with realistic assessment of opportunities, risks, and the practical work required to manifest financial goals in the material world. Channel your pioneer spirit into creating financial approaches that honor both innovation and proven principles, recognizing that true financial mastery includes both creative thinking and practical application."
  }
};