/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Past Life Mistakes Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * karmic patterns from past lives, mistakes to heal, shadow aspects to transform,
 * and lessons carried forward that need conscious attention and healing.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Past Life Mistakes - Karmic patterns and shadows from previous incarnations
 */
export const pastLifeMistakesInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your past life mistakes involve the misuse of personal power and leadership, including patterns of domination, selfishness, and placing ego desires above collective good. You may have been in positions of authority where you ruled through force rather than wisdom, or pursued personal glory at the expense of others' wellbeing. These karmic patterns manifest as challenges with anger, impatience, or difficulty collaborating. The shadow includes tendencies toward tyranny and the need to heal your relationship with power and authority.",
    positive: "Recognition of these patterns allows you to transform past misuse of power into conscious leadership that serves others. Your awareness of the shadow side of authority helps you use power responsibly and inspire others' growth. You can develop authentic confidence that doesn't need to dominate or diminish others to feel strong.",
    challenge: "Continuing patterns of selfishness, impatience, or difficulty sharing power and recognition with others may indicate unresolved karma from past life abuse of authority. Tendency to become angry or aggressive when challenged, or to unconsciously repeat patterns of putting personal desires before collective needs. May struggle with collaborative leadership or accepting others' contributions.",
    advice: "Practice conscious leadership that empowers others rather than seeking personal glory or control. Work on transforming anger and impatience into focused energy for positive change. Develop collaborative skills and learn to find satisfaction in others' success and growth. Use your natural leadership abilities to serve causes larger than personal achievement."
  },
  2: {
    general: "Your past life mistakes involve avoiding responsibility through excessive passivity, manipulation through emotional manipulation or victim consciousness, and failing to develop clear boundaries or direct communication. You may have used sensitivity as a way to avoid taking action or manipulated others through emotional drama rather than expressing needs clearly. These karmic patterns manifest as difficulty with assertion, unclear communication, or emotional overwhelm. The shadow includes passive-aggression and using spiritual or emotional insights to avoid practical responsibility.",
    positive: "Recognition of these patterns allows you to transform past avoidance into conscious receptivity balanced with appropriate action. Your understanding of emotional manipulation helps you communicate authentically and support others without enabling dependency. You can develop genuine spiritual wisdom that includes practical application and clear boundaries.",
    challenge: "Continuing patterns of passive-aggressive behavior, emotional manipulation, or avoiding responsibility by claiming spiritual sensitivity may indicate unresolved karma from past life misuse of receptive gifts. Tendency to become overwhelmed by others' emotions or to use intuitive insights to avoid taking practical action. May struggle with direct communication or setting clear boundaries.",
    advice: "Practice direct, honest communication about your needs and boundaries while maintaining your natural sensitivity and intuition. Work on taking appropriate action based on your insights rather than remaining passive. Develop emotional boundaries that allow you to be supportive without becoming overwhelmed or manipulative."
  },
  3: {
    general: "Your past life mistakes involve using creativity and nurturing abilities to control or possess others, measuring worth through external validation, and creating codependent relationships through excessive giving or emotional manipulation. You may have used beauty, creativity, or caregiving as tools for gaining power or security rather than authentic expression. These karmic patterns manifest as difficulty with boundaries, codependency, or using creative gifts to seek approval rather than authentic expression. The shadow includes possessiveness and conditional love.",
    positive: "Recognition of these patterns allows you to transform past manipulation into authentic generosity and creative expression that doesn't seek to control outcomes. Your understanding of codependency helps you create healthy relationships with balanced giving and receiving. You can develop genuine self-worth that doesn't depend on others' approval or your ability to please them.",
    challenge: "Continuing patterns of codependency, difficulty receiving love, or using creative gifts primarily to gain approval may indicate unresolved karma from past life misuse of nurturing abilities. Tendency to give excessively to maintain relationships or to become possessive when others don't respond as expected. May struggle with authentic self-expression that doesn't seek external validation.",
    advice: "Practice receiving love and support as freely as you give it, and develop self-worth that doesn't depend on others' approval or happiness. Work on creating healthy boundaries in relationships while maintaining your generous nature. Use your creative gifts for authentic expression rather than seeking approval or controlling others' responses."
  },
  4: {
    general: "Your past life mistakes involve rigid authoritarianism, building structures that oppressed rather than supported others, and using rules and traditions to control rather than serve growth. You may have been overly conservative or resistant to necessary change, or used your organizational abilities to maintain power structures that limited others' freedom. These karmic patterns manifest as rigidity, controlling behavior, or difficulty adapting to change. The shadow includes using authority to limit rather than empower others.",
    positive: "Recognition of these patterns allows you to transform past rigidity into flexible structure that supports growth and positive change. Your understanding of the shadow side of authority helps you create systems that empower rather than limit others. You can develop organizational skills that serve collective good while maintaining necessary structure and stability.",
    challenge: "Continuing patterns of rigidity, controlling behavior, or resistance to necessary change may indicate unresolved karma from past life misuse of structural authority. Tendency to become inflexible when security feels threatened or to impose rules that serve control rather than growth. May struggle with adapting to new circumstances or allowing others the freedom to make their own choices.",
    advice: "Practice creating structures and systems that support rather than limit growth and freedom. Work on developing flexibility while maintaining your ability to provide stability and organization. Use your natural authority to empower others rather than maintaining control, and remain open to necessary changes that serve evolution."
  },
  5: {
    general: "Your past life mistakes involve spiritual or intellectual dogmatism, using knowledge or spiritual authority to control others, and imposing beliefs rather than teaching through example and love. You may have been a religious or spiritual authority who became rigid about doctrine or used spiritual concepts to justify judgment and control. These karmic patterns manifest as spiritual superiority, intellectual arrogance, or difficulty accepting different perspectives. The shadow includes using wisdom as a weapon rather than a gift.",
    positive: "Recognition of these patterns allows you to transform past dogmatism into humble wisdom that serves others' authentic spiritual growth. Your understanding of spiritual abuse helps you teach through example and love rather than imposing beliefs. You can develop genuine spiritual authority based on compassion and personal experience rather than external knowledge alone.",
    challenge: "Continuing patterns of spiritual or intellectual superiority, difficulty accepting different beliefs, or using knowledge to judge others may indicate unresolved karma from past life misuse of teaching authority. Tendency to become rigid about spiritual or moral principles or to dismiss others' different approaches to truth. May struggle with remaining open to new learning or admitting when you're wrong.",
    advice: "Practice sharing wisdom with humility and respect for others' individual spiritual journeys. Work on developing intellectual and spiritual flexibility that honors truth while accepting different expressions of it. Use your knowledge to serve others' growth rather than maintaining superiority or control over their beliefs."
  },
  6: {
    general: "Your past life mistakes involve using beauty, charm, or diplomatic skills to manipulate others for personal gain, avoiding necessary conflicts that could have served growth, and creating superficial harmony that prevented authentic relationship development. You may have prioritized appearance and social approval over truth and authentic expression. These karmic patterns manifest as people-pleasing, conflict avoidance, or using charm to get what you want rather than honest communication. The shadow includes vanity and superficial relating.",
    positive: "Recognition of these patterns allows you to transform past manipulation into authentic diplomacy that serves mutual growth and understanding. Your understanding of superficial harmony helps you create genuine peace through honest communication and real conflict resolution. You can develop true beauty that comes from authentic expression rather than external approval.",
    challenge: "Continuing patterns of people-pleasing, conflict avoidance, or using charm to manipulate outcomes may indicate unresolved karma from past life misuse of diplomatic gifts. Tendency to prioritize harmony over truth or to avoid difficult conversations that could deepen relationships. May struggle with authentic self-expression when it might displease others.",
    advice: "Practice authentic communication and honest expression of your feelings and needs while maintaining your natural consideration for others. Work on addressing conflicts directly as opportunities for deeper understanding rather than avoiding them. Use your diplomatic gifts to facilitate genuine resolution rather than superficial peace."
  },
  7: {
    general: "Your past life mistakes involve using competitive drive and determination to dominate or harm others, pursuing victory at any cost without regard for ethical considerations, and allowing aggression and ambition to override compassion and wisdom. You may have been a warrior or leader who achieved goals through violence or manipulation rather than honor. These karmic patterns manifest as excessive competitiveness, aggression, or difficulty with collaborative achievement. The shadow includes using strength to harm rather than protect.",
    positive: "Recognition of these patterns allows you to transform past aggression into conscious strength that protects and empowers others. Your understanding of competitive shadows helps you channel drive toward mutual benefit rather than domination. You can develop warrior energy that serves justice and protection rather than conquest and personal glory.",
    challenge: "Continuing patterns of excessive competitiveness, aggression, or pursuing goals without regard for others' wellbeing may indicate unresolved karma from past life misuse of warrior energy. Tendency to become hostile when challenged or to see others as threats rather than potential allies. May struggle with collaborative achievement or supporting others' success.",
    advice: "Practice channeling your competitive energy toward inspiring mutual excellence rather than defeating others. Work on developing patience and collaboration while maintaining your natural drive and determination. Use your strength to protect and empower others rather than seeking personal victory at others' expense."
  },
  8: {
    general: "Your past life mistakes involve enabling others' harmful behavior through excessive patience, avoiding necessary action by hiding behind spiritual concepts of acceptance, and failing to use your strength when intervention could have prevented suffering. You may have been overly passive in situations requiring courage and action. These karmic patterns manifest as codependency, difficulty with healthy anger, or avoiding responsibility by claiming spiritual detachment. The shadow includes spiritual bypassing and enabling dysfunction.",
    positive: "Recognition of these patterns allows you to transform past passivity into conscious compassion that includes appropriate action and healthy boundaries. Your understanding of enabling helps you support others without taking responsibility for their choices. You can develop genuine strength that knows when to act and when to accept with wisdom.",
    challenge: "Continuing patterns of enabling destructive behavior, avoiding necessary action, or using spiritual concepts to justify passivity may indicate unresolved karma from past life misuse of acceptance and patience. Tendency to endure abuse or harmful situations rather than taking protective action. May struggle with expressing anger or setting firm boundaries when necessary.",
    advice: "Practice using your natural compassion and strength to take appropriate action when situations require intervention rather than just accepting harmful circumstances. Work on developing healthy expression of anger and firm boundaries that protect yourself and others. Balance acceptance with wisdom about when action serves love and healing."
  },
  9: {
    general: "Your past life mistakes involve spiritual or intellectual isolation that avoided responsibility for practical service, using wisdom to judge others rather than help them, and becoming disconnected from human needs and emotions in pursuit of abstract knowledge. You may have been a scholar or hermit who became superior or withdrawn from ordinary human concerns. These karmic patterns manifest as intellectual arrogance, emotional detachment, or avoiding practical engagement with life. The shadow includes using wisdom to separate from rather than serve others.",
    positive: "Recognition of these patterns allows you to transform past isolation into conscious solitude balanced with meaningful service and engagement. Your understanding of intellectual pride helps you share wisdom humbly and practically. You can develop genuine spiritual understanding that includes compassion for human struggles and practical application.",
    challenge: "Continuing patterns of intellectual superiority, emotional withdrawal, or avoiding practical responsibilities through spiritual or academic pursuits may indicate unresolved karma from past life misuse of wisdom gifts. Tendency to judge others' less contemplative approaches or to retreat from emotional connection when challenged. May struggle with translating insights into practical service.",
    advice: "Practice sharing your wisdom through practical service and emotional connection rather than remaining in isolated contemplation. Work on developing humility and compassion for different approaches to life and learning. Use your insights to help others navigate practical challenges rather than maintaining superiority or separation."
  },
  10: {
    general: "Your past life mistakes involve fatalistic passivity that avoided personal responsibility, using belief in destiny or karma to justify inaction when intervention was needed, and failing to exercise appropriate choice and will in shaping circumstances. You may have become overly dependent on external authorities or fate rather than developing personal agency. These karmic patterns manifest as victim consciousness, avoiding responsibility, or waiting for external rescue rather than taking action. The shadow includes spiritual laziness and avoiding accountability.",
    positive: "Recognition of these patterns allows you to transform past fatalism into conscious participation in creating your life within larger cosmic patterns. Your understanding of victim consciousness helps you take appropriate responsibility while maintaining faith in divine support. You can develop genuine spiritual understanding that includes personal accountability and inspired action.",
    challenge: "Continuing patterns of victim consciousness, avoiding responsibility by attributing everything to fate, or waiting for external rescue rather than taking action may indicate unresolved karma from past life abdication of personal power. Tendency to become passive when challenges require initiative or to blame circumstances rather than examining your own choices. May struggle with decision-making or taking appropriate action.",
    advice: "Practice taking appropriate responsibility for your life circumstances while maintaining faith in divine timing and support. Work on developing decision-making skills and the ability to take inspired action when opportunities arise. Balance acceptance of what you cannot control with appropriate effort to create positive change where you have influence."
  },
  11: {
    general: "Your past life mistakes involve rigid judgment and punishment that lacked compassion, using moral authority to control rather than guide others, and creating systems of justice that served power rather than healing and growth. You may have been a judge or authority figure who applied rules without wisdom or mercy. These karmic patterns manifest as judgmental thinking, moral rigidity, or difficulty with forgiveness and mercy. The shadow includes using justice as a weapon rather than a healing tool.",
    positive: "Recognition of these patterns allows you to transform past rigidity into compassionate justice that serves healing and growth rather than punishment. Your understanding of judgmental shadows helps you apply moral principles with wisdom and mercy. You can develop genuine ethical understanding that includes forgiveness and the possibility of redemption.",
    challenge: "Continuing patterns of judgmental thinking, moral rigidity, or difficulty with forgiveness may indicate unresolved karma from past life misuse of judicial authority. Tendency to apply rules without considering individual circumstances or to hold grudges rather than allowing for growth and change. May struggle with mercy or seeing the good in those who have made mistakes.",
    advice: "Practice applying moral principles with wisdom and compassion that serves healing rather than punishment. Work on developing forgiveness and the ability to see potential for growth and redemption in yourself and others. Use your sense of justice to create healing and positive change rather than maintaining rigid judgment."
  },
  12: {
    general: "Your past life mistakes involve martyrdom and victim consciousness that manipulated others through guilt and suffering, using sacrifice to control outcomes rather than serving authentic growth, and avoiding direct action by claiming spiritual surrender when intervention was needed. You may have used suffering as a way to gain power or avoid responsibility. These karmic patterns manifest as manipulation through victimhood, guilt-inducing behavior, or avoiding responsibility by claiming helplessness. The shadow includes using sacrifice as a form of control.",
    positive: "Recognition of these patterns allows you to transform past manipulation into authentic service and healthy sacrifice that empowers rather than controls others. Your understanding of victim consciousness helps you take appropriate responsibility while maintaining compassion. You can develop genuine spiritual surrender that includes wise action when called for.",
    challenge: "Continuing patterns of manipulating through guilt or victimhood, avoiding responsibility by claiming spiritual surrender, or using sacrifice to control others' behavior may indicate unresolved karma from past life misuse of suffering and sacrifice. Tendency to create drama or crisis to gain attention or control outcomes. May struggle with taking direct action or expressing needs clearly.",
    advice: "Practice authentic service and healthy sacrifice that empowers others rather than creating guilt or obligation. Work on taking appropriate responsibility for your life while maintaining genuine compassion and spiritual understanding. Express your needs directly rather than manipulating through suffering or victimhood."
  },
  13: {
    general: "Your past life mistakes involve creating unnecessary destruction and chaos, using transformation as an excuse to avoid commitment and responsibility, and destroying what could have been healed or improved rather than doing the patient work of genuine transformation. You may have used change as a way to escape consequences or avoid deep growth. These karmic patterns manifest as creating drama, avoiding commitment, or destroying relationships and situations when they become challenging. The shadow includes using transformation to avoid rather than facilitate real growth.",
    positive: "Recognition of these patterns allows you to transform past destructiveness into conscious transformation that serves genuine growth and healing. Your understanding of chaotic patterns helps you create positive change through commitment and patience rather than destruction. You can develop genuine transformation abilities that heal and renew rather than just ending things.",
    challenge: "Continuing patterns of creating unnecessary drama, avoiding commitment through constant change, or destroying situations rather than working through challenges may indicate unresolved karma from past life misuse of transformative energy. Tendency to abandon relationships or projects when they require sustained effort or patience. May struggle with building lasting foundations or working through difficulties constructively.",
    advice: "Practice creating conscious, constructive change that builds better foundations rather than just destroying what doesn't work perfectly. Work on developing commitment and patience for the slow work of genuine transformation and healing. Use your understanding of change to support growth rather than avoiding responsibility or consequences."
  },
  14: {
    general: "Your past life mistakes involve avoiding necessary intensity and passion that could have served growth, suppressing vital life force in the name of balance and moderation, and failing to take strong stands when situations required clear positions and decisive action. You may have used spiritual concepts of balance to avoid engagement with life's challenges. These karmic patterns manifest as emotional suppression, avoiding conflict, or lack of passion and commitment. The shadow includes spiritual bypassing through false balance.",
    positive: "Recognition of these patterns allows you to transform past avoidance into dynamic balance that includes appropriate intensity and passionate engagement when they serve growth. Your understanding of emotional suppression helps you embrace the full spectrum of human experience. You can develop genuine moderation that enhances rather than limits authentic expression and commitment.",
    challenge: "Continuing patterns of emotional suppression, avoiding necessary conflict, or lack of passionate engagement with life may indicate unresolved karma from past life misuse of balance and moderation. Tendency to maintain surface peace rather than working through important issues that need attention. May struggle with commitment or taking strong positions when situations require clear stands.",
    advice: "Practice embracing appropriate intensity and passionate engagement while maintaining your natural wisdom about balance and moderation. Work on expressing strong emotions constructively rather than suppressing them in the name of peace. Use your healing abilities to work with conflict and challenge rather than avoiding them."
  },
  15: {
    general: "Your past life mistakes involve using power to exploit and manipulate others for personal gain, becoming obsessed with material accumulation and control at the expense of spiritual development, and using knowledge of human shadow to harm rather than heal. You may have been involved in dark arts, exploitation, or abuse of power that served ego rather than soul growth. These karmic patterns manifest as manipulation, obsession with control, or difficulty with healthy relationships and boundaries. The shadow includes using power to dominate and exploit rather than empower.",
    positive: "Recognition of these patterns allows you to transform past exploitation into conscious power use that serves healing and empowerment of others. Your understanding of shadow dynamics helps you work with difficult energies constructively rather than destructively. You can develop genuine spiritual power that serves love and liberation rather than control and domination.",
    challenge: "Continuing patterns of manipulation, obsession with control or material gain, or using psychological insights to exploit others may indicate unresolved karma from past life abuse of power. Tendency to become possessive or controlling in relationships or to use charm and understanding to manipulate outcomes. May struggle with ethical use of influence and power.",
    advice: "Practice using your understanding of power and human nature always in service of others' empowerment and healing rather than personal gain or control. Work on developing healthy relationships based on mutual respect rather than manipulation or dominance. Channel your intensity toward conscious transformation rather than exploitation or possession."
  },
  16: {
    general: "Your past life mistakes involve using revolutionary energy to destroy rather than transform, creating chaos and upheaval without building better alternatives, and shocking or traumatizing others with truth rather than helping them integrate insights gradually. You may have been a destructive revolutionary who tore down structures without wisdom about what should replace them. These karmic patterns manifest as creating unnecessary drama, shocking others, or destroying rather than transforming. The shadow includes using revelation as a weapon rather than a gift.",
    positive: "Recognition of these patterns allows you to transform past destructiveness into conscious revolution that builds better alternatives while breaking down limiting structures. Your understanding of shock and trauma helps you communicate insights in ways that others can integrate. You can develop genuine liberation abilities that free rather than harm others.",
    challenge: "Continuing patterns of creating unnecessary shock or drama, destroying without building alternatives, or communicating insights in ways that traumatize rather than heal may indicate unresolved karma from past life misuse of revolutionary energy. Tendency to be insensitive to others' capacity for change or to prioritize dramatic effect over genuine helpfulness. May struggle with patience for gradual change or building sustainable improvements.",
    advice: "Practice using your gift for breakthrough and liberation to create positive alternatives rather than just destroying what doesn't work. Work on communicating insights in ways that others can receive and integrate gradually rather than shocking them. Channel your revolutionary energy toward building better structures and relationships rather than just tearing down existing ones."
  },
  17: {
    general: "Your past life mistakes involve spiritual bypassing and false hope that avoided dealing with practical realities, creating unrealistic expectations that led to disappointment and disillusionment, and using spiritual concepts to escape rather than transform earthly challenges. You may have been overly idealistic in ways that ignored practical needs or realistic limitations. These karmic patterns manifest as unrealistic expectations, spiritual bypassing, or difficulty with practical implementation of ideals. The shadow includes using hope and faith to avoid rather than inspire action.",
    positive: "Recognition of these patterns allows you to transform past escapism into grounded spirituality that includes practical action and realistic approaches to manifesting ideals. Your understanding of spiritual bypassing helps you maintain hope while engaging constructively with current realities. You can develop genuine inspiration that motivates practical positive change rather than just beautiful visions.",
    challenge: "Continuing patterns of unrealistic expectations, avoiding practical responsibilities through spiritual focus, or creating disappointment by promising more than can be delivered may indicate unresolved karma from past life misuse of spiritual idealism. Tendency to focus on future possibilities while neglecting present opportunities and responsibilities. May struggle with practical implementation of spiritual insights.",
    advice: "Practice grounding your spiritual vision in practical action and realistic steps that create real positive change in the present moment. Work on maintaining hope and inspiration while engaging constructively with current challenges and limitations. Use your faith to motivate practical service rather than escaping from earthly responsibilities."
  },
  18: {
    general: "Your past life mistakes involve using psychic abilities to deceive and manipulate others, becoming lost in illusion and fantasy rather than serving truth and clarity, and avoiding responsibility through confusion and unclear communication. You may have been involved in deception, illusion, or using psychic gifts to gain power over others rather than serving their highest good. These karmic patterns manifest as confusion, deception, or difficulty distinguishing between truth and illusion. The shadow includes using mystical gifts to manipulate rather than heal.",
    positive: "Recognition of these patterns allows you to transform past deception into clear psychic discernment that serves truth and healing. Your understanding of illusion helps you guide others toward clarity rather than confusion. You can develop genuine mystical abilities that serve wisdom and healing rather than manipulation and control.",
    challenge: "Continuing patterns of confusion, unclear communication, or difficulty distinguishing between intuition and projection may indicate unresolved karma from past life misuse of psychic abilities. Tendency to create confusion or use emotional manipulation rather than clear, honest communication. May struggle with maintaining clear boundaries between your own energy and others' projections.",
    advice: "Practice developing clear discernment between genuine intuitive guidance and emotional projection or wishful thinking. Work on communicating insights clearly and honestly rather than creating confusion or mystery. Use your psychic sensitivity to serve clarity and healing rather than maintaining power through confusion or manipulation."
  },
  19: {
    general: "Your past life mistakes involve narcissism and ego-inflation that ignored others' needs and contributions, using charisma and success to exploit rather than serve others, and becoming addicted to admiration and external validation at the expense of authentic development. You may have been a performer or leader who used natural magnetism for personal gain rather than collective benefit. These karmic patterns manifest as narcissistic behavior, need for constant admiration, or difficulty with genuine humility. The shadow includes using success and charisma to exploit rather than inspire.",
    positive: "Recognition of these patterns allows you to transform past narcissism into authentic confidence that serves and inspires others rather than seeking personal glory. Your understanding of ego-inflation helps you use success and charisma responsibly. You can develop genuine radiance that comes from authentic achievement and service rather than just external validation.",
    challenge: "Continuing patterns of narcissistic behavior, excessive need for admiration, or using success to gain power over others may indicate unresolved karma from past life misuse of natural magnetism and charisma. Tendency to become depressed when not receiving adequate attention or to compete rather than collaborate for recognition. May struggle with genuine humility or supporting others' success.",
    advice: "Practice using your natural charisma and success to inspire and serve others rather than seeking personal glory or admiration. Work on developing authentic self-worth that doesn't depend entirely on external recognition or achievement. Share your gifts generously while maintaining genuine humility about your accomplishments."
  },
  20: {
    general: "Your past life mistakes involve spiritual grandiosity and messiah complex that claimed divine authority inappropriately, using spiritual calling to justify ignoring earthly responsibilities and relationships, and creating spiritual movements or teachings that served ego rather than genuine awakening. You may have been a spiritual leader who became corrupted by power or lost touch with humility and human compassion. These karmic patterns manifest as spiritual superiority, neglecting practical responsibilities, or using spiritual concepts to justify selfish behavior. The shadow includes spiritual narcissism and false prophecy.",
    positive: "Recognition of these patterns allows you to transform past spiritual arrogance into humble service that genuinely supports collective awakening and individual spiritual growth. Your understanding of spiritual corruption helps you maintain integrity and humility in spiritual service. You can develop authentic spiritual authority based on genuine wisdom and compassion rather than ego-inflation.",
    challenge: "Continuing patterns of spiritual superiority, neglecting earthly responsibilities for spiritual pursuits, or using spiritual calling to justify selfish behavior may indicate unresolved karma from past life misuse of spiritual authority. Tendency to claim special status or divine connection inappropriately or to judge others as spiritually inferior. May struggle with maintaining human humility while serving spiritual purposes.",
    advice: "Practice serving spiritual awakening and growth with genuine humility and respect for others' individual spiritual journeys. Work on balancing spiritual calling with attention to practical responsibilities and human relationships. Use any spiritual authority you have to empower others' authentic development rather than maintaining special status or control."
  },
  21: {
    general: "Your past life mistakes involve spiritual pride and complacency that stopped growing and serving others, using achievements to maintain superiority rather than inspiring others' development, and becoming disconnected from the ongoing learning process and beginner's mind. You may have achieved mastery but then became stagnant or used accomplishments to separate yourself from others rather than serving their growth. These karmic patterns manifest as spiritual or intellectual pride, resistance to continued learning, or difficulty relating to others' developmental process. The shadow includes using mastery to separate rather than serve.",
    positive: "Recognition of these patterns allows you to transform past pride into humble mastery that continues to grow while serving others' development. Your understanding of spiritual stagnation helps you maintain beginner's mind and connection to the learning process. You can develop genuine accomplishment that inspires and supports rather than intimidates or separates.",
    challenge: "Continuing patterns of spiritual or intellectual pride, resistance to continued learning, or difficulty relating to others who are less developed may indicate unresolved karma from past life misuse of achievement and mastery. Tendency to rest on past accomplishments rather than continuing to grow or to judge others' efforts as inferior. May struggle with maintaining humility and connection to the learning process.",
    advice: "Practice using your achievements and mastery to support others' development while remaining open to continued learning and growth yourself. Work on maintaining humility and connection to the beginner's mind even as you share your expertise. Remember that true mastery includes continued service and evolution rather than static accomplishment."
  },
  22: {
    general: "Your past life mistakes involve spiritual or practical immaturity that avoided necessary learning and development, using innocence as an excuse to avoid responsibility or consequences, and failing to develop wisdom and skills needed to serve effectively. You may have remained childlike in ways that served avoidance rather than authentic openness. These karmic patterns manifest as avoidance of responsibility, difficulty with commitment, or using innocence to manipulate others. The shadow includes false innocence that avoids accountability.",
    positive: "Recognition of these patterns allows you to transform past avoidance into conscious choice about when to maintain beginner's mind and when to develop expertise and take responsibility. Your understanding of false innocence helps you balance openness with appropriate wisdom and accountability. You can develop genuine fresh perspective that enhances rather than avoids mature development.",
    challenge: "Continuing patterns of avoiding responsibility, difficulty with sustained commitment, or using innocence or confusion to avoid consequences may indicate unresolved karma from past life misuse of fresh perspective and openness. Tendency to abandon projects when they require sustained effort or to claim ignorance when accountability is needed. May struggle with developing expertise or learning from others' experience.",
    advice: "Practice balancing your natural openness and fresh perspective with willingness to develop expertise and take appropriate responsibility. Work on maintaining wonder and curiosity while also learning from experience and committing to sustained development. Use your gift for seeing new possibilities to enhance rather than avoid the value of wisdom and mature commitment."
  }
};