/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Power of Ancestors Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * the ancestral wisdom, energy, and support available to you through
 * your family lineage and spiritual inheritance.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Power of Ancestors - How ancestral wisdom and energy supports you
 */
export const powerOfAncestorsInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your ancestral line carries the powerful energy of leaders, innovators, and pioneers who blazed new trails and created opportunities for future generations through courage, determination, and visionary thinking. You inherit the cellular memory of ancestors who took initiative, started new ventures, and had the courage to break away from tradition when necessary to create better circumstances. This lineage provides you with natural confidence, leadership abilities, and the inner knowing that you have the power to create your own path and manifest your vision in the world.",
    positive: "Strong ancestral backing for leadership roles, entrepreneurial ventures, and any situation requiring personal initiative and creative problem-solving. Your lineage carries the accumulated wisdom of successful leaders who overcame obstacles and created lasting change through determination and vision. You have access to powerful ancestral energy that supports your confidence, helps you take calculated risks, and provides the inner strength needed to persist through challenges that would discourage others.",
    challenge: "May carry the ancestral burden of having to be strong and self-reliant all the time, with family patterns that discourage vulnerability or asking for help when needed. Your lineage may include ancestors who sacrificed personal relationships or emotional well-being for success, creating patterns of isolation or difficulty accepting support from others. There may be ancestral pressure to achieve or lead that feels overwhelming, especially if previous generations faced significant hardships or responsibilities.",
    advice: "Honor your ancestral leadership gifts while allowing yourself to receive support and share responsibilities with others rather than carrying everything alone as some ancestors may have done. Use your inherited leadership abilities to create positive change while also breaking any family patterns of isolation or emotional unavailability that may have developed. Connect with the strength of your lineage while also healing any wounds around the burden of leadership and creating space for vulnerability and interdependence."
  },
  2: {
    general: "Your ancestral line is rich with wise women, healers, mystics, and intuitive beings who served as bridges between the seen and unseen worlds, often holding space for community healing and spiritual guidance. You inherit deep psychic abilities, emotional sensitivity, and natural healing gifts that have been passed down through generations of ancestors who understood the mysteries of life and death. This lineage provides you with access to ancient wisdom, intuitive knowing, and the ability to sense what others need for healing and growth.",
    positive: "Deep connection to ancestral wisdom traditions, psychic abilities, and healing gifts that have been refined and strengthened through multiple generations of spiritual practitioners. Your lineage provides you with natural access to intuitive guidance, dreams, and spiritual insights that can help you navigate life's challenges and serve others. You have inherited the ability to hold sacred space, facilitate healing, and bridge different worlds or perspectives through your sensitive, intuitive nature.",
    challenge: "May carry ancestral trauma around persecution, suppression, or punishment for psychic gifts and healing abilities, creating fear about fully expressing or monetizing your intuitive talents. Your lineage may include ancestors who were misunderstood, rejected, or even harmed for their spiritual gifts, leading to unconscious patterns of hiding your abilities or downplaying their value. There may be ancestral patterns of martyrdom or giving away gifts freely without appropriate recognition or compensation.",
    advice: "Trust your inherited intuitive abilities and use them confidently to heal both ancestral wounds and current challenges, knowing that expressing your gifts fully honors your lineage. Work to heal any ancestral trauma around persecution by creating safe spaces to share your abilities and finding communities that appreciate and support your spiritual gifts. Break patterns of undervaluing your intuitive services by charging appropriately and recognizing that your gifts are valuable contributions that deserve fair exchange."
  },
  3: {
    general: "Your ancestral line carries the abundant energy of creators, mothers, nurturers, and builders of community who understood how to manifest resources and create beauty and fertility in their environment. You inherit the wisdom of ancestors who knew how to work with natural cycles, create sustainable abundance, and nurture others while also caring for themselves. This lineage provides you with natural creativity, generosity, and the ability to see potential and help it flourish in yourself and others.",
    positive: "Strong ancestral support for creativity, fertility, abundance, and the ability to nurture and grow whatever you focus your attention on with patience and love. Your lineage carries the accumulated wisdom of successful creators and community builders who knew how to manifest resources and create beautiful, nourishing environments. You have access to ancestral energy that supports your natural generosity, helps you attract resources, and provides guidance for creating sustainable abundance.",
    challenge: "May carry ancestral patterns of over-giving, sacrifice, or putting others' needs before your own, potentially repeating family dynamics where caregivers became depleted or resentful. Your lineage may include ancestors who gave so much to others that they neglected their own needs, creating patterns of boundary issues or difficulty receiving care and support. There may be ancestral memories of times when resources were scarce, leading to either hoarding or compulsive giving behaviors.",
    advice: "Channel your ancestral nurturing wisdom while maintaining healthy boundaries that allow you to give generously without depleting yourself or creating resentment in relationships. Honor the creative and abundant energy of your lineage while also healing any patterns of sacrifice or scarcity that may have developed during difficult times. Use your inherited gifts for manifestation and nurturing to create abundance that serves both yourself and others in sustainable, balanced ways."
  },
  4: {
    general: "Your ancestral line includes builders, protectors, organizers, and leaders who created lasting structures, institutions, and systems that provided security and stability for future generations. You inherit the wisdom of ancestors who understood the importance of creating solid foundations, planning for the future, and building things that would endure beyond their own lifetime. This lineage provides you with natural organizational abilities, practical wisdom, and the patience needed to create lasting success through systematic effort.",
    positive: "Solid ancestral foundation for creating lasting structures, building wealth, and organizing resources effectively for long-term security and success. Your lineage carries the accumulated experience of successful builders and managers who knew how to create systems that could weather challenges and provide stability. You have access to ancestral wisdom about practical matters, strategic planning, and the patience required to build something meaningful and enduring.",
    challenge: "May carry the ancestral burden of excessive responsibility or rigid expectations, with family patterns that emphasize duty and achievement over emotional expression or personal fulfillment. Your lineage may include ancestors who sacrificed personal happiness or creativity for security and stability, creating pressure to maintain traditional roles or approaches even when they no longer serve. There may be ancestral patterns of resistance to change or difficulty adapting when circumstances require flexibility.",
    advice: "Build on the solid foundation and practical wisdom of your ancestral lineage while allowing for growth, change, and emotional expression that some ancestors may have suppressed. Use your inherited organizational abilities and strategic thinking to create structures that support both security and personal fulfillment rather than choosing one over the other. Honor the stability your ancestors created while also bringing more flexibility and adaptability to family patterns that may have become too rigid over time."
  },
  5: {
    general: "Your ancestral line includes teachers, priests, wisdom keepers, and spiritual authorities who served as bridges between divine wisdom and earthly communities, often holding important knowledge and moral guidance for others. You inherit the deep spiritual understanding and teaching abilities that have been cultivated through generations of ancestors who dedicated their lives to learning, growing, and sharing wisdom with others. This lineage provides you with natural access to spiritual traditions, moral guidance, and the ability to help others find their path of growth and development.",
    positive: "Strong ancestral connection to spiritual traditions, wisdom teachings, and moral guidance that can support your own growth and help you serve others as a teacher or guide. Your lineage carries the accumulated knowledge of spiritual practitioners and teachers who understood the deeper meaning of life and how to live according to higher principles. You have access to ancestral wisdom about spiritual development, ethical behavior, and the patience required for genuine learning and growth.",
    challenge: "May carry ancestral religious trauma, rigid belief systems, or patterns of judgment that limit your ability to explore diverse spiritual paths or accept others' different approaches. Your lineage may include ancestors who experienced persecution, dogmatism, or spiritual abuse, creating fear around religious or spiritual expression. There may be ancestral patterns of spiritual superiority or judgment that create separation rather than connection with others.",
    advice: "Honor the spiritual wisdom and teaching abilities of your ancestral lineage while finding your own authentic spiritual path that may differ from traditional family beliefs. Use your inherited connection to higher wisdom to serve others while also healing any ancestral wounds around religious trauma or spiritual dogmatism. Break patterns of spiritual judgment by embracing a more inclusive, compassionate approach that honors diverse paths while maintaining your own spiritual integrity."
  },
  6: {
    general: "Your ancestral line carries the harmonious energy of artists, diplomats, peacemakers, and lovers who understood the importance of beauty, relationship, and creating win-win solutions that served everyone involved. You inherit the wisdom of ancestors who were skilled at bringing people together, creating aesthetic beauty, and finding balance between competing needs or perspectives. This lineage provides you with natural diplomatic abilities, aesthetic sense, and the gift for creating harmony in relationships and environments.",
    positive: "Natural ancestral gifts for creating harmony, beauty, and loving relationships, with inherited abilities for diplomacy, aesthetic expression, and bringing out the best in others. Your lineage carries the accumulated wisdom of successful artists, mediators, and relationship builders who knew how to create beauty and resolve conflicts peacefully. You have access to ancestral energy that supports your partnerships, helps you create beautiful environments, and provides guidance for maintaining balance in all areas of life.",
    challenge: "May carry ancestral patterns of avoiding conflict, people-pleasing, or maintaining surface harmony at the expense of authentic expression or necessary confrontation. Your lineage may include ancestors who suppressed their own needs or authentic feelings to keep peace, creating patterns of codependency or difficulty with assertiveness. There may be ancestral wounds around betrayal, relationship loss, or having to choose between love and other important values.",
    advice: "Use your ancestral diplomatic gifts and relationship abilities while maintaining authentic self-expression and healthy boundaries that some ancestors may have sacrificed for harmony. Honor the beauty and peace-making traditions of your lineage while also learning to engage in necessary conflicts constructively rather than avoiding them. Heal any ancestral wounds around relationships by creating partnerships that honor both harmony and individual authenticity."
  },
  7: {
    general: "Your ancestral line includes warriors, travelers, pioneers, and achievers who faced significant challenges with courage and determination, often overcoming obstacles that seemed impossible to others. You inherit the fierce energy and resilience of ancestors who never gave up, who fought for what they believed in, and who had the strength to keep moving forward even when the path was difficult. This lineage provides you with natural courage, determination, and the inner fire needed to overcome obstacles and achieve your goals.",
    positive: "Strong ancestral backing for overcoming obstacles, achieving goals, and protecting what matters most, with inherited courage and determination that helps you persist when others might give up. Your lineage carries the accumulated strength of warriors and pioneers who faced tremendous challenges and found ways to triumph through sheer will and strategic action. You have access to ancestral energy that supports your courage, helps you take necessary risks, and provides the fierce determination needed to fight for your values and dreams.",
    challenge: "May carry ancestral battle trauma, patterns of aggression, or difficulty with peace and stillness due to generations of ancestors who had to fight for survival or justice. Your lineage may include ancestors who experienced war, persecution, or constant struggle, creating patterns of hypervigilance, anger, or difficulty trusting that peace is possible. There may be ancestral wounds around violence, loss, or having to choose between personal safety and standing up for principles.",
    advice: "Channel your ancestral warrior energy and courage into purposeful action and protection of what you value most, while also healing any trauma or aggression patterns that no longer serve. Use your inherited determination and fighting spirit to create positive change rather than perpetuating cycles of conflict or struggle that may have been necessary for previous generations. Honor the strength of your lineage while also learning to embrace peace, rest, and collaboration when they are appropriate and available."
  },
  8: {
    general: "Your ancestral line includes healers, shamans, gentle strength holders, and those who possessed the quiet power to transform suffering into wisdom and help others find their inner strength. You inherit the deep healing abilities and emotional resilience of ancestors who understood that true power comes from within and that patience and compassion can overcome even the greatest challenges. This lineage provides you with natural healing gifts, emotional intelligence, and the ability to remain centered during difficult times.",
    positive: "Deep ancestral connection to healing abilities, inner strength, and the power to transform challenges into wisdom and growth for yourself and others. Your lineage carries the accumulated knowledge of healers and wise ones who knew how to work with energy, emotions, and the subtle forces that create change and healing. You have access to ancestral wisdom about patience, compassion, and the gentle power that can move mountains through persistence and love.",
    challenge: "May carry ancestral trauma around persecution, suppression, or punishment for healing gifts and unconventional wisdom, creating fear about fully expressing your abilities or standing in your power. Your lineage may include ancestors who were misunderstood, rejected, or harmed for their healing gifts, leading to patterns of hiding your abilities or downplaying your strength. There may be ancestral patterns of taking on others' pain or sacrificing personal well-being for the sake of helping others.",
    advice: "Trust your inherited healing abilities and use them confidently to transform both ancestral pain and current challenges, knowing that fully expressing your gifts honors your lineage. Work to heal any ancestral trauma around persecution by creating safe spaces to share your abilities and finding communities that value and support your healing gifts. Break patterns of taking on too much responsibility for others' healing by maintaining healthy boundaries while still offering your natural compassion and support."
  },
  9: {
    general: "Your ancestral line includes wise elders, hermits, seekers of truth, and keepers of ancient knowledge who dedicated their lives to understanding the deeper mysteries of existence and sharing their insights with others. You inherit the profound wisdom and introspective abilities of ancestors who spent lifetimes contemplating life's deeper questions and developing spiritual understanding. This lineage provides you with natural access to ancient wisdom, intuitive knowing, and the patience needed for deep understanding and spiritual development.",
    positive: "Ancient ancestral wisdom available for guidance, spiritual insight, and understanding of life's deeper patterns and meanings. Your lineage carries the accumulated knowledge of wise teachers, philosophers, and spiritual seekers who developed profound understanding through years of study and contemplation. You have access to ancestral guidance that can help you navigate complex situations, understand patterns that others miss, and provide wisdom and perspective to those who seek your counsel.",
    challenge: "May carry ancestral patterns of isolation, withdrawal from the world, or difficulty connecting with others due to generations of ancestors who spent much time in solitude or study. Your lineage may include ancestors who became so focused on spiritual or intellectual pursuits that they struggled with practical matters or intimate relationships. There may be ancestral patterns of feeling misunderstood or separate from others due to advanced spiritual or intellectual development.",
    advice: "Access the profound wisdom of your ancestral lineage while maintaining connection to current life and relationships rather than withdrawing into isolation as some ancestors may have done. Use your inherited spiritual understanding and insight to serve others while also staying grounded in practical matters and human connection. Balance your natural tendency toward solitude and contemplation with regular engagement in the world where your wisdom is needed and appreciated."
  },
  10: {
    general: "Your ancestral line is connected to the great cycles of fate, destiny, and natural law, with ancestors who understood the larger patterns that govern life and how to work with rather than against these powerful forces. You inherit the wisdom of ancestors who experienced dramatic ups and downs in life and learned to navigate major changes and transitions with grace and understanding. This lineage provides you with natural understanding of timing, cycles, and the larger forces that shape human experience.",
    positive: "Natural understanding of life cycles, timing, and karmic patterns inherited from ancestors who learned to work with destiny and fate rather than fighting against them. Your lineage carries the accumulated wisdom of those who experienced major life changes and transitions and developed resilience and perspective about the larger patterns that govern human experience. You have access to ancestral guidance about timing, patience, and how to recognize when major changes or opportunities are approaching.",
    challenge: "May carry ancestral karma or feel bound by family patterns and inherited obligations that limit your freedom to create your own path and destiny. Your lineage may include ancestors who experienced significant trauma, loss, or dramatic reversals of fortune, creating patterns of fatalism or fear about taking risks. There may be ancestral patterns of feeling powerless or believing that external forces control your life rather than recognizing your power to influence outcomes.",
    advice: "Work with ancestral karma and family patterns consciously to transform limiting cycles and create new, more positive destinies for yourself and future generations. Use your inherited understanding of life's larger patterns to navigate changes and transitions while also taking active responsibility for creating the life you want. Honor the wisdom your ancestors gained through their experiences while also breaking free from any limiting beliefs or patterns that no longer serve your highest potential."
  },
  11: {
    general: "Your ancestral line includes judges, lawyers, justice seekers, and moral leaders who dedicated their lives to creating fairness, upholding ethical principles, and ensuring that truth and justice prevailed in their communities. You inherit the strong moral foundation and sense of justice that has been developed through generations of ancestors who stood up for what was right even when it was difficult or unpopular. This lineage provides you with natural integrity, ethical clarity, and the courage needed to stand up for justice and truth.",
    positive: "Strong ancestral foundation for fairness, justice, and moral decision-making, with inherited integrity and ethical principles that guide you toward right action. Your lineage carries the accumulated wisdom of those who understood the importance of treating others fairly and creating systems that serve the greater good. You have access to ancestral guidance about ethical behavior, moral courage, and the wisdom needed to make difficult decisions that balance competing needs and interests.",
    challenge: "May carry ancestral burden of judgment, rigid moral expectations, or patterns of criticism that create separation rather than healing and understanding. Your lineage may include ancestors who became overly focused on right and wrong in ways that limited compassion or flexibility when situations required nuanced understanding. There may be ancestral patterns of perfectionism, self-righteousness, or difficulty forgiving mistakes and imperfections in yourself and others.",
    advice: "Balance the strong sense of justice and integrity inherited from your ancestral lineage with compassion, forgiveness, and understanding of human complexity and imperfection. Use your natural moral clarity and ethical principles to create positive change while also healing any ancestral patterns of judgment or rigidity that may limit your effectiveness. Honor the justice-seeking tradition of your lineage while also developing the flexibility and compassion needed to work with others who may have different values or approaches."
  },
  12: {
    general: "Your ancestral line includes martyrs, mystics, sacrificial figures, and those who willingly gave up personal comfort or gain for the sake of higher purpose, spiritual understanding, or service to others. You inherit the deep wisdom that comes from understanding sacrifice, surrender, and the willingness to let go of ego needs for greater spiritual understanding. This lineage provides you with access to profound spiritual insights, the ability to see situations from multiple perspectives, and wisdom about when to sacrifice and when to preserve your energy.",
    positive: "Deep ancestral understanding of sacrifice, surrender, and the wisdom that comes from letting go of ego attachments for higher spiritual understanding and service. Your lineage carries the accumulated insights of those who learned to see beyond surface appearances and understood the deeper spiritual lessons available through difficult experiences. You have access to ancestral guidance about patience, acceptance, and the transformative power of conscious sacrifice for meaningful purposes.",
    challenge: "May carry ancestral patterns of martyrdom, unnecessary suffering, or giving up personal power and well-being without clear purpose or benefit to anyone. Your lineage may include ancestors who sacrificed too much or became trapped in victim patterns that served no higher purpose, creating patterns of self-neglect or unconscious suffering. There may be ancestral beliefs that suffering is noble or necessary for spiritual development, leading to patterns of creating unnecessary difficulty.",
    advice: "Transform ancestral sacrifice patterns into conscious service and wisdom that serves both your own growth and the benefit of others rather than unconscious martyrdom that helps no one. Use the spiritual insights and perspective available through your lineage to serve others while also maintaining healthy boundaries and self-care. Honor the wisdom your ancestors gained through their experiences while also breaking free from any patterns of unnecessary suffering or sacrifice that no longer serve a higher purpose."
  },
  13: {
    general: "Your ancestral line has experienced major transformations, losses, endings, and rebirths, with ancestors who learned to navigate death, change, and renewal with courage and wisdom. You inherit the profound understanding of life's cyclical nature and the strength that comes from experiencing and surviving major transitions and transformations. This lineage provides you with natural resilience, comfort with change, and the ability to help others navigate difficult transitions and transformative experiences.",
    positive: "Strong ancestral support for navigating life transitions, transformations, and major changes with courage and wisdom gained through generations of experience with renewal and rebirth. Your lineage carries the accumulated knowledge of those who survived wars, migrations, natural disasters, or other major life upheavals and learned to find strength and wisdom through change. You have access to ancestral guidance about letting go, embracing transformation, and finding new life and opportunity through endings and transitions.",
    challenge: "May carry ancestral trauma from sudden losses, dramatic changes, or experiences of death and destruction that create fear about stability or trust in life's processes. Your lineage may include ancestors who experienced significant trauma, loss, or upheaval, creating patterns of anxiety about change or difficulty trusting that new beginnings can emerge from endings. There may be ancestral patterns of expecting loss or creating dramatic changes when stability would be more beneficial.",
    advice: "Use the ancestral wisdom about transformation and renewal to heal past trauma and create positive change in your current life while also building some stability and security. Honor the resilience and transformation abilities of your lineage while also creating sustainable foundations that can support you through periods of change. Transform any ancestral patterns of expecting loss or trauma into conscious appreciation for life's cycles and the opportunities for growth and renewal they provide."
  },
  14: {
    general: "Your ancestral line includes healers, moderators, wise counselors, and those who possessed the gift of bringing balance, harmony, and healing to conflicted situations and relationships. You inherit the natural ability to find middle ground, create synthesis between opposing forces, and help others heal from wounds and imbalances. This lineage provides you with patience, wisdom, and the healing presence that can transform conflict into cooperation and discord into harmony.",
    positive: "Natural ancestral gifts for healing, balance, and bringing opposing forces together in harmonious synthesis that serves everyone involved. Your lineage carries the accumulated wisdom of healers and peacemakers who understood how to work with different energies and perspectives to create solutions that honored all parties. You have access to ancestral guidance about patience, moderation, and the healing power of balanced perspective and compassionate understanding.",
    challenge: "May carry ancestral avoidance of necessary conflict, intensity, or extreme action, with family patterns that emphasize harmony at the expense of authentic expression or needed change. Your lineage may include ancestors who became so focused on maintaining balance that they avoided taking strong stands or making difficult decisions when they were needed. There may be ancestral patterns of suppressing passion, anger, or other intense emotions in favor of maintaining peaceful equilibrium.",
    advice: "Use the ancestral healing wisdom and gift for balance while also embracing necessary intensity, passion, and conflict when they serve growth and positive change. Honor the peacemaking and healing traditions of your lineage while also developing the courage to take strong stands and engage in necessary confrontations when harmony is not possible or appropriate. Balance your natural tendency toward moderation with willingness to embrace extremes when they are needed for healing and transformation."
  },
  15: {
    general: "Your ancestral line has experienced both the benefits and dangers of material power, wealth, influence, and the shadow aspects of human nature including temptation, manipulation, and the corrupting influence of unchecked power. You inherit deep understanding of how material forces work and the importance of using power and resources consciously and ethically. This lineage provides you with insights into human psychology, material manifestation, and the responsibility that comes with power and influence.",
    positive: "Deep understanding of the material world's power and how to work with money, influence, and resources consciously and ethically for positive purposes. Your lineage carries the accumulated knowledge of those who learned to navigate power dynamics, material success, and human psychology with wisdom and integrity. You have access to ancestral guidance about using power and resources responsibly, understanding human motivation, and creating material success that serves rather than corrupts spiritual development.",
    challenge: "May carry ancestral karma around greed, corruption, addiction, or abuse of power, with family patterns that involve unhealthy relationships with money, sexuality, or control over others. Your lineage may include ancestors who became corrupted by power or wealth, creating patterns of guilt, shame, or fear around material success and influence. There may be ancestral wounds around betrayal, manipulation, or being used by others for material or sexual purposes.",
    advice: "Transform ancestral shadow patterns around power and material resources into conscious, ethical use of your abilities to create positive change and abundance that serves the greater good. Use your inherited understanding of material forces and human psychology to help others while also healing any ancestral karma around corruption or misuse of power. Create healthy relationships with money, power, and influence that honor both spiritual values and practical needs without repeating past mistakes."
  },
  16: {
    general: "Your ancestral line has experienced sudden upheavals, revelations, wars, disasters, and institutional collapses that required rapid adaptation and the ability to rebuild from destruction. You inherit the strength and resilience that comes from surviving dramatic changes and the wisdom to recognize when old structures need to be dismantled for new growth to occur. This lineage provides you with courage during crisis, ability to adapt quickly to changing circumstances, and insight into how to create positive change from challenging situations.",
    positive: "Strong ancestral resilience and ability to rebuild quickly from setbacks, with inherited wisdom about adapting to dramatic changes and finding opportunities in chaos and disruption. Your lineage carries the accumulated strength of those who survived wars, natural disasters, economic collapses, or other major upheavals and learned to create new foundations from destruction. You have access to ancestral guidance about courage during crisis, innovative solutions to problems, and the ability to help others navigate sudden changes and transitions.",
    challenge: "May carry ancestral trauma from wars, disasters, persecution, or sudden upheavals that create anxiety about security, fear of change, or expectation that stability will always be disrupted. Your lineage may include ancestors who experienced significant trauma from sudden losses or dramatic changes, creating patterns of hypervigilance or difficulty trusting that peace and stability are possible. There may be ancestral patterns of creating crisis or drama when life becomes too peaceful or predictable.",
    advice: "Use the ancestral resilience and adaptability to build flexible security that can weather unexpected changes while also healing trauma and creating genuine stability where possible. Honor the strength and innovation of your lineage while also breaking cycles of crisis and trauma by creating sustainable foundations and peaceful environments. Transform any ancestral patterns of expecting disaster into conscious preparation and resilience that allows you to handle challenges without creating unnecessary stress or drama."
  },
  17: {
    general: "Your ancestral line includes visionaries, hope-bringers, spiritual guides, and those who maintained faith and optimism even during the darkest times, serving as beacons of light and possibility for their communities. You inherit the natural ability to see potential and possibility where others see only problems, and the gift of inspiring others to believe in better futures. This lineage provides you with access to spiritual guidance, eternal optimism, and the ability to channel divine inspiration for healing and positive change.",
    positive: "Strong ancestral connection to hope, inspiration, and spiritual guidance, with inherited ability to see possibilities and potential that others miss due to pessimism or limited perspective. Your lineage carries the accumulated faith and vision of those who maintained hope during difficult times and inspired others to keep going when circumstances seemed impossible. You have access to ancestral guidance about maintaining faith, channeling inspiration, and using your natural optimism to create positive change and healing.",
    challenge: "May carry ancestral disappointment, broken promises, or unrealistic expectations that create patterns of either naive optimism or deep cynicism about life's possibilities. Your lineage may include ancestors who experienced profound disappointments or betrayals that challenged their faith, creating patterns of either avoiding realistic planning or becoming too cautious about hope and vision. There may be ancestral patterns of expecting too much too quickly or avoiding practical action in favor of spiritual idealism.",
    advice: "Channel the ancestral vision and hope into practical action and realistic planning that can manifest positive change in the material world rather than remaining only in the realm of inspiration. Use your inherited optimism and spiritual connection to serve others while also developing practical skills and realistic timelines for achieving your visions. Balance the faith and inspiration of your lineage with grounded action and practical wisdom that can turn dreams into reality."
  },
  18: {
    general: "Your ancestral line includes mystics, dreamers, seers, and intuitive beings who navigated the realms of dreams, visions, and unconscious wisdom, often serving as bridges between different dimensions of reality. You inherit deep psychic abilities, connection to dreams and symbols, and the ability to access hidden knowledge and unconscious wisdom. This lineage provides you with natural access to mystical experiences, prophetic dreams, and the ability to understand the hidden meanings and patterns that influence human experience.",
    positive: "Deep ancestral connection to dreams, intuition, mystical experiences, and the ability to access hidden knowledge and unconscious wisdom for guidance and healing. Your lineage carries the accumulated psychic abilities and mystical understanding of those who served as oracles, dreamers, and bridges between different realms of consciousness. You have access to ancestral guidance through dreams, symbols, and intuitive insights that can help you navigate complex situations and understand hidden dynamics.",
    challenge: "May carry ancestral confusion, mental health challenges, deception, or difficulty distinguishing between genuine psychic experiences and emotional confusion or wishful thinking. Your lineage may include ancestors who struggled with mental illness, addiction, or were deceived or persecuted for their psychic abilities, creating patterns of confusion about what is real or trustworthy. There may be ancestral patterns of escapism, fantasy, or difficulty staying grounded in practical reality.",
    advice: "Use the ancestral intuitive gifts and mystical abilities while also developing clear discernment and grounding practices that help you distinguish between genuine guidance and emotional confusion or fantasy. Honor the psychic and mystical traditions of your lineage while also healing any ancestral trauma around mental health or persecution for spiritual gifts. Create healthy boundaries between mystical experiences and practical life, using your intuitive abilities to enhance rather than escape from material reality."
  },
  19: {
    general: "Your ancestral line carries the radiant energy of successful, joyful, and naturally abundant beings who understood how to create happiness, celebration, and positive energy that attracted success and good fortune. You inherit the wisdom of ancestors who knew how to find joy and meaning in life and share their positive energy with others in ways that created mutual benefit and celebration. This lineage provides you with natural magnetism, optimism, and the ability to create success through positive energy and genuine enthusiasm.",
    positive: "Strong ancestral foundation of success, joy, and natural magnetism that attracts opportunities and positive relationships through inherited optimism and enthusiasm. Your lineage carries the accumulated wisdom of those who created abundant, joyful lives and shared their success and happiness with others in generous, sustainable ways. You have access to ancestral guidance about maintaining positive energy, creating celebration and joy, and using your natural magnetism to attract success and opportunities.",
    challenge: "May carry ancestral pressure to always be positive or successful, with family patterns that avoid dealing with difficulties, shadows, or negative emotions that need attention and healing. Your lineage may include ancestors who maintained success and positivity by avoiding or denying problems, creating patterns of superficiality or inability to deal with necessary challenges. There may be ancestral patterns of taking success for granted or expecting abundance to continue without effort or conscious maintenance.",
    advice: "Honor the joy and success traditions of your ancestral lineage while also developing the ability to face challenges and deal with difficult emotions and situations that require attention. Use your inherited magnetism and positive energy to create sustainable success while also addressing any problems or shadows that need healing. Balance the celebration and abundance of your lineage with responsibility and conscious stewardship of your gifts and resources."
  },
  20: {
    general: "Your ancestral line has experienced profound spiritual awakening, calling, and rebirth, with ancestors who underwent major transformations and dedicated their lives to serving higher purposes and spiritual development. You inherit the deep spiritual understanding and sense of mission that comes from generations of ancestors who answered spiritual calls and used their lives to serve something greater than personal interest. This lineage provides you with access to spiritual awakening, sense of higher purpose, and the courage needed to follow your spiritual calling even when it requires sacrifice or change.",
    positive: "Strong ancestral support for spiritual awakening, higher purpose, and the courage to answer your calling even when it requires major life changes or sacrifices. Your lineage carries the accumulated wisdom of those who experienced profound spiritual transformation and learned to integrate spiritual understanding with practical service in the world. You have access to ancestral guidance about spiritual development, finding and following your purpose, and using your gifts to serve both your own growth and the benefit of others.",
    challenge: "May carry ancestral burden of spiritual responsibility, religious trauma, or pressure to live up to high spiritual standards that feel overwhelming or impossible to achieve. Your lineage may include ancestors who sacrificed too much for spiritual purposes or became disconnected from practical life and human relationships in pursuit of spiritual development. There may be ancestral patterns of spiritual perfectionism or feeling obligated to save others or carry spiritual burdens that are too heavy.",
    advice: "Answer the ancestral calling to spiritual service and awakening while also maintaining balance with practical life and human relationships rather than sacrificing everything for spiritual purposes. Use your inherited spiritual understanding and sense of purpose to serve others while also taking care of your own needs and maintaining healthy boundaries. Honor the spiritual mission of your lineage while also creating sustainable ways to integrate spiritual purpose with material success and personal happiness."
  },
  21: {
    general: "Your ancestral line includes masters, achievers, successful completion-bringers, and those who understood how to bring projects, relationships, and life goals to successful fruition and lasting fulfillment. You inherit the wisdom of ancestors who achieved mastery in their chosen fields and created lasting contributions that benefited not only themselves but also future generations. This lineage provides you with natural ability to complete projects, achieve goals, and create success that feels meaningful and sustainable over time.",
    positive: "Strong ancestral wisdom about achieving goals, completing projects, and creating lasting success that serves multiple purposes and benefits others as well as yourself. Your lineage carries the accumulated knowledge of masters and achievers who understood how to persist through challenges, refine their skills, and create contributions that stood the test of time. You have access to ancestral guidance about mastery, completion, and the satisfaction that comes from achieving meaningful goals through dedication and skill.",
    challenge: "May carry ancestral pressure to achieve or maintain high standards, with family expectations that feel overwhelming or that limit your freedom to explore different paths or make mistakes. Your lineage may include ancestors who became so focused on achievement and success that they neglected other important aspects of life like relationships, play, or spiritual development. There may be ancestral patterns of perfectionism or difficulty appreciating progress and success when they don't meet impossibly high standards.",
    advice: "Build on the ancestral mastery and achievement wisdom while also defining success in your own terms and maintaining balance with other important life areas like relationships and personal fulfillment. Use your inherited ability to complete projects and achieve goals while also allowing yourself room for exploration, mistakes, and learning that leads to genuine mastery. Honor the achievement tradition of your lineage while also creating space for play, relationships, and aspects of life that may not fit traditional definitions of success."
  },
  22: {
    general: "Your ancestral line offers the energy of fresh starts, new beginnings, and unlimited potential, with ancestors who understood that each generation has the opportunity to create completely new paradigms and break free from limiting patterns of the past. You inherit the wisdom that comes from approaching life with beginner's mind and the courage to explore new possibilities that haven't been tried before. This lineage provides you with natural optimism, openness to possibility, and the ability to start fresh when needed.",
    positive: "Ancestral support for breaking old patterns, creating new paradigms, and approaching life with fresh perspective and unlimited potential for positive change. Your lineage carries the accumulated courage of those who were willing to leave behind what wasn't working and start over with hope and enthusiasm for better possibilities. You have access to ancestral guidance about new beginnings, creative solutions, and the faith needed to try approaches that haven't been tested before.",
    challenge: "May carry ancestral naivety, tendency to repeat past mistakes, or lack of wisdom that comes from experience, leading to patterns of starting over repeatedly without building on previous learning. Your lineage may include ancestors who were so focused on new beginnings that they didn't learn from past experiences or build sustainable foundations for lasting success. There may be ancestral patterns of avoiding commitment or responsibility by constantly seeking fresh starts when challenges arise.",
    advice: "Use the ancestral fresh start energy and openness to possibility while also learning from both your own experience and the wisdom of previous generations to avoid repeating past mistakes. Honor the innovation and new beginning traditions of your lineage while also developing the patience and commitment needed to build lasting success and meaningful relationships. Balance your natural openness to new possibilities with practical wisdom and the ability to persist through challenges rather than always seeking escape through fresh starts."
  }
};