/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Present Life Task Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * your current lifetime mission, soul purpose, main lessons to learn,
 * and primary tasks for spiritual and personal development in this incarnation.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Present Life Task - Your soul's mission and primary lessons in this lifetime
 */
export const presentLifeTaskInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your present life task involves learning to be a conscious leader and pioneer who creates new possibilities while balancing personal will with service to others. You are here to develop authentic self-confidence and the courage to initiate projects that serve collective good. Your soul's mission includes breaking new ground, inspiring others to embrace their own creative power, and demonstrating what's possible when individual will aligns with divine purpose. This lifetime is about mastering the art of leadership that empowers rather than dominates.",
    positive: "Natural ability to see new possibilities and the courage to take the first steps toward manifesting them in reality. Your pioneering spirit helps you break through limitations and create innovative solutions that benefit others. You excel at inspiring confidence in others and helping them discover their own leadership potential and creative abilities.",
    challenge: "Learning to balance your strong will and desire for independence with consideration for others and collaborative approaches to achievement. Developing patience with slower processes and others' different timing while maintaining your initiating energy. Overcoming tendencies toward selfishness or domination in favor of leadership that serves collective evolution.",
    advice: "Focus on developing leadership skills that empower others rather than just expressing personal will. Practice patience and collaboration while maintaining your natural pioneering spirit. Use your creative energy to serve causes larger than personal achievement, and remember that true leadership creates more leaders rather than followers."
  },
  2: {
    general: "Your present life task involves learning to trust and develop your intuitive abilities while finding ways to share your inner wisdom in practical, accessible ways. You are here to develop deep receptivity and spiritual understanding while learning to express your insights clearly and confidently. Your soul's mission includes serving as a bridge between the seen and unseen realms, helping others access their own inner wisdom, and demonstrating the power of patient, receptive wisdom in an action-oriented world.",
    positive: "Natural access to intuitive guidance and the ability to understand complex situations through feeling and inner knowing rather than just logical analysis. Your gentle wisdom helps others feel safe to explore their own depths and spiritual understanding. You excel at providing guidance that comes from deep listening rather than quick judgment.",
    challenge: "Learning to trust your intuitive perceptions and express them confidently rather than doubting or dismissing your inner knowing. Developing the ability to take action based on intuitive guidance while balancing receptivity with appropriate assertion. Overcoming tendencies to withdraw or remain passive when situations require your active participation.",
    advice: "Practice trusting and acting on your intuitive insights while developing clear communication skills that help others understand your guidance. Balance receptivity with appropriate action and expression. Use your natural wisdom to help others access their own inner guidance rather than creating dependency on your insights."
  },
  3: {
    general: "Your present life task involves learning to create abundance and beauty while maintaining healthy boundaries and authentic self-worth that doesn't depend on others' approval. You are here to develop your creative gifts and generous nature while learning to receive love and support as freely as you give it. Your soul's mission includes demonstrating how creativity and nurturing can create abundance for all, inspiring others to embrace their own creative potential, and showing how true abundance includes emotional and spiritual richness.",
    positive: "Natural ability to create beauty and abundance that nourishes yourself and others, combined with generous sharing of your creative gifts and loving support. Your appreciation for life's pleasures helps others embrace joy and creativity without guilt. You excel at seeing and nurturing potential in people and situations.",
    challenge: "Learning to receive love and appreciation rather than only giving, and developing self-worth that doesn't depend on others' approval or your ability to please them. Balancing your generous nature with healthy boundaries that protect your energy and creativity. Overcoming tendencies to measure your value through external achievements or others' happiness.",
    advice: "Practice receiving love and support as openly as you give it, and develop inner sources of self-worth that don't depend on external validation. Use your creative gifts to serve your authentic expression rather than just pleasing others. Create sustainable patterns of giving and receiving that honor both your generous nature and your need for nourishment."
  },
  4: {
    general: "Your present life task involves learning to create stable foundations and systems that support long-term growth while developing flexibility and emotional intelligence that enhances rather than limits your achievements. You are here to master the art of building lasting value through disciplined effort while remaining open to change and innovation. Your soul's mission includes creating security and structure that serves others' growth, demonstrating the power of consistent effort, and showing how discipline can serve freedom rather than limiting it.",
    positive: "Natural ability to create stable foundations and organize complex projects that provide lasting value and security for yourself and others. Your disciplined approach helps you achieve long-term goals that others might abandon due to impatience. You excel at creating systems and structures that support sustained growth and development.",
    challenge: "Learning to balance your need for structure and security with flexibility and openness to change when circumstances require adaptation. Developing emotional intelligence and interpersonal skills that enhance your practical abilities. Overcoming tendencies toward rigidity or controlling behavior that might limit growth and innovation.",
    advice: "Use your organizational abilities to create structures that support rather than limit growth and creativity. Practice flexibility and emotional openness while maintaining your commitment to building lasting value. Balance your focus on security with willingness to take calculated risks that serve long-term goals."
  },
  5: {
    general: "Your present life task involves learning to bridge traditional wisdom with contemporary understanding while developing your own authentic spiritual authority based on personal experience rather than just external teaching. You are here to study universal principles while finding your unique way of expressing and teaching them. Your soul's mission includes serving as a spiritual teacher or guide, helping others connect with meaningful traditions while honoring their individual path, and demonstrating how ancient wisdom applies to modern life.",
    positive: "Natural connection to spiritual wisdom and universal principles that provides reliable guidance for ethical decision-making and meaningful living. Your respect for tradition helps you learn from those who have gone before while adapting teachings to contemporary circumstances. You excel at teaching and sharing wisdom in ways that others can understand and apply practically.",
    challenge: "Learning to balance respect for traditional wisdom with personal spiritual authority and individual revelation that may challenge established beliefs. Developing authentic teaching ability based on personal experience rather than just intellectual knowledge. Overcoming tendencies toward dogmatism or spiritual superiority that might limit your ability to serve others' individual spiritual growth.",
    advice: "Study traditional wisdom while developing your own authentic spiritual understanding through personal experience and practice. Share knowledge in ways that empower others' individual spiritual development rather than creating dependency. Balance respect for established teaching with openness to new revelations and contemporary applications of universal principles."
  },
  6: {
    general: "Your present life task involves learning to create authentic harmony and beauty that includes rather than avoids the full spectrum of human experience, while developing the ability to make decisions based on your true values rather than others' approval. You are here to master the art of loving relationship while maintaining your individual identity and authentic expression. Your soul's mission includes creating beauty that uplifts consciousness, facilitating harmony through honest communication, and demonstrating how love can include healthy conflict and growth.",
    positive: "Natural ability to create harmony and beauty in relationships and environments while appreciating different perspectives and finding fair solutions to conflicts. Your diplomatic skills help others feel valued and understood even during disagreements. You excel at creating aesthetically pleasing experiences that support everyone's wellbeing and growth.",
    challenge: "Learning to maintain authentic self-expression and make decisions based on your true values rather than constantly adapting to others' preferences or expectations. Developing comfort with necessary conflict and difficult conversations that deepen rather than threaten relationships. Overcoming tendencies to avoid decisions or suppress authentic feelings to maintain surface harmony.",
    advice: "Practice expressing your authentic feelings and needs while maintaining your natural consideration for others' wellbeing. Use your diplomatic gifts to facilitate honest communication rather than avoiding difficult conversations. Create beauty and harmony through truth and authentic expression rather than suppression of differences."
  },
  7: {
    general: "Your present life task involves learning to channel your drive and competitive energy toward serving collective good while developing patience and collaborative skills that enhance rather than hinder your achievements. You are here to master focused effort and determination while learning that true victory includes others' success and wellbeing. Your soul's mission includes inspiring others to pursue excellence, demonstrating the power of persistence through challenges, and showing how individual achievement can serve larger purposes.",
    positive: "Natural drive and determination that helps you overcome obstacles and achieve meaningful goals while inspiring others to pursue their own excellence and potential. Your competitive spirit motivates you to develop skills and capabilities that serve important purposes. You excel at maintaining focus and energy during challenging circumstances when others might give up.",
    challenge: "Learning to balance individual achievement with collaborative effort and others' different paces and approaches to success. Developing patience with processes that require time and gradual development rather than immediate results. Overcoming tendencies toward aggressive pursuit of goals that might damage relationships or ignore others' needs and contributions.",
    advice: "Channel your competitive energy toward inspiring mutual excellence and collective achievement rather than just personal victory. Practice patience with others' different timing and approaches while maintaining your natural drive and focus. Use your determination to serve causes that benefit others as well as yourself."
  },
  8: {
    general: "Your present life task involves learning to express your inner strength through compassionate action and clear communication rather than just patient endurance, while developing the ability to receive support and care as well as giving it. You are here to master the art of transformation through love while learning to advocate for yourself and others when necessary. Your soul's mission includes demonstrating how gentleness and strength can work together, facilitating healing and transformation, and showing how patience can serve positive change rather than just acceptance of difficulties.",
    positive: "Natural inner strength and healing presence that helps you endure challenges with grace while supporting others through their difficult times. Your patient, compassionate approach creates safety for others to explore vulnerability and work through emotional challenges. You excel at transforming pain into wisdom and helping others find meaning in their struggles.",
    challenge: "Learning to express your needs and feelings directly rather than only showing strength and support for others, while developing assertiveness that serves positive change rather than just enduring difficult situations. Balancing your care for others with equal attention to your own emotional needs and healing. Overcoming tendencies to suppress anger or avoid conflict when direct action would serve healing and growth.",
    advice: "Practice expressing your authentic emotions and needs while maintaining your natural compassion and strength. Use your healing abilities to create positive change rather than just accepting difficult circumstances. Balance your care for others with equal attention to your own emotional wellbeing and growth."
  },
  9: {
    general: "Your present life task involves learning to share your wisdom and insights in ways that serve others' practical needs while balancing contemplation with engaged participation in life and relationships. You are here to develop deep understanding through experience while finding meaningful ways to contribute your knowledge to others' growth and wellbeing. Your soul's mission includes serving as a teacher or guide based on genuine wisdom, helping others find their own inner guidance, and demonstrating how spiritual understanding applies to everyday life.",
    positive: "Natural wisdom and understanding that comes from deep reflection and life experience, providing valuable guidance for your own growth and others' spiritual development. Your contemplative nature helps you see patterns and meanings that others might miss. You excel at offering insights that help others understand their experiences and find direction for their spiritual journey.",
    challenge: "Learning to balance solitary contemplation with regular engagement in relationships and practical service that allows your wisdom to benefit others. Developing communication skills that make your insights accessible rather than remaining in abstract or theoretical realms. Overcoming tendencies toward isolation or intellectual superiority that might limit your ability to serve others effectively.",
    advice: "Share your wisdom through practical service and accessible teaching rather than remaining in isolation or abstract contemplation. Engage regularly with others while maintaining the contemplative practices that nourish your insight. Use your understanding to help others find their own inner wisdom rather than creating dependency on your guidance."
  },
  10: {
    general: "Your present life task involves learning to work consciously with life's cycles and timing while taking appropriate responsibility for your choices and actions within larger patterns. You are here to develop wisdom about when to act and when to wait while understanding how your personal decisions contribute to collective evolution. Your soul's mission includes helping others understand life's larger patterns, demonstrating how to work with rather than against natural timing, and showing how individual responsibility and cosmic forces work together.",
    positive: "Natural understanding of life's cycles and timing that helps you navigate challenges with faith and wisdom about when circumstances will naturally improve or when action is required. Your philosophical perspective helps you find meaning in difficult experiences and maintain hope during challenging times. You excel at recognizing patterns and helping others understand their life's larger significance.",
    challenge: "Learning to balance acceptance of natural timing with appropriate initiative and responsibility for creating positive change in your life and circumstances. Developing the ability to take action when opportunities arise rather than always waiting for perfect timing or external intervention. Overcoming tendencies toward fatalism or passive waiting that might prevent you from fulfilling your potential.",
    advice: "Practice working with natural timing while also taking inspired action when opportunities require your participation. Balance acceptance of larger patterns with responsibility for your individual choices and their consequences. Use your understanding of cycles to help others find meaning in their experiences while encouraging appropriate action."
  },
  11: {
    general: "Your present life task involves learning to make ethical decisions efficiently while balancing justice with compassion and understanding the complexity of human nature. You are here to develop moral clarity and fair judgment while learning to apply principles with wisdom about individual circumstances and human imperfection. Your soul's mission includes serving justice and fairness, helping others understand consequences of their choices, and demonstrating how ethical principles can serve love and healing rather than just punishment.",
    positive: "Natural sense of justice and ethical understanding that helps you make fair decisions and create equitable solutions in challenging situations. Your principled approach provides reliable guidance for moral decisions and helps others understand right and wrong. You excel at seeing truth clearly and helping others recognize the consequences of their choices and actions.",
    challenge: "Learning to balance moral principles with compassion for human imperfection and the complexity of real-life situations that don't fit neat categories. Developing the ability to make ethical decisions efficiently rather than becoming paralyzed by analysis of every moral implication. Overcoming tendencies toward rigidity or judgment that might limit your ability to serve healing and growth.",
    advice: "Apply your ethical understanding with wisdom and compassion for human complexity while maintaining your commitment to fairness and justice. Make moral decisions based on both principle and love, considering individual circumstances and the goal of healing and growth. Use your sense of justice to serve reconciliation and positive change rather than just punishment."
  },
  12: {
    general: "Your present life task involves learning to distinguish between meaningful sacrifice that serves growth and unnecessary martyrdom, while developing the ability to see situations from multiple perspectives and find creative solutions to seemingly impossible problems. You are here to develop wisdom through surrender while learning when to take direct action and when to wait for new understanding to emerge. Your soul's mission includes helping others find meaning in difficult experiences, offering alternative perspectives that transform problems into opportunities, and demonstrating how letting go can lead to greater freedom.",
    positive: "Natural wisdom and spiritual understanding that comes from willingness to see life from different perspectives and ability to find meaning in challenging experiences. Your accepting attitude helps you navigate difficult circumstances with grace and find solutions that others might miss. You excel at helping others reframe problems and discover unexpected opportunities for growth.",
    challenge: "Learning to distinguish between healthy sacrifice that serves meaningful purposes and unnecessary self-denial or martyrdom that doesn't create positive change. Developing the ability to take direct action when situations require intervention rather than always accepting difficult circumstances passively. Overcoming tendencies to complicate simple situations or avoid taking responsibility for creating positive change.",
    advice: "Practice conscious discernment about when acceptance serves growth and when action is required to create positive change. Use your ability to see multiple perspectives to find creative solutions rather than just accepting difficult circumstances. Balance wisdom gained through surrender with willingness to take appropriate action when called for."
  },
  13: {
    general: "Your present life task involves learning to facilitate healthy transformation and renewal while building sustainable foundations that can weather necessary changes. You are here to master the art of letting go and beginning again while helping others navigate transitions with courage and wisdom. Your soul's mission includes facilitating transformation that serves growth, helping others release what no longer serves their development, and demonstrating how endings can be gateways to new and better beginnings.",
    positive: "Natural ability to navigate major life transitions and help others transform through challenging circumstances with courage and understanding of renewal processes. Your comfort with change helps you release attachments that limit growth and embrace new possibilities. You excel at helping others find meaning and opportunity in difficult endings and transitions.",
    challenge: "Learning to create stability and lasting foundations while remaining open to necessary change and transformation that serves authentic growth. Developing the ability to work through difficulties rather than abandoning situations too quickly when they become challenging. Overcoming tendencies to create unnecessary drama or crisis when gradual change would be more effective.",
    advice: "Balance your comfort with transformation with commitment to building lasting value and working through challenges that could lead to deeper satisfaction. Create conscious change that serves growth rather than just seeking intensity or avoiding difficulties. Help others navigate necessary transitions while also building foundations that support sustained development."
  },
  14: {
    general: "Your present life task involves learning to create dynamic balance that includes rather than excludes the full spectrum of life experience, while developing healing abilities that serve integration and wholeness. You are here to master the art of moderation and patience while remaining open to appropriate intensity and passion when they serve growth. Your soul's mission includes facilitating healing and integration, helping others find sustainable approaches to life challenges, and demonstrating how balance can be dynamic rather than static.",
    positive: "Natural ability to create balance and healing in challenging situations while helping others integrate different aspects of themselves into harmonious wholes. Your moderate approach creates sustainability and helps others avoid extremes that might cause problems. You excel at finding middle ground and creating solutions that honor multiple needs and perspectives.",
    challenge: "Learning to embrace appropriate intensity and passionate engagement when they serve authentic expression and growth rather than always maintaining comfortable equilibrium. Developing the ability to work with conflict and strong emotions as natural parts of healing rather than avoiding them. Overcoming tendencies to suppress vital energy or avoid necessary challenges in favor of peaceful balance.",
    advice: "Practice creating dynamic balance that includes rather than excludes strong emotions and passionate engagement when they serve authentic expression and growth. Use your healing abilities to work with rather than avoid difficult feelings and challenging situations. Balance your natural moderation with openness to intensity that serves transformation and authentic development."
  },
  15: {
    general: "Your present life task involves learning to use power and influence responsibly while transforming material attachments and desires into conscious choice and spiritual understanding. You are here to master working with complex motivations and shadow aspects while using your understanding of human nature to serve healing and empowerment. Your soul's mission includes helping others understand their own relationship with power and desire, facilitating conscious choice about material goals, and demonstrating how worldly success can serve spiritual development.",
    positive: "Natural understanding of power dynamics and human motivation that helps you navigate complex situations and achieve practical goals while maintaining spiritual perspective. Your comfort with intensity and difficult emotions helps others accept their shadow aspects. You excel at transforming challenging circumstances into opportunities for empowerment and conscious choice.",
    challenge: "Learning to use power and influence always in service of others' authentic growth rather than personal gain or control over outcomes. Developing the ability to work with desires and attachments consciously rather than being driven by unconscious motivations. Overcoming tendencies toward manipulation or using understanding of human nature to take advantage of others' vulnerabilities.",
    advice: "Use your understanding of power and human motivation to serve others' empowerment and conscious choice rather than personal control or gain. Practice working with desires and material goals as opportunities for spiritual development rather than just acquisition. Channel your intensity and understanding of shadow aspects toward healing and transformation rather than manipulation or dominance."
  },
  16: {
    general: "Your present life task involves learning to create conscious change and breakthrough that builds better structures rather than just destroying old patterns, while developing the ability to communicate insights in ways that inspire rather than shock or overwhelm others. You are here to master the art of revolution and revelation while building foundations that support the insights and changes you create. Your soul's mission includes helping others break free from limiting patterns, facilitating necessary awakening and change, and demonstrating how destruction can serve creation.",
    positive: "Natural ability to see through illusions and break free from limiting patterns while helping others recognize truth and make liberating choices. Your willingness to face difficult realities creates opportunities for authentic freedom and positive change. You excel at catalyzing breakthroughs that lead to better understanding and more authentic living.",
    challenge: "Learning to create constructive change that builds better alternatives rather than just breaking down existing structures without providing improvements. Developing communication skills that help others integrate insights gradually rather than overwhelming them with sudden revelations. Overcoming tendencies to create unnecessary drama or crisis when patient building would be more effective.",
    advice: "Focus on creating positive alternatives and better structures rather than just destroying what doesn't work. Practice communicating insights in ways that others can receive and integrate gradually rather than shocking them with sudden revelations. Use your gift for breakthrough and liberation to serve lasting positive change rather than just dramatic transformation."
  },
  17: {
    general: "Your present life task involves learning to ground spiritual vision and inspiration in practical action that creates real positive change in the world, while maintaining hope and faith during challenging circumstances. You are here to develop the ability to translate ideals into achievable steps while inspiring others to pursue their highest potential. Your soul's mission includes serving as a beacon of hope and positive vision, helping others maintain faith in difficult times, and demonstrating how spiritual inspiration can guide practical success.",
    positive: "Natural ability to maintain hope and inspire others with vision of positive possibilities even during difficult circumstances. Your optimistic perspective helps others believe in their potential and pursue meaningful goals with faith and determination. You excel at connecting others with their spiritual guidance and higher purpose while providing practical direction.",
    challenge: "Learning to ground spiritual vision in practical steps and present-moment action rather than remaining in abstract idealism or future possibilities. Developing realistic approaches to manifesting ideals while maintaining inspiration and positive vision. Overcoming tendencies to avoid practical details or become discouraged when reality doesn't immediately match your vision.",
    advice: "Practice translating spiritual vision into concrete steps and practical actions that create real positive change rather than remaining in abstract idealism. Maintain your inspirational abilities while developing realistic approaches to manifesting goals. Use your faith and optimism to sustain yourself and others through the practical work required to create positive change."
  },
  18: {
    general: "Your present life task involves learning to distinguish between genuine intuitive guidance and emotional projection or wishful thinking, while developing the ability to communicate psychic insights in ways that serve practical healing and clear understanding. You are here to master working with the unconscious realm while maintaining grounded discernment and clear communication. Your soul's mission includes helping others access their own intuitive abilities, facilitating emotional and psychic healing, and bridging the gap between mystical experience and practical wisdom.",
    positive: "Natural psychic sensitivity and intuitive understanding that provides access to hidden knowledge and emotional depths that help you and others understand complex situations. Your comfort with mystery helps you navigate ambiguous circumstances and find guidance through feeling and inner knowing. You excel at providing insights that help others understand their unconscious patterns and spiritual journey.",
    challenge: "Learning to distinguish between genuine psychic guidance and emotional confusion or projection that might cloud your perception of reality. Developing clear communication about intuitive insights that helps others understand rather than creating more confusion. Overcoming tendencies to become lost in fantasy or avoid taking practical action based on your insights.",
    advice: "Practice developing clear discernment between genuine intuitive guidance and emotional projection while maintaining your natural psychic sensitivity. Ground mystical insights in practical action and clear communication that serves others' understanding and healing. Use your intuitive abilities to facilitate clarity and positive change rather than avoiding practical responsibilities."
  },
  19: {
    general: "Your present life task involves learning to share your natural radiance and positive energy in ways that inspire others' authentic success while maintaining inner sources of happiness that don't depend entirely on external recognition or circumstances. You are here to master joyful achievement and authentic self-expression while developing depth and the ability to work through challenges. Your soul's mission includes inspiring others to pursue their dreams, demonstrating authentic confidence and joy, and showing how success can serve collective good.",
    positive: "Natural charisma and positive energy that inspires others and attracts opportunities for success and meaningful achievement. Your authentic enthusiasm helps others believe in their own potential and pursue their goals with confidence. You excel at creating celebratory experiences and helping others recognize their accomplishments and find joy in their lives.",
    challenge: "Learning to maintain authentic joy and confidence while also developing depth and the ability to work through challenges and difficult emotions without losing your positive energy. Balancing your focus on success and recognition with attention to inner development and others' needs. Overcoming tendencies toward superficiality or avoidance of difficulties that might diminish your radiant energy.",
    advice: "Maintain your natural positive energy while developing depth and the ability to work through challenges that create lasting satisfaction rather than just temporary pleasure. Use your success and charisma to inspire others rather than just seeking personal recognition. Balance your focus on achievement with attention to inner development and service to others' growth."
  },
  20: {
    general: "Your present life task involves learning to answer your spiritual calling while maintaining healthy boundaries and attention to practical responsibilities, while developing the ability to serve collective evolution through your individual gifts and circumstances. You are here to integrate spiritual awakening with everyday life while helping others recognize their own divine nature and purpose. Your soul's mission includes facilitating spiritual awakening and transformation, serving collective consciousness and evolution, and demonstrating how individual spiritual development serves universal good.",
    positive: "Natural spiritual awareness and sense of higher purpose that provides clear direction for meaningful service and spiritual development. Your understanding of collective needs helps you contribute to positive change while maintaining your individual spiritual practice. You excel at inspiring others' spiritual awakening and helping them recognize their connection to universal consciousness.",
    challenge: "Learning to balance spiritual calling with practical responsibilities and personal relationships while avoiding spiritual superiority or neglect of everyday human needs. Developing the ability to serve collective evolution through your individual circumstances rather than seeking escape from ordinary life. Overcoming tendencies to sacrifice personal wellbeing entirely for spiritual service or become overwhelmed by collective responsibilities.",
    advice: "Answer your spiritual calling through your individual life circumstances and relationships rather than seeking to escape ordinary human experience. Balance service to collective evolution with attention to your personal needs and practical responsibilities. Use your spiritual awareness to serve healing and awakening while remaining grounded in compassionate human connection."
  },
  21: {
    general: "Your present life task involves learning to use your achievements and mastery to serve others' development while remaining open to continued growth and evolution in areas where you have less experience. You are here to integrate all aspects of your development into wise service while maintaining humility and curiosity about new possibilities. Your soul's mission includes demonstrating what's possible through dedicated development, mentoring others in their growth, and showing how mastery includes continued learning and service.",
    positive: "Natural ability to achieve integration and mastery that provides stable foundation for serving others' development and demonstrating what's possible through dedicated effort. Your wholeness and accomplishment inspire others and provide examples of successful development. You excel at helping others recognize their potential and take steps toward their own fulfillment and mastery.",
    challenge: "Learning to remain open to continued growth and learning while using your achievements to serve others rather than resting on past accomplishments or becoming disconnected from the development process. Balancing confidence in your abilities with humility about areas where you still have room to grow. Overcoming tendencies toward complacency or spiritual pride that might limit your continued evolution.",
    advice: "Use your achievements and mastery to serve others' development while remaining open to continued learning and growth in new areas. Maintain humility and connection to the learning process even as you share your expertise and experience. Balance confidence in your abilities with curiosity about new possibilities for growth and service."
  },
  22: {
    general: "Your present life task involves learning to balance unlimited potential and fresh perspective with practical wisdom and sustained commitment to meaningful development, while maintaining wonder and openness without avoiding necessary learning and growth. You are here to pioneer new approaches while benefiting from others' experience and guidance. Your soul's mission includes bringing fresh energy and perspective to established patterns, helping others maintain openness to possibility, and demonstrating how innocence and wisdom can work together.",
    positive: "Natural openness and unlimited potential that allows you to approach situations with fresh perspective and discover possibilities that others might miss through preconceptions. Your spontaneous creativity helps you find innovative solutions and adapt to changing circumstances. You excel at maintaining beginner's mind and helping others rediscover wonder and possibility in their lives.",
    challenge: "Learning to balance openness to new experiences with commitment to sustained development and learning from others' experience and wisdom. Developing practical skills and depth while maintaining your natural spontaneity and fresh perspective. Overcoming tendencies toward naivety or avoidance of necessary discipline and sustained effort that builds real capability.",
    advice: "Balance your natural openness and fresh perspective with willingness to learn from others' experience and commit to sustained development in areas that truly matter to you. Maintain your sense of wonder while developing practical wisdom and skills that allow you to serve effectively. Use your gift for seeing new possibilities to enhance rather than replace the value of experience and sustained effort."
  }
};