/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Reputation Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * your public image, how others perceive you, professional reputation,
 * social standing, and the legacy you create through your actions and presence.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Reputation - How you are perceived by others and your public image
 */
export const reputationInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your reputation is built around being seen as a confident leader, innovator, and trailblazer who breaks new ground and inspires others to pursue their own creative visions with courage. People perceive you as someone who takes initiative, creates original solutions, and isn't afraid to be first or stand alone when pursuing important goals. Your public image centers on strength, independence, and the ability to turn ideas into reality through bold action. Others see you as a natural leader who empowers others to discover their own potential for creative leadership and authentic self-expression.",
    positive: "Strong reputation as an inspiring leader and innovative pioneer who demonstrates what's possible when courage and creativity are combined with authentic vision and determined action. People admire your confidence and ability to achieve original accomplishments that open new possibilities for others. You're known for empowering others to believe in themselves and pursue their own creative goals with greater courage and determination.",
    challenge: "Reputation may suffer if others perceive you as overly aggressive, selfish, or dominating rather than truly inspiring and empowering. Risk of being seen as impatient with others' different approaches or insensitive to collaborative processes. May develop reputation for being difficult to work with if leadership style doesn't include adequate consideration for others' contributions and needs.",
    advice: "Build your reputation through leadership that clearly serves others' empowerment and collective good rather than just personal achievement and recognition. Demonstrate collaborative skills alongside your natural initiative and independence. Use your platform and influence to celebrate others' achievements and contributions while maintaining your authentic leadership presence and innovative spirit."
  },
  2: {
    general: "Your reputation is built around being seen as a wise counselor, intuitive guide, and emotionally intelligent person who provides deep understanding and spiritual insight to those seeking guidance. People perceive you as someone who listens deeply, understands complex emotional and spiritual dynamics, and offers profound wisdom that comes from genuine inner development. Your public image centers on sensitivity, spiritual awareness, and the ability to help others access their own inner wisdom. Others see you as a trusted advisor who provides emotional safety and spiritual guidance during challenging times.",
    positive: "Strong reputation as a wise and trustworthy spiritual guide who provides profound insights and emotional support that genuinely helps people grow and heal. People value your intuitive understanding and ability to see beneath surface appearances to deeper truths and patterns. You're known for creating emotional safety and helping others develop their own spiritual understanding and intuitive abilities.",
    challenge: "Reputation may suffer if others perceive you as overly passive, unclear in communication, or avoiding practical engagement when situations require decisive action and clear guidance. Risk of being seen as too withdrawn or mystical to be helpful with practical concerns. May develop reputation for being unreliable if spiritual sensitivity is used to avoid responsibilities or commitments.",
    advice: "Build your reputation by combining your natural wisdom and intuitive abilities with clear communication and practical guidance that helps others navigate both spiritual and everyday challenges. Demonstrate reliability and follow-through alongside your spiritual insights. Use your platform to provide accessible wisdom that serves others' practical growth and spiritual development without creating dependency or confusion."
  },
  3: {
    general: "Your reputation is built around being seen as a creative, generous, and nurturing person who creates beauty and abundance while supporting others' growth and artistic development. People perceive you as someone who gives generously of your talents and resources, creates beautiful and inspiring environments, and helps others appreciate life's pleasures and creative possibilities. Your public image centers on artistic ability, generous spirit, and the capacity to make others feel valued and supported. Others see you as someone who demonstrates how creativity and love can transform difficult circumstances into opportunities for beauty and growth.",
    positive: "Strong reputation as a generous creator and nurturer who inspires others through your artistic achievements and caring support for their creative development. People admire your ability to create beauty and abundance that enriches many lives. You're known for making others feel valued and supported while encouraging them to develop their own creative talents and capacity for generous love.",
    challenge: "Reputation may suffer if others perceive you as seeking approval through giving, lacking boundaries, or being unable to receive support as well as give it. Risk of being seen as codependent or measuring your worth through others' happiness. May develop reputation for being unreliable if generous impulses aren't balanced with realistic commitments and self-care.",
    advice: "Build your reputation through authentic generosity that comes from genuine abundance rather than need for approval or validation from others. Demonstrate healthy boundaries and the ability to receive support alongside your natural giving. Use your creative gifts and platform to inspire others' authentic creative expression while maintaining sustainable practices that support your long-term effectiveness and wellbeing."
  },
  4: {
    general: "Your reputation is built around being seen as a reliable, organized, and responsible person who creates stable foundations and achieves lasting results through disciplined effort and systematic approaches. People perceive you as someone who follows through on commitments, builds solid structures that serve long-term goals, and provides security and stability for others. Your public image centers on dependability, practical competence, and the ability to turn ideas into concrete achievements through persistent work. Others see you as someone who demonstrates how patience and consistent effort create lasting value and success.",
    positive: "Strong reputation as a dependable achiever and master builder who creates lasting value and provides reliable support for others' goals and security needs. People admire your ability to organize complex projects and achieve substantial results through patient, consistent effort. You're known for following through on commitments and creating foundations that others can count on for their own development and success.",
    challenge: "Reputation may suffer if others perceive you as overly rigid, controlling, or resistant to necessary changes and new approaches that could improve existing systems. Risk of being seen as inflexible or prioritizing rules over human needs. May develop reputation for being difficult to work with if organizational preferences don't include adequate consideration for others' input and different working styles.",
    advice: "Build your reputation through reliable excellence that includes flexibility and emotional intelligence alongside your natural organizational abilities and commitment to quality results. Demonstrate openness to improvement and collaboration while maintaining your valuable standards and systematic approaches. Use your platform to create systems and structures that empower rather than limit others' creativity and growth."
  },
  5: {
    general: "Your reputation is built around being seen as a wise teacher, moral authority, and spiritual guide who provides ethical guidance and helps others connect with meaningful principles and traditions. People perceive you as someone who has deep understanding of universal truths, lives according to high moral standards, and can be trusted to provide guidance based on wisdom and spiritual insight. Your public image centers on teaching ability, ethical integrity, and connection to spiritual and philosophical traditions. Others see you as someone who helps them understand life's deeper meaning and develop their own spiritual and moral understanding.",
    positive: "Strong reputation as a respected teacher and spiritual authority who provides valuable guidance based on genuine wisdom and ethical understanding. People admire your moral integrity and ability to help them connect with meaningful principles and spiritual traditions. You're known for teaching through example and helping others develop their own authentic spiritual understanding and ethical reasoning abilities.",
    challenge: "Reputation may suffer if others perceive you as dogmatic, judgmental, or imposing beliefs rather than guiding others toward their own authentic spiritual understanding. Risk of being seen as rigid about spiritual or moral principles without consideration for individual circumstances. May develop reputation for spiritual or intellectual superiority that distances you from others rather than serving their growth.",
    advice: "Build your reputation through humble teaching that honors both traditional wisdom and others' individual spiritual journeys and authentic development. Demonstrate flexibility and compassion alongside your commitment to important principles and universal truths. Use your platform to guide others toward their own spiritual authority rather than creating dependency on your beliefs or interpretations."
  },
  6: {
    general: "Your reputation is built around being seen as a diplomatic peacemaker, aesthetic appreciator, and harmony creator who brings people together and helps resolve conflicts through understanding and cooperation. People perceive you as someone who considers all perspectives fairly, creates beautiful and harmonious environments, and facilitates win-win solutions that serve everyone's needs. Your public image centers on fairness, aesthetic taste, and the ability to create cooperation and mutual appreciation among different people and groups. Others see you as someone who demonstrates how love and beauty can heal divisions and create lasting harmony.",
    positive: "Strong reputation as a skilled mediator and harmony creator who helps people find common ground and resolve conflicts through mutual understanding and respect. People admire your aesthetic sense and ability to create beautiful, peaceful environments that support everyone's wellbeing. You're known for treating others fairly and helping them appreciate both beauty and each other's unique contributions and perspectives.",
    challenge: "Reputation may suffer if others perceive you as avoiding necessary conflicts, being indecisive, or prioritizing surface harmony over authentic communication and real problem-solving. Risk of being seen as people-pleasing or lacking authentic opinions and positions on important issues. May develop reputation for being unreliable if desire for approval prevents you from taking clear stands when situations require decisive positions.",
    advice: "Build your reputation through authentic diplomacy that includes honest communication and real conflict resolution rather than just surface peace and harmony. Demonstrate genuine principles and values alongside your natural consideration for others' perspectives and needs. Use your platform to facilitate real understanding and problem-solving rather than just maintaining comfortable appearances and avoiding difficult conversations."
  },
  7: {
    general: "Your reputation is built around being seen as a determined achiever, competitive champion, and goal-oriented leader who overcomes obstacles and inspires others to pursue excellence through focused effort and persistent determination. People perceive you as someone who doesn't give up when facing challenges, achieves meaningful victories through skill and dedication, and motivates others to develop their own capabilities and pursue their goals with greater courage. Your public image centers on strength, persistence, and the ability to turn challenges into opportunities for growth and achievement. Others see you as someone who demonstrates what's possible through focused effort and unwavering commitment.",
    positive: "Strong reputation as an inspiring achiever and motivational leader who demonstrates how persistence and focused effort can overcome seemingly impossible obstacles and achieve meaningful success. People admire your determination and ability to maintain focus during challenging circumstances. You're known for motivating others to pursue their own excellence and develop the skills needed to achieve their most important goals.",
    challenge: "Reputation may suffer if others perceive you as overly competitive, aggressive, or prioritizing personal victory over collaboration and others' wellbeing. Risk of being seen as impatient with others' different approaches or insensitive to those who work at different paces. May develop reputation for being difficult to work with if competitive drive doesn't include adequate support for others' success and different definitions of achievement.",
    advice: "Build your reputation through inspiring achievement that clearly demonstrates how individual excellence can serve collective advancement and mutual success. Show patience and support for others' different approaches and timing while maintaining your natural drive and focus. Use your platform to motivate others toward their own goals rather than competing with them or demanding they match your pace and methods."
  },
  8: {
    general: "Your reputation is built around being seen as an emotionally strong, patient, and healing presence who demonstrates how gentle power and compassionate persistence can transform difficult circumstances and support others through challenges. People perceive you as someone who maintains grace under pressure, provides emotional stability and support, and shows how inner strength can accomplish what force cannot. Your public image centers on resilience, emotional wisdom, and the ability to help others find their own inner strength and healing. Others see you as someone who demonstrates how love and patience can overcome any obstacle and create positive transformation.",
    positive: "Strong reputation as a healing presence and emotional anchor who provides stability and support during difficult times while helping others develop their own inner strength and resilience. People admire your ability to remain calm and compassionate during crises and challenges. You're known for helping others transform pain into wisdom and find meaning and growth in their most difficult experiences.",
    challenge: "Reputation may suffer if others perceive you as overly passive, enabling problematic behavior, or avoiding necessary action when situations require firm boundaries and decisive intervention. Risk of being seen as too patient with harmful situations or people. May develop reputation for being unreliable if emotional support doesn't include appropriate action and advocacy when circumstances require strong responses.",
    advice: "Build your reputation through compassionate strength that includes appropriate action and healthy boundaries alongside your natural patience and emotional support. Demonstrate wise discernment about when to accept and when to advocate for positive change. Use your platform to model how gentle strength can create real positive change rather than just enduring difficult circumstances without response."
  },
  9: {
    general: "Your reputation is built around being seen as a wise teacher, contemplative guide, and deep thinker who provides profound insights and understanding that help others navigate life's complexities and find meaning in their experiences. People perceive you as someone who has developed wisdom through experience and contemplation, offers valuable perspective on important questions, and helps others understand patterns and significance in their own lives. Your public image centers on wisdom, intellectual depth, and spiritual understanding that comes from genuine development rather than just knowledge. Others see you as someone who demonstrates how contemplation and learning can create practical wisdom that serves real-world challenges.",
    positive: "Strong reputation as a wise counselor and insightful teacher who provides valuable guidance based on genuine understanding and life experience rather than just theoretical knowledge. People admire your depth of insight and ability to help them understand complex situations and find meaning in difficult experiences. You're known for offering perspective that helps others make better decisions and navigate challenges with greater wisdom and understanding.",
    challenge: "Reputation may suffer if others perceive you as too withdrawn, intellectually superior, or disconnected from practical concerns and everyday human needs. Risk of being seen as avoiding engagement with ordinary social interactions and responsibilities. May develop reputation for being impractical or superior if wisdom isn't shared in accessible ways that serve others' actual needs and circumstances.",
    advice: "Build your reputation through accessible wisdom that clearly serves others' practical needs and spiritual development while maintaining your valuable depth and contemplative insights. Demonstrate regular engagement with community and practical concerns alongside your intellectual and spiritual development. Use your platform to share insights in ways that others can understand and apply practically rather than maintaining distance or superiority."
  },
  10: {
    general: "Your reputation is built around being seen as a wise philosopher, pattern recognizer, and faith keeper who helps others understand life's larger cycles and maintain hope during challenging times through understanding of how events connect and serve larger purposes. People perceive you as someone who sees the bigger picture, maintains faith in positive outcomes even during difficulties, and helps others find meaning and direction through understanding of life's patterns. Your public image centers on philosophical wisdom, spiritual faith, and the ability to help others understand their experiences within larger contexts of meaning and purpose. Others see you as someone who demonstrates how acceptance and understanding can create peace and positive outcomes.",
    positive: "Strong reputation as a wise guide and hope provider who helps others maintain faith and find meaning even during the most challenging circumstances. People admire your ability to see patterns and connections that provide comfort and direction. You're known for helping others understand how their individual experiences contribute to larger purposes and how patience and faith can lead to positive outcomes and spiritual growth.",
    challenge: "Reputation may suffer if others perceive you as too passive, fatalistic, or avoiding personal responsibility by attributing everything to fate or external forces. Risk of being seen as discouraging action or initiative when circumstances require practical intervention. May develop reputation for being unreliable if philosophical understanding doesn't include appropriate personal accountability and practical engagement with challenges.",
    advice: "Build your reputation through wise understanding that includes both acceptance of larger patterns and encouragement of appropriate personal responsibility and action when circumstances require practical engagement. Demonstrate how faith and philosophy can guide effective action rather than replacing it. Use your platform to help others understand their role in creating positive outcomes within larger cosmic patterns and divine timing."
  },
  11: {
    general: "Your reputation is built around being seen as a fair judge, ethical leader, and moral authority who makes principled decisions and helps others understand right from wrong while treating everyone with justice and respect. People perceive you as someone who can be trusted to consider all perspectives fairly, make decisions based on ethical principles, and stand up for what's right even when it's difficult. Your public image centers on integrity, fairness, and the ability to help others understand consequences and make ethical choices. Others see you as someone who demonstrates how justice and moral principles can guide decisions that serve both individual growth and collective good.",
    positive: "Strong reputation as a trustworthy authority and ethical leader who makes fair decisions based on moral principles while treating everyone with respect and consideration. People admire your integrity and ability to see truth clearly even in complex situations. You're known for helping others understand ethical implications and make decisions that serve both their authentic development and others' wellbeing.",
    challenge: "Reputation may suffer if others perceive you as overly rigid, judgmental, or harsh in applying moral standards without consideration for human complexity and individual circumstances. Risk of being seen as lacking compassion or mercy when dealing with mistakes and imperfections. May develop reputation for being difficult to approach if ethical standards create distance rather than serving healing and growth.",
    advice: "Build your reputation through compassionate justice that applies moral principles with wisdom about human complexity and the learning process. Demonstrate mercy and understanding alongside your commitment to fairness and ethical behavior. Use your platform to help others understand how ethical principles serve love and growth rather than just maintaining rules and punishing mistakes."
  },
  12: {
    general: "Your reputation is built around being seen as a wise counselor, alternative perspective provider, and spiritual guide who helps others find meaning in difficult experiences and discover creative solutions through seeing situations from completely different angles. People perceive you as someone who offers unique insights, finds wisdom in challenging circumstances, and helps others transform problems into opportunities through changed perspective and spiritual understanding. Your public image centers on wisdom, acceptance, and the ability to help others find meaning and growth in their most difficult experiences. Others see you as someone who demonstrates how surrender and alternative perspectives can lead to liberation and renewed possibility.",
    positive: "Strong reputation as a wise advisor and perspective shifter who helps others find meaning and opportunity in challenging circumstances through spiritual understanding and creative reframing. People admire your ability to see situations from unique angles that reveal hidden gifts and possibilities. You're known for helping others transform their relationship with difficulties and discover spiritual growth and wisdom through experiences that initially seemed purely negative or limiting.",
    challenge: "Reputation may suffer if others perceive you as too passive, confusing, or avoiding practical action when situations require direct intervention and clear solutions. Risk of being seen as making situations unnecessarily complex or mystical when simpler approaches would be more helpful. May develop reputation for being unreliable if spiritual perspectives don't include appropriate practical engagement and clear communication about concrete needs and solutions.",
    advice: "Build your reputation through wise guidance that combines spiritual insight with practical application and clear communication that helps others understand and implement alternative approaches. Demonstrate appropriate action alongside your wisdom about acceptance and surrender. Use your platform to help others find practical solutions and spiritual meaning rather than just philosophical understanding that doesn't translate into positive change."
  },
  13: {
    general: "Your reputation is built around being seen as a transformation catalyst, change facilitator, and renewal guide who helps others navigate major life transitions and discover new possibilities that emerge from releasing outdated patterns and relationships. People perceive you as someone who understands the necessity of endings for new beginnings, provides courage and support during transitions, and demonstrates how transformation can lead to more authentic and fulfilling ways of living. Your public image centers on transformation ability, courage during change, and the capacity to help others find meaning and opportunity in life's inevitable transitions. Others see you as someone who demonstrates how conscious change can serve growth and renewal.",
    positive: "Strong reputation as a transformation guide and renewal catalyst who helps others navigate major changes with courage and wisdom about how endings can lead to better beginnings. People admire your ability to find opportunity and meaning in difficult transitions. You're known for helping others release what no longer serves their growth and embrace new phases of life with confidence and spiritual understanding.",
    challenge: "Reputation may suffer if others perceive you as creating unnecessary drama, being unstable, or destroying rather than transforming situations that could be improved through patience and sustained effort. Risk of being seen as avoiding commitment or abandoning projects when they require work rather than excitement. May develop reputation for being unreliable if transformation energy doesn't include appropriate building of sustainable foundations and lasting positive change.",
    advice: "Build your reputation through conscious transformation that creates positive alternatives and lasting improvements rather than just dramatic change or destruction of existing patterns. Demonstrate commitment to building better foundations alongside your ability to facilitate necessary endings. Use your platform to help others distinguish between healthy transformation and unnecessary instability, and show how conscious change can serve long-term growth and stability."
  },
  14: {
    general: "Your reputation is built around being seen as a balanced healer, integration facilitator, and harmony creator who helps others find sustainable solutions and heal divisions through patient wisdom and moderate approaches that honor all aspects of complex situations. People perceive you as someone who creates emotional balance, facilitates healing and integration, and demonstrates how patience and moderation can achieve lasting solutions that serve everyone's needs. Your public image centers on healing abilities, emotional balance, and the capacity to help others integrate different aspects of themselves and their circumstances into harmonious wholes. Others see you as someone who demonstrates how balance and patience can create sustainable success and genuine healing.",
    positive: "Strong reputation as a skilled healer and balance creator who helps others find sustainable solutions and emotional integration through patient, moderate approaches that serve long-term wellbeing. People admire your ability to remain centered during conflicts and create solutions that honor multiple perspectives and needs. You're known for helping others achieve lasting healing and integration rather than just temporary fixes or dramatic interventions.",
    challenge: "Reputation may suffer if others perceive you as avoiding necessary intensity, being too moderate when situations require passionate engagement, or suppressing important emotions and conflicts that need direct attention. Risk of being seen as lacking conviction or avoiding taking clear positions when circumstances require decisive action. May develop reputation for being ineffective if moderation prevents addressing serious problems that need more focused intervention.",
    advice: "Build your reputation through dynamic balance that includes appropriate intensity and passionate engagement when they serve authentic healing and positive change. Demonstrate wise discernment about when moderation serves growth and when more focused action is needed. Use your platform to show how true healing includes working with rather than avoiding challenging emotions and situations that require integration rather than suppression."
  },
  15: {
    general: "Your reputation is built around being seen as a powerful achiever, material success creator, and practical wisdom provider who understands how to work with complex motivations and achieve tangible results in challenging circumstances. People perceive you as someone who gets things done, understands human nature and power dynamics, and can navigate difficult situations successfully while maintaining ethical standards. Your public image centers on practical competence, material achievement, and the ability to help others understand and work with complex realities including shadow aspects that need integration. Others see you as someone who demonstrates how worldly success and understanding of power can serve positive purposes.",
    positive: "Strong reputation as an effective achiever and practical guide who helps others navigate complex situations and achieve material success while maintaining ethical standards and spiritual perspective. People admire your ability to get real results and understand human nature without being naive about difficulties. You're known for helping others work consciously with power and desire rather than being controlled by unconscious motivations and fears.",
    challenge: "Reputation may suffer if others perceive you as manipulative, overly focused on material gain, or using understanding of human nature to exploit rather than empower others. Risk of being seen as lacking spiritual values or prioritizing success over relationships and ethical considerations. May develop reputation for being untrustworthy if power and influence aren't used consistently to serve others' empowerment and authentic growth.",
    advice: "Build your reputation through ethical achievement that clearly demonstrates how material success and understanding of power dynamics can serve spiritual development and others' empowerment. Use your practical abilities and influence always to help rather than exploit others. Maintain transparent ethical standards and show how worldly competence can enhance rather than compromise spiritual values and authentic relationships."
  },
  16: {
    general: "Your reputation is built around being seen as a truth-teller, breakthrough catalyst, and liberation facilitator who helps others break free from limiting beliefs and patterns that prevent authentic living and spiritual growth. People perceive you as someone who isn't afraid to speak difficult truths, challenge false structures, and create opportunities for genuine awakening and positive change. Your public image centers on honesty, breakthrough ability, and the capacity to help others see through illusions and discover more authentic ways of understanding themselves and their possibilities. Others see you as someone who demonstrates how facing truth can lead to liberation and more fulfilling ways of living.",
    positive: "Strong reputation as a courageous truth-teller and awakening catalyst who helps others break free from limiting patterns and discover authentic freedom through honest self-examination and spiritual growth. People admire your willingness to speak truth even when it's uncomfortable or challenging. You're known for helping others see through false beliefs and societal conditioning to discover their own authentic nature and potential.",
    challenge: "Reputation may suffer if others perceive you as too harsh, insensitive, or destructive in your approach to truth-telling and change facilitation. Risk of being seen as shocking or traumatizing others rather than helping them integrate insights gradually. May develop reputation for being difficult or disruptive if breakthrough energy doesn't include adequate sensitivity to others' capacity for change and need for constructive alternatives.",
    advice: "Build your reputation through compassionate truth-telling that helps others integrate insights and create positive alternatives rather than just shocking them with sudden revelations. Demonstrate sensitivity to others' capacity for change while maintaining your commitment to honesty and authentic liberation. Use your platform to facilitate awakening that leads to constructive positive change rather than just dramatic recognition or destruction of existing patterns."
  },
  17: {
    general: "Your reputation is built around being seen as an inspirational leader, hope provider, and spiritual guide who maintains optimism and faith while helping others connect with their highest potential and divine guidance. People perceive you as someone who radiates positive energy, maintains vision during difficult times, and helps others believe in positive possibilities and their own spiritual potential. Your public image centers on inspiration, spiritual connection, and the ability to help others maintain hope and pursue meaningful goals with faith and determination. Others see you as someone who demonstrates how spiritual faith and positive vision can create practical miracles and positive change.",
    positive: "Strong reputation as an inspiring leader and hope bringer who helps others maintain faith and pursue their highest potential even during the most challenging circumstances. People admire your positive energy and ability to see possibilities that others might miss due to discouragement or limited vision. You're known for connecting others with their spiritual guidance and inspiring them to take action toward meaningful goals and positive change.",
    challenge: "Reputation may suffer if others perceive you as overly idealistic, unrealistic, or avoiding practical challenges while focusing only on positive possibilities and spiritual visions. Risk of being seen as promising more than you can deliver or lacking practical competence to support your inspirational messages. May develop reputation for being impractical if inspiration doesn't include realistic approaches and concrete steps that help others achieve their goals.",
    advice: "Build your reputation through grounded inspiration that combines spiritual vision with practical guidance and realistic approaches to achieving positive goals and meaningful change. Demonstrate practical competence alongside your inspirational abilities and spiritual connection. Use your platform to provide both hope and practical steps that help others manifest their ideals and spiritual insights in concrete reality."
  },
  18: {
    general: "Your reputation is built around being seen as an intuitive guide, emotional depth provider, and mystery navigator who helps others understand the hidden aspects of their experiences and relationships through psychic insight and spiritual sensitivity. People perceive you as someone who understands the mysterious realms of emotion and intuition, provides guidance about unconscious patterns, and helps others navigate complex emotional and spiritual territory. Your public image centers on psychic ability, emotional wisdom, and the capacity to help others understand influences and patterns that aren't immediately visible or rational. Others see you as someone who demonstrates how intuition and spiritual sensitivity can provide practical guidance and healing.",
    positive: "Strong reputation as a trusted psychic guide and emotional counselor who provides valuable insights about hidden influences and unconscious patterns that affect people's lives and relationships. People admire your intuitive abilities and emotional depth that help them understand complex situations. You're known for providing guidance that helps others navigate mysterious or confusing circumstances with greater clarity and spiritual understanding.",
    challenge: "Reputation may suffer if others perceive you as too mystical, confusing, or unable to provide clear practical guidance when situations require concrete direction and decisive action. Risk of being seen as creating more mystery rather than clarity or avoiding practical responsibilities through psychic sensitivity claims. May develop reputation for being unreliable if intuitive insights don't include appropriate practical application and clear communication.",
    advice: "Build your reputation through clear psychic guidance that provides practical insight and helpful direction rather than just mystical information that doesn't serve others' real needs and circumstances. Demonstrate good discernment between genuine spiritual guidance and emotional projection or confusion. Use your intuitive abilities to provide clarity and practical healing rather than creating more mystery or avoiding practical engagement with others' concrete needs."
  },
  19: {
    general: "Your reputation is built around being seen as a confident achiever, positive energy source, and inspirational success story who demonstrates what's possible through authentic self-expression and determined pursuit of meaningful goals. People perceive you as someone who radiates natural confidence, achieves recognition for genuine talents and efforts, and inspires others to believe in their own potential for success and happiness. Your public image centers on achievement, positive energy, and the ability to help others pursue their goals with greater confidence and enthusiasm. Others see you as someone who demonstrates how authentic confidence and positive energy can create success that serves both personal fulfillment and collective inspiration.",
    positive: "Strong reputation as an inspiring achiever and confidence builder who demonstrates authentic success while encouraging others to pursue their own goals and develop their natural talents and abilities. People admire your positive energy and genuine accomplishments that serve as examples of what's possible. You're known for celebrating others' achievements and helping them develop confidence in their own potential for meaningful success and personal fulfillment.",
    challenge: "Reputation may suffer if others perceive you as overly focused on external recognition, narcissistic, or lacking substance behind your confident appearance and achievements. Risk of being seen as seeking attention or measuring worth through others' admiration rather than authentic accomplishment. May develop reputation for being superficial if positive energy doesn't include genuine depth and consideration for others' needs and different definitions of success.",
    advice: "Build your reputation through authentic achievement and genuine confidence that comes from substantial accomplishment and character development rather than just external recognition and approval. Demonstrate humility and support for others' success alongside your natural confidence and positive energy. Use your platform to inspire others' authentic development while maintaining focus on meaningful goals that serve both personal fulfillment and collective good."
  },
  20: {
    general: "Your reputation is built around being seen as a spiritual leader, awakening facilitator, and collective servant who helps others recognize their divine nature and spiritual calling while serving the evolution of human consciousness. People perceive you as someone who lives according to higher spiritual principles, facilitates awakening experiences, and demonstrates how individual spiritual development can serve collective good and universal consciousness. Your public image centers on spiritual authority, collective service, and the ability to help others understand their role in larger spiritual evolution and cosmic purpose. Others see you as someone who demonstrates how spiritual awakening can be integrated with practical service and everyday life.",
    positive: "Strong reputation as a respected spiritual leader and awakening facilitator who helps others develop their spiritual understanding while serving collective consciousness and positive change. People admire your spiritual wisdom and commitment to serving purposes larger than personal gain. You're known for helping others recognize their own divine nature and spiritual calling while demonstrating how spiritual development can enhance rather than escape from practical effectiveness and human compassion.",
    challenge: "Reputation may suffer if others perceive you as spiritually superior, neglecting practical responsibilities, or using spiritual calling to justify avoiding ordinary human needs and relationships. Risk of being seen as impractical or disconnected from everyday concerns and challenges. May develop reputation for being unreliable if spiritual focus doesn't include appropriate attention to practical commitments and human relationships that support rather than conflict with spiritual service.",
    advice: "Build your reputation through humble spiritual service that demonstrates how awakening and spiritual development can enhance rather than replace practical effectiveness and human compassion. Show how spiritual calling can be answered through ordinary life and relationships rather than requiring escape from human responsibilities. Use your platform to serve collective awakening while maintaining grounded engagement with practical needs and everyday human connection."
  },
  21: {
    general: "Your reputation is built around being seen as a master achiever, integration example, and accomplished guide who demonstrates what's possible through dedicated development while using achievements to support others' growth and success. People perceive you as someone who has achieved substantial mastery and integration, provides an example of what dedicated effort can accomplish, and uses success to help others develop their own potential. Your public image centers on accomplishment, integration, and the ability to demonstrate how excellence and mastery can serve both personal fulfillment and collective advancement. Others see you as someone who shows how true achievement includes continued service and support for others' development.",
    positive: "Strong reputation as an accomplished master and inspiring example who demonstrates authentic achievement while generously supporting others' development and success. People admire your substantial accomplishments and ability to integrate different aspects of excellence into satisfying wholes. You're known for using your achievements and expertise to help others develop their own capabilities while maintaining humility and continued commitment to growth and service.",
    challenge: "Reputation may suffer if others perceive you as complacent, superior, or disconnected from others' developmental processes due to your achievements and recognition. Risk of being seen as resting on past accomplishments or becoming isolated by success. May develop reputation for being inaccessible if mastery creates distance rather than serving others' growth and continued learning.",
    advice: "Build your reputation through humble mastery that remains connected to others' developmental processes while sharing your expertise and achievements generously in service of their growth. Demonstrate continued learning and evolution alongside your substantial accomplishments. Use your platform to inspire and support others' development rather than maintaining separation or superiority based on your achievements and recognition."
  },
  22: {
    general: "Your reputation is built around being seen as an innovative pioneer, possibility expander, and fresh perspective provider who approaches situations with unlimited potential and helps others break free from conventional limitations and discover new possibilities. People perceive you as someone who maintains beginner's mind, explores new approaches without being limited by past experience, and demonstrates what becomes possible when people remain open to unlimited potential. Your public image centers on innovation, openness, and the ability to help others see beyond conventional thinking to discover new possibilities for growth and achievement. Others see you as someone who demonstrates how maintaining wonder and possibility can create breakthrough innovations and achievements.",
    positive: "Strong reputation as an innovative pioneer and possibility expander who demonstrates unlimited potential while inspiring others to break free from conventional limitations and explore new approaches to growth and achievement. People admire your fresh perspective and ability to see possibilities that others miss due to limiting assumptions. You're known for helping others maintain openness to new experiences and approaches that can expand their potential and create innovative solutions.",
    challenge: "Reputation may suffer if others perceive you as lacking focus, avoiding sustained commitment, or being unreliable due to constant exploration of new possibilities without developing depth or following through on important projects. Risk of being seen as immature or avoiding responsibility through claims of needing freedom to explore. May develop reputation for being ineffective if unlimited potential doesn't translate into concrete accomplishments and meaningful contributions.",
    advice: "Build your reputation through conscious balance of exploration and commitment that demonstrates how unlimited potential can be channeled into meaningful accomplishments and sustained contributions. Show how fresh perspective can enhance rather than replace the value of sustained effort and practical development. Use your openness to possibility to create innovations and achievements that inspire others while also demonstrating the practical benefits of commitment and sustained effort in important areas."
  }
};