/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Self Expression Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * self-expression, creativity, authentic voice, and the way you naturally
 * communicate your inner world to others through various forms of expression.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Self Expression - How you naturally express your authentic self and creativity
 */
export const selfExpressionInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your self-expression is bold, pioneering, and naturally leadership-oriented, characterized by confident communication and the ability to inspire others through your authentic voice and creative vision. You express yourself through taking initiative, creating new possibilities, and demonstrating your unique perspective with courage and conviction. Your natural mode of expression involves leading by example and encouraging others to embrace their own creative power and authentic self-expression.",
    positive: "Natural charisma and magnetic presence that draws attention to your ideas and creative expressions, making you an influential communicator and inspiring leader. Your confident self-expression encourages others to be more authentic and bold in their own creative endeavors. You excel at expressing new ideas and innovative approaches that break through conventional thinking and inspire positive change in your community or field.",
    challenge: "May dominate conversations or creative spaces without allowing adequate room for others to express themselves, potentially overshadowing collaborative creative efforts. Tendency to express yourself impulsively without considering the impact on others or the appropriateness of timing and context. Can become impatient with slower or more subtle forms of self-expression, preferring direct action over careful consideration or gradual development of ideas.",
    advice: "Balance your natural leadership in creative expression with genuine interest in others' perspectives and collaborative creative processes. Practice listening as much as speaking and create space for others to contribute their unique voices to shared creative endeavors. Channel your expressive energy toward building inclusive environments where multiple forms of authentic expression can flourish rather than just promoting your own voice and vision."
  },
  2: {
    general: "Your self-expression is intuitive, subtle, and deeply connected to inner wisdom and emotional truth, characterized by sensitivity to nuance and the ability to communicate profound insights through gentle, reflective means. You naturally express yourself through listening, observing, and sharing wisdom gained from inner reflection and spiritual understanding. Your mode of expression often involves creating sacred spaces for deep conversation and helping others access their own inner voice and intuitive understanding.",
    positive: "Natural ability to express profound truths and insights in ways that resonate deeply with others' inner wisdom and spiritual understanding. Your gentle, reflective approach to self-expression creates safety for others to share their authentic feelings and perspectives. You excel at expressing complex emotional and spiritual concepts through metaphor, symbolism, and intuitive communication that bypasses rational analysis and speaks directly to the heart.",
    challenge: "May struggle to express yourself directly or assertively when situations require clear communication or decisive action rather than subtle suggestion. Tendency to withhold your authentic expression due to sensitivity to others' reactions or fear of disrupting harmony and peace. Can become overwhelmed by others' emotional expressions or lose your own voice when trying to accommodate everyone's feelings and perspectives.",
    advice: "Trust your intuitive wisdom while also developing skills for clear, direct communication when situations require explicit expression of your needs and boundaries. Practice expressing your authentic feelings and perspectives even when they might create temporary tension or require others to adjust their expectations. Balance your natural receptivity with conscious choice about when to absorb others' expressions and when to maintain your own energetic boundaries."
  },
  3: {
    general: "Your self-expression is abundant, creative, and naturally nurturing, characterized by generous sharing of your talents and the ability to create beautiful, inspiring expressions that uplift and nourish others. You naturally express yourself through creating beauty, abundance, and joy in your environment and relationships. Your mode of expression involves celebrating life's richness and encouraging others to embrace their own creative fertility and expressive generosity.",
    positive: "Natural ability to express yourself in ways that feel nourishing and inspiring to others, creating beautiful and abundant experiences through your creative expression. Your generous approach to sharing your talents and perspectives encourages others to explore their own creative potential and express themselves more fully. You excel at creating aesthetic expressions and environments that feel welcoming and abundant, making others feel valued and inspired.",
    challenge: "May give too much of yourself in creative expression without ensuring your own needs for inspiration and creative nourishment are met, potentially leading to creative burnout or depletion. Tendency to focus on creating beautiful expressions while avoiding more challenging or uncomfortable truths that need to be communicated. Can struggle with setting boundaries around your creative energy and time, saying yes to too many expressive opportunities without adequate focus or depth.",
    advice: "Balance your generous creative expression with attention to your own needs for inspiration, rest, and creative nourishment that sustains your long-term expressive abilities. Practice expressing difficult truths and challenging perspectives with the same care and beauty you bring to more pleasant communications. Develop discernment about which creative opportunities truly serve your authentic expression versus those that drain your creative energy without adequate return."
  },
  4: {
    general: "Your self-expression is structured, reliable, and grounded in practical wisdom and consistent effort, characterized by methodical development of your expressive abilities and commitment to building lasting creative foundations. You naturally express yourself through creating systems, structures, and practical solutions that serve long-term goals and sustainable development. Your mode of expression involves demonstrating values through consistent action and building expressive skills through disciplined practice and gradual mastery.",
    positive: "Natural ability to express complex ideas and concepts in organized, systematic ways that others can understand and implement practically. Your consistent approach to self-expression builds trust and reliability, making you someone others turn to for practical wisdom and grounded perspective. You excel at creating lasting expressions and building expressive skills that develop steadily over time through dedicated practice and careful attention to craft.",
    challenge: "May be too rigid or methodical in your self-expression, lacking spontaneity or emotional flexibility that could enhance your creative communication. Tendency to focus on perfecting your expressive techniques rather than allowing authentic emotions and spontaneous insights to emerge naturally. Can become frustrated with others' less structured approaches to expression or dismiss creative methods that don't fit your systematic preferences.",
    advice: "Build upon your natural organizational skills and systematic approach while also allowing room for spontaneity and emotional expression that enhances rather than disrupts your structured foundation. Practice expressing yourself in ways that feel authentic and emotionally honest rather than just technically correct or socially appropriate. Balance your preference for proven expressive methods with openness to new approaches that could expand your creative range and emotional depth."
  },
  5: {
    general: "Your self-expression is guided by traditional wisdom, moral principles, and respect for established forms of communication and creative expression that have proven valuable over time. You naturally express yourself through conventional channels and established frameworks while seeking to understand and communicate deeper spiritual and ethical truths. Your mode of expression involves teaching, sharing wisdom, and helping others connect with time-tested principles and meaningful traditions.",
    positive: "Natural ability to express complex spiritual and philosophical concepts in ways that connect with established wisdom traditions and resonate with others' desire for meaning and moral guidance. Your respectful approach to traditional forms of expression creates trust and allows others to receive your insights without feeling threatened or challenged. You excel at communicating timeless truths and universal principles through conventional means that feel familiar and accessible to diverse audiences.",
    challenge: "May be too conservative or traditional in your self-expression, limiting your authentic voice when it doesn't fit conventional patterns or established expectations. Tendency to suppress aspects of your creativity or perspective that seem inconsistent with traditional values or social norms. Can struggle with expressing innovative ideas or personal insights that challenge conventional wisdom or established expressive forms.",
    advice: "Honor your connection to traditional wisdom and established forms of expression while also allowing your authentic voice to emerge and contribute new insights to these traditions. Practice expressing your personal perspectives and innovative ideas within the framework of your values rather than suppressing them entirely. Recognize that authentic self-expression can both honor tradition and contribute to its evolution and development over time."
  },
  6: {
    general: "Your self-expression is harmonious, aesthetically focused, and naturally oriented toward creating beauty and balance in your communications and creative endeavors. You naturally express yourself through collaborative creation, diplomatic communication, and the pursuit of aesthetic excellence that pleases and harmonizes with others. Your mode of expression involves creating beautiful relationships and environments through balanced, considerate communication that honors multiple perspectives and values.",
    positive: "Natural ability to express yourself in ways that create harmony and beauty in your relationships and creative collaborations. Your diplomatic communication style helps resolve conflicts and create mutual understanding among people with different perspectives and needs. You excel at creating aesthetically pleasing expressions and environments that feel balanced and welcoming, making others feel valued and appreciated through your thoughtful communication.",
    challenge: "May avoid expressing authentic feelings or perspectives when they might create conflict or disrupt harmony, potentially limiting your genuine self-expression. Tendency to focus more on how your expression appears or sounds rather than whether it accurately represents your true thoughts and feelings. Can become overly concerned with others' approval or aesthetic preferences, losing touch with your own authentic creative voice and perspective.",
    advice: "Balance your natural gift for creating harmony and beauty with commitment to authentic self-expression that honors your true feelings and perspectives. Practice expressing difficult truths and personal needs in ways that maintain respect for others while still communicating your genuine experience and desires. Develop confidence in your own aesthetic sense and creative voice rather than constantly adjusting your expression to match others' preferences or expectations."
  },
  7: {
    general: "Your self-expression is dynamic, goal-oriented, and characterized by passionate communication and the ability to inspire others through your enthusiasm and determination to achieve meaningful objectives. You naturally express yourself through active pursuit of your goals and encouraging others to overcome obstacles and pursue their own aspirations with courage and persistence. Your mode of expression involves competitive excellence and the demonstration of what's possible through focused effort and unwavering commitment.",
    positive: "Natural ability to express yourself with passion and conviction that motivates others to pursue their own goals and overcome challenges they might otherwise avoid. Your dynamic communication style creates excitement and momentum around shared objectives and creative projects. You excel at expressing confidence and determination that helps others believe in their own abilities and push through difficulties toward achieving their aspirations.",
    challenge: "May be too intense or aggressive in your self-expression, overwhelming others or creating pressure when gentler approaches might be more effective. Tendency to focus on achieving expressive goals rather than enjoying the process of creative exploration and authentic communication. Can become impatient with slower or more reflective forms of expression, missing opportunities for deeper connection and understanding.",
    advice: "Channel your passionate energy and goal-oriented drive toward inspiring others while also creating space for quieter, more reflective forms of expression and communication. Practice expressing yourself in ways that motivate others without creating pressure or expectations that feel overwhelming or demanding. Balance your focus on achieving expressive excellence with appreciation for the journey of creative development and authentic self-discovery."
  },
  8: {
    general: "Your self-expression is characterized by gentle strength, patient persistence, and the ability to communicate healing and transformation through compassionate presence and emotional resilience. You naturally express yourself through demonstrating how to handle challenges with grace and how to transform difficulties into opportunities for growth and deeper understanding. Your mode of expression involves modeling emotional strength and helping others find their own inner resources for dealing with life's complexities.",
    positive: "Natural ability to express yourself in ways that provide comfort and healing to others, helping them find strength and hope during difficult times. Your patient, compassionate communication style creates safety for others to share their vulnerabilities and work through challenges without judgment. You excel at expressing difficult truths and complex emotions in ways that promote healing and growth rather than creating additional stress or confusion.",
    challenge: "May suppress your own needs for expression and emotional processing in order to focus on helping others, potentially leading to internal stress or resentment. Tendency to avoid expressing anger or frustration directly, preferring to endure difficulties rather than addressing them assertively when necessary. Can become too focused on others' emotional needs while neglecting your own authentic expression and creative fulfillment.",
    advice: "Use your natural gift for compassionate expression while also advocating for your own needs and creative fulfillment with the same gentleness and persistence you offer others. Practice expressing your authentic feelings and perspectives even when they might temporarily create tension or require others to adjust their expectations. Balance your focus on helping others with regular attention to your own expressive needs and creative development."
  },
  9: {
    general: "Your self-expression is wise, contemplative, and deeply connected to spiritual understanding and the sharing of insights gained through solitary reflection and inner development. You naturally express yourself through teaching, mentoring, and sharing profound wisdom that helps others understand life's deeper meanings and navigate their own spiritual journey. Your mode of expression involves creating opportunities for others to access their own inner wisdom and spiritual understanding.",
    positive: "Natural ability to express complex spiritual and philosophical concepts in ways that help others understand themselves and their life circumstances more deeply. Your wise, contemplative approach to communication creates opportunities for meaningful dialogue and mutual learning. You excel at expressing insights that help others find their own inner guidance and develop their spiritual understanding through practical application of universal principles.",
    challenge: "May become too withdrawn or solitary in your expression, missing opportunities to share your wisdom and insights with others who could benefit from your guidance. Tendency to intellectualize your expression rather than connecting with others on emotional or practical levels that make your insights accessible and applicable. Can struggle with expressing yourself in social situations or adapting your communication style to different audiences and contexts.",
    advice: "Balance your natural wisdom and contemplative insights with regular engagement in communication and expression that serves others' practical needs and spiritual development. Practice expressing your understanding in ways that connect with others' everyday experiences and challenges rather than remaining in abstract or theoretical realms. Find ways to share your wisdom that feel authentic and meaningful while also being accessible and applicable to others' lives."
  },
  10: {
    general: "Your self-expression follows natural cycles and rhythms with periods of intense creative output alternating with times of reflection and integration, allowing your authentic voice to emerge through awareness of timing and natural flow. You naturally express yourself through recognition of life's patterns and cycles, helping others understand how to work with rather than against natural timing and development. Your mode of expression involves demonstrating how to flow with circumstances while maintaining authentic self-expression.",
    positive: "Natural understanding of timing and cycles that allows you to express yourself most effectively when the moment is right for your message or creative contribution. Your ability to flow with changing circumstances helps you adapt your expression to different situations and audiences without losing your authentic voice. You excel at recognizing and expressing the deeper patterns and meanings in life events that help others understand their own journey and development.",
    challenge: "May become passive about self-expression, waiting for perfect timing or ideal circumstances rather than actively creating opportunities to share your voice and perspective. Tendency to use belief in natural cycles to avoid taking responsibility for consistent creative effort or regular communication when relationships and projects need your active participation. Can become confused about when to express yourself assertively and when to remain receptive and observant.",
    advice: "Learn to work with natural timing and cycles while also taking proactive steps to express yourself consistently and maintain your creative practices and relationships. Practice distinguishing between appropriate patience and passive avoidance of necessary expression and communication. Develop confidence in your ability to express yourself authentically regardless of external circumstances while still honoring natural timing and appropriate response to changing situations."
  },
  11: {
    general: "Your self-expression is guided by strong moral principles and commitment to fairness, characterized by honest communication and the ability to express ethical perspectives that promote justice and balanced understanding. You naturally express yourself through advocating for fairness and helping others understand different perspectives and moral implications of decisions and actions. Your mode of expression involves creating equitable communication and ensuring that all voices are heard and valued appropriately.",
    positive: "Natural ability to express yourself in ways that promote fairness and justice, helping others understand ethical implications and moral considerations in their decisions and relationships. Your honest, principled communication creates trust and respect, making you someone others turn to for ethical guidance and balanced perspective. You excel at expressing complex moral concepts and helping others find fair solutions to conflicts and challenging situations.",
    challenge: "May become too focused on moral correctness or fairness in your expression, potentially limiting spontaneity or emotional authenticity when they don't align with your ethical principles. Tendency to analyze the ethical implications of your expression so thoroughly that you become paralyzed or unable to communicate naturally and spontaneously. Can become judgmental about others' expressive choices or communication styles that don't meet your standards for fairness and moral clarity.",
    advice: "Balance your natural commitment to ethical expression with acceptance of human complexity and the recognition that authentic communication sometimes requires emotional honesty that may temporarily disrupt perfect fairness. Practice expressing yourself more spontaneously while maintaining your core ethical principles and commitment to treating others with respect and consideration. Develop tolerance for the imperfect nature of human communication while still advocating for fairness and justice in your relationships and community."
  },
  12: {
    general: "Your self-expression involves unique perspectives, willingness to sacrifice conventional approaches for deeper truth, and the ability to communicate insights gained through seeing situations from completely different angles. You naturally express yourself through unconventional methods and alternative viewpoints that challenge others to think differently and question their assumptions. Your mode of expression involves offering fresh perspectives that can transform understanding and create breakthrough insights.",
    positive: "Natural ability to express yourself in ways that offer fresh perspectives and innovative approaches that others might not consider or discover on their own. Your willingness to sacrifice conventional expression for authentic truth often leads to profound insights and creative breakthroughs. You excel at communicating complex ideas through unconventional means that capture attention and inspire others to expand their thinking and creative possibilities.",
    challenge: "May make your self-expression unnecessarily complex or difficult to understand when simpler, more direct communication would be more effective and accessible. Tendency to sacrifice practical communication needs for the sake of being different or unconventional rather than truly serving deeper understanding. Can become stuck in alternative perspectives without taking action or making the practical changes that your insights suggest are necessary.",
    advice: "Use your gift for unique perspectives and unconventional expression to enhance rather than complicate communication and creative collaboration with others. Practice expressing your insights in ways that others can understand and apply practically rather than just appreciating intellectually or aesthetically. Balance your willingness to sacrifice conventional approaches with attention to what actually serves effective communication and positive change in your relationships and creative endeavors."
  },
  13: {
    general: "Your self-expression involves transformation, letting go of old patterns, and the ability to communicate profound change and renewal through your authentic voice and creative evolution. You naturally express yourself through demonstrating how to release what no longer serves and embrace new forms of creative expression and authentic communication. Your mode of expression involves constant evolution and the courage to transform your voice and message as you grow and change.",
    positive: "Natural ability to express yourself authentically through periods of significant change and transformation, helping others understand how to navigate their own evolving identity and creative expression. Your comfort with letting go of old expressive patterns allows you to continually evolve and discover new depths of authentic communication. You excel at expressing the transformative power of authentic self-expression and helping others find courage to change and grow.",
    challenge: "May create unnecessary drama or crisis in your self-expression when gradual evolution would be more sustainable and effective for your relationships and creative development. Tendency to abandon expressive projects or relationships too quickly when they become challenging rather than working through difficulties that could lead to deeper understanding and growth. Can become so focused on transformation that you don't build lasting foundations for your creative expression and authentic communication.",
    advice: "Embrace your natural gift for transformation and evolving expression while also building sustainable foundations that can support your creative development over time. Practice communicating about change and growth in ways that help others understand and adapt rather than shocking or overwhelming them with sudden shifts. Balance your comfort with expressive transformation with appreciation for consistency and gradual development that allows relationships and creative projects to mature and deepen."
  },
  14: {
    general: "Your self-expression is characterized by balance, moderation, and the ability to integrate different aspects of your personality and creative abilities into harmonious, sustainable communication and artistic expression. You naturally express yourself through finding middle ground and helping others discover balanced approaches to creative expression and authentic communication. Your mode of expression involves healing integration and the demonstration of how different perspectives and abilities can work together harmoniously.",
    positive: "Natural ability to express yourself in ways that integrate different aspects of your personality and experience, creating authentic communication that feels whole and balanced. Your moderate approach to self-expression creates sustainability and allows for long-term creative development without burnout or extremes. You excel at helping others find balanced approaches to their own creative expression and authentic communication that honor multiple aspects of their identity and experience.",
    challenge: "May avoid necessary intensity or passionate expression in favor of maintaining balance, potentially limiting the depth and authenticity of your creative expression. Tendency to suppress aspects of yourself that feel extreme or challenging in order to maintain harmony and moderation in your communication. Can become stuck in comfortable patterns of expression that feel safe but don't allow for growth or exploration of your full creative potential.",
    advice: "Maintain your valuable ability to create balanced, integrated expression while also allowing for appropriate intensity and passionate communication when they serve authentic self-expression. Practice expressing all aspects of yourself, including those that feel challenging or intense, while using your natural moderation to communicate them constructively. Balance your preference for harmony with willingness to explore the full range of your creative and expressive potential."
  },
  15: {
    general: "Your self-expression is intense, powerful, and involves honest acknowledgment of shadow aspects and desires that others might prefer to hide or ignore. You naturally express yourself through embracing the full spectrum of human experience and helping others accept and integrate their own complex desires and motivations. Your mode of expression involves passionate intensity and the courage to communicate truths that others might find uncomfortable or challenging.",
    positive: "Natural ability to express yourself with intense authenticity that helps others accept and integrate their own shadow aspects and complex desires. Your willingness to embrace and communicate about difficult topics creates opportunities for deeper understanding and authentic connection. You excel at expressing passionate intensity and helping others access their own power and authentic desires without shame or judgment.",
    challenge: "May overwhelm others with the intensity of your expression or use your powerful communication to manipulate or control rather than to promote mutual understanding and growth. Tendency to focus on expressing your desires and perspectives without adequate consideration of others' needs and boundaries. Can become obsessed with particular forms of expression or creative projects at the expense of balanced attention to other life areas and relationships.",
    advice: "Channel your powerful expressive energy toward creating authentic connections and mutual understanding rather than using intensity to dominate or control others' responses. Practice expressing your authentic desires and perspectives while also remaining open to others' needs and boundaries in communication and creative collaboration. Use your understanding of shadow aspects and complex motivations to create conscious, consensual expressions rather than unconscious manipulation or emotional overwhelm."
  },
  16: {
    general: "Your self-expression involves sudden revelations, breakthrough insights, and the ability to communicate transformative truths that shatter illusions and create liberation from limiting patterns of thought and communication. You naturally express yourself through dramatic realizations and the courage to speak truths that others might find shocking or disruptive. Your mode of expression involves breakthrough moments that fundamentally change understanding and create new possibilities for authentic communication.",
    positive: "Natural ability to express breakthrough insights and revelations that help others see their situations clearly and break free from limiting patterns of thought and communication. Your willingness to speak difficult truths creates opportunities for liberation and authentic transformation. You excel at expressing sudden realizations that fundamentally shift perspective and create new possibilities for creative expression and authentic relationship.",
    challenge: "May express revelations and insights in ways that shock or overwhelm others rather than helping them integrate new understanding gradually and constructively. Tendency to create unnecessary drama or crisis through your expression when more gradual communication might be more effective for promoting lasting change. Can become addicted to breakthrough moments and dramatic expression rather than building steady foundations for authentic communication and creative development.",
    advice: "Use your gift for breakthrough insights and revelatory expression to help others grow and transform rather than just to shock or get attention. Practice communicating your realizations in ways that others can receive and integrate constructively rather than becoming overwhelmed or defensive. Build upon the insights and revelations you experience rather than constantly seeking new dramatic expressions without integrating and applying what you've already discovered."
  },
  17: {
    general: "Your self-expression is hopeful, inspiring, and connected to higher purpose and spiritual vision, characterized by communication that uplifts others and helps them connect with their own highest potential and spiritual guidance. You naturally express yourself through sharing inspiration and helping others maintain faith in positive possibilities and divine guidance. Your mode of expression involves creating hope and spiritual connection that transcends immediate circumstances and challenges.",
    positive: "Natural ability to express yourself in ways that inspire hope and connect others with their highest potential and spiritual guidance. Your optimistic, spiritually-oriented communication helps others maintain faith during difficult times and vision for positive future possibilities. You excel at expressing spiritual insights and inspiration that help others find meaning and purpose in their experiences and challenges.",
    challenge: "May express idealistic visions without adequate attention to practical realities or the steps needed to manifest positive change in concrete circumstances. Tendency to avoid expressing difficult truths or challenging emotions that might diminish hope or optimistic perspective. Can become disappointed when your inspirational expression doesn't immediately create the positive changes you envision, leading to discouragement about your ability to make a difference.",
    advice: "Balance your natural gift for inspirational expression with practical attention to the concrete steps needed to manifest positive change and spiritual growth. Practice expressing hope and spiritual vision while also acknowledging current challenges and difficulties that need to be addressed practically. Ground your spiritual insights and inspirational communication in practical actions and realistic steps that can actually create the positive changes you so beautifully envision."
  },
  18: {
    general: "Your self-expression is mysterious, intuitive, and deeply connected to unconscious realms and psychic dimensions of communication that exist beyond rational understanding. You naturally express yourself through dreams, symbols, and intuitive insights that communicate on subtle levels and connect with others' unconscious understanding. Your mode of expression involves accessing and sharing hidden knowledge and helping others understand the mysterious aspects of their own psyche and spiritual development.",
    positive: "Natural ability to express profound mysteries and unconscious insights that help others understand hidden aspects of themselves and their experiences. Your intuitive communication style connects with others on psychic and emotional levels that bypass rational analysis and speak directly to the soul. You excel at expressing complex psychological and spiritual concepts through symbols, metaphors, and intuitive insights that resonate deeply with others' inner knowing.",
    challenge: "May struggle with clear, practical communication when situations require explicit information or direct instruction rather than subtle, intuitive exchange. Tendency to become lost in symbolic or metaphorical expression that others find confusing or difficult to understand and apply practically. Can become overwhelmed by psychic information or others' emotional projections, losing clarity about your own authentic expression and message.",
    advice: "Trust your intuitive gifts and mystical understanding while also developing practical communication skills that help others understand and apply your insights in their daily lives. Practice expressing your psychic and spiritual insights in ways that others can receive and use constructively rather than just appreciate aesthetically. Maintain clear boundaries between your own intuitive expression and others' psychic projections or emotional needs."
  },
  19: {
    general: "Your self-expression is joyful, radiant, and naturally enthusiastic, characterized by authentic celebration of life and the ability to inspire others through your genuine happiness and positive energy. You naturally express yourself through sharing joy and helping others recognize and celebrate their own accomplishments and positive experiences. Your mode of expression involves authentic enthusiasm that attracts others and creates opportunities for shared celebration and mutual encouragement.",
    positive: "Natural ability to express yourself with genuine joy and enthusiasm that lifts others' spirits and helps them appreciate their own positive experiences and accomplishments. Your radiant communication creates attractive energy that draws others and opportunities for creative collaboration and shared celebration. You excel at expressing authentic appreciation and helping others recognize and celebrate their own gifts and achievements.",
    challenge: "May avoid expressing challenging emotions or difficult truths in order to maintain positive energy, potentially limiting the depth and authenticity of your communication and relationships. Tendency to suppress or deny problems and conflicts rather than addressing them directly when they need attention and resolution. Can become superficial in your expression, focusing on positive experiences while avoiding the full spectrum of human emotion and experience.",
    advice: "Maintain your natural gift for joyful expression while also creating space for authentic communication about challenges and difficulties that need attention and resolution. Practice expressing the full range of your emotions and experiences while maintaining your positive outlook and faith in positive possibilities. Balance your focus on celebration and appreciation with willingness to address problems and conflicts directly when they arise."
  },
  20: {
    general: "Your self-expression represents a spiritual calling and involves communicating messages that serve higher purpose and collective awakening, characterized by expression that transcends personal needs and serves universal truth and spiritual development. You naturally express yourself through sharing spiritual insights and helping others recognize their own divine nature and spiritual calling. Your mode of expression involves answering a higher calling and using your voice to serve spiritual awakening and collective transformation.",
    positive: "Natural ability to express yourself in ways that serve spiritual awakening and help others recognize their own divine nature and spiritual calling. Your expression often carries spiritual authority and wisdom that helps others connect with universal truth and higher purpose. You excel at communicating spiritual insights that inspire others to pursue their own spiritual development and service to higher consciousness.",
    challenge: "May struggle with expressing everyday concerns and practical needs when focused on spiritual service and higher purpose, potentially neglecting important personal relationships and responsibilities. Tendency to suppress personal desires and individual expression in favor of serving collective needs, which can lead to spiritual bypassing or loss of personal authenticity. Can become overwhelmed by the responsibility of spiritual expression or confused about how to serve higher purpose while maintaining healthy personal boundaries.",
    advice: "Answer your spiritual calling and serve higher purpose through your expression while also maintaining attention to your personal needs and practical responsibilities. Practice integrating spiritual service with authentic personal expression rather than sacrificing your individual needs entirely. Find ways to serve universal truth and collective awakening that also honor your personal journey and individual creative gifts."
  },
  21: {
    general: "Your self-expression represents completion, fulfillment, and the successful integration of all aspects of your creative abilities and authentic voice into mature, satisfying expression that serves as a model for others. You naturally express yourself through demonstrating what's possible when all aspects of personality and creative potential are honored and integrated. Your mode of expression involves sharing the wisdom and fulfillment you've achieved through complete authentic self-expression.",
    positive: "Natural ability to express yourself with completeness and integration that demonstrates the full potential of authentic creative expression and communication. Your mature, fulfilled approach to self-expression inspires others and provides a model of what's possible through dedicated development of creative abilities. You excel at expressing yourself in ways that feel complete and satisfying while also serving others' growth and creative development.",
    challenge: "May become complacent about your expressive abilities or take your creative fulfillment for granted, potentially limiting continued growth and evolution in your communication and creative expression. Tendency to rest on past achievements rather than continuing to explore new possibilities for creative expression and authentic communication. Can become isolated from others' creative processes or lose touch with beginner's mind and openness to learning and growth.",
    advice: "Celebrate your achievements in authentic self-expression while remaining open to continued growth and evolution in your creative abilities and communication skills. Use your fulfillment and integration to help others develop their own expressive abilities rather than becoming disconnected from the learning process. Maintain curiosity about new possibilities for creative expression and authentic communication rather than assuming you've reached the final destination in your expressive development."
  },
  22: {
    general: "Your self-expression is characterized by unlimited potential, beginner's mind, and the ability to approach creative expression with fresh perspective and innocent curiosity that isn't limited by past experience or conventional expectations. You naturally express yourself through experimentation and discovery without predetermined limitations about what's possible or appropriate. Your mode of expression involves pioneering new forms of creative expression and helping others maintain openness to discovery and authentic exploration.",
    positive: "Natural openness and unlimited potential for creative expression that isn't constrained by conventional thinking or past experiences. Your fresh perspective and willingness to experiment often leads to breakthrough discoveries and innovative approaches to creative expression and authentic communication. You offer others the gift of experiencing creative expression as an adventure and opportunity for mutual discovery rather than performance or repetition of familiar patterns.",
    challenge: "May lack practical experience or communication skills needed to express yourself effectively in complex situations, potentially creating misunderstandings through inexperience rather than lack of good intentions. Tendency toward expressive impulsiveness without adequate consideration of consequences or impact on others and relationships. Can struggle with developing consistency or depth in your expression, preferring constant novelty over sustained development of creative abilities.",
    advice: "Embrace your natural openness and unlimited potential for creative expression while also developing practical communication skills and learning from experienced mentors and guides. Practice expressing yourself in ways that consider the impact on others and long-term consequences while maintaining your spontaneous creativity and fresh perspective. Balance your love of experimentation with commitment to developing some areas of expressive expertise and consistent creative practice."
  }
};