/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Sexuality Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * sexual expression, intimate energy, and the way you experience and
 * share physical and energetic connection with others.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Sexuality - How you express and experience sexual energy
 */
export const sexualityInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "Your sexual energy is bold, confident, and highly creative, characterized by strong initiative and the ability to manifest your desires through passionate self-expression and magnetic personal power. You approach sexuality with the same pioneering spirit that you bring to other areas of life, preferring to lead and create rather than follow conventional patterns. Your sexual nature is fundamentally about creation, manifestation, and the expression of pure life force energy through intimate connection with others.",
    positive: "Natural sexual magnetism and ability to inspire passion in others, with strong capacity for manifesting your sexual desires and creating fulfilling intimate experiences. Your confidence and initiative in sexual matters helps partners feel desired and appreciated while encouraging them to explore their own sexual expression more fully. You bring creative energy and innovative approaches to intimacy that keep sexual relationships exciting and dynamic over time.",
    challenge: "May be too aggressive or self-focused in sexual expression, prioritizing your own satisfaction and desires without adequate attention to your partner's needs and preferences. Tendency to dominate sexual encounters or rush through intimacy without taking time for emotional connection and mutual exploration. Can struggle with vulnerability and receptivity in sexual relationships, finding it easier to give pleasure than to receive it fully.",
    advice: "Balance your powerful sexual energy with genuine consideration and attention to your partner's needs, creating space for mutual exploration and shared pleasure rather than one-sided expression. Practice vulnerability and receptivity in intimate moments, allowing yourself to be pleasured and cared for rather than always taking the leadership role. Channel your creative sexual energy toward building deeper intimacy and connection rather than just physical satisfaction."
  },
  2: {
    general: "Your sexuality is intuitive, mysterious, and deeply connected to emotional and psychic realms, characterized by sensitivity to subtle energies and the ability to create profound spiritual connections through intimate touch. You approach sexual expression through feeling and intuition rather than technique or performance, preferring intimate encounters that honor the sacred and mysterious aspects of sexual energy. Your sexual nature thrives in environments of trust, emotional safety, and spiritual connection where deeper communion beyond the physical is possible.",
    positive: "Strong intuitive understanding of your partner's sexual needs and desires, often sensing what they want before they express it verbally or even consciously recognize it themselves. Natural ability to create mystical, transcendent sexual experiences that connect both partners to spiritual realms and deeper aspects of themselves. Your emotional sensitivity and psychic awareness bring healing and transformation to sexual relationships through compassionate, intuitive touch.",
    challenge: "May be too passive or withdrawn in sexual expression, expecting partners to intuitively understand your needs without clear communication about desires and boundaries. Difficulty expressing sexual desires directly or asking for what you want, preferring to hint or hope that partners will guess rather than speaking openly. Can become overwhelmed by intense sexual energy or your partner's emotions, losing your own center and boundaries in intimate encounters.",
    advice: "Trust your intuitive understanding of sexual energy while also developing skills for clear, direct communication about your own needs, desires, and boundaries in intimate relationships. Practice expressing your sexual wants and fantasies openly rather than expecting partners to read your mind or pick up on subtle cues. Create healthy energetic boundaries that allow you to be emotionally and sexually open without losing yourself in your partner's experience."
  },
  3: {
    general: "Your sexuality is abundant, creative, and naturally sensual, characterized by generous expression of pleasure and the ability to create fertile, nourishing intimate experiences that feel like celebrations of life and love. You approach sexual connection with the same nurturing, creative energy that you bring to other forms of expression, seeing sexuality as an opportunity to give and receive pleasure abundantly. Your sexual nature is fundamentally about creation, fertility, and the joyful expression of life force energy through sensual pleasure and intimate connection.",
    positive: "Natural sensuality and ability to create beautiful, pleasurable sexual experiences that feel abundant and nourishing for both partners involved. Your generous approach to sexual pleasure helps partners feel cherished and appreciated while encouraging them to embrace their own sensual nature more fully. You excel at creating romantic, aesthetic environments for intimacy and bringing creativity and playfulness to sexual expression.",
    challenge: "May focus too much on giving sexual pleasure without allowing yourself to receive fully, potentially creating imbalance or resentment in intimate relationships over time. Tendency to use sexual generosity as a way to gain love or approval rather than expressing authentic desire and passion for mutual pleasure. Can struggle with sexual boundaries, giving too much of your sexual energy without ensuring that your own needs and desires are also met and honored.",
    advice: "Balance your natural generosity in sexual expression with willingness to receive pleasure fully and communicate your own desires and needs clearly to partners. Allow yourself to be the focus of sexual attention and care rather than always being the one who provides pleasure and nurturing to others. Practice asking for what you want sexually and setting boundaries that protect your sexual energy while still allowing for generous, loving expression."
  },
  4: {
    general: "Your sexuality is structured, reliable, and grounded in physical sensation and consistent patterns that create security and trust in intimate relationships over time. You approach sexual expression with the same methodical, building-focused energy that characterizes other areas of your life, preferring to develop sexual intimacy gradually through repeated positive experiences. Your sexual nature values commitment, consistency, and the creation of stable intimate relationships where both partners can explore and grow sexually within a secure foundation.",
    positive: "Dependable sexual partner who builds lasting intimate relationships through consistent attention to your partner's needs and steady development of sexual trust and connection over time. Your grounded approach to sexuality helps partners feel safe and secure enough to explore their desires and vulnerabilities without fear of judgment or abandonment. You excel at creating sexual routines and practices that deepen intimacy and satisfaction through repetition and refinement.",
    challenge: "May be too rigid or resistant to sexual exploration and variety, preferring familiar patterns even when new experiences might enhance pleasure and connection for both partners. Tendency to approach sexuality with excessive seriousness or focus on performance rather than play, spontaneity, and emotional connection. Can struggle with sexual spontaneity or adapting to your partner's changing needs and desires over time.",
    advice: "Build on your natural ability to create sexual security and consistency while remaining open to new experiences and varieties of expression that can enhance intimacy and pleasure. Practice sexual spontaneity and playfulness within the secure foundation you create, allowing room for experimentation and growth. Balance your preference for sexual routine with willingness to adapt and evolve as your own and your partner's sexual needs change over time."
  },
  5: {
    general: "Your approach to sexuality is influenced by traditional values, spiritual beliefs, and respect for established wisdom about intimate relationships and sexual expression within committed partnerships. You tend to honor conventional approaches to sexual intimacy while seeking to understand the deeper spiritual and moral dimensions of sexual connection between committed partners. Your sexual nature values respect, commitment, and the integration of sexual expression with spiritual and emotional development within the context of meaningful relationships.",
    positive: "Natural respect for sexual boundaries, commitments, and the sacred aspects of intimate connection, creating relationships where both partners feel honored and respected. Your traditional approach to sexuality provides stability and moral foundation that helps partners feel secure in exploring intimacy within committed relationships. You bring wisdom about the connection between sexual expression and spiritual development, helping to integrate physical pleasure with higher purposes and values.",
    challenge: "May be overly conservative or judgmental about sexual expression, limiting your own or your partner's exploration of desires that don't fit traditional patterns or expectations. Tendency to suppress or deny aspects of your sexuality that seem inconsistent with spiritual or moral beliefs, potentially creating internal conflict or sexual repression. Can be resistant to sexual education or exploration that challenges conventional ideas about appropriate sexual behavior and expression.",
    advice: "Honor your values and spiritual beliefs about sexuality while remaining open to growth and learning that can enhance your sexual expression and intimate relationships. Explore how your sexual nature can be expressed authentically within the framework of your values rather than suppressing desires that feel inconsistent with your beliefs. Respect others' sexual journeys and choices even when they differ from your own approach, recognizing that authenticity takes many forms."
  },
  6: {
    general: "Your sexuality is harmonious, partnership-focused, and deeply concerned with creating beautiful, balanced intimate experiences that satisfy both partners equally and enhance the overall aesthetic and emotional quality of your relationship. You approach sexual expression as an art form that should be pleasing, harmonious, and mutually satisfying, preferring intimate encounters that feel like collaborative creations of beauty and pleasure. Your sexual nature thrives in relationships where there is mutual appreciation, aesthetic pleasure, and shared commitment to creating beautiful intimate experiences together.",
    positive: "Natural ability to create beautiful, harmonious sexual experiences that feel like art and leave both partners feeling appreciated and satisfied. Your partnership-focused approach to sexuality ensures that both people's needs and desires are considered and honored in intimate encounters. You excel at reading your partner's responses and adjusting your approach to create maximum pleasure and connection for both people involved.",
    challenge: "May avoid sexual conflict or difficult conversations about desires and boundaries, preferring to maintain surface harmony rather than addressing underlying issues that need attention. Tendency to focus more on how sexual encounters look or feel aesthetically rather than embracing the raw, intense, or messy aspects of sexual passion and desire. Can struggle with sexual assertiveness or expressing desires that might create temporary tension or require negotiation with your partner.",
    advice: "Embrace both the beautiful and the intensely passionate aspects of sexual expression, recognizing that sometimes great sex requires moving beyond comfortable harmony into more intense territory. Practice expressing your authentic sexual desires even when they might create temporary tension or require difficult conversations with your partner. Allow for some messiness and intensity in sexual expression rather than always maintaining perfect balance and aesthetic appeal."
  },
  7: {
    general: "Your sexual energy is dynamic, goal-oriented, and characterized by strong drive and determination to overcome obstacles to intimate connection and achieve satisfying sexual experiences through focused effort and persistent pursuit. You approach sexuality with the same competitive, achievement-focused energy that characterizes other areas of your life, preferring active, energetic intimate encounters that feel like shared adventures or conquests. Your sexual nature thrives on challenge, variety, and the excitement of pursuing and winning your partner's desire and satisfaction.",
    positive: "Passionate sexual energy and determination that helps overcome obstacles to intimacy and creates exciting, dynamic sexual experiences full of energy and enthusiasm. Your drive and focus help ensure that sexual encounters are satisfying and complete, with attention to achieving mutual pleasure and satisfaction. You bring adventure and excitement to sexual relationships, keeping intimacy dynamic and preventing sexual routines from becoming boring or stagnant.",
    challenge: "May be impatient with slower sexual processes like extended foreplay, emotional connection, or gradual building of arousal, preferring to move quickly toward goals and completion. Tendency to focus on sexual performance and achievement rather than presence, connection, and the journey of intimate exploration with your partner. Can become competitive or ego-focused in sexual encounters, treating intimacy like a performance to be mastered rather than a connection to be enjoyed.",
    advice: "Channel your sexual drive and energy toward creating deeper intimacy and connection rather than just achieving sexual goals or demonstrating performance capabilities. Practice slowing down and savoring the process of sexual connection, paying attention to subtle sensations and emotional responses rather than rushing toward climax. Focus on the journey of sexual exploration and mutual discovery rather than treating intimate encounters as challenges to be conquered or performances to be perfected."
  },
  8: {
    general: "Your sexuality is characterized by gentle power, patience, and the ability to transform sexual challenges into opportunities for deeper intimacy and healing through compassionate, consistent presence and emotional strength. You approach sexual expression with inner resilience and the understanding that true sexual satisfaction comes from emotional safety, trust, and gradual development of intimate connection over time. Your sexual nature values healing, transformation, and the patient cultivation of sexual trust and vulnerability within committed relationships.",
    positive: "Natural healing presence in sexual relationships that helps partners feel safe enough to explore their desires and vulnerabilities without fear of judgment or rejection. Your patient approach to sexual development allows for gradual building of trust and intimacy that creates lasting satisfaction and deep connection. You excel at transforming sexual difficulties or past traumas into opportunities for healing and greater intimacy through gentle, consistent support.",
    challenge: "May suppress or minimize your own sexual desires and needs in order to focus on your partner's healing or satisfaction, potentially creating imbalance in intimate relationships. Tendency to endure sexual problems or unsatisfying patterns too long without addressing them directly, hoping that patience and love alone will resolve issues that need active communication. Can struggle with asserting your own sexual needs or boundaries, preferring to accommodate your partner even when it compromises your own satisfaction.",
    advice: "Trust in your gentle power to create profound sexual connections while also advocating clearly for your own needs and desires in intimate relationships. Use your natural healing abilities to address sexual issues directly through communication and conscious effort rather than just enduring problems patiently. Balance your focus on your partner's sexual healing and satisfaction with attention to your own sexual growth and fulfillment."
  },
  9: {
    general: "Your sexuality is wise, introspective, and deeply connected to spiritual dimensions of intimate connection, characterized by need for meaningful, soulful sexual experiences that integrate physical pleasure with emotional and spiritual communion. You approach sexual expression through understanding, wisdom, and the desire to connect with your partner on multiple levels beyond just physical attraction and pleasure. Your sexual nature requires solitude and reflection to process intimate experiences and may prefer deep, infrequent sexual connections over frequent, casual encounters.",
    positive: "Deep understanding of sexuality's spiritual aspects and ability to create profound, meaningful intimate experiences that connect both partners to higher dimensions of love and consciousness. Your wisdom and introspective nature help you understand the psychological and emotional dynamics of sexual relationships in ways that can be healing and transformative. You offer thoughtful guidance and patient support for your partner's sexual growth and spiritual development through intimate connection.",
    challenge: "May intellectualize sexuality or avoid fully embodied physical sexual expression, preferring to discuss or analyze intimate connection rather than experiencing it directly through your body. Tendency to isolate or withdraw from sexual relationships when they become too intense or demanding, retreating into solitude rather than working through challenges with your partner. Can become overly serious or philosophical about sexuality, missing opportunities for playful, spontaneous, or purely physical sexual expression.",
    advice: "Integrate your sexual wisdom and spiritual understanding with full embodied experience, allowing yourself to be present in your body during intimate encounters. Balance your need for solitude and reflection with regular engagement in physical sexual expression that honors both spiritual and bodily dimensions of intimacy. Share your insights about sexuality while also remaining open to learning from your partner's different approach to intimate connection and physical pleasure."
  },
  10: {
    general: "Your sexual energy follows natural cycles and rhythms with periods of high passion alternating with times of lower sexual interest, and you have intuitive understanding of timing and natural flow in intimate relationships. You approach sexuality with awareness that sexual desire and connection have their own natural timing that can't be forced or controlled, preferring to work with these cycles rather than fighting against them. Your sexual nature is connected to larger rhythms of life, seasons, and personal energy cycles that influence when and how you express intimate connection.",
    positive: "Natural understanding of sexual cycles and timing that helps you work with rather than against your own and your partner's natural rhythms of desire and availability. Your ability to flow with changing sexual energy helps create sustainable intimate relationships that honor both high-passion periods and quieter times of connection. You excel at recognizing when the timing is right for sexual connection and when it's better to focus on other forms of intimacy and bonding.",
    challenge: "Sexual energy may be unpredictable or dependent on external factors like stress, health, or life circumstances, making it difficult for partners to understand or predict your sexual availability. Tendency to become passive about sexual connection, waiting for perfect timing or ideal circumstances rather than actively creating opportunities for intimacy. Can use belief in natural cycles to avoid taking responsibility for sexual communication or working through relationship challenges that affect intimacy.",
    advice: "Learn to work with your natural sexual cycles while also taking proactive steps to maintain intimate connection during all phases of your sexual rhythm. Communicate clearly with your partner about your sexual patterns and needs so they can understand and work with your natural flow rather than taking it personally. Balance acceptance of natural sexual cycles with conscious effort to nurture intimacy and address challenges that may be affecting your sexual connection."
  },
  11: {
    general: "Your approach to sexuality is balanced, ethical, and deeply concerned with fairness, justice, and mutual respect in all aspects of intimate relationships and sexual expression. You seek to create sexual experiences that feel equitable and satisfying for both partners, with clear agreements about boundaries, desires, and expectations. Your sexual nature values honesty, integrity, and ethical behavior in intimate relationships, preferring sexual connections that align with your moral principles and sense of what is right and fair.",
    positive: "Natural sense of sexual justice and fairness that creates intimate relationships where both partners feel respected, valued, and ethically treated in all sexual encounters. Your balanced approach to sexuality helps ensure that both people's needs and boundaries are honored and that sexual experiences feel mutually satisfying. You excel at having clear, honest conversations about sexual desires, boundaries, and agreements that create trust and safety in intimate relationships.",
    challenge: "May be too analytical or rigid about sexual rightness and wrongness, potentially limiting spontaneous or experimental sexual expression that doesn't fit predetermined categories of appropriate behavior. Tendency to overthink sexual decisions or become paralyzed by trying to ensure perfect fairness in every intimate encounter. Can become judgmental about your own or your partner's sexual desires if they seem to conflict with your sense of what is morally or ethically correct.",
    advice: "Balance your natural sense of sexual ethics with acceptance of the complexity and ambiguity that exists in real intimate relationships and sexual expression. Make sexual decisions more quickly by establishing clear personal values that can guide you without requiring extensive analysis of every situation. Allow for some experimentation and exploration in sexual expression while maintaining your core ethical principles about respect and mutual consent."
  },
  12: {
    general: "Your sexuality involves willingness to explore unconventional approaches, sacrifice certain desires for deeper connection, and see sexual experiences from completely different perspectives that reveal hidden gifts within challenges. You may find that your sexual expression requires patience, letting go of conventional expectations, and openness to unique or unusual forms of intimate connection. Your sexual nature thrives when you can approach intimacy from fresh angles that others might not consider or understand.",
    positive: "Willingness to explore unconventional sexual experiences and approaches that can lead to unique insights and deep wisdom about intimate connection and human sexuality. Your ability to see sexual situations from multiple perspectives helps resolve conflicts and creates innovative solutions to sexual challenges that conventional approaches might miss. You offer your partner the gift of experiencing sexuality as a journey of discovery rather than just physical pleasure or emotional bonding.",
    challenge: "May sacrifice your own sexual needs or authentic desires too much in order to accommodate your partner or explore unusual approaches that don't actually serve your satisfaction. Tendency to make sexual expression more complex or difficult than necessary, looking for unconventional approaches when simpler, more direct expression might be more satisfying. Can become stuck in sexual situations that require action rather than just changing your perspective or approach to the relationship.",
    advice: "Ensure that any sexual exploration or sacrifice you make serves authentic growth and connection rather than just being different for its own sake or avoiding more direct approaches. Balance your willingness to see sexuality from new perspectives with practical attention to what actually creates satisfaction and fulfillment for both you and your partner. Use your unique sexual perspective to enhance rather than complicate intimate connection, finding ways to be both innovative and genuinely satisfying."
  },
  13: {
    general: "Your sexuality involves transformation, letting go, and the rebirth that comes from allowing sexual patterns and desires to evolve and change rather than remaining static or comfortable. You understand that authentic sexual expression requires the courage to let old patterns die and be reborn into deeper, more authentic forms of intimate connection. Your sexual nature is fundamentally about transformation, renewal, and the constant evolution of how you express and experience intimate energy with others.",
    positive: "Natural ability to transform through sexual experience and comfort with sexual changes and transitions that deepen intimacy and authentic expression over time. Your understanding of sexuality's transformative power helps create relationships that continuously evolve and deepen rather than becoming stagnant or superficial. You offer your partner the gift of experiencing sexuality as a catalyst for personal growth and authentic self-expression.",
    challenge: "May fear sexual commitment or long-term intimate relationships due to awareness that sexual desires and expressions naturally change over time. Tendency to create unnecessary sexual drama or endings when intimate relationships become comfortable or predictable, preferring intensity and change over stability. Can become too focused on sexual transformation and change, missing opportunities to enjoy consistent connection and develop steady intimate patterns when they serve the relationship.",
    advice: "Embrace sexuality's transformative power while also building intimate foundations that can support you and your partner through periods of sexual change and growth. Allow for natural evolution in your sexual expression without forcing change or creating crisis when sexual connection is satisfying and stable. Balance your comfort with sexual transformation with appreciation for the consistency and security that also nourish lasting intimate relationships."
  },
  14: {
    general: "Your sexuality is characterized by moderation, healing, and the balanced integration of different aspects of sexual expression into a harmonious, sustainable approach to intimate connection. You naturally seek to balance passion with tenderness, physical pleasure with emotional connection, and individual desires with relationship harmony. Your sexual nature values healing, balance, and the creation of intimate experiences that feel nourishing and sustainable rather than intense or extreme.",
    positive: "Natural ability to heal and balance sexual energies, creating intimate relationships that feel sustainable and nourishing for both partners over long periods of time. Your moderate approach to sexuality helps avoid extremes and creates steady satisfaction and connection that deepens gradually. You excel at helping partners integrate different aspects of their sexuality and find balance between various desires and needs.",
    challenge: "May avoid necessary sexual intensity or passionate extremes, seeking balance even when the relationship needs more fire, excitement, or deep sexual engagement to grow and thrive. Tendency toward sexual neutrality that feels safe but may limit the depth of intimate connection and passionate expression possible in your relationships. Can become too focused on maintaining sexual equilibrium rather than allowing for the natural variations in passion and desire that create growth and excitement.",
    advice: "Balance your natural moderation with openness to intense sexual experiences and passionate expressions that deepen intimacy even if they temporarily disrupt your preferred equilibrium. Allow for natural fluctuations in sexual energy and passionate intensity rather than always seeking to maintain steady, moderate sexual expression. Recognize that sometimes great sexuality requires passionate engagement and sexual risk-taking rather than just careful balance and measured responses."
  },
  15: {
    general: "Your sexuality is intense, powerful, and potentially obsessive, characterized by strong physical desires and deep exploration of the shadow aspects of sexual expression including power dynamics, control, and raw physical passion. You have the capacity for profound sexual experiences that explore the full range of human desire and physical sensation, but this intensity needs conscious direction to avoid becoming destructive or compulsive. Your sexual nature understands the connection between sexuality and power, and you may be drawn to explore dominance, submission, or other power dynamics in intimate relationships.",
    positive: "Powerful sexual magnetism and ability to embrace sexuality fully without shame or limitation, creating intense, deeply satisfying intimate experiences for yourself and your partners. Your understanding of sexuality's shadow aspects helps you navigate complex desires and power dynamics consciously rather than unconsciously acting them out. You offer partners the opportunity to explore their full sexual nature including desires they might be afraid to express with others.",
    challenge: "May become obsessed with sex or particular partners, losing perspective on other important life areas or using sexuality manipulatively to maintain control in relationships. Tendency to focus on sexual power and intensity at the expense of emotional intimacy and genuine connection with your partner as a whole person. Can become trapped by your own sexual desires or compulsions, making decisions based on physical attraction rather than overall compatibility and relationship health.",
    advice: "Enjoy your powerful sexual nature and physical passion without becoming enslaved by desires or losing your freedom and authentic self-expression in intimate relationships. Use your understanding of sexual power dynamics to create conscious, consensual experiences rather than unconscious manipulation or control of your partners. Channel your intense sexual energy toward building deeper intimacy and spiritual connection rather than just physical satisfaction or power games."
  },
  16: {
    general: "Your sexuality involves sudden awakenings, revelations, and the breaking free from limiting patterns or beliefs that have prevented authentic sexual expression and genuine intimate connection. You may experience dramatic shifts in sexual understanding, preferences, or experiences that liberate you from old conditioning about sexuality. Your sexual nature is characterized by breakthrough moments that shatter illusions and reveal new possibilities for authentic sexual expression and intimate connection.",
    positive: "Natural ability to break free from unhealthy sexual patterns, limiting beliefs about sexuality, and relationships that don't serve your authentic sexual expression and growth. Your willingness to face difficult truths about sexuality helps create relationships based on authenticity rather than fantasy, projection, or social conditioning. You offer partners the gift of sudden insights and liberation from sexual shame, fear, or limiting beliefs that have prevented full intimate expression.",
    challenge: "Tendency toward dramatic sexual revelations, sudden changes in sexual preferences, or shocking disclosures that can destabilize intimate relationships without adequate preparation or communication. May create unnecessary sexual drama or crisis when gradual change or patient communication would be more effective for relationship growth. Can use sexual revelations or insights as weapons to hurt or shock your partner rather than tools for mutual growth and deeper understanding.",
    advice: "Use sexual revelations and breakthrough insights to build better intimacy and authentic connection rather than just to shock, escape, or create drama when relationships become challenging. Communicate your sexual realizations and need for change clearly and compassionately, preparing your partner for transitions rather than creating sudden shocks. Build upon the insights and sexual liberation you experience rather than just breaking free from old patterns without creating new, healthier forms of intimate expression."
  },
  17: {
    general: "Your sexuality is hopeful, inspiring, and connected to higher spiritual purpose, characterized by faith in love's healing power and the belief that sexual expression can serve spiritual awakening and positive transformation. You approach intimate connection with optimism and vision, seeing sexuality as a pathway to higher consciousness and spiritual union rather than just physical pleasure or emotional bonding. Your sexual nature is fundamentally idealistic and seeks to elevate both yourself and your partner through intimate connection.",
    positive: "Natural ability to bring hope, inspiration, and spiritual vision to sexual relationships, helping partners connect with their highest potential through intimate connection. Your faith in sexuality's healing and transformative power creates an atmosphere of possibility and transcendence that can be deeply healing and awakening. You offer the gift of seeing your partner's divine sexual nature and spiritual potential even when they struggle to recognize it themselves.",
    challenge: "May have unrealistic expectations about sexual expression or your partner's capacity for spiritual sexual connection, expecting transcendent experiences rather than accepting human limitations and gradual development. Tendency to focus on sexual ideals and future possibilities rather than appreciating your partner and current intimate experiences as they actually are. Can become disappointed when everyday sexual reality doesn't match your vision of what enlightened sexuality should be like.",
    advice: "Keep your spiritual vision and ideals about sexuality while also embracing the beautiful imperfection of human sexual expression and the gradual process of sexual and spiritual development. Appreciate your partner's current level of sexual and spiritual development rather than focusing only on their potential for future growth. Ground your sexual inspiration in practical intimate experiences and communication that nurture your actual relationship rather than just your vision of ideal sexual union."
  },
  18: {
    general: "Your sexuality is mysterious, intuitive, and deeply connected to unconscious realms, dreams, and psychic dimensions of intimate connection that exist beyond rational understanding or conventional sexual expression. You may experience sexuality as a gateway to other dimensions of consciousness and may have psychic or telepathic connections with intimate partners. Your sexual nature thrives in environments that honor mystery, imagination, and the exploration of subtle energetic and psychic aspects of intimate connection.",
    positive: "Deep intuitive understanding of sexual mysteries and ability to create profound psychic and energetic connections with partners that transcend ordinary physical intimacy. Your sensitivity to subtle sexual energies and unconscious dynamics helps you understand and navigate the deeper psychological aspects of intimate relationships. You offer partners the gift of experiencing sexuality as a mystical, transformative journey into unconscious realms and hidden aspects of themselves.",
    challenge: "May struggle with sexual confusion, unclear boundaries, or difficulty distinguishing between genuine psychic sexual connection and projection, fantasy, or emotional confusion. Tendency to get lost in sexual fantasies, dreams, or psychic experiences rather than maintaining connection to practical intimate needs and physical sexual expression. Can become overly dependent on mystical or psychic sexual connection while neglecting direct communication and practical aspects of intimate relationships.",
    advice: "Trust your intuitive understanding of sexual mysteries while also maintaining clear communication about practical needs, boundaries, and desires in your intimate relationships. Develop discernment between genuine psychic sexual connection and emotional projection, fantasy, or confusion that can cloud your perception of what's actually happening. Balance your appreciation for sexuality's mysteries with attention to clear, direct communication about everyday intimate needs and physical sexual satisfaction."
  },
  19: {
    general: "Your sexuality is joyful, radiant, and naturally enthusiastic, characterized by genuine celebration of physical pleasure, intimate connection, and the pure enjoyment of sexual energy as a source of happiness and life satisfaction. You approach sexual expression with the same positive energy and enthusiasm that you bring to other enjoyable life experiences, seeing sexuality as a natural source of joy rather than something complex or problematic. Your sexual nature is fundamentally optimistic and attracts partners who appreciate authentic enthusiasm and celebration of intimate pleasure.",
    positive: "Natural joy and enthusiasm in sexual expression that makes intimate encounters feel celebratory and positive for both you and your partners. Your magnetic sexual energy and genuine appreciation for physical pleasure creates an atmosphere of abundance and satisfaction that helps partners feel desired and appreciated. You excel at making sexuality feel natural, healthy, and joyful rather than complicated, shameful, or problematic.",
    challenge: "May avoid dealing with sexual shadows, difficult emotions, or necessary intimate growth work, preferring to stay positive rather than addressing underlying issues that affect sexual satisfaction. Tendency to suppress or deny challenging aspects of sexuality in yourself or your partner, which can prevent authentic intimacy and resolution of important sexual problems. Can become superficial in sexual expression, focusing on fun and pleasure while avoiding the deeper emotional and psychological work that creates lasting intimate satisfaction.",
    advice: "Maintain your joyful approach to sexuality while also creating space for authentic expression of all emotions and experiences that are part of complete intimate connection. Address necessary sexual growth areas and relationship challenges while maintaining your positive outlook and faith in your partnership's sexual potential. Balance your focus on sexual happiness and celebration with willingness to explore the full range of human sexual experience including its more challenging aspects."
  },
  20: {
    general: "Your sexuality represents a spiritual calling involving rebirth, awakening, and the recognition that intimate connection serves as a powerful catalyst for profound personal transformation and spiritual development. You approach sexual expression as a sacred practice that has significance beyond personal pleasure, seeing intimate relationships as opportunities for spiritual awakening and service to higher consciousness. Your sexual nature is fundamentally about rebirth, transformation, and the integration of physical pleasure with spiritual purpose and meaning.",
    positive: "Natural understanding of sexuality as a spiritual path and ability to use intimate connection as a catalyst for profound personal and spiritual growth and awakening. Your recognition that sexuality serves higher purpose helps create relationships that feel meaningful and aligned with spiritual development rather than just physical satisfaction. You offer partners the gift of experiencing sexuality as a sacred practice and opportunity for transformation rather than just pleasure or emotional bonding.",
    challenge: "May struggle with practical aspects of sexuality and everyday intimate maintenance, focusing on spiritual significance while neglecting ordinary needs for physical pleasure and practical sexual communication. Tendency to expect partners to share your spiritual understanding of sexuality rather than accepting their individual approach and level of sexual spiritual development. Can become overwhelmed by the responsibility or significance you place on sexual expression, making it difficult to enjoy simple physical pleasure and playful intimate connection.",
    advice: "Answer sexuality's spiritual calling while also attending to everyday intimate needs for physical pleasure, practical communication, and ordinary human sexual connection and enjoyment. Honor your sense that sexuality serves higher purpose while also accepting your partner's individual sexual and spiritual path and timing for awakening. Balance the spiritual significance you place on sexuality with appreciation for simple moments of physical pleasure and playful intimate connection that also nourish lasting sexual relationships."
  },
  21: {
    general: "Your sexuality represents completion, fulfillment, and the successful integration of all aspects of sexual expression into a mature, satisfying approach to intimate connection that serves as a model for others. You have achieved or are capable of achieving sexual wholeness that integrates passion with tenderness, physical pleasure with emotional connection, and individual desires with relationship harmony. Your sexual nature represents mastery of intimate skills and the ability to create deeply fulfilling sexual relationships that feel complete and satisfying.",
    positive: "Natural achievement of sexual wholeness and integration that creates deeply satisfying intimate relationships where all aspects of sexual expression are honored and expressed authentically. Your mastery of sexual communication and intimate skills helps create stable, lasting relationships that continue to grow and evolve sexually over time. You excel at helping partners achieve their own sexual fulfillment and integration through your wisdom and example of sexual maturity.",
    challenge: "May become sexually complacent or take intimate satisfaction for granted, assuming that achievement of sexual fulfillment means the growth and exploration are complete. Need for new sexual challenges or experiences to maintain engagement and continued development, which can create unnecessary restlessness in sexually satisfying relationships. Can become overly focused on maintaining sexual achievement rather than continuing to explore new depths of intimate connection and sexual expression.",
    advice: "Celebrate your sexual wholeness and intimate mastery while remaining open to continued growth and evolution in your sexual expression as your needs and circumstances change over time. Use your sexual maturity and relationship skills to help others achieve fulfilling intimate relationships while also maintaining attention to your own continued sexual development. Stay curious about new possibilities for sexual expression and intimate connection rather than assuming you've achieved the final answer to sexual fulfillment."
  },
  22: {
    general: "Your sexuality is characterized by fresh innocence, spontaneous exploration, and unlimited potential for discovering new forms of intimate expression that aren't constrained by conventional expectations or past sexual experiences. You approach sexual connection with beginner's mind and natural curiosity, willing to explore and experiment without preconceived limitations about what sexuality should or shouldn't include. Your sexual nature has the potential to pioneer new paradigms of intimate connection that could influence and inspire others.",
    positive: "Natural openness and unlimited potential for sexual exploration and discovery that isn't limited by conventional thinking, past experiences, or social conditioning about appropriate sexual expression. Your fresh perspective and willingness to experiment can lead to breakthrough discoveries about intimate connection and sexual satisfaction that others might miss. You offer partners the gift of experiencing sexuality as an adventure and opportunity for mutual discovery rather than performance or repetition of familiar patterns.",
    challenge: "May be sexually naive or lack practical experience and wisdom about intimate relationships, making decisions based on enthusiasm rather than realistic understanding of sexual consequences and relationship dynamics. Tendency toward sexual impulsiveness without adequate consideration of emotional impact, safety concerns, or long-term relationship effects. Can lack the experience or communication skills needed to navigate sexual challenges effectively, potentially creating problems through inexperience rather than lack of care.",
    advice: "Embrace your fresh perspective and willingness to explore sexually while also learning practical intimate skills and seeking guidance from experienced mentors who can help you avoid common sexual pitfalls. Maintain your openness to sexual possibilities while also developing the communication abilities and emotional intelligence needed for building lasting intimate relationships. Balance your spontaneous approach to sexuality with careful consideration of important intimate decisions that affect your long-term sexual health and relationship satisfaction."
  }
};