/* eslint-disable @typescript-eslint/no-unused-vars */

/**
 * Work Life Balance Interpretations
 * 
 * Detailed interpretations for how each Major Arcana (1-22) influences
 * your approach to balancing career demands with personal life needs.
 */

export interface MatrixInterpretation {
  general: string;
  positive: string;
  challenge: string;
  advice: string;
}

export interface MatrixAspectInterpretations {
  [arcanaNumber: number]: MatrixInterpretation;
}

/**
 * Work Life Balance - How you balance career and personal life
 */
export const workLifeBalanceInterpretations: MatrixAspectInterpretations = {
  1: {
    general: "You are a driven professional who tends to blur the lines between work and personal life, often bringing your intense focus and leadership energy into all areas of life. Your natural inclination is to approach both career and personal goals with the same pioneering spirit and determination. Learning to create healthy boundaries becomes essential as your success-oriented nature can easily lead to overcommitment in professional pursuits.",
    positive: "Strong leadership abilities allow you to manifest career goals quickly while inspiring others in both professional and personal contexts. Your pioneering energy creates opportunities for advancement and helps you take initiative in solving work-life conflicts. You have the natural ability to lead by example, showing others how to pursue ambitious goals while maintaining personal relationships.",
    challenge: "Tendency to overwork and bring work stress home, making it difficult for family and friends to connect with your non-professional side. Difficulty delegating professional responsibilities or truly relaxing, as your mind constantly seeks new challenges and goals to conquer. May struggle with vulnerability in personal relationships, preferring the familiar territory of professional achievement where you feel more in control.",
    advice: "Schedule personal time as seriously as you schedule business meetings, treating rest and relationships as essential components of your overall success strategy. Practice delegating both at work and at home, allowing others to contribute while you focus on high-level leadership. Create physical and mental rituals that help you transition from work mode to personal mode, such as changing clothes or taking a walk."
  },
  2: {
    general: "You take an intuitive, receptive approach to work-life balance, naturally sensing when you need to withdraw from professional demands to restore your emotional and spiritual energy. Your work-life integration depends heavily on following your inner rhythms rather than external schedules or expectations. You require regular quiet time and emotional processing to maintain equilibrium between your professional responsibilities and personal well-being.",
    positive: "Strong ability to sense when balance is needed, often recognizing burnout or stress before it becomes overwhelming. Your intuitive nature helps you make career choices that align with your personal values and emotional needs. You bring a calm, emotionally intelligent presence to workplace conflicts and can help others find balance through your example of following inner wisdom.",
    challenge: "May withdraw too much from work demands when feeling overwhelmed, potentially missing important opportunities or letting colleagues down. Difficulty with confrontation or assertive communication in professional settings, preferring to avoid conflict rather than address work-life boundary issues directly. Can become overly sensitive to workplace dynamics, taking professional feedback or pressure too personally.",
    advice: "Trust your inner wisdom about when to engage professionally and when to retreat for personal restoration, while also communicating your needs clearly to supervisors and colleagues. Develop gentle but firm communication skills for addressing work-life boundary issues before they become overwhelming. Create supportive networks both at work and personally that understand and respect your need for emotional processing time."
  },
  3: {
    general: "You seek creative fulfillment and nurturing connections in both your professional and personal life, often struggling when work doesn't allow for creative expression or meaningful relationships. Your approach to balance involves integrating your natural creativity and caring nature into all areas of life rather than compartmentalizing them. You thrive when your career allows you to create, nurture, or help others grow while still having energy for personal creative projects and relationships.",
    positive: "Natural ability to bring creativity and innovation to any professional role, making work more enjoyable and productive. Your nurturing approach creates positive work environments where colleagues feel supported and valued. You excel at finding creative solutions to work-life conflicts and can often integrate personal interests with professional responsibilities in innovative ways.",
    challenge: "May struggle with structured corporate environments that don't value creativity or personal expression, leading to frustration and imbalance. Tendency to take on too many projects both professionally and personally, spreading your creative energy too thin. Can have difficulty saying no to requests for help, leading to overcommitment in both work and personal relationships.",
    advice: "Focus your creative energy on fewer, more meaningful projects that align with your values and allow for both professional success and personal fulfillment. Set clear boundaries around your time and energy, protecting space for personal creative expression even during busy work periods. Learn to delegate nurturing responsibilities both at work and home, allowing others to contribute while you focus on your most important creative contributions."
  },
  4: {
    general: "You prefer a structured, systematic approach to work-life balance with clear boundaries and established routines that support both professional productivity and personal stability. Your natural inclination is to create reliable systems and frameworks that allow you to meet professional obligations while protecting time for personal responsibilities and relationships. You work best when you can establish predictable patterns that serve both career advancement and personal well-being.",
    positive: "Excellent at creating systems and routines that support both career goals and personal life, bringing order and stability to potentially chaotic situations. Your methodical approach helps you build lasting success in both professional and personal areas without sacrificing one for the other. You provide a stable foundation for family and colleagues, creating security that allows others to take risks or pursue growth.",
    challenge: "May be too rigid in your approach to balance, struggling to adapt when life circumstances require flexibility or spontaneous responses. Difficulty adapting when external changes disrupt your established routines, potentially causing stress in both work and personal relationships. Can become overly focused on maintaining control and structure, missing opportunities for growth that require stepping outside your comfort zone.",
    advice: "Build flexibility into your structured approach to balance, creating contingency plans and buffer time for unexpected changes or opportunities. Practice adapting your systems when circumstances change, viewing flexibility as a strength rather than a threat to your stability. Allow space for spontaneity and growth within your structured framework, recognizing that some of life's best opportunities come through unexpected changes."
  },
  5: {
    general: "You approach work-life balance through traditional methods and established wisdom, preferring to follow proven strategies and seek guidance from mentors or established authorities. Your sense of balance comes from aligning with conventional expectations about career progression and family responsibilities while honoring time-tested approaches to managing both. You find security in following established protocols and social norms around work-life integration.",
    positive: "Stable career progression through following established paths and building on traditional foundations of success. Natural respect for proper work-life boundaries and social expectations, creating predictability and security for yourself and family. Your traditional approach provides a solid foundation that allows for steady growth in both professional and personal areas without unnecessary risk or upheaval.",
    challenge: "May resist new approaches to work-life balance that could be more effective, preferring familiar methods even when they're not serving your current needs. Overly dependent on external validation and approval from authority figures, potentially sacrificing personal needs to meet others' expectations. Can be judgmental of others who choose non-traditional approaches to career or family life, limiting your ability to learn from alternative models.",
    advice: "Honor traditional wisdom about work-life balance while remaining open to modern approaches that might enhance your effectiveness and satisfaction. Seek guidance from mentors who have successfully adapted traditional approaches to contemporary challenges. Balance respect for established norms with attention to your own unique needs and circumstances, recognizing that some traditional advice may need updating for your situation."
  },
  6: {
    general: "You seek harmony, beauty, and partnership in both your professional and personal life, working to create aesthetically pleasing and emotionally satisfying environments in all areas. Your approach to balance involves collaboration and mutual support, preferring to share responsibilities and make decisions jointly with partners, colleagues, and family members. You thrive when your work and personal life both involve meaningful relationships and opportunities to create beauty or harmony for others.",
    positive: "Excellent at creating collaborative work environments where team members feel valued and supported in balancing their own professional and personal needs. Your diplomatic skills help resolve conflicts between work and personal demands, both for yourself and others. You bring an aesthetic sense and attention to relationship quality that enhances both professional networking and personal partnerships.",
    challenge: "May struggle with independent decision-making about work-life priorities, seeking too much input from others or avoiding decisions that might disappoint someone. Tendency toward people-pleasing that leads to overcommitment in both professional and personal areas as you try to meet everyone's expectations. Can avoid necessary conflicts about boundaries, allowing work-life balance issues to persist rather than addressing them directly.",
    advice: "Make work-life balance choices based on your own values and needs, not just to keep others happy or maintain harmony at any cost. Practice having difficult conversations about boundaries and priorities before small issues become major problems. Seek partnerships both professionally and personally with people who support your need for balance rather than demanding constant availability or sacrifice."
  },
  7: {
    general: "You take a dynamic, goal-oriented approach to work-life balance, constantly moving between different demands and working to overcome obstacles that threaten your equilibrium. Your natural drive and determination help you navigate competing priorities, but you may struggle with finding stillness and truly restful downtime. You approach balance as something to be achieved through effort and strategic action rather than natural flow or acceptance.",
    positive: "Strong ability to overcome work-life conflicts through determination and creative problem-solving, refusing to accept that balance is impossible. Your drive helps you achieve significant results in both professional and personal areas, often accomplishing more than others think possible. You inspire others through your example of persistent effort to maintain important relationships while pursuing ambitious career goals.",
    challenge: "May push too hard in both professional and personal areas, creating exhaustion and stress rather than sustainable balance. Difficulty with stillness, rest, or unproductive time, constantly feeling the need to be moving toward goals or solving problems. Can become impatient with the natural rhythms and slower processes required for relationship building and personal restoration.",
    advice: "Channel your drive purposefully toward creating sustainable systems rather than constantly pushing harder to maintain balance through effort alone. Schedule regular periods of rest and stillness as strategic investments in your long-term effectiveness rather than time wasted. Learn to appreciate the journey and process of building relationships and personal well-being, not just the achievement of specific goals."
  },
  8: {
    general: "You approach work-life balance with gentle strength and patience, understanding that true equilibrium requires inner resilience and the ability to handle pressure without losing your center. Your natural empathy and emotional intelligence help you navigate the complex demands of both professional and personal life with grace. You have the rare ability to remain calm and supportive during stressful periods while maintaining your own boundaries and well-being.",
    positive: "Natural ability to handle workplace and personal pressure with grace, providing stability and emotional support to colleagues and family members during challenging times. Your patient approach allows you to build sustainable balance over time rather than forcing quick fixes that don't last. You bring healing energy to both professional and personal relationships, helping others find their own balance through your example.",
    challenge: "May endure imbalance or difficult situations too long without advocating for necessary changes, preferring to adapt rather than confront problems directly. Tendency to put others' needs first in both work and personal contexts, potentially neglecting your own requirements for rest, growth, or fulfillment. Can be too accommodating with unreasonable demands, allowing others to take advantage of your patient, supportive nature.",
    advice: "Use your natural strength to protect and advocate for your own needs and boundaries, recognizing that self-care enables you to better serve others. Address work-life balance issues early and directly rather than enduring problems in hopes they will resolve themselves. Practice saying no to demands that would compromise your well-being, understanding that maintaining your own balance allows you to be more helpful to others."
  },
  9: {
    general: "You take a reflective, wisdom-based approach to work-life balance, needing regular solitude and contemplation to process the demands of both professional and personal life. Your deep understanding of life's patterns and priorities helps you make wise decisions about where to invest your time and energy. You require more alone time than most people to maintain your equilibrium and may struggle in highly social or demanding work environments.",
    positive: "Deep wisdom about what truly matters in both career and personal life, helping you avoid getting caught up in superficial concerns or social pressures. Your reflective nature allows you to make thoughtful decisions about work-life priorities that align with your deeper values and long-term goals. You offer valuable guidance to others struggling with balance issues through your perspective and experience.",
    challenge: "May isolate too much from both professional opportunities and personal relationships, preferring solitude even when engagement would be beneficial. Tendency to overthink work-life decisions, analyzing all possibilities rather than taking action when situations require immediate response. Can withdraw from necessary but challenging interactions, missing opportunities to influence positive changes in work or personal environments.",
    advice: "Share your wisdom and insights about work-life balance while maintaining the solitude you need for reflection and restoration. Balance your need for contemplation with regular engagement in both professional and personal relationships that matter to you. Trust your deep understanding of priorities while also remaining open to new experiences and perspectives that could enhance your balance."
  },
  10: {
    general: "Your work-life balance follows cyclical patterns with natural periods of intense professional focus alternating with times when personal life takes priority. You have an intuitive understanding of timing and natural rhythms, recognizing when to push forward professionally and when to step back for personal restoration or family needs. Your approach to balance involves working with these natural cycles rather than trying to maintain constant equilibrium.",
    positive: "Natural ability to flow with changing demands and recognize the right timing for major work-life decisions like career changes, moves, or family planning. Your understanding of cycles helps you prepare for busy periods by building in recovery time and support systems. You excel at making major life transitions that integrate career advancement with personal growth and family needs.",
    challenge: "Work-life balance may feel unpredictable with periods of harmony followed by times of significant stress or imbalance that are difficult to manage. Tendency to wait for perfect timing rather than taking proactive steps to create better balance when current patterns aren't working. May become too passive about balance issues, believing that everything is predetermined rather than recognizing your power to influence outcomes.",
    advice: "Learn to work with natural cycles of professional and personal demands while also taking proactive steps to create the balance you want. Use periods of natural balance to prepare for more challenging times by building support systems and reserves of energy and resources. Recognize that while timing matters, you also have the power to influence your work-life integration through conscious choices and planning."
  },
  11: {
    general: "You approach work-life balance with a strong sense of fairness and justice, believing that both professional success and personal fulfillment are legitimate needs that deserve equal consideration. Your decisions about work-life priorities are based on ethical considerations and what feels right and fair to all parties involved. You work to create balance not just for yourself but also advocate for fair work-life policies and practices in your professional environment.",
    positive: "Strong sense of what constitutes fair treatment in work-life balance issues, both for yourself and others, making you an effective advocate for positive workplace policies. Your ethical approach to balance creates trust and respect in both professional and personal relationships. You excel at making difficult decisions about competing priorities by applying consistent principles and values.",
    challenge: "May be too rigid about what constitutes 'fair' balance, potentially missing creative solutions that don't fit your preconceived notions of how things should work. Difficulty with necessary compromises or imperfect solutions, preferring to wait for ideal conditions rather than working with current realities. Can become judgmental of others who make different choices about work-life priorities, limiting your ability to learn from alternative approaches.",
    advice: "Balance your idealism about fair work-life integration with practical acceptance of imperfect solutions that move you toward your goals. Communicate your boundaries and expectations clearly while remaining flexible about how balance might be achieved in different circumstances. Apply your sense of justice constructively by working to improve work-life policies and practices rather than just critiquing what's wrong with current systems."
  },
  12: {
    general: "Your approach to work-life balance involves willingness to make temporary sacrifices and see situations from completely different perspectives than conventional wisdom suggests. You may find that achieving balance requires letting go of traditional expectations about career progression or personal life milestones. Your unique perspective often reveals creative solutions to work-life conflicts that others miss, but these solutions may require patience and unconventional thinking.",
    positive: "Ability to see work-life balance situations from multiple angles, often finding creative solutions that serve everyone's needs in unexpected ways. Your willingness to make temporary sacrifices can lead to breakthrough opportunities that create better long-term balance. You bring fresh perspective to work-life challenges, helping others see possibilities they hadn't considered.",
    challenge: "May sacrifice too much of your own needs for work or family demands, giving up important personal goals or well-being in ways that aren't ultimately helpful to anyone. Difficulty with conventional approaches to balance, potentially missing straightforward solutions while seeking more complex alternatives. Can become stuck in situations that require action rather than just changing your perspective or attitude.",
    advice: "Ensure that any sacrifices you make serve a higher purpose and have a clear endpoint rather than becoming permanent patterns of self-neglect. Sometimes the most balanced choice requires temporary sacrifice, but make sure these decisions align with your deeper values and long-term goals. Balance your willingness to see situations differently with practical action when change is needed rather than just adjustment."
  },
  13: {
    general: "Your approach to work-life balance involves embracing transformation and letting go of professional or personal patterns that no longer serve your growth and well-being. You understand that achieving true balance sometimes requires ending careers, relationships, or life situations that have become stagnant or destructive. Your comfort with change and transition allows you to make bold moves toward better integration when others might cling to familiar but unsatisfying situations.",
    positive: "Natural ability to transform work-life challenges into opportunities for growth and renewal, seeing endings as doorways to better balance. Your comfort with change allows you to make necessary transitions in career or personal life when current situations aren't serving your well-being. You help others navigate major work-life transitions through your understanding that transformation, while difficult, often leads to greater fulfillment.",
    challenge: "May resist commitment to stable work-life patterns due to awareness that all situations are temporary and subject to change. Fear of commitment can prevent you from building the consistent relationships and routines that actually support long-term balance. Can become too comfortable with chaos or transition, avoiding the stability that might actually serve your current needs.",
    advice: "Embrace transformation as your natural path to better work-life integration while also building some stable foundations that can support you through periods of change. Recognize that some relationships and commitments become stronger and more meaningful through weathering transitions together. Use your comfort with change to help others while also creating some consistency in your own life."
  },
  14: {
    general: "You have a natural gift for finding middle ground between work and personal demands, approaching balance as an ongoing process of adjustment and integration rather than a fixed state to achieve. Your moderate, healing approach helps you avoid extremes and create sustainable patterns that support both professional success and personal well-being over time. You excel at helping others find their own balance through your example of patience and integration.",
    positive: "Excellent natural ability to create moderation and avoid extremes in work-life integration, maintaining steady progress in both areas without burning out. Your healing approach to balance helps resolve conflicts and stress in both professional and personal relationships. You serve as a stabilizing influence for colleagues and family members who struggle with work-life extremes.",
    challenge: "May avoid necessary extremes or intense focus when situations require temporary imbalance to achieve important goals or address urgent needs. Tendency to compromise too much, seeking middle ground even when taking a strong position about boundaries or priorities would be more appropriate. Can be slow to make significant changes even when current balance isn't working well, preferring gradual adjustment over bold action.",
    advice: "Trust your natural ability to find sustainable balance while remaining open to periods when temporary focus or intensity in one area serves your long-term integration goals. Sometimes achieving better balance requires making significant changes rather than just minor adjustments to current patterns. Use your gift for moderation to create sustainable practices while also recognizing when situations call for more decisive action."
  },
  15: {
    general: "You may struggle with becoming obsessed with either work success or personal desires, finding it difficult to maintain healthy integration when your passions are engaged. Your intense focus and drive can lead to significant achievements but also to periods where one area of life completely dominates at the expense of the other. Understanding your tendency toward extremes is the first step toward creating more conscious balance.",
    positive: "Intense focus and drive can achieve remarkable results when channeled consciously toward creating better work-life integration. Your passion and commitment inspire others and can lead to breakthrough success in whichever area you choose to prioritize. When you achieve balance, your integrated approach can be deeply fulfilling and materially successful.",
    challenge: "Tendency toward obsession with work success or personal gratification, losing perspective on other important life areas when your passions are engaged. Difficulty maintaining boundaries between different life areas, allowing work stress to affect personal relationships or personal drama to impact professional performance. Can become trapped by material success or lifestyle expectations that actually limit your freedom and well-being.",
    advice: "Recognize when you're becoming obsessed with work or personal pursuits and consciously choose to moderate your focus before it becomes destructive. Create clear boundaries and accountability systems that help you maintain perspective when your intensity threatens to overwhelm your judgment. Regular self-reflection and honest feedback from trusted friends can help you recognize when you're out of balance before it becomes a serious problem."
  },
  16: {
    general: "Your work-life balance is subject to sudden disruptions, revelations, and dramatic changes that force you to rebuild your approach to integrating professional and personal life. These upheavals, while challenging, often lead to breakthrough insights and innovative solutions that create better long-term balance. Your ability to adapt quickly to changing circumstances is both a strength and a necessity given your tendency to experience sudden shifts.",
    positive: "Natural ability to quickly adapt to changing circumstances and recover from work-life disruptions that would overwhelm others. Your flexibility and resilience help you find innovative solutions to balance challenges when traditional approaches don't work. Sudden changes often lead to breakthrough opportunities for better integration that you wouldn't have discovered through gradual adjustment.",
    challenge: "Unpredictable work-life balance with sudden changes that can be destabilizing for both professional relationships and personal commitments. Tendency toward crisis-driven changes rather than proactive planning, potentially creating unnecessary stress for yourself and others. May burn bridges or make dramatic decisions during disruptions that have long-term consequences you didn't fully consider.",
    advice: "Build flexibility and emergency resources into your life systems to handle unexpected changes more gracefully when they occur. Learn to distinguish between necessary dramatic changes and reactive decisions made during stressful periods. Use your adaptability as a strength while also creating some stable foundations that can weather sudden shifts without being completely destroyed."
  },
  17: {
    general: "You approach work-life balance with hope, inspiration, and faith that it's possible to create a fulfilling integration of professional success and personal happiness. Your optimistic vision of what's possible helps you persist through challenging periods and inspires others to believe in their own ability to achieve meaningful balance. You work toward idealistic goals that may seem unrealistic to others but often prove achievable through your sustained faith and effort.",
    positive: "Natural optimism and inspirational vision help you navigate work-life challenges with grace and hope, maintaining faith in positive outcomes even during difficult periods. Your belief in possibilities attracts opportunities and support from others who want to participate in your vision of integrated success. You inspire colleagues and family members to pursue their own visions of meaningful work-life balance.",
    challenge: "May have unrealistic expectations about how quickly or easily ideal work-life balance can be achieved, leading to disappointment when reality doesn't match your vision. Tendency to focus on future possibilities rather than addressing current practical needs or challenges that require immediate attention. Can avoid difficult but necessary work-life decisions by hoping that problems will resolve themselves naturally.",
    advice: "Keep faith in your vision of ideal work-life integration while also taking practical steps toward your goals and addressing current challenges directly. Ground your optimism in realistic timelines and concrete actions that move you steadily toward your ideals. Use your inspirational energy to motivate sustained effort rather than just dreaming about perfect outcomes."
  },
  18: {
    general: "Your approach to work-life balance is intuitive but sometimes unclear, with your path to integration often involving navigation of complex emotions, hidden motivations, and unconscious patterns that affect both professional and personal decisions. You may struggle with illusions about what will bring you happiness or success, requiring deep self-reflection to understand your true needs. Your journey toward balance involves uncovering and healing unconscious conflicts between different aspects of your life.",
    positive: "Strong intuition about work-life balance needs and ability to sense when something isn't right even if you can't immediately identify the problem. Your deep emotional intelligence helps you understand the psychological aspects of work-life integration for yourself and others. You excel at helping others navigate the emotional complexity of major work-life decisions.",
    challenge: "May struggle with illusions or unrealistic expectations about work or personal life, making decisions based on fantasy rather than clear assessment of reality. Tendency toward confusion about priorities or what you actually want, leading to inconsistent choices that don't create sustainable balance. Can be influenced by unconscious fears or desires that sabotage your conscious efforts to create better integration.",
    advice: "Trust your intuition about work-life balance while also seeking clarity through honest self-reflection, feedback from trusted advisors, and practical testing of your assumptions. Pay attention to recurring patterns in your work-life decisions that might reveal unconscious motivations or conflicts. Develop practices like journaling, therapy, or meditation that help you distinguish between genuine intuition and emotional reactivity or wishful thinking."
  },
  19: {
    general: "You approach work-life balance with natural joy and enthusiasm, believing that both professional success and personal happiness should be fulfilling and energizing rather than draining or sacrificial. Your positive energy and optimistic outlook help you create work-life integration that feels celebratory and abundant rather than restrictive or compromising. You inspire others through your example that balance can be joyful and sustainable.",
    positive: "Natural ability to find joy and fulfillment in both work and personal life, creating an integrated approach that feels energizing rather than depleting. Your enthusiasm and positive energy attract opportunities and relationships that support your vision of abundant, joyful living. You help others see possibilities for work-life integration that they might not have considered, inspiring them to pursue more fulfilling approaches.",
    challenge: "May avoid dealing with necessary but unpleasant aspects of work-life balance, preferring to focus on positive possibilities rather than addressing current problems. Tendency to overspend time, energy, or resources on enjoyable activities while neglecting less pleasant but important responsibilities. Can become unrealistic about the effort required to maintain joyful balance, expecting it to happen naturally without sustained work.",
    advice: "Maintain your joyful approach to work-life integration while also addressing challenging aspects of balance that require less enjoyable but necessary attention. Use your natural enthusiasm to motivate yourself through difficult but important work-life decisions and changes. Balance your focus on positive possibilities with practical attention to current responsibilities and challenges that need to be handled."
  },
  20: {
    general: "You are called to find higher purpose and meaning in your work-life integration, with your approach to balance involving spiritual awakening and alignment with your deepest mission and values. Your work-life decisions are guided by a sense of calling rather than just practical considerations, leading you toward choices that serve both personal fulfillment and contribution to something larger than yourself. You may experience dramatic awakenings or shifts in understanding about what truly matters in both work and personal life.",
    positive: "Natural ability to align work and personal life with your highest purpose and spiritual values, creating integration that feels meaningful and transformational. Your sense of calling attracts opportunities and relationships that support both professional success and personal spiritual growth. You inspire others to consider their own higher purpose in making work-life balance decisions.",
    challenge: "May struggle with practical aspects of work-life balance while focusing on higher purpose, potentially neglecting basic needs for security, routine, or conventional success. Difficulty integrating spiritual calling with practical realities of earning money, maintaining relationships, or meeting family responsibilities. Can become judgmental of others who make more conventional work-life choices, limiting your ability to learn from different approaches.",
    advice: "Answer your calling to meaningful work-life integration while also attending to practical needs for security, stability, and conventional responsibilities. Recognize that serving your higher purpose often requires mastering practical skills and working within existing systems rather than avoiding them. Use your sense of calling to inspire sustainable practices rather than expecting spiritual purpose to automatically resolve practical challenges."
  },
  21: {
    general: "You have achieved or are capable of achieving successful integration of all aspects of work and personal life, representing mastery of work-life balance that serves as a model for others. Your approach involves bringing together different life areas in a way that creates synergy and mutual support rather than competition or conflict. You understand that true balance is not about perfect equality but about conscious integration that serves your overall life purpose and well-being.",
    positive: "Natural achievement of sustainable work-life balance that integrates professional success with personal fulfillment in a way that feels complete and satisfying. Your mastery of integration serves as inspiration and guidance for others struggling with work-life challenges. You excel at helping others achieve their own version of successful balance through your wisdom and example.",
    challenge: "May become complacent about work-life balance, resting on current achievements rather than continuing to grow and adapt as circumstances change. Need for new challenges or evolution in your approach to balance to maintain engagement and continued development. Can become overly focused on maintaining current success rather than exploring new possibilities for growth and integration.",
    advice: "Celebrate your success in achieving work-life integration while remaining open to continued growth and evolution in your approach as your needs and circumstances change. Use your mastery to help others achieve their own balance while also setting new meaningful challenges for yourself. Stay curious about new approaches and possibilities rather than assuming you've found the final answer to work-life integration."
  },
  22: {
    general: "You bring a fresh, innocent approach to work-life balance with unlimited potential for creating new paradigms of integration that others haven't yet discovered or tried. Your willingness to approach balance without preconceived limitations allows you to experiment with innovative solutions and unconventional approaches. You have the potential to pioneer new ways of integrating work and personal life that could influence others and create positive change in workplace culture.",
    positive: "Natural openness to new approaches and unlimited potential for creating innovative work-life integration that isn't constrained by conventional thinking. Your fresh perspective and willingness to experiment can lead to breakthrough discoveries about what's possible in balancing different life areas. You inspire others through your example that work-life balance doesn't have to follow traditional patterns or limitations.",
    challenge: "May be naive about practical realities or challenges involved in work-life integration, making decisions based on enthusiasm rather than realistic assessment of consequences. Tendency toward impractical approaches that sound good in theory but don't work in real-world conditions with actual responsibilities and constraints. Can lack the discipline or experience needed to sustain innovative approaches when they require consistent effort or sacrifice.",
    advice: "Embrace your fresh perspective and willingness to try new approaches while also learning from others' experience and developing practical skills for sustaining your innovations. Balance your openness to possibilities with realistic assessment of what's required to make new approaches work in practice. Seek mentorship and guidance that can help you avoid common pitfalls while maintaining your innovative spirit and unlimited potential."
  }
};